- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
**Purpose**
https://github.com/wso2-enterprise/choreo/issues/4039
**Issue**
The auto-incrementing APIID retried from APIIdentifier is giving the first entry of the DB.
**Approach**
Retrieve the autoincrementing API correctly from APIIdentifier.
- Created APIs with name **test** and version **1.0**  in **org1** and **org2**.
- Create an application in **org2** and subscribe to the **test** api.
Subscription for the API **test**  in **org2** was correctly populated in **AM_SUBSCRIPTION** table.
> Fixes https://github.com/wso2-enterprise/choreo/issues/4039

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
This PR adds the following changes.
1. Adds organization ID changes to restoreAPIRevision method in publisher rest api.
2. Adds organization ID changes to changeAPILifecycle method in publisher rest api.
3. Adds organization ID changes to getAPILifecycleState method in publisher rest api.
4. Removes unused tenant ID from getAPILifecycleHistory.
> Add organization ID to publisher rest apis

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
Fix https://github.com/wso2-enterprise/choreo/issues/4027
The following error will be received upon an negative expiry time 
{"code":901410,"message":"Invalid additional properties","description":"Invalid additional properties given for application","moreInfo":"","error":[]}
> Add validation for token expiry

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence.mongodb/src/main/java/org/wso2/carbon/apimgt/persistence/mongodb/MongoDBPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/KeyManagersApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/RestApiAdminUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/KeyManagersApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR adds 
- new REST API resource `GET /apis/{apiId}/idps` to fetch IdPs configured for the API. 
- fixes the issue in updating IdPs configured for an API with org support
- add org support to `GET /key-managers` in Publisher REST API
Fixes https://github.com/wso2-enterprise/choreo/issues/4204
Fixes https://github.com/wso2-enterprise/choreo/issues/4202
> Add REST API impl to fetch IdPs configured for the API

- components/apimgt/org.wso2.carbon.apimgt.persistence.mongodb/src/main/java/org/wso2/carbon/apimgt/persistence/mongodb/MongoDBPersistenceImpl.java
Adding nulll check in order to retrieve the total when there are no apis created.
Please refer the discussion [#4000](https://github.com/wso2-enterprise/choreo/issues/4000)
> Adding the null check when retrieving total count

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionDeletionSimpleWorkflowExecutor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/WorkflowConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionDeletionSimpleWorkflowExecutorTest.java
To add https://github.com/wso2/carbon-apimgt/pull/10551 changes to master
This PR,
1. Set organizationID as the tenant domain of the api events
2. Fix subscription deletion issue when api and application names are equal in different organizations
as mentioned in PR: https://github.com/wso2/carbon-apimgt/pull/10551
Fixes: https://github.com/wso2-enterprise/choreo/issues/4625
Fixes: https://github.com/wso2-enterprise/choreo/issues/4273 with dependant PR https://github.com/wso2/product-microgateway/pull/2042
> Add OrganizationId for API events

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractKeyManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/AuthClient.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationTokenGenerateRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml
This PR adds changes to improve the `POST /applications/{applicationId}/oauth-keys/{keyMappingId}/generate-token` Devportal REST API to generate token using token exchange grant type.
Request format:
```curl
curl --location --request POST 'https://localhost:9443/api/am/devportal/v2/applications/91e162e8-576b-402e-bff7-0c40c6a7d1e7/oauth-keys/a5eb6431-8c1b-4d97-976b-81aba133681e/generate-token' \
--header 'authorization: Bearer ${accessToken}' \
--data-raw '{
"consumerSecret": "v2ZSpVrFSKo5sUlK9K1R6BZScdka",
"validityPeriod": 3600,
"revokeToken": null,
"scopes": [],
"grantType": "TOKEN_EXCHANGE",
"additionalProperties": {
"id_token_expiry_time": 3600,
"application_access_token_expiry_time": 3600,
"user_access_token_expiry_time": 3600,
"refresh_token_expiry_time": 86400,
"subject_token": …
```
> Improve the existing DevPortal REST API to generate token using token-exchange grant type

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/KeyManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/KeyManagersApiServiceImpl.java
When adding/updating an IdP/Key Manager a user can enter any type as they wish. But this may cause issues in the scenario explained in [1]. Hence a validation will be done.
- When adding/updating an IdP/Key Manager if the token type is EXCHANGED, the **type** will be validated against a set of allowed enum values.
- Remove the masking values if the token type is EXCHANGED during the retrieval of an IdP because the connector configs will not be used when the token type is EXCHANGED.
[1] https://github.com/wso2-enterprise/choreo/issues/4200
> Validating IdP type if the token type is EXCHANGED

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/KMClientErrorDecoder.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
Currently the `POST /applications/{applicationId}/oauth-keys/{keyMappingId}/generate-token` REST API is used to generate token from Devportal UI. If any error occurred during the token generation it returns a general error response as follows:
```json
{
"code":900967,
"message":"General Error",
"description":"Server Error Occurred",
"moreInfo":"","error":[]
}
```
This PR fixes it as:
```json
{
"code": 900967,
"message": "Bad Request",
"description": "Error occurred while calling token endpoint - No Registered IDP found for the JWT with issuer name : https://{okta-domain}/oauth2/default",
"error": []
}
```
> Fix the error response if the feign service call to token endpoint fails

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiCommonUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/ImportExportAPIServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Goals
To provide async API creation support for Choreo APIM core.[1]
Objective
Change the code to use getAsyncDefinition (registry) method in the persistence layer
[1]: Issue: https://github.com/wso2-enterprise/choreo/issues/5567
Git Actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/971542548
> Use persistsnce layer method for async api getDefinition

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/WebsubSubscriptionConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
To provide async API creation support for Choreo APIM core.[1]
Change the code to use getAsyncDefinition (registry) method in the persistence layer
[1]: Issue: https://github.com/wso2-enterprise/choreo/issues/5567
Git Actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/982064866
https://github.com/YasasRangika/carbon-apimgt/actions/runs/985304156(latest)
> Fix API get failure in Choreo Async API feature

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/test/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImplTestCase.java
To provide async API creation support for Choreo APIM core.[1]
Add unit test for getAsyncDefinition() method.
[1]: Issue: https://github.com/wso2-enterprise/choreo/issues/5567
Git Actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/982683451
> Add unit test for getAsyncDefinition method

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
This will retrieve the matching searched apis total with pagination & shows the correct total in network tab in Devportal.
Fixes: [#11393](https://github.com/wso2/product-apim/issues/11393)
> Retrieving correct search total in Devportal [master branch]

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
This will retrieve the matching searched apis total with pagination & shows the correct total in network tab in Devportal.
Fixes: [#11393](https://github.com/wso2/product-apim/issues/11393)
> Retrieving correct search total in Devportal [8.x branch]

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/KeyManagerDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/KeyManagersApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/KeyManagerInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/KeyManagerMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml
Fixes: https://github.com/wso2-enterprise/choreo/issues/4200
There is a requirement to retrieve the alias (audience) value stored in the IdP tables from the GET key-managers call from Devportal V2 REST API to show it in the Choreo Devportal UI User Keys tab. Hence the backend has been improved.
- A new property as alias has been added to KeyManagerInfoDTO as shown below
```
alias:
type: string
description: |
The alias of Identity Provider.
If the tokenType is EXCHANGED, the alias value should be equal to the audience value of the JWT token
example: https://localhost:8243/token
```
- If the token type is EXCHANGED the IS components will be called to get data from the IDP tables
- Set the alias in the KeyManagerConfigurationDTO from the above-retrieved data
- Set that alias value to the …
> Retrieving IdP alias in key-managers GET Devportal V2 REST API

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ThrottlingApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/11401
Improve the error messages from the backend when deleting an Advanced Throttling Policy that is already assigned to an API.
- Introduced a new error code
- Throw the errors as APIManagement Exceptions with a meaningful message
https://github.com/wso2/product-apim/pull/11403
> Improving the error messages from the backend when deleting an Advanced Throttling Policy that is already assigned to an API

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/RestApiAdminUtils.java
Fixes: https://github.com/wso2/product-apim/issues/11410
Underscores should be allowed in throttling policy names since they are quite common in naming conventions.
Changed the backend regular expression for throttling policy name.
- https://github.com/wso2/apim-apps/pull/37
> Changing the backend regular expression for throttling policy name

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
This fixes the monetization label being null in the API response returned for devportal listing. 
Issue: wso2/product-apim#6760
> Fix monetization label being null in API response error

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
This PR will change the default Keystore to use when signing APIKeys
Fixes 
https://github.com/wso2-support/carbon-apimgt/pull/2159
> Change default key store when signing APIkeys 

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
This PR fixes an issue where the `additionalPropertiesMap` is not updated properly when updating an API (PUT). Earlier, the values in `additionalPropertiesMap` will be overridden by the values in `additionalProperties` array. This issue is fixed this PR.
Related issue: https://github.com/wso2-enterprise/choreo/issues/6888
> Use additionalPropertiesMap when updating API

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
Fixes: https://github.com/wso2/product-apim/issues/11435
Previously the endpoint security OAuth credentials have been encrypted only during an update of an API. Now it will be done when adding an API as well.
- Refactored the existing code to encrypt OAuth Credentials, to a common place and called during the POST and PUT methods of APIs.
- Support both String and Object parameter for customParameters field in the endpoint security.
- https://github.com/wso2/product-apim/pull/11444
> Encrypt OAuth Credentials in the endpoint security when adding an API (POST request)

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
Related to [1].
- Adding a missing if statement which is related to WSDL import issues in Windows.
- Added a missing if statement which is related to WSDL import issues in Windows.
- OS: Ubuntu 20.04.2 LTS, Windows 10
[1] https://github.com/wso2/product-apim/issues/11448
> Adding a missing fix for WSDL import on Windows

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.internal.service/swagger.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/ApplicationsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/ScopeInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
We have a similar resource is Devportal rest API. However, that resource only returns the applications created by the user. Since admin users should be able to view the other applications in a specific tenant, this new resource will provide that capability.
Fixes : wso2/product-apim#11324
> Add a new resource to Admin rest API to query application details by providing the app id

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
Fixes https://github.com/wso2/product-apim/issues/11430 and sends `httpMethod` and `path` to AWS Lambda function.
The sample payload send to Lambda function would look like:
```json
{
"headers": {
"Accept": "*/*",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en,en-US;q=0.5",
"activityid": "401688ab-a955-42ee-b16e-96ab26ff31ec"
},
"pathParameters": {
"xxxx": "xxxxx"
},
"queryStringParameters": {
"xxxx": "xxxxx"
},
"body": {
"key1": "value1",
"key2": "value2"
},
"httpMethod": "POST",
"path": "/resource/{path}"
}
```
> Fix issue in passing headers, query/path params to lamda function from Gateway

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/11508
Fixes: https://github.com/wso2/product-apim/issues/11511
After updating a sequence of a SOAP to REST API, the changes were not persisted after a refresh, restarting the server etc. This will fix this problem.
Adding a missing function to **updateResourcePolicyFromRegistryResourceId**
> List any other related PRs
> Fixing the issue when updating the SOAP to REST API generated sequence

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- This PR fixes https://github.com/wso2-enterprise/choreo/issues/7298
- This PR includes a null check before getting the context from the title in OAS definition. If the title is empty it sets context as null.
> Fix NPE coming when having the title in OAS definition as empty

- components/apimgt/org.wso2.carbon.apimgt.eventing/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.eventing/src/main/java/org/wso2/carbon/apimgt/eventing/EventPublisher.java
- components/apimgt/org.wso2.carbon.apimgt.eventing/src/main/java/org/wso2/carbon/apimgt/eventing/EventPublisherEvent.java
- components/apimgt/org.wso2.carbon.apimgt.eventing/src/main/java/org/wso2/carbon/apimgt/eventing/EventPublisherFactory.java
- components/apimgt/org.wso2.carbon.apimgt.eventing/src/main/java/org/wso2/carbon/apimgt/eventing/EventPublisherFactoryProducer.java
- components/apimgt/org.wso2.carbon.apimgt.eventing/src/main/java/org/wso2/carbon/apimgt/eventing/internal/ServiceComponent.java
- components/apimgt/org.wso2.carbon.apimgt.eventing/src/main/java/org/wso2/carbon/apimgt/eventing/internal/ServiceReferenceHolder.java
- components/apimgt/pom.xml
This PR adds an eventing component to be used instead of the current event publishers. However, the wiring of the written publisher will be done as a seperate PR.
Resolves: https://github.com/wso2/product-apim/issues/11513
> Add eventing component for externalizing event publishing

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.unit-resolve.json
Add transport.receiver.session_timeout unit to unit-resolve.json
Related Issue: https://github.com/wso2/product-apim/issues/11346
[WUM][3.2.0] - https://github.com/wso2-support/carbon-apimgt/pull/3479
[U2][3.2.0] - https://github.com/wso2-support/carbon-apimgt/pull/3480
> Add transport.receiver.session_timeout unit to unit-resolve.json

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/EventHubConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIManagerConfigurationTest.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Supports passing parameters in the for event hub publishers in the format of:
```
<EventPublisherConfiguration>
<Properties>
<Property name="connectionString">connection_string_value</Property>
</Properties>
</EventPublisherConfiguration>
```
Supported deployment.toml configuration would be:
```
[apim.event_hub.publish.properties]
'connectionString'="sampleConnectionString"
'testParam2'="sampleTestParam2"
```
> Add event publisher parameters

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
Fixes wso2/product-apim#11527
**Note** : This error log is not reproducible in master/4.0.0 as we have added a null check at [1] to fix [2]. However the issue with role permissions not getting deleted is still there in master hence fixed it with this PR. 
[1]. https://github.com/wso2/carbon-apimgt/pull/9234
[2]. https://github.com/wso2/product-apim/issues/8921
> Remove tier permissions record when deleting subscription policies

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/11534
Fixes the issue when importing some WSDL definition files to create SOAP to REST APIs via the Publisher portal.
Use the WSDL content retrieved after validating the content, instead of directly using the File Input Stream when importing/creating a SOAP to REST API.
##Related PRs
- https://github.com/wso2/product-apim/pull/10981
> Fixing SOAP to REST API import issues with some WSDL definitions

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Fix for https://github.com/wso2/product-apim/issues/11500
As a part of this PR following changes are done
- Introduce additional extensions as default types
- Provide config to change the extensions types
> Add config to modify doc types

- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
when using scopes => apim:api_create apim:api_manage
{
"access_token": "c10a2418-aaa1-34e7-bbd0-8f7ecfe95c83",
"refresh_token": "332a10a2-5263-3930-a1db-d4b939cb19d6",
"scope": "apim:api_create apim:api_manage",
"token_type": "Bearer",
"expires_in": 3600
}
the APIM gives this error:
{"code":500,"message":"Internal server error","description":"Error while updating the swagger definition of the API: 83a20a71-5000-40fa-9f7c-aa168b3cdc88 - 900380:Insufficient permission to update the API::Updating the API is restricted as as it is PUBLISHED.","moreInfo":"","error":[]}
while using scopes =>  apim:api_create apim:api_publish
{
"access_token": "dcbaa7d1-fdd7-37bb-87f5-6dee7e5a43c1",
"refresh_token": "baa74507-56af-3c08-a55a-106a892437a4",
"scope": "apim:api_create apim:api_publish", …
> fix REST PUT API /apis/{apiId}/swagger error 500

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
- pom.xml
Reverts wso2/carbon-apimgt#10715
API creation and update fails due to invalid endpoint URL when creating an integration in Choreo. This PR will temporarily disable the validation till the proper fix is sent.
- https://github.com/wso2-enterprise/choreo/issues/7917
> Revert "Add endpoint validation"

- pom.xml
Upgrading openapi-generator version from 4.3.1.wso2v2 to 4.3.1.wso2v3
Related wso2/orbit PR: https://github.com/wso2/orbit/pull/461
> Upgrade openapi-generator Version

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/OAuthMediator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/OAuthTokenGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/client/OAuthClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthTokenGeneratorTest.java
Handle the issue when invoking endpoint secured by OAuth2.0, when expires_in is not present in the token response
Related Issue: https://github.com/wso2/product-apim/issues/11366
Successfully invoke an endpoint which is secured by OAuth2.0 even if the expires_in property is not present in the token response.
The issue was occurring when trying to set the validTill property using the expires_in value. So, changed the logic to set the validTill property only when expires_in is present in the token response.
Also, when expires_in is not present in the token response, changed the logic so that the token response will not be cached.
> Handle the Issue when Invoking an Endpoint Secured by OAuth2.0, when expires_in is not Present in the Token Response

- components/apimgt/org.wso2.carbon.apimgt.eventing/src/main/java/org/wso2/carbon/apimgt/eventing/EventPublisherFactory.java
This PR changes the interface to throw an exception so that the server startup can be interrupted upon an exception that is thrown while configuring the even publisher factory.
> Add EventPublisherException to EventPublisherFactory.configure method

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR adds the apim.throttling.jms.ssl configuration to the api-manager.xml.j2 template file.
Fixes https://github.com/wso2/product-apim/issues/11571
> Add apim.throttling.jms.ssl to the template

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractKeyManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractKeyManagerTestCase.java
Fixes: https://github.com/wso2/product-apim/issues/9541
Fixes: https://github.com/wso2/product-apim/issues/11585
Fix the issue in generating a valid infinite access token.
- When a user provides application access token expiry time, user access token expiry time, refresh token expiry time, or id token expiry time with a negative value, it will be rejected with an error.
- To generate infinite tokens the user needs to provide long values not the negative values.
- https://github.com/wso2/product-apim/pull/11591
> Fixing the issue in generating a valid infinite access token

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
- pom.xml
As of now, a user can send any invalid url as the backend url. With this fix, we do a validation on the user provided url in order to ensure its validity.
- Initial PR that added this capability was https://github.com/wso2/carbon-apimgt/pull/10715
- This was temporarily reverted with https://github.com/wso2/carbon-apimgt/pull/10764 due to an issue that arose with API deploy step in Choreo Integrations and Services https://github.com/wso2-enterprise/choreo/issues/7934
The [apache commons UrlValidator](https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/UrlValidator.html) that was used to introduce the validation, failed to validate custom domains. And hence, was failing to identify the TLD of Choreo. It seems to only validate URLs with known …
> Add endpoint validation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.notification/src/main/java/org/wso2/carbon/apimgt/notification/AbstractKeyManagerEventHandler.java
To fix AM_REVOKED_JWT table clean up process is not working as expected in APIM 3.2.0.
Fixes: https://github.com/wso2/product-apim/issues/11541
Invoke `ExpiredJWTCleaner` thread that is already there in the code from the `AbstractKeyManagerEventHandler.java` class.
**Git Actions:** https://github.com/YasasRangika/carbon-apimgt/actions/runs/1158197405
> Start ExpiredJWTCleaner thread to clean AM_REVOKED_JWT table

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
Fixes: https://github.com/wso2/product-apim/issues/11627
When displaying the multiple version of APIs feature in the dev portal is disabled, we need to display the search count based on the default version of the API
Changed the total length while filtering the APIs with multiple versions to display
- https://github.com/wso2/product-apim/pull/11639
> Updating the length of filtered multiple versioned APIs list

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.notification/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.notification/src/main/java/org/wso2/carbon/apimgt/notification/AbstractKeyManagerEventHandler.java
- components/apimgt/org.wso2.carbon.apimgt.notification/src/test/java/org/wso2/carbon/apimgt/notification/AbstractKeyManagerEventHandlerTest.java
Fixes: https://github.com/wso2/product-apim/issues/11642
Fixing the NPE arisen due to the missing tokenType in the IDN_OIDC_PROPERTY table.
- Since the IDN_OIDC_PROPERTY table is not populated with the data after migration, added an if block to assign `Default` to the tokenType if it is null when accessing the tokenType.
- Wrote a unit test for the function **handleTokenRevocationEvent**
- Unit tests
Provided a unit test for **handleTokenRevocationEvent** function
> Fixing the NPE error for the migrated applications

- components/apimgt/org.wso2.carbon.apimgt.common.jms/src/main/java/org/wso2/carbon/apimgt/common/jms/utils/JMSUtils.java
- components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/test/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSUtilsTestCase.java
need to mask the credentials in JMS error logs
> Improve parameter masking for JMS configs in error logs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/11454
Fixing the issue of endpoint security when using an OAS definition to create an API
Encrypted the OAuth credentials in the  **POST apis/import-openapi** as previously done for POST apis: and PUT apis/{apiId}.
- https://github.com/wso2/product-apim/pull/11727
> Encrypting the endpoint secret during import OAS REST API call

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
This is to increase the character length limit from 50 to 60 ( Since the limit in Choreo is 60 )
> Increase the charactor length limit of the API name attribute from 50 to 60

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
This PR introduces the following changes:
- Updates the URL validation logic to allow two slashes in the path component of the URL
- Removes the temporarily introduced feature flag for URL validation (this was introduced by [1])
- [1] https://github.com/wso2/carbon-apimgt/pull/10773
> Update endpoint validation fix

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/KeyManagerDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/KeyManagerMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/KeyManagerMappingUtil.java
As $subject, this will add two new parameters called display token endpoint and display revoke endpoint to admin key manager REST APIs and set those values in dev portal REST API token endpoint and revoke endpoints.
1. https://github.com/wso2/product-apim/issues/11590
> Add display token endpoint and display revoke endpoint to admin key manager REST APIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/ClientInfo.java
- Resolves https://github.com/wso2/product-apim/issues/11620
This PR introduces the support to display the application name on the consent page. By default, the consent page follows the format: **\<tenant\>\_\<application uuid\>\_\<key type\>**. With the proposed changes, the application name would appear in the consent page, so as to make the user-facing interface more meaningful. To achieve this, the following config should be set to true in `deployment.toml`:
```
[oauth]
show_display_name_in_consent_page = true
```
Thus improved consent page is as follows:
- https://github.com/wso2-extensions/apim-km-wso2is/pull/57
- https://github.com/wso2/carbon-identity-framework/pull/3740
- https://github.com/wso2/product-apim/pull/11716
> Add support to display application name in consent page

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticatorTest.java
Fixes: https://github.com/wso2/product-apim/issues/11745
This PR fixes the issue where Basic Authentication drops the Authorization header at the gateway level when a load test is run. This happens due to the remainingAuthHeader variable in OAuthAuthenticator when both OAuth and Basic security are enabled for the testing API.
> Fixing basic auth missing credential issue

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/KeyManagerConfiguration.java
Add Asgardeo idp type as an allowed IdP
Fixes https://github.com/wso2-enterprise/choreo/issues/8480
> Add Asgardeo IdP type

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/src/main/java/org/wso2/carbon/apimgt/rest/api/service/catalog/impl/ServicesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/src/main/java/org/wso2/carbon/apimgt/rest/api/service/catalog/utils/ServiceEntryMappingUtil.java
$subject. This PR includes following tasks.
- Refactoring Service Catalogue - getServiceDefinition Endpoint
- Refactoring Service Catalogue - importService Endpoint
- Refactoring Publisher - importServiceFromCatalog Endpoint
- Refactoring Publisher - reimportServiceFromCatalog Endpoint
Related Issue: https://github.com/wso2/product-apim/issues/11656
Related EPIC: https://github.com/wso2/micro-integrator/issues/2397
> Adding WSDL definition and proxy service support for Service Catalog APIs

- .azure/masterBranchPRValidation.yaml
Add publishing docker-compose logs step to contract tests
Related PR:
https://github.com/wso2-enterprise/choreo-product-apim/pull/275
> Add publishing docker-compose logs step to contract tests

- .github/workflows/coverage.yml
- .github/workflows/main-forks.yml
- .github/workflows/main.yml
This PR adds `apim-grant-type-token-tests` to workflow yamls. 
Note:
With [1], the exisiting `GrantTypeTokenGenerateTestCase` was moved to a separate test tag with the name, `apim-grant-type-token-tests`. 
1. https://github.com/wso2/product-apim/pull/11716
> Add apim-grant-type-token-tests to workflow ymls

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
To fix that the imported api is not searchable in the search bar on the subscription section but showing in the API list in the Dev portal UI.
Fixes: https://github.com/wso2/product-apim/issues/11806
The Dev portal UI that imported api by apictl tool is not searchable in the search bar on the subscription section but showing in the API list.
Used latest four parameter `changeLifeCycleStatus(tenantDomain, apiId, lifecycleAction, lifecycleMap)` method instead of two parameter method `changeLifeCycleStatus(apiId, lifecycleAction)`
**Git Actions:** https://github.com/YasasRangika/carbon-apimgt/actions/runs/1337479982
> Fix API listing after export and import from APICTL in DevPortal

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/783
Fising the NPE when isAdvertised property is not there in the api.yaml when the project is created using the apictl init with the definition flag.
- Added a null check. If the isAdvertised value is null, set it to False
The user story that broke in [1] is fixed now.
- https://github.com/wso2/product-apim-tooling/pull/814
- https://github.com/wso2/product-apim-tooling/pull/814
- Ubuntu 20.04.4 LTS
[1] https://github.com/wso2/product-apim-tooling/issues/783
> Fixing the NPE when isAdvertised is not specified in api.yaml of apictl

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/ImportExportAPIServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/810
Fixes: https://github.com/wso2/product-apim-tooling/issues/742
Fixes: https://github.com/wso2/product-apim/issues/11212
Modifying the apictl artifacts version and fixing error messages related apictl export
- Updated the apictl artifacts version to 4.1.0
- Validated the revision ID when exporting an API/API Product and provided a meaningful error message
- Improved the error responses of Publisher V2 apis/export and api-products/export
- https://github.com/wso2/product-apim-tooling/pull/817
- https://github.com/wso2/product-apim-tooling/pull/817
> Modifying the apictl artifacts version and fixing error messages related apictl export

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Related issue: https://github.com/wso2-enterprise/choreo/issues/8890
scope validation failures will give the following error with 400 status code after this fix:
`{"code":900988,"message":"Scope already assigned locally by another API","description":"Scope already assigned locally by another API","moreInfo":"","error":[]}`
> Give 400 Bad Request for scope validation failure.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationMappingUtil.java
Fix issue of token type changing from `Opaque` to `JWT` when updating a migrated application.
Fixes: https://github.com/wso2/product-apim/issues/11888
Token type should not change when updating a migrated application
- Implemented the logic to retain the `DEFAULT` token type of migrated applications unless the token type is changed to `JWT`.
- Added a condition to prevent the change of token type of applications having `JWT` token type.
| Existing App Token Type  | Token Type in Request | Action | Token Type Added to DB |
| ------------- | ------------- | ------------- | ------------- |
| DEFAULT  | OAUTH  | Allowed | DEFAULT |
| DEFAULT  | JWT  | Allowed | JWT |
| OAUTH  | OAUTH  | Allowed | OAUTH |
| OAUTH  | JWT  | Allowed | JWT |
| JWT  | OAUTH  | Not Allowed | - |
| JWT  | JWT  | …
> Fix Issue of Token Type Changing from Opaque to JWT When Updating a Migrated Application

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/client/OAuthClient.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
This PR will improve the behavior when invoking endpoint secured by OAuth2.0, when expires_in is not present in the token response by allowing to configure a value to expire the token by default.
Related Issue: wso2/product-apim#11366
The default value can be provided in **deployment.toml** under the **[apim.mediator_configs.oauth]**
```
[apim.mediator_configs.oauth]
expires_in = "3600"
```
The default value will be 3600 seconds.
> Make expires_in time configurable if not specified in Token Response

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ExternalGatewayNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.solace/src/main/java/org/wso2/carbon/apimgt/solace/notifiers/SolaceApplicationNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.solace/src/main/java/org/wso2/carbon/apimgt/solace/notifiers/SolaceKeyGenNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.solace/src/main/java/org/wso2/carbon/apimgt/solace/notifiers/SolaceSubscriptionsNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.solace/src/main/java/org/wso2/carbon/apimgt/solace/utils/SolaceNotifierUtils.java
Without this check, the solace notifiers will always retrieve API objects from the DB even though solace environments are not configured.
> Improve external gateway and solace notifiers to reduce db queries

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
This issue is related to APIM migration from 1.9.0 to 4.0.0. After the APIs are migrated from APIM 1.9.0 to 4.0.0, the endpoint deployment fails at the runtime with the below error. in APIM 1.9.0, the endpoint timeout value is maintained as an integer in the JSON configuration object which in turn is stored in the registry metadata file. When this JSON is deserialized into a DTO at the server startup a decimal point is added to the timeout value via GSON. This leads to a NumberFormatException during the endpoint deployment. This issue will be fixed from this PR and add the update for the Master branch.
Fixes https://github.com/wso2/product-apim/issues/12030
Fixes https://github.com/wso2/product-apim/issues/12079
> [Master] Fix for Endpoint timeout duration expected as a number but was not number

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/DeployedAPIRevision.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/UnDeployedAPIRevision.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/dto/UnDeployedAPIRevisionDTO.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/resources/api.yaml
> API provider throws exceptions when un-deploy a revision , but those exceptions doesn't catch from API service implementation.Purpose of this PR is to catching those exceptions.
FIX : https://github.com/wso2-enterprise/choreo/issues/9175
> Remove un-deployed revision entries from the db

- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/utils/JWTUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/OAuthJwtAuthenticatorImpl.java
This PR contains following changes:
1. Remove additional check on JWT's org claim. This is done since now in the JWT we receive org handle instead of org UUID.
2. To push this as non breaking change, removed feature flag check and added a check to verify whether scope contains org ID to get the similar behaviour. 
Sample JWT payload
```
{
"sub": "e9fe9002-6623-4d63-acfe-e07c5d8bcf76",
"aut": "APPLICATION_USER",
"aud": "Wxqy0liCfLBsdpXOhkcxZz6uLPka",
"nbf": 1639120199,
"azp": "Wxqy0liCfLBsdpXOhkcxZz6uLPka",
"scope": "apim:admin apim:api_manage apim:subscription_manage apim:tier_manage",
"organization": "erandiganepola",
"iss": "https://apim.preview-dv.choreo.dev:443/oauth2/token",
"organizations": [
"19bfb6f6-13db-44bb-99a5-ccfd478f4301",
"f79950b4-f28b-4dc7-a41a-5e50fac6a9fe"
],
"exp": …
```
> Remove feature flag check and additional check on JWT's org claim

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/LogsHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/LogsHandlerTestCase.java
To fix Websocket APIs are not working when correlation logs are enabled
fixes: https://github.com/wso2/product-apim/issues/11836
Added validation to check whether the headers are not available.
Git actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/1529688729
> Fix Websocket APIs are not working when correlation logs are enabled

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
This PR introduces the relevant changes for $subject. 
Fixes for : https://github.com/wso2-enterprise/choreo/issues/9537
Configurations for max revision count can be added to the `tenant-conf.json` file as follows.
```JSON
{
"EnableMonetization" : false,
"EnableRecommendation" : false,
"IsUnlimitedTierPaid" : false,
"ApiMaxRevisionCount" : 34,
"ExtensionHandlerPosition": "bottom",
"RESTAPIScopes": {
```
> Make max revision count configurable in APIM

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
To fix failover endpoint certificate is not added to the project and not working with the choreo-connect backend.
fixes: https://github.com/wso2/product-apim/issues/11856
and
fixes: https://github.com/wso2/product-apim/issues/11982
and
fixes: https://github.com/wso2/product-apim/issues/11946
Git actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/1557500077
> Fix failover endpoint certificate is not added to project and not working with choreo-connect backend

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIAdmin.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ThrottlingApiServiceImpl.java
Fixes wso2/product-apim#12105
Add a separate method in APIAdminImpl to fetch policies (getPolicies) and avoid to skip the unauthenticated tier as done in provider.
> Fix issue with missing unauthenticated tier in admin portal

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
- pom.xml
This PR removes the following unused dependencies.
- commons-compress
- kubernetes-client
> Remove unused commons-compress and kubernetes-client

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/AuthClient.java
A Part of the fix that was included in https://github.com/wso2/carbon-apimgt/pull/10610 PR was reverted by the https://github.com/wso2/carbon-apimgt/pull/10860 PR. This PR adds back the reverted code change.
> Add reverted fix which was caused by token generation failure in devportal fix

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/analyzer/SubscriptionAnalyzer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandlerTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/GraphQLSchemaDefinition.java
- pom.xml
GraphQL version upgrades from 13.0 to 17.3 to fix [1] [2]. The Codebase had to be refactored to fit with latest graphql version.  Related Orbit PR [3] is merged and bundle is deployed.
Also Added fix for [4]
[1] https://github.com/wso2/product-apim/issues/12025
[2] https://github.com/wso2/product-apim/issues/12044
[3] https://github.com/wso2/orbit/pull/552/files
[4] https://github.com/wso2/product-apim/issues/12301
> Refactoring codebase to fit with latest graphql-java version

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java
- Resolves https://github.com/wso2/product-apim/issues/12126
This PR fixes the issue where the API invocations result in a 404 response when the `Gateway Profile` is started first.
The artifact retrieval step fails with an artifact synchronization exception when the gateway profile is started first. This is encountered with the inability to retrieve the existing artifacts since the control plane is not up yet. In order to fix the aforementioned issue, a delaying factor is introduced to the thread that is trying to retrieve the artifacts
> Fix artifact retrieval issue when gateway worker node is started first

- pom.xml
This PR adds the support for af-south-1 Cape town AWS region for lambda functions.
Fixes https://github.com/wso2/product-apim/issues/12225
> Update AWS SDK to 1.11.1034

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandler.java
Fixes: https://github.com/wso2/product-apim/issues/12481
Added WebsocketHandler constructor accepting the WebsocketInboundHandler and WebsocketOutboundHandler, so that these classes can be customized
> Adding a new WebsocketHandler constructor

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/client/OAuthClient.java
https://github.com/wso2/product-apim/issues/12425
Above issue occurs due to inability to get previous token response from the cache and decode since the validTill value comes as null.
https://github.com/wso2/carbon-apimgt/pull/10901
> Fix not setting validTill value in tokenResponse

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fixes part of https://github.com/wso2/product-apim/issues/11500 with default support for json, yaml and md files.
> Add support to add json yaml and md type documents

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/GraphQLRequestProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/GraphQLResponseProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/GraphQLRequestProcessorTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/GraphQLResponseProcessorTest.java
Fix: https://github.com/wso2/product-apim/issues/12334
> Skipping scope validation for GraphQL subscription when security disabled for subscription operation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
$subject is needed to ensure the comparable version values of an API artifact in the registry has been populated successfully while running the migration client. It calls to APIUtil.getAPI method and verifies the values.
> Adding versionComparable attribute to getAPI flow

- pom.xml
This PR updates kernel version to `4.6.3-beta` along with the relevant identity components.
> Update kernel and identity versions

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/AbstractAPIMgtGatewayJWTGenerator.java
Fix wso2/product-microgateway#2687
jwtClaimSetBuilder expect the `iat` and `exp` claim values to be in milliseconds and internally converts the values to seconds when generating the jwt string. hense we need to provide milliseconds value to the builder.
> Fix backend jwt's incorrect `iat` and `exp` claims

- features/apimgt/org.wso2.carbon.apimgt.core.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.internal.service.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.keymanager.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.persistence.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.tokenmgt.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.tracing.feature/pom.xml
Changed module names to be consistent with other module names. Other modules in apimgt features contain proper title case module names. Following change is done.
before: `Api management ...`
after: `Api Management ...`
> Refactor module names of features with Api Management prefix

- components/apimgt/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.admin.feature/pom.xml
- features/apimgt/pom.xml
- service-stubs/apimgt/pom.xml
This PR renames aggregator module names with `Aggregator Module` suffix for better understanding.
> Refactor aggregator modules with proper names

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/OperationPolicy.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/OperationPolicyDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapsePolicyAggregator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/OperationPolicyMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/OperationPoliciesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/OperationPoliciesApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/OperationPoliciesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
A new property is added as policy version to the API object. Policy specs are updated via https://github.com/wso2/product-apim/pull/12612.
Fixed https://github.com/wso2/product-apim/issues/12643
Added two new scopes for common operation policies.
> Add the policy versioning support and few bug fixes for Operation policies

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS2ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas2/oas2_uri_template_with_responsesObject.json
As $subject, this will add a workaround for OASParser2 to remove reposnsesObject inorder to fix swagger-editor issue for swagger2.
- https://github.com/wso2/product-apim/issues/12561
> Remove responsesObject from swagger to fix swagger-editor issue for swagger2

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/898
Retrieving the updated API with correct swagger and URI templates in apictl import
Earlier incorrect swagger and the URI templates was passed during API revision deployment. This fixes it by correctly retrieving the updated imported API.
> Retrieving the updated API with correct swagger and URI templates in apictl import

- pom.xml
Upgrade carbon-identity-outbound-auth-samlsso version from 5.3.18 to 5.3.34
product-apim - https://github.com/wso2/product-apim/pull/12690
> Upgrade carbon-identity-outbound-auth-samlsso Version

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/InboundMessageContext.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/GraphQLRequestProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/GraphQLResponseProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/GraphQLRequestProcessorTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/GraphQLResponseProcessorTest.java
**Approach**
* A new field ctx was introduced to the  inboundMessageContext to hold ChannelHandlerContext
* API_ELECTED_RESOURCE is set as a property to ctx
Related Issue : https://github.com/wso2/product-apim/issues/12197
Note : The wildcard entries in the screenshot are from invocations before applying this fix.
> Display subscription operation as the resource path in analytics graphs

- components/apimgt/org.wso2.carbon.apimgt.api/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.internal.service/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.output.adapter.http/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.devops/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/pom.xml
- components/apimgt/samples/org.wso2.carbon.apimgt.samples.calculator/pom.xml
- components/apimgt/samples/org.wso2.carbon.apimgt.samples.pizzashack/pom.xml
* Added missing version for REST API module names
* org.wso2.carbon.apimgt.internal.service/pom.xml
* org.wso2.carbon.apimgt.rest.api.devops/pom.xml 
* org.wso2.carbon.apimgt.rest.api.service.catalog/pom.xml
* Added name of APIs for sample API module names
* org.wso2.carbon.apimgt.samples.calculator/pom.xml
* org.wso2.carbon.apimgt.samples.pizzashack/pom.xml
* Renamed module names with title case and consistency
* org.wso2.carbon.apimgt.api/pom.xml
* org.wso2.carbon.apimgt.output.adapter.http/pom.xml
* org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
> Refactor apimgt component module names

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- Resolves https://github.com/wso2/product-apim/issues/12767
With this PR, the endpoint validation logic is bypassed for Consul endpoints like `consul(google,https://10.10.1.5:5000/)`
> Modify endpoint validation to allow consul endpoints

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/GatewayArtifactsMgtDAO.java
Fixes: https://github.com/wso2-enterprise/choreo/issues/12586
Deployed the same revision in two gateways. Following is the `deployment.json` file returned by `/runtime-metadata` endpoint.
```
{
"type": "deployments",
"version": "v4.1.0",
"data": {
"deployments": [
{
"apiFile": "6271d4fe543df9406cf9e355-6271e18d3451604807f7fca1",
"environments": [
{
"name": "Production",
"vhost": "prod.e1-us-east-azure.choreoapis.dev"
},
{
"name": "Default",
"vhost": "prod.e1-us-east-azure.choreoapis.dev"
}
],
"organizationId": "WSO2",
"apiContext": "/shalkiwenushika/cp-test-api4/1.0.0"
}
]
}
```
Deleted the deployment for `Default` gateway. After the fix, /runtime-metadata endpoint returned the correct deployment details:
```
{ 
"type": "deployments",
"version": "v4.1.0",
"data": { …
```
> Fix issues in /undeploy-revision path

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApiProductsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
Fixes: https://github.com/wso2/product-apim-tooling/issues/910
Fixing apictl get keys for API Products with Internal/devops user
- Added the apim:api_product_import_export to GET /{apiProductId}
> Fixing apictl get keys for API Products with Internal/devops user

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
This PR fixes an issue where the migrated APIs with scopes throw an error when deploying the API without saving it. This fix checks whether legacy scopes exist for the API and adds them to the definition if no scopes are already defined.
Fixes https://github.com/wso2/product-apim/issues/12783
> Fix scope missing issue in migrated APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
This PR fixes an issue where the description is not added to the API based on the description in the OpenAPI definition.
Related issue: https://github.com/wso2/product-apim/issues/12640
> Fix description not being populated when importing openapi definition

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/api-manager/issues/115
Adding a meaningful message when importing the OpenAPI specification/Swagger definition during an API import via apictl
- If the Open API/Swagger definition has errors, a message like the below will be displayed.
wasura@wasura:~/Desktop/apictl$ apictl import api -f API410API/ -e production
Error importing API.
Status: 400
Response: {"code":900754,"message":"Error while parsing OpenAPI definition","description":"attribute paths.'/test/{val_1}_{val_2}/abc'. Declared path parameter val_1}_{val_2 needs to be defined as a path parameter in path or operation level. attribute paths.'/test/{val_1}_{val_2}/xyz'. Declared path parameter val_1}_{val_2 needs to be defined as a path parameter in path or operation level","moreInfo":"","error":[]} …
> Adding a meaningful message when importing the OpenAPI specification/Swagger definition during an API import via apictl

- components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/Util.java
- pom.xml
Upgrading the jaeger client version to 1.8.0 which contains libthrift 0.16.0 and upgrading the okhttp and okio versions to 4.9.3 and 2.8.0 accordingly.
Upgrading libthrift version to 0.16.0 and okhttp and okio versions to 4.9.3 and 2.8.0 accordingly.
- After bumping the jaeger client version, there were some interface changes related to TextMapAdapter. Those changes had to be properly modified in the code.
- Updated the pom with the correct versions.
- Ubuntu 20.04.3 LTS
> Upgrading the jaeger client, okhttp and okio versions

- pom.xml
Bumping the identity, identity inbound and synapse versions with regard to the changes done in [1], [2] and [3] accordingly.
Bumping the identity, identity inbound and synapse versions.
- Bumped the carbon identity version to reflect the change in [1].
- Bumped the identity inbound version to reflect the change in [2].
- Bumped the synapse version to reflect the change in [3].
- https://github.com/wso2/product-apim/pull/12918
[1] https://github.com/wso2/carbon-identity-framework/pull/4066
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1858
[3] https://github.com/wso2/wso2-synapse/pull/1966
> Bumping the identity, identity inbound and synapse versions

- pom.xml
Revert the synapse version to 2.1.7-wso2v289 to omit the test failure due to [1].
The synapse version was initially bumped to reflect the changes via [2]. But that bumped version had changes of [1] too, which fails some integration tests in product-apim. Hence, downgrading the synapse version for now.
Omit the test failure due to https://github.com/wso2/wso2-synapse/pull/1970
[1] https://github.com/wso2/wso2-synapse/pull/1970
[2] https://github.com/wso2/carbon-apimgt/pull/11295
> Reverting the synapse version to 2.1.7-wso2v289

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/keymgt/KeyMgtNotificationSender.java
Address: https://github.com/wso2-enterprise/choreo/issues/13718
This fix will work for choreo but will break some cases for on-premise. So do not add this fix to master branch.
And this is already fixed in master branch in a different way (send KM events through event hub interface)
> Avoid sending events to EXCHANGE type KMs

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/listener/ExtensionListenerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/payloadhandler/SynapsePayloadHandler.java
This PR includes two changes with regard to the gateway.
1. When building the message if a json payload already exists in the MessageContext it is returned as it is without rebuilding it. 
2. Allowing to pass the charset value as well in the Content-Type header.
Also note that these changes were prior added to the APIM 4.0.0 version using this [PR](https://github.com/wso2-support/carbon-apimgt/pull/4775).
> Returning the existing json payload when building message from the context

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/AbstractAPIMgtGatewayJWTGenerator.java
The fix is cherry-picked from https://github.com/wso2/carbon-apimgt/pull/11122
Fix wso2/product-microgateway#2687 
jwtClaimSetBuilder expect the iat and exp claim values to be in
millinseconds and internally converts the values to seconds when
generating the jwt string.
> jwt: Use milliseconds in jwtClaimSetBuilder

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Following PR[1]  has bee raised in order to solve the issue[2]. But , after a clarification regarding the issue we identify that returns a 200 HTTP status code for duplicate entry exception was a expected behavior.Since raise this PR to revert that change.
[1] https://github.com/wso2/carbon-apimgt/pull/11301
[2] https://github.com/wso2-enterprise/choreo/issues/13035
> Remove throwing the 409 when detect duplicate entry while deploying revision

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
Fixes https://github.com/wso2/api-manager/issues/309. Setting following properties to message context from Authentication flow if it's not set in CORS handler:
```
APIConstants.API_ELECTED_RESOURCE
APIConstants.API_RESOURCE_CACHE_KEY
APIConstants.REST_METHOD
```
> Fix issue when globally disabling cors

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Convert entityInfo into a JsonObject inside logAuditMessage. 
Will be able to close https://github.com/wso2/carbon-apimgt/pull/11333 with this PR.
> Convert entityInfo into a JsonObject inside logAuditMessage

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/CredentialsCache.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- pom.xml
This PR adds STS AssumeRole support to Lambda feature to invoke Lambda functions using cross accounts. Fixes https://github.com/wso2/api-manager/issues/365.
> Add STS AssumeRole support to Lambda

- components/apimgt/org.wso2.carbon.apimgt.cache.invalidation/src/main/java/org/wso2/carbon/apimgt/cache/invalidation/APIMgtServerStartupListener.java
Related : https://github.com/wso2-enterprise/choreo/issues/14234
Debug logs were added to [APIMgtServerStartupListener.java](https://github.com/wso2/carbon-apimgt/compare/9.2.x...ThusharaSampath:carbon-apimgt:9.2.x?expand=1#diff-7bdf1d09c1caacf359c1dce059c15e643a2bb5020e0a9bb77ee17d5c889156c7) class's invoke() and shutDownListener() methods to aid JMSListener related bug fixing.
p.s: All other Listener classes have this log in these particular functions.
> Add Unsubscribe debug logs

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataLoaderImpl.java
- Add null check when retrieving APIs against gateway labels
- Related Issue: https://github.com/wso2/api-manager/issues/103
When fetching APIs against gateway labels array, the implementation returns the API even it is null and hence, the loop finishes with the first gateway label and does not search for the API with other gateway labels. This PR adds the null check so that no null API is returned.
> Add null Check When Retrieving APIs Against Gateway Labels

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Remove the WSDL FileInputStream Reset Logic
Related Github Issue: https://github.com/wso2/product-apim/issues/12149
When creating a SOAP API or generating SOAP to REST, since the WSDL content retrieved after validating the content is used  instead of directly using the FileInputStream, there is no need of the FileInputStream reset logic. Hence, removed the FileInputStream reset logic.
> Remove the WSDL FileInputStream Reset Logic

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
Resolves https://github.com/wso2-enterprise/choreo/issues/14546
If an API present in the mongoDB search result is not persisted in the APIM DB, APIM DB retrival call will fail for that API. And will give a 500 status code to devportal API search call (`devportal/v2/apis`). This fix will skip such an APIs so that remaining search results will be sent with a 200 status code.
> Skip the API that is not stored in APIM DB in devportal API search

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/AsyncApiParser.java
> Allow web socket APIs to be deployed with only the sandbox endpoint
> Fix: https://github.com/wso2/api-manager/issues/562
> Allow web socket APIs to be deployed on sandbox endpoint

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/model/OpenAPIRequest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandlerTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/TestSchemaValidator.java
Making the Header validations of Swagger Schema Validator Case Insensitive
Related Issue: https://github.com/wso2/api-manager/issues/559
Feed the lower cased headers to the schema validation library and pick the lower cased headers from the swagger for header validations.
> Making the Header validations of Swagger Schema Validator Case Insensitive

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/operationPolicy/operation-policy-specification-schema.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/EnvironmentsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/KeyManagerConfigurationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/OperationPolicyDataDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/OperationPolicyMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtilsTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/OperationPoliciesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/OperationPoliciesApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/OperationPoliciesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
**Purpose**
Fix: [wso2/api-manager#223](https://github.com/wso2/api-manager/issues/223) [wso2/api-manager#344](https://github.com/wso2/api-manager/issues/344) [wso2/api-manager#345](https://github.com/wso2/api-manager/issues/345)
**Approach**
- Add export operation policy API to export a policy by name and version.
- Add import operation policy API to accept an archive file.
- Add `policyName` and `policyVersion` query parameters support for `GET` operation polices API
- Adde Unit Test for `ImportAPIPolicy` function
> Add REST APIs for APICTL Common API Policy Operations

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/AbstractAPIMgtGatewayJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
This PR fixes the issue of generated backend JWTs are identified as invalid JWTs due to the padding applied in the token.
Fixes https://github.com/wso2/product-apim/issues/12655
> Remove padding in backend JWT encoding

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
To fix returning an HTML page when invoking a new version of SOAP to REST API.
Fixes: https://github.com/wso2/product-apim/issues/12150
Added a conditional clause to update the swagger definition to get the sequences from swagger before deploying a new revision.
Git Actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/2075607917
> Fix issue while invoking a new version of SOAP to REST API

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Resolves: https://github.com/wso2-enterprise/choreo/issues/14755
Send custom error codes when an API is partially saved in DBs.
In this change, 
- When an API is not preserved in the SQL DB, APIM will throw an specific exception with the error code (900359). (since the existence of the API in mongoDB is checked before SQL)
- When an API is not preserved in the mongoDB, the APIM will send a 404 response.
> Send a custom error code when an API with no DB record is requested

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/api-manager/issues/663
Support importing locked APIs and API Products.
- Converted the API/API Product life cycle state from CREATED to PUBLISHED and then PUBLISHED to BLOCKED if the API/API Product should be in the BLOCKED state
- Converted the API/API Product life cycle state from CREATED to PUBLISHED and then PUBLISHED to DEPRECATED if the API/API Product should be in the DEPRECATED state 
- Converted the API/API Product life cycle state from CREATED to PUBLISHED and then PUBLISHED to DEPRECATED and then DEPRECATED to RETIRED if the API/API Product should be in the RETIRED state 
- OpenJDK jdk-11.0.16
- Ubuntu 20.04.3 LTS
> Support importing locked APIs and API Products using apictl

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandlerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
- pom.xml
Fixes: https://github.com/wso2/api-manager/issues/661
Fixing WS close code missing issue and adding the missing master fix of setting API_PROPERTIES to WS channelctx 
- Adding the missing master fixes of [1].
- Bumping the synapse version to reflect the netty version upgrade that is required for compile time [2]
- By setting the property _api.ut.WS_SC_ inside exceptionCaught.
[1] https://github.com/wso2/product-apim/issues/12541
[2] https://github.com/wso2/wso2-synapse/pull/1999
> Fixing WS close code missing issue and adding the missing master fix of setting API_PROPERTIES to WS channelctx 

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/api-manager/issues/713
Perform a validation: if the API/API Product is in BLOCKED/RETIRED/DEPRECATED state, then only if the current state was set to CREATED, then Publish the API/API Product before Blocking, Retiring, or Deprecating
> Fixing the issue when importing Blocked API/API Products with import update

- pom.xml
- Bump siddhi version from 3.2.7 to 3.2.8
- Bump event processor version from 2.3.2 to 2.3.3
- Related Issue: https://github.com/wso2/api-manager/issues/655
> Bump siddhi and event processor Versions

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
Fixes: https://github.com/wso2/api-manager/issues/714
Adding the missing values in API_PROPERTIES when invoking WS APIs using Opaque tokens
##Approach
- Earlier the API_PROPERTIES were set based on the values in the authenticationContext. However, authenticationContext is not common to both the JWT and Other (Opaque) flows. 
- Because of that, some of the values such as the Application Name, API Name, Username, and API type were null in the API_PROPERTIES. 
- Hence, using APIKeyValidationDTO information solved the problem, because it is common to both JWT and Opaque token validation flows.
- Improved the unit tests as well to validate the API_PROPERTIES correctly.
> Adding the missing values in API_PROPERTIES when invoking WS APIs using Opaque tokens

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/OAuthJwtAuthenticatorImpl.java
As per the previous logic, the scope array is getting set to an empty array when the `urn:choreo:<ORG_ID>:` is not included in the JWT claim set. This PR will fix that issue.
```
[2022-09-16 07:35:23,010] DEBUG ecb3f583-5606-4ffc-8824-9644af004a7c - OAuthJwtAuthenticatorImpl Starting JWT token validation ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB9mu3T6Y
[2022-09-16 07:35:23,113] DEBUG ecb3f583-5606-4ffc-8824-9644af004a7c - OAuthJwtAuthenticatorImpl scopeClaim in the signedJWTInfo: apim:admin apim:api_manage apim:dcr:app_manage apim:publisher_settings apim:subscription_manage apim:tier_manage choreo:role_manage choreo:user_manage environments:view_dev environments:view_prod
[2022-09-16 07:35:23,113] DEBUG ecb3f583-5606-4ffc-8824-9644af004a7c - OAuthJwtAuthenticatorImpl scopes after spliting …
```
> Fix scope validation issue in JWT token validation path

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsDB2.java
Fix wso2/api-manager/issues/669 for master branch
Add the query string GET_APPLICATIONS_PREFIX_CASESENSITVE_WITH_MULTIGROUPID
wso2-support/carbon-apimgt/pull/5365
> Add missing query string for DB2

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
This PR adds null checks to swagger and asyncAPI json strings in the ExportUtils.
Fixes https://github.com/wso2/api-manager/issues/634
> Add null check to swagger and asyncAPI json strings

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractKeyManager.java
When checking whether a key manager can handle an access token pattern, it will only return true if the whole string matches the given pattern for the key manager.
Fix : https://github.com/wso2/api-manager/issues/749
> Change the regex matcher to match the whole string

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/OAuthJwtAuthenticatorImpl.java
As per the previous logic, the scope array is getting set to an empty array when the `urn:choreo:<ORG_ID>:` is not included in the JWT claim set. This PR will fix that issue.
9.22.x branch PR: https://github.com/wso2/carbon-apimgt/pull/11470
> Fix JWT scope validation failure

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
This PR adds support for both /v2 and /v3 endpoints to make both of those endpoints work temporarily for APIM upgrade testing. 
Related Issue: https://github.com/wso2-enterprise/choreo/issues/9668
> [9.22.x] Add support for both /v2 and /v3 endpoints

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/SuccessRequestDataCollector.java
- Resolves https://github.com/wso2/api-manager/issues/157
> Fix analytics events getting dropped when User-Agent header is missing

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
This provides support for role names with white spaces (eg: Role A) for role restricted API visibility in publisher portal.
Fix for - https://github.com/wso2/api-manager/issues/553
> Support for role names with white spaces for API visibility

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SearchApiServiceImpl.java
When search operation with URL pattern `{{basepath}}/search?limit=25&offset=0&query=context:` is performed, 500 error response with below response was observed. 
```
{
"code": 900967,
"message": "General Error",
"description": "Server Error Occurred",
"error": []
}
```
Therefore to handle that, added proper error message for Search API admin call when an empty context is set. Public git issue is https://github.com/wso2/api-manager/issues/745.
- Parsed error message from `APIPersistenceException` and thrown to `SearchAPIServiceImpl` level if there is a error message parsed or otherwise default to `"Error while searching the api"`.
- Catched the `APIManagementException` in `SearchAPIServiceImpl`.
> Added proper error message for Search API admin call when an empty context is set

- pom.xml
Update axiom, synapse, and carbon-mediation for build in JDK 11 and run on JDK 17
> Update synapse, mediation for JDK 11 builds

- .gitignore
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/SystemScopesMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiCommonUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
Move getScopesInfoFromAPIYamlDefinitions method to rest.api.common from rest.api.util
Fix https://github.com/wso2/api-manager/issues/795
- wso2/carbon-apimgt/pull/11443
> Move a Util method to rest.api.common

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/GraphQLProcessorResponseDTO.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/GraphQLRequestProcessorTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/utils/InboundWebsocketProcessorUtilTest.java
Use an JSON array to throw the error payload in GraphQL instead of an single JSON object.
> Use an JSON array to throw the error payload in GraphQL

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayJMSMessageListener.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/EventHubConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/GatewayArtifactSynchronizerProperties.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/DBRetriever.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR adds support to a new config which will add an event waiting time for all event hub events.
```
[apim.event_hub]
event_waiting_time = 5000
```
This config will not be added to the default.json, as it is intended not to be applied by default. If anyone is experiencing DB slowness, this can help with overcoming inconsistencies.
Fixes: https://github.com/wso2/api-manager/issues/702
> Add waiting time config for event hub events

- pom.xml
Bump graphql.java.version to `18.2.wso2v1`
- Resolves: https://github.com/wso2/api-manager/issues/469
- Related PR: https://github.com/wso2/orbit/pull/765
> Bump graphql.java.version to `18.2.wso2v1`

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
$subject. Fixes https://github.com/wso2/api-manager/issues/612
> Add implementation to validate the origin header only if it's present in the request

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/RequestContextDTO.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/MutualSSLCertificateHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/listener/ExtensionListenerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/authenticator/MutualSSLAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/jwt/JWTValidatorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/jwt/SignedJWTInfo.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/jwt/JWTValidatorImplTest.java
- pom.xml
Fixes: https://github.com/wso2/api-manager/issues/636
**This should be merged after merging [1] and [2] while bumping the Synapse version of carbon-apimgt. After that, need to bump the Synapse version in product-apim too.**
- Remove the usage of javax.security.cert.X509Certificate when using the implementations related to getPeerCertificates()
- Use  java.security.cert.Certificate in the above use cases
- OpenJDK 11.0.16+8
- OpenJDK 17.0.4+8
[1] https://github.com/wso2/wso2-synapse/pull/1965
[2] https://github.com/wso2/wso2-synapse/pull/1996
> Adding the changes related to https://github.com/wso2/wso2-synapse/pull/1996

- components/apimgt/org.wso2.carbon.apimgt.internal.service/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.devops/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/pom.xml
- pom.xml
- hibernate-validator has been updated from 5.4.3.Final to 6.0.23.Final
- validation-api has been updated from 1.1.0.Final to 2.0.1.Final
The following components will be updated from this PR
- ./repository/deployment/server/webapps/api#am#admin#v0.17/WEB-INF/lib/hibernate-validator-5.4.3.Final.jar
- ./repository/deployment/server/webapps/api#am#gateway/WEB-INF/lib/hibernate-validator-5.4.3.Final.jar
- ./repository/deployment/server/webapps/api#am#gateway#v0.9/WEB-INF/lib/hibernate-validator-5.4.3.Final.jar
- ./repository/deployment/server/webapps/api#am#publisher/WEB-INF/lib/hibernate-validator-5.4.3.Final.jar
- ./repository/deployment/server/webapps/api#am#store/WEB-INF/lib/hibernate-validator-5.4.3.Final.jar
- ./repository/deployment/server/webapps/client-registration#v0.17/WEB-INF/lib/ …
> Fixes for vulnerable third-party dependencies

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandlerTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/resources/swaggerEntry/swagger.yaml
**Purpose**
Improving the the Header validations of Swagger Schema Validator Case Insensitivity to support for swagger 2.0 and OpenApi 3.0
Related Issue: https://github.com/wso2/api-manager/issues/559
**Approach**
The fix was initially done only considering the Open API 3.0 hence a modification added to improve it for swagger 2.0 as well.
> Change parameter filter to work with swagger 2.0 and open api 3.0

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/webhook/WebhookApiHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/webhooks/SubscriberInfoLoader.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/webhooks/SubscribersPersistMediator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/PublisherAPI.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryPersistenceUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/template/APITemplateBuilderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
Add 'application/x-www-form-urlencoded' support for subscription creation.
Modify Subscription initialization to use 'GET' requests with 'hub.challenge' parameter.
Add link header for content distribution requests.
Add conditional subscription verification.
To enable subscription verification .
- Go to publisher portal and click on API Configurations.
- Under WebSub Configurations select 'Enable subscriber verification' checkbox.
Fix https://github.com/wso2/api-manager/issues/775
> Related PRs: https://github.com/wso2/apim-apps/pull/358, https://github.com/wso2/product-apim/pull/12989
>  Refactor Web-Sub Subscription process

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- Currently, when fetching APIs using the DevPortal REST API, the Key Managers field for API Products is assigned a value of `null`. 
- This PR sets `all` value to the Key Managers fields in API Products model returned from the DevPortal REST API.
- This is done to enable the `SUBSCRIPTION AND KEY GENERATION WIZARD` button in the Subscription page of API Products in DevPortal. This button was disabled based on a condition related to the Key Managers field of the returned API object. Since the value for API products was null, the button was disabled.
- Fixes https://github.com/wso2/api-manager/issues/33
- Set `all` value to the Key Managers fields in API Products model returned from the DevPortal REST API
> Set "all" Value to Key Managers Field in API Products Model Returned from DevPortal REST API

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapsePolicyAggregator.java
We have introduced a fix[1] to wrap the policy XML String with a super parent before building the OMElement. this was introduced to fix the child elements being dropped when a parent element is not found[2]. However this fix will break if the policy contains XML prologs.
This fix will initially try with the super parent node approach and if this fails, it will just render whatever the policy string provided without any modifications.
[1] - https://github.com/wso2/carbon-apimgt/pull/11347
[2] - https://github.com/wso2/api-manager/issues/25
> Build the policy definition without super root if the policy contains xml prologs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/operationPolicy/operation-policy-specification-schema.json
With this PR, we are adding the support for multiple API types for policies framework.
Fixes : https://github.com/wso2/product-apim/issues/12559
> Add the support for different API types for policies

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
Fix the issue of returning 500 error returns with the following error logs when doing /export REST API call. 
Related Issue:
https://github.com/wso2-enterprise/choreo/issues/9668
**Curl Request:**
```
curl -k -H "Authorization: Bearer ea5f7ea4-d5f6-3eaa-ba61-2d31d1e41268" "https://localhost:9443/api/am/publisher/v2/apis/export?organizationId=12345&apiId=636b8c72a920ee66caf023de&provider=admin&format=YAML" > exportAPI.zip
```
**Error logs:**
```
11/9/2022, 1:47:25 PM
TID: [-1234] [2022-11-09 08:17:25,218] INFO {AUDIT_LOG} 2f32eb06-bc1a-422f-9d85-58e4e53a2d56 - GET /api/am/publisher/apis/export?organizationId=e628f45c-d4fc-4d2a-9105-350b60beb84e&apiId=63628ea96b97733b88a5f480&format=YAML&provider=d5035fcc-656f-4b7b-84c1-6eff0087abea user: choreo_dev_apim_admin@carbon.super app: …
```
> [9.22.x] Fix issue with /export REST API call

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
To fix the NPE error when adding WSO2-IS as Key Manager from the Admin portal.
Fixes: https://github.com/wso2/api-manager/issues/885
- Validation added to validate before searching a value for revokeOneTimeTokenEndpoint since this is only for resident KM.
- UI validation added for other required fields: userInfoEndpoint and scopeManagementEndpoint
Related PR: https://github.com/wso2/apim-apps/pull/379
> Fix error adding WSO2-IS as Key Manager from Admin portal

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
$subject to prevent an API being renamed to already existing API name.
Related: https://github.com/wso2-enterprise/choreo/issues/16300
> Validate API name when updating an API

- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/dto/OperationPolicyAttachmentStatusDTO.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/resources/api.yaml
- components/apimgt/org.wso2.carbon.apimgt.internal.service/swagger.json
An internal endpoint to check whether mediation policies are attached to a particular API.
Request : 
```
<host>/internal/data/v1/apis/<apiId>/operation-policy/is-attached?organizationId=<orgId>
```
Response : 
```
{
"isAttached": boolean
}
```
> `isAttached` internal API endpoint

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Remove erroneous API name validation introduced by https://github.com/wso2/carbon-apimgt/pull/11630.
Add 9.2.x changes of https://github.com/wso2/carbon-apimgt/pull/11640 to valid API name when updating the API.
Related: https://github.com/wso2-enterprise/choreo/issues/16300
> Validate API name when updating the API

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/VHost.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
This PR resolves https://github.com/wso2/api-manager/issues/942.
Earlier `DEFAULT_HTTP_PORT` and `DEFAULT_HTTPS_PORT` were initialized to 80 and 443 respectively. Even though http or https endpoint is not defined, both endpoints were reflected in Publisher Portal and Devportal UIs. To overcome this issue [1], `DEFAULT_HTTP_PORT` and `DEFAULT_HTTPS_PORT` were changed to `Integer` type assigning null as default values by [2]. It introduced an NPE when http or https endpoint is not defined or defined without ports in deployment.toml. 
This PR reverts port numbers back to 80 and 443 and change httpPort and httpsPort of VHost to -1 as the default value. By this change we can identify whether an endpoint is defined or not by referring only to the port number. Following table describes how UI …
> Fix NPE when http port is not defined

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Related Task https://github.com/wso2-enterprise/choreo/issues/16049
This PR will fix `Cannot create a revision of policy with ID 55c2651a-4ce7-4e08-8faa-f9229ace5f55 as it does not exists.` issue that happens when creating a revision of mediation attached API.
> Fixed `API revision flow issue` issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Related Task https://github.com/wso2-enterprise/choreo/issues/16049
This PR will fix the `Cannot create a revision of policy with ID 55c2651a-4ce7-4e08-8faa-f9229ace5f55 as it does not exists.` issue that happens when creating a revision of mediation attached API.
> Use `Organization ID` instead of `tenantDomain` in API revision flow

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
Fixes: https://github.com/wso2/api-manager/issues/349
Implementation detail: Recursively removing the unsupported blocks from API definition.
> Remove unsupported blocks in api definitions

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
Fixes the deployment issue in https://github.com/wso2/api-manager/issues/951 step 10.
Fixes: https://github.com/wso2/api-manager/issues/908
Using policy name and version as the key when exporting common API Policies
> Using policy name and version as the key when exporting common API Policies

- pom.xml
Bump the carbon-kernel version to 4.8.0-m2
Related to https://github.com/wso2/api-manager/issues/973
> Bumping the carbon-kernel version to 4.8.0-m2

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleConditionEvaluator.java
When we set up the JWT conditional rate limiting policy under advanced throttling policies there was a NullPointException popping up without throttling out at the expected limit at the time a non-authenticated resource is invoked. That issue is fixed with this PR. Now for non-authenticated resources, it throttles out from the default limit as the security limit is not applicable.
> Handling Null Point Exception | JWT Conditional Policy 

- pom.xml
This PR includes changes to sysnapse version to 4.0.0-wso2v1 from 2.1.7-wso2v313
> Bump sysnapse version to 4.0.0-wso2v1 from 2.1.7-wso2v313

- .github/workflows/coverage.yml
- .github/workflows/main.yml
- .github/workflows/sonar-scan.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
Fix for the issue :Key generation fails when a Custom Key Manager is created other than the IS Key Manager
> change to check if resident km

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayJMSMessageListenerTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/listeners/KeyManagerDataServiceImplWrapper.java
Added a unit test to assert the changes done to the GatewayJMSListner to reflect the throttling policy changes in the gateway in runtime.
Fix: else if (EventType.POLICY_CREATE.toString().equals(eventType) || EventType.POLICY_DELETE.toString().equals(eventType) || EventType.POLICY_UPDATE.toString().equals(eventType))
> Unit Test for Throttling Policy Update Fix

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes https://github.com/wso2-enterprise/choreo/issues/17043
- Log output if the api identifier is null when getting the lifecycle state information:
```
ERROR - ApisApiServiceImpl Error while deleting API : 638a2d7269b8a04384698a9c
org.wso2.carbon.apimgt.api.APIManagementException: Error while getting the api identifier for the API:638a2d7269b8a04384698a9c
at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.getLifecycleState(ApisApiServiceImpl.java:2065) [classes/:?]
at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.getAPILifecycleState(ApisApiServiceImpl.java:2044) [classes/:?]
at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.getAPILifecycleState(ApisApi.java:800) [classes/:?]
```
> Fix NPE when getting the lifecycle state information

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
$subject. The following span tags will now be visible in Jaeger UI:
| Span Tag | Value represents |
|---|---|
| `span.http.response.status.code` | `HTTP_SC` property from axis2 msgCtx |
| `span.http.response.status.code.description` | `HTTP_SC_DESC` property from axis2 msgCtx |
Resolves: https://github.com/wso2/api-manager/issues/1183
> Add HTTP response status code & description as Jaeger span tags

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
For the REST API call when sending an **invalid action parameter** below issues were reported,
1. Return HTTP Status Code 400 instead of 500 which is incorrect
2. Do not log a huge stack trace, only the `Action 'Deprecate' is not allowed. Allowed actions are [Retire]` line would be sufficient.
This PR will resolve above two issues.
Below is the sample log output that you will observe when you sent an invalid life-cycle state,
`[2023-01-09 21:58:14,021] ERROR - ApisApiServiceImpl Error while updating lifecycle of API 63bc4008a4b76f2f6db146b4 Action 'Deprecate' is not allowed. Allowed actions are [Publish, Deploy as a Prototype]`
Below is the response you will receive for a request with an invalid life-cycle state,
`{"code":400,"message":"Bad Request","description":"Error while updating …
> Resolve incorrectly returning 500 for an invalid life-cycle state change

- codecov.yml
This change fixes "upload expired" failure in codecov according to the following thread https://community.codecov.com/t/result-upload-marked-as-upload-expired/4015.
> Fix coverage report upload expired failure

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
- Resolves https://github.com/wso2/api-manager/issues/1162
This PR fixes the IOException getting thrown when schema validation is enabled, resulting in a 400 Bad Request even when the XML payload is adhering to the provided XSD.
According to the logic in XMLSchemaValidator and GatewayUtils.cloneRequestMessage(), when the passthrough pipe message is not available we get the inputstream XML from the axis2 msg context's envelope body. But we are only setting it in the returned inputStreamMap under XML key and setting a null stream for the SCHEMA key. This is the root cause for the reported bug.
> Fix stream closed error encountered due to XSD validation not working as expected

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/TestSchemaValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/resources/swaggerEntry/openapi.yaml
$subject. Resolves https://github.com/wso2/api-manager/issues/1193
Create SchemaValidator LevelResolver with level IGNORE for `"validation.schema.additionalProperties"`
> Fix `oneOf` OpenAPI Schema Validation

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
To add more debug logs to print in WebSocket API invocation flows.
Fixes: https://github.com/wso2/api-manager/issues/567
- In this PR we have added the correlationId and API context to the debug logs where those data are available.
- Furthermore, this has updated the debug logs specific to in and out flows with inbound and outbound tags.
> Add more debug logs to print in WebSocket API invocation flows

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/JWTConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/AbstractAPIMgtGatewayJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/util/JWTUtil.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/test/java/org/wso2/carbon/apimgt/common/gateway/JWTUtilTestCase.java
Adding the kid property to the JWT header.
By default the x5t property is used as the identifier. When turned on, kid property will be the sha-256 hash of the public key with no padding.
> Kid property for backendJWT

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
This PR replaces ObjectMapper from JSONParser to support JSON objects and arrays as claims in AbstractJWTGenerator.
Fixes https://github.com/wso2/api-manager/issues/997
> Replace ObjectMapper from JSONParser to support JSON objects and arrays as claims

- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiConstants.java
This PR fixes the scope validation flow being skipped in the devportal REST API. "/" joining the context and the version has been missing in the product and this has resulted in skipping the scope validation.
Fixes https://github.com/wso2/api-manager/issues/1110
> Fix the error in devportal full context

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
When importing multiple versions of APIs with publisher access control enabled by a different user than the API provider, role validation is done based on the provider. Previously provider was taken from the artefact which was the original user and if that user does not exist in the new environment, there were multiple errors and this sets the provider to the logged in user.
Resolves: https://github.com/wso2/api-manager/issues/1020
> Fix API import when publisher access control enabled

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
This PR populates the error messages of Swagger validation of import flow.
This will parse the JSON content as an additional measure to validate the swagger json.
Related git issues : https://github.com/wso2/api-manager/issues/115
> Populate error messages with meaning in the swagger parsing flow

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/LifeCycleUtils.java
There is an option at the lifecycle change to publish an API while deprecating other versions of the same API. Here, API objects of other APIs are updated with the deprecated state, however, the API object is having very minimal information. This breaks the newly deprecated API in the UI portals as it does not contain the minimum information needed to show in the publisher and dev portal UI.
Resolves: https://github.com/wso2/api-manager/issues/1115
> Fix API update when publishing while deprecating old versions

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Earlier there was an error when export/importing an API Policy that supports both Synapse and Choreo Connect gateways. This will fix that issue.
Fixes: https://github.com/wso2/api-manager/issues/1274
Support export/import API policies with Synapse and CC gateway types
Check the extension type of the definition file and if it is ".gotmpl", then set the gateway type accordingly.
> Support export/import API policies with Synapse and CC gateway types

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/api-manager/issues/1275
Allow importing CC API Policies without .gotmpl
Mandate checking for .j2 template file only for Synapse. If the type is Choreo Connect, no check has been done
> Allowing to import Choreo Connect API Policies without .gotmpl

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/utils/InboundWebsocketProcessorUtil.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
This PR adds the change to take WebSocket backend JWT header from configuration instead of the hardcoded value.
Moreover, This PR adds the change to take the backend JWT header prefix from the `ws.custom.header` parameter included in `transport.ws.sender.parameters` and `transport.wss.sender.parameters` instead of including the prefix in the `apim.jwt.header` configuraiton.
Fixes https://github.com/wso2/product-apim/issues/12286
> Add WS backend JWT header from the config

- pom.xml
Upgrades velocity-engine-core version to 2.3.
Fixes https://github.com/wso2/api-manager/issues/1301
> [4.2.0] Upgrade velocity-engine-core version

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/AnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/SuccessRequestDataCollector.java
- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/publishers/dto/Event.java
- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/publishers/dto/ExtendedAPI.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/SynapseAnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/websocket/WebSocketAnalyticsDataProvider.java
Note: same as approved PR #11669
Modification to include the end user name and api context in analytics event object.
By default, end user name and api context should be included in the event object.
Included end user name as a new event attribute.
Included api context inside ExtendedAPI.
- Unit tests : No
- Integration tests : No
JDK 11.0.16
Ubuntu 22.04.1 LTS
> Modified to support userName and apiContext [9.0.369.x].

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SwaggerData.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/ThrottlingLimit.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OASTestBase.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas2/oas2_scopes.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas3/oas3_scopes.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIOperationsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIOperationsThrottlingLimitDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ThrottlingLimitMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
With the new Envoy rate-limit service users can define own rate-limits from the UI relevant to the operations. With this change UI can provide operation level rate-limits defined by the user to the backend. In the backend provided rate-limit details will be stored in below format in the API definition file (under the `x-throttling-tier`) field value. 
```
{ "requestCount" : "9999" , "unit" : "min" }
```
When sending responses back to the UI below structure is used.
```
"throttlingPolicy": "20KPerMin",
"throttlingLimit": { 
"requestCount" : 20000, 
"unit" : "min" 
},
```
> Operation level throttling with rate-limit service

- pom.xml
Upgrades carbon-analytics-common and carbon-identity-framework versions to reflect the pax logging version upgrades in [1] and [2].
Related git issue : https://github.com/wso2/api-manager/issues/1267
[1]. https://github.com/wso2/carbon-identity-framework/pull/4423 
[2]. https://github.com/wso2/carbon-analytics-common/pull/82
> Upgrade carbon-analytics-common and carbon-identity-framework versions 

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
The publisher portal tryout console should work for either production or sandbox endpoint. But if there is no production endpoint, we could not invoke the API.
This is due to our current code only having the capability to handle this only if a production endpoint is available. In this commit, I added sandbox key capability to publisher tryout console to fix https://github.com/wso2/api-manager/issues/1190
> Added sandbox key capability to publisher tryout console

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
Fixes the null pointer exception happens due to defining the `x-throttling-tier` as `null
Related PR: https://github.com/wso2/carbon-apimgt/pull/11760
> Throttling tier fix

- pom.xml
Upgrades carbon-governance version to reflect pax-logging upgrade in [1].
Related git issue : https://github.com/wso2/api-manager/issues/1267
[1]. https://github.com/wso2/carbon-governance/pull/370
> Upgrade carbon-governance version

- pom.xml
Upgrades carbon-messaging version to latest to reflect the protobuf-java version upgrade in PR [1].
[1]. https://github.com/wso2/carbon-business-messaging/pull/718
> Upgrade carbon-messaging version

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/SystemScopeUtils.java
- Error is getting logged in the console when login into the publisher portal via tenant account for the first time.
- Fixed https://github.com/wso2/api-manager/issues/1333
- Added `loadAndSyncTenantConf` method to get the tenant configuration from the file system if its not available and then add it to the database so that it can be used or saved in the tenant config cache.
> Add loadAndSyncTenantConf to load tenant rest api scopes before getting tenant configurations

- pom.xml
Upgrades carbon-analytics-common version to reflect jsonpath upgrade in PR [1].
Related git issue : https://github.com/wso2/api-manager/issues/1297
[1]. https://github.com/wso2/carbon-analytics-common/pull/822
> Upgrade analytics-common and jsonpath versions

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/model/OpenAPIRequest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/TestSchemaValidator.java
Fixes https://github.com/wso2/api-manager/issues/192
> Fixing API invocation failures when SchemaValidation is enabled for unauthenticated APIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- The API count under API categories in the admin portal is displayed as zero although APIs are there with the category assigned.
- Fixed https://github.com/wso2/api-manager/issues/1338
- Changed api search query with `:` instead of `=` in https://github.com/wso2/carbon-apimgt/blob/0947ffa2befeb438c937e0e5aae5069bfb4b4c71/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java#L1011
> Change search query to correctly fetch the api-category api count

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/constants/GraphQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketUtil.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/GraphQLRequestProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/RequestProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/GraphQLResponseProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/ResponseProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandlerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/GraphQLRequestProcessorTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/request/RequestProcessorTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/GraphQLResponseProcessorTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/response/ResponseProcessorTest.java
When applying a deny policy to WebSocket/GraphQL API using the admin portal in the WSO2 API manager, It doesn't block the requests which in turn gives the ability to invoke the WS API regardless of the blocking condition.
This PR fixes the issue.
Resolves https://github.com/wso2/api-manager/issues/1128
> Fix not working deny policies for WebSocket APIs

- pom.xml
This PR upgrades gson to 2.9.1 and removes multiple versions of the jar available in the pack.
Related issue: https://github.com/wso2/api-manager/issues/1310
> Upgrade gson to 2.9.1

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
This PR will add Swagger relaxed validation to API Manager. With this, the swagger will be only validated to check whether the provided definition returns a valid swagger object after validating via the swagger parser. 
By default, the provided swagger definitions will be returned invalid if any errors are found while parsing via the swagger parser.  
To enable the relaxed validation, the following system property has to be passed to the runtime.
```-DswaggerRelaxedValidation```
> Add Swagger Relaxed Validation

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fix the issue of throwing 500 status when trying to create an API(copy API) with a version that already exists. This issue occurred when more than one version already exists for an API.
Resolves: https://github.com/wso2/api-manager/issues/1094
> Fix the issue of throwing 500 status when copying an API with same version

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ThrottlingLimitMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ThrottlingLimitMappingUtilTest.java
Use throttleLimit enum's name() function rather than using toString as toString() method is already overridden during the code generation phase
> Bug fix: API Update fails due ThrottleLimit parsing issue.

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
Issue: https://github.com/wso2/api-manager/issues/1435
Note: Although the exception gets resolved after this, the warning for OSGiAxis2Service remains.
> Fix for the AnalyticsException when apim-analytics-publisher added to dropins

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/dto/ClonePolicyMetadataDTO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Previous fix (https://github.com/wso2/carbon-apimgt/pull/11495) which was sent to fix a deadlock when adding and managing operation policies(https://github.com/wso2/api-manager/issues/618, https://github.com/wso2/api-manager/issues/699), API product policies path was breaking and there were multiple persistency-related issues. Cloned policy ID was missing when revisions were created and this will grow the api specific policies logic if policies were restored.
Resolves: https://github.com/wso2/api-manager/issues/1309 and https://github.com/wso2/api-manager/issues/1387
> Fix operation policy clone logic to remove deadlocks

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/FaultCodeClassifier.java
Fix https://github.com/wso2/api-manager/issues/1487
> Fix NPE when invoking GraphQL subscriptions with invalid scope token when analytics enabled

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/OAuthMediator.java
- Fix https://github.com/wso2/api-manager/issues/1224
- Add setters for clientSecret, password and username of oAuthEndpoint.
When the secure vault is enabled even though the clientSecret and password are in the registry, clientSecret, username and password were passed as null when generating the AccessToken in [1]. 
It was identified that when the secure vault is enabled, password and clientSecret properties are getting resolved in the runtime. Therefore in this PR setters were added to set those missing properties.
[1] - https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/OAuthTokenGenerator.java#:~:text=public%20static%20TokenResponse%20generateToken(OAuthEndpoint%20oAuthEndpoint% …
> Add missing properties in the OAuthMediator

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- Fix https://github.com/wso2/api-manager/issues/1446
- Fix NumberFormatException encountered when swagger contains high values for doubles
When a user try to create/update an API with large maximum values using swagger definition, it shows the following error message.
Also following error was observed in the APIM server.
```
ERROR - ApisApiServiceImpl Error while parsing OpenAPI definition. Error code: 900754. Error: java.lang.NumberFormatException: For input string: "9223372036854776000"
```
It was identified that this was caused due to a limitation in `json-simple` library which was used to parse the swagger content. In this PR `json-simple` usages were replaced by `gson` as the fix.
> Fix NumberFormatException for swagger definitions with high value doubles

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPToRESTConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SequenceUtils.java
n the current SOAP to REST API creation, the SOAP envelop elements are not mapped in the same order
defined in the wsdl. The current implementation used JSONObjects to record the parameters and this will not preserve the order. However, if the operation has sequence elements, the changed order will break the operation. Instead of JSONObject, this implementation uses the swagger example data type which internally uses Linked Hash maps.
Resolves: https://github.com/wso2/api-manager/issues/1441
> Add the support to generate SOAP to REST operation elements in order

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
This fix fixes the issue, HTTP 401 has been observed intermittently for Basic Auth with correct credentials if an API has Basic Auth and OAuth as application security. 
Since this is concurrence issue, to make the remainingAuthHeader variable thread safe, We have used ThreadLocal method.
> Basic Auth Intermittent 401 HTTP error fixed.

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ThrottlingLimitDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
With this PR, unit value Enums in the throttling limit converts to the upper-case.
Related PRs:
- https://github.com/wso2/carbon-apimgt/pull/11760
- https://github.com/wso2/carbon-apimgt/pull/11785
> ThrottlingLimit unit value change for rate-limits

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/authenticator/InternalAPIKeyAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/authenticator/MutualSSLAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticatorTest.java
Set the message context properly `api.ut.userName` for missing authenticators.
Resolves: https://github.com/wso2/api-manager/issues/1482
> Add the missing enduser name to msgContext property

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
Fixes https://github.com/wso2/api-manager/issues/1167
- With this change for the OAS2 parser, we check whether a given OpenAPI definition contains empty resource paths and throws an error.
- We do this manually since the Swagger parser does not throw an error for this which is a known issue of the Swagger 2.0 parser. ( OAS3 parser does not have this issue )
- According to the OpenAPI specification empty paths are a violation of the specification.
- API paths get stored in the AM_API_URL_MAPPING table under the URL_PATTERN column. But it seems having empty paths does not affect APIM 3.2.0 in most cases as most of the databases store empty strings as it is.
- But in the Oracle database, empty strings are converted and stored as Null.
- This behavior could result in Null pointer exceptions …
> Check for empty resource paths in OAS2 definitions

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryPersistenceUtil.java
- Fix https://github.com/wso2/api-manager/issues/1502
- Set business owner name for APIs when getting API details for dev portal
When a user add Business owner name to an API, in the dev-portal API listing page it should be displayed instead of the provider name. However, when users try to use the search function it did not display Business owner name even though it was provided by the publisher.
> Fix business owner details not showing in dev portal

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
Engaging the cors_request_handler.xml file for web socket APIs flow only if the product level cors validation failed.
Unified solution for both REST API flow and web socket flow to update the origin header values in the cors_request_handler.xml. With this PR we can support the cors sequence for web socket flow. It paves a way to engage the cors_request_handler.xml sequence in the web socket flow and it will be triggered when the default cors validation of the product fails. If the normal cors validation(Including the deployment.toml configs and UI level origin addition) is succeeded, we do not need to engage this sequence in that flow.But, if the above default cors validation fails,
then we can engage the cors_request_handler.xml sequence in the web socket
flow to do an additional …
> Engaging cors_request_handler sequence in the web socket cors flow

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
The unlimited tier is default set to all the operations since wso2/carbon-apimgt#11710.
This PR will set this to the soap operation
Address: https://github.com/wso2/api-manager/issues/1524
> Add the unlimited throttle tier for soap operations

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwttransformer/DefaultJWTTransformer.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/test/java/org/wso2/carbon/apimgt/common/gateway/jwttransformer/DefaultJWTTransformerTest.java
If AUD claim is provided as the consumerKey containing claim and the value of the claim is an array, pick the 0th element of the array instead of throwing parse exception: when the km is forgerock this issue appears for the choreo connect
> Support picking consumer key from array valued claim in DefaultJWTTransformer 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS2ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS3ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/petstore_v2_throttle_limit.yaml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/petstore_v3_throttle_limit.yaml
populate x-throttle-limit extension (using -1 for request count which indicates the unlimited policy) for all the operations in the swagger, if the operations does not have the extension.
P.S.
Correct approach would be process the x-throttling-tier to generate the x-throttling-limit when the operation has that property.
> Bug fix: Populate x-throttle-limit extension with default  throttle limit for operations based on x-throttling-tier

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/util/ModelUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS2ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS3ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/petstore_v2_throttle_limit.yaml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/petstore_v3_throttle_limit.yaml
bug fix: In openapi v3 scenario, if the already existing api openapi definition contains the x-throttling-tier extension but the value is null, then it would result in a Null pointer error, with this fix, if the x-throttling-tier is null, it is considered as Unlimited
> Bug fix: Avoid NPE when the x-throttling-tier value is null.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- Fix https://github.com/wso2/api-manager/issues/1578
- Mock scripts were not generated for API resource paths with only `default` response in the OAS3 definition. This caused an error while deploying these APIs to the gateway. 
- Related PRs: https://github.com/wso2/carbon-apimgt/pull/11492
> Fix default response content missing from generated mock scripts

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
Fixes the issue by https://github.com/wso2/api-manager/issues/1539, by returning the connection back to client pool after updating the scopes.
> Resolves https://github.com/wso2/api-manager/issues/1539

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencySynapseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/SubscriptionDataHolder.java
$subject
- https://github.com/wso2/api-manager/issues/1550
> Fix: Web Socket Invocation Error with Tracing Enabled

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/GatewayArtifactsMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/APIArtifactPropertyValues.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/APIRuntimeArtifactDto.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/ArtifactSynchronizerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/MicroGatewayArtifactGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/RuntimeArtifactGeneratorUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/dto/EnvironmentDto.java
Add envId to gateway artifacts.
This will result in deployment.json to include the related envId to environment info object.
ex:
In here `my-foo-dev` environment id `9ec5b162-3a9b-405a-8d94-e1b9720824b7` attached.
```
{
"type": "deployments",
"version": "v4.1.0",
"data": {
"deployments": [
{
"apiFile": "64477a36d5452c29958fc252-64477b2fd5452c29958fc253.zip",
"environments": [
{
"id": "9ec5b162-3a9b-405a-8d94-e1b9720824b7",
"name": "my-foo-dev",
"vhost": "my.wso2.com",
"deploymentType": "SANDBOX",
"deployedTimeStamp": 1682406822693
}
],
"organizationId": "testOrg1"
}
]
}
}
```
> Add envId to gateway artifact

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/jwt/RevokedJWTMapCleaner.java
This PR fixes https://github.com/wso2/api-manager/issues/1752.
As in the below image `expiryTime` always gets 1000 times higher value and hence the code block in the condition will not be executed ever. To match the `currentTimestamp` and `expiryTime` in same unit (milliseconds) we have to remove multiplication from 1000.
> Fix revoked token cleanup issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryPersistenceUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductSearchResultAllOfDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductSearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APISearchResultAllOfDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APISearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/SearchResultMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
The hasThumbnail variable is set so that when searching for APIs and APIProducts the thumbnail will be shown
> Fix for when searching for an API in the publisher, the image disappears

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerTestCase.java
This update fixes the feature of having different visibility levels for the documentation of an API as Private, Owners only and Same as API.
Fixes: https://github.com/wso2/api-manager/issues/1610
> Fix the Documentation Visibility Feature

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- Fix issues related to importing APIs containing documents
- Related Issue: https://github.com/wso2/api-manager/issues/1452
- During the document import operation, replaced the tenantDomain with organization variable as the tenant domain.
- When adding registry permissions for the document file, while performing the substring operation, checked for the existence of "governance" string to avoid index out of range issue.
> Fix Issues Related to Importing APIs Containing Documents

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/throttling/BlockingConditionMappingUtil.java
This PR filters out the SUBSCRIPTION type deny policies retrieved from the AM_BLOCK_CONDITIONS table since subscription blocking is no longer added to the table.
Fixes https://github.com/wso2/api-manager/issues/1802
> Filter out SUBSCRIPTION type deny policies

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/PreAuthenticationInterceptor.java
Observed an issue while fetching developer portal APIs using a backend JWT. If the request contains the `x-jwt-assertion` header , authentication function consider that request as a anonymous user's request.
this PR fixes that issue.
> Fix dev portal API get issue for backend JWT

- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
- pom.xml
- Add Thumbnail Content Validation for API and API Products
- Related Issue: https://github.com/wso2/api-manager/issues/1280
- Prevent files with invalid content to be uploaded as thumbnails for APIs and API Products
- Used the Apache Tika dependency to detect the file media type using the input stream
- Validated the detected media type against the allowed media types (image/jpeg, image/png, image/gif, image/svg+xml)
- Converted svg media type images to png using the Apache Batik dependency
> Add Thumbnail Content Validation for APIs and API Products

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/GatewayArtifactSynchronizerProperties.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/DBRetriever.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/exception/ArtifactSynchronizerException.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/exception/DataLoadingException.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- Fix https://github.com/wso2/api-manager/issues/1780
- Add `MaxRetryCount` as a configuration parameter
```
[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default"]
artifact_retriever = "DBRetriever"
deployment_retry_duration = 15000
max_retry_count = 5
data_retrieval_mode = "async"
event_waiting_time = 5000
```
- Retrieve max retry count and retry timeout duration from configurations in newly added `org.wso2.carbon.apimgt.impl.utils.APIUtil#executeHTTPRequestWithRetries` method
- Update retry logic used in `org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener#deployArtifactsInGateway`
> Update retry mechanism used in artifact synchroniser

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/TestSchemaValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/resources/swaggerEntry/swagger.json
- Add schema validation unit tests to include resource with only slash and resources with trailing slash
- Related Issue: https://github.com/wso2/api-manager/issues/1783
> Add Schema Validation Unit Tests to Include Resource with Only Slash and Resources with Trailing Slash

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
This PR fixes the Internal Server Error while Trying to Remove All Published External API Developer Portals from an API  issue.
Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/2465
NullPointerException is happening in the org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java:2182.
- ExternalStoreId parameter is missing in the request.
- Since ExternalStoreId is null, 
```
List<String> externalStoreIdList = Arrays.asList(externalStoreIds.split("\\s*,\\s*"));
```
splitting occurs the null pointer exception.
- Added an if condition to check whether the ExternalStoreId is null, and if it is null then it will assign a new empty arraylist.
- https://github.com/wso2-support/carbon-apimgt/pull/5822
> Unpublishing from external stores null pointer exception fixed.

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
This PR adds the change to check only the invalid token cache for invalid tokens instead of both the INVALID status of signed token and invalid token cache.
Fixes https://github.com/wso2/api-manager/issues/1820
> Add change to check only the invalid token cache for invalid tokens

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
Data type base64Binary will be converted to String datatype with byte format and data type time will be converted to string data type without any specific data format 
Fix https://github.com/wso2/api-manager/issues/1840
> Add data type base64Binary and time

- pom.xml
There were few vulnerable `snakeyaml` versions detected from the choreo-apim product.
Fix for : https://github.com/wso2-enterprise/choreo/issues/16768
> Upgrade snakeyaml and jsckson dependency versions

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
We need to cater to the requirement of supporting adding additional Properties to the params.yaml file which can be used to override the additionalProperties of the exported APIs when importing it to the new environment (Similar to overriding the production/sandbox urls using the params.yaml file).
Fixes: https://github.com/wso2/api-manager/issues/1862
Introduced `handleAdditionalProperties` method to set the property values to the API/API Product that came through params.yaml.
> Add support for adding additional properties to the params.yaml

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
This PR adds the serviceInfo check before the API update query execution to mitigate the limitations of MySQL NDB cluster.
Fixes https://github.com/wso2/api-manager/issues/1864
> Add serviceInfo check before the API update query execution

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
When using basic auth for APIs, if the password contains the "colon" character then the requests are getting failed. 
Related Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/3181
Extended the split method by adding 2 as the split parameter. Now the user can use colons as multiples times for the password. But in this approach we have assumed that user don't use colon for the username.
> Fixed colon can't include in the password issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
Related Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/3095
Related Public Issue: https://github.com/wso2/api-manager/issues/1859
- To enable the "Enable Failover" config in the endpoint configuration, User have defined "failOver: true" in the params.yaml. When the user has checked the load-balanced configs of the imported API, from the publisher portal. It displays that load-balanced configs specified in the params.yaml are reflected in the publisher portal as follows but the "Enable Failover" config is not selected.
- Added the property ```failOver``` to ```updatedRESTEndpointParams```.
> Fixed failover enabled in params.yaml appear as disabled in UI

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APILoggerManager.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/EndpointCertificateDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/GoogleAnalyticsConfigDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/jwt/RevokedJWTTokensRetriever.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/throttling/util/BlockingConditionRetriever.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/throttling/util/KeyTemplateRetriever.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/util/BlockingConditionRetrieverTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/util/KeyTemplateRetrieverTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataLoaderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.throttle.policy.deployer/src/main/java/org/wso2/carbon/apimgt/throttle/policy/deployer/PolicyRetriever.java
- Fix https://github.com/wso2/api-manager/issues/1853
- In this PR, retry mechanism used for following internal API requests were updated.
- /internal/data/v1/api-logging-configs 
- /internal/data/v1/applications
- /internal/data/v1/api-policies
- /internal/data/v1/revokedjwt
- /internal/data/v1/keyTemplates
- /internal/data/v1/block
- /internal/data/v1/subscription-policies
- /internal/data/v1/application-key-mappings
- /internal/data/v1/application-policies
- /internal/data/v1/subscriptions
- /internal/data/v1/scopes
- /internal/data/v1/ga-config
- /internal/data/v1/endpoint-certificates
> Update retry logic used for internal API requests

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
@subject as it may create inconsistencies if the database is partially updated.
> Send ASB event after all the DB operations are complete for the undeploy call.

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
A new field named lastUpdatedTimestamp is introduced and UI will read this value to show Last Updated Time in APIs and API Products pages 
Fix wso2/api-manager#1860
> Introduce new field 'lastUpdatedTimestamp' for APIs and API Products

- pom.xml
Upgrading json-smart version to the latest for addressing a security vulnerability[1] in currently used version. Json-path is also updated as it packs json-smart [2].
[1] https://nvd.nist.gov/vuln/detail/CVE-2023-1370
[2] https://github.com/wso2/orbit/pull/980
> Bump json-smart and json-path versions

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/VHost.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/publisher/ApisApiServiceImplUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/VHostUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/VHostDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/EnvironmentMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/VHostDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/EnvironmentMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- Fix https://github.com/wso2/api-manager/issues/1844
- ForwardPort https://github.com/wso2-support/carbon-apimgt/pull/5890
---
- ForwardPort https://github.com/wso2-support/carbon-apimgt/pull/5561
- Gateway Access URL should displays the host name which given for `ws_endpoint` in the `deployment.toml` file. However in the publisher and dev-portal it showed the host name given for `http_endpoint`.
---
- ForwardPort the fix for validating VHost when deploying API revisions.
- Add `wsHost` and `wssHost` to `components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/VHost.java`.
- Update `org.wso2.carbon.apimgt.api.model.VHost#getUrl` method to fetch `wsHost` and `wssHost` when retrieving URLs.
- Add changes to the UI to use `wsHost` and `wssHost` parameters …
> Fix Host Name in Gateway Access URL in Portals for WebSocket APIs Showing Wrong Host

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
Fixes : https://github.com/wso2/api-manager/issues/1886
> Add a default version_comparable value to fix error thrown in APIs migrated from the version which doesn't support API Revisions

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/RedisBaseDistributedCountManager.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
Checks the conditions of redisConfig seperately to get the user credentials even when the other configs are missing and fix a null pointer exception which occurs due to redisPool being null.
https://github.com/wso2/api-manager/issues/1887
> Gets user credentials for redis when other configs are missing

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
- Modify the feature introduced in https://github.com/wso2/carbon-apimgt/pull/11926/files, so that it enables only when both system properties, namely "**corsForbidBlockedRequests**" and "**corsSetStatusCodeFromMsgContext**," are enabled.
- To enable this feature start API Manager as following.
`./wso2server.sh -DcorsForbidBlockedRequests=true -DcorsSetStatusCodeFromMsgContext=true`
> Git Issue: https://github.com/wso2/api-manager/issues/1902
> Introduce system property for CORS request blocking with 403 error

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
To fix the errors thrown while starting the APIM server even if a SAN entry matches the server hostname when hostname verification is set as "DefaultAndLocalhost".
Fixes: https://github.com/wso2/api-manager/issues/1876
and also fixes issues from: https://github.com/wso2/api-manager/issues/1698
- When DefaultAndLocalhost hostname verifier is enabled, all hostnames that match the below list should pass hostname verification regardless of what is on the server’s certificate.
"::1", "127.0.0.1", "localhost", "localhost.localdomain"
- Apart from that above should support default hostname verification as well. So DefaultAndLocalhost verification is Default hostname verification + a relaxation on localhost hostnames.
- To fix the above issues we should improve the verify method to validate the …
> Fix errors when hostname verification is set as "DefaultAndLocalhost"

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SettingsCustomPropertiesDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SettingsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- This PR resolves the master fix for wso2-enterprise/wso2-apim-internal#3166.
This PR adds the implementation of mandatory custom properties support feature to the publisher portal. This feature can be enabled by defining server config or tenant config as below.
Server Config
```
[[apim.publisher.custom_properties]]
required=true
name="PropertyName"
description="Property Description"
```
Tenant Config
Add the configuration as shown below by navigating to the Settings -> Advanced page of the admin portal
```
"PropertyConfigurations": {
"Properties": [
{
"Name": "PropertyName",
"Required": true,
"Description": "Property Description"
}
]
}
```
This PR includes a rest API validation to the mandatory custom properties when updating the additionalPropertiesMap.
Related PRs
- UI PR for Master: …
> [RRT] Add mandatory custom properties support feature

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SwaggerData.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/AsyncApiParser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
With this PR users will be able disable/ enable application level security.
Also the `x-wso2-disable-security` extension will be added to the API definition based on the enabling or disabling of application level security.
> Application level security disabling

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
This PR fixes the SOAP APIs are not working for "_" path operators.
Related Github Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/1004
This fix has done by changing the string splitting method from "_" to the "httpmethod" and the other fix is changing the indexof() to lastindexof().
> Fixed SOAP APIs are not working properly for "_" path operators

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
With the previously created PR (https://github.com/wso2/carbon-apimgt/pull/12076) enabled to disable the security when `x-wso2-disabled-security` extension assigned as `true.` However due to the `x-auth-type` extension value change happened with the above PR avoided to re-enable security after disabling it. With this PR it is fixed.
> Fix considering the x-wso2-disabled security extension

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- Fix pack startup issue due to missing end tag under `api-manager.xml.j2` due to the changes added via https://github.com/wso2/carbon-apimgt/pull/12082
> Fix startup issue due to missing end tag

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fix the issue of configuring parameterized endpoints after the URL validation is introduced. With this PR it will skip validating parameterized endpoints.
Resolved : https://github.com/wso2/api-manager/issues/1961
> Skip URL validation for parameterized endpoints

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/JWTConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Public fix for issue: https://github.com/wso2/api-manager/issues/1975
> JWT decoding for both base64url and base64

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/jwt/JWTValidatorImpl.java
This PR is introduced to enhance error logs by providing specific explanations.
> Error log improvements & handle jwksinfo null instance

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/BackendJWTConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/BackendJWTConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/PublisherAPI.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIBackendJWTConfigurationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
With the existing implementation, users cannot pass user defined `aud` claims to the backend with the token. 
This PR is created to provide the above mentioned support.
Relevant change added to the `api.yaml` 
```
.
.
.
"backendJWTConfig": {
"audiences": [
"abcOrg.com",
"xyzOrg.com"
]
},
.
.
```
> Audience claim addition

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
Fixing : https://github.com/wso2/api-manager/issues/2068
> Add fix to ommit `getAllAPICategoriesOfOrganization` during migration

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
This PR fixes a contract test failure happens when accessing a class field maintained to determine backend JWT enabled or not.
Related Previous PR: https://github.com/wso2/carbon-apimgt/pull/12111
> Fix for the contract test failure

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SwaggerData.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIOperationsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/TemplateBuilderUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
Fixes https://github.com/wso2/api-manager/issues/1878
**Implementation Details**
- Added support for multipart/formdata content in AWS lambda mediator
**Bug Fixes**
- While testing with form-data content it was observed that the WSO2 gateway did not send the correct response from lambda back to the client when form-data content is used. This was fixed by adding below change.
`JsonUtil.setJsonStream(axis2MessageContext, new ByteArrayInputStream(invokeResult.getPayload().array()));`
to
`JsonUtil.getNewJsonPayload(axis2MessageContext, new String(invokeResult.getPayload().array()), true, true);`
**Related PRs**
UI : https://github.com/wso2/apim-apps/pull/468
Product : https://github.com/wso2/product-apim/pull/13215
> Add multipart/form-data support in AWSLambdaMediator

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/clients/Rudder.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
$subject
```
[choreo.api_backend_url_validation]
enable_organization_validation = true
rudder_endpoint_url = "http://localhost:8002"
```
> Addition of a configuration to define rudder endpoint

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
$subject as certain IDP vendors does not include revocation endpoint in their openid-configuration.
> Remove revoke endpoint from mandatory list when registering an IDP

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/APIMgtGatewayJWTGeneratorImpl.java
Previously backend JWT did not contain the AUD claim.
As per the request initiated in the below issue, this PR enables to add `aud` claim to the
backend JWT.
> Addition of aud claim to the backend JWT

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
This PR adds the change to preserve advanceEndpointConfig when setting endpoint config for the API.
This property is used for MGW for ballerina endpoint configurations.
Please find a sample endpoint config with advanceEndpointConfig.
```
{
"endpoint_type":"http",
"production_endpoints":{
"url":"https://localhost:9443/am/sample/pizzashack/v1/api/",
"advanceEndpointConfig":{
"timeoutInMillis":240000
}
},
"sandbox_endpoints":{
"url":"https://localhost:9443/am/sample/pizzashack/v1/api/"
}
}
```
Related issue: https://github.com/wso2/product-microgateway/issues/3387
> Preserve advanceEndpointConfig when setting endpoint config

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/HybridThrottleProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/RedisBaseDistributedCountManager.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/ServiceReferenceHolder.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/RedisConfig.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- pom.xml
**Problem**
We have had implemented distributed backend throttling and distributed burst control support with the use of the Redis cluster. This is done by periodically syncing throttling-related parameters such as counter values, first access timestamp, time window, etc. between the Redis server and the Gateway nodes. But the related throttling limits are not accurate due to the periodic sync time. There is a considerable slippage prior to throttling taking place until the sync takes place between gateways and the Redis server. This needs to be reduced to achieve better accuracy at high-load use cases, where conforming to the defined backend throttling limits is critical.
Git issue: https://github.com/wso2/api-manager/issues/1791
**Solution:**
The presented solution by this PR is a …
> Porting redis improvement related fixes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
This avoids setting SWAGGER_X_AMZN_RESOURCE_CONTNET_ENCODED vendor extension to normal APIs. The extension is set only if an ARN is present (which is possible only if it is an AWS Lambda Endpoint type API)
> Add SWAGGER_X_AMZN_RESOURCE_CONTNET_ENCODED only if ARN is present

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/DevPortalAPIInfo.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/DevPortalSearchContent.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/PublisherAPIInfo.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/PublisherAPIProductInfo.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/PublisherSearchContent.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryPersistenceUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductSearchResultAllOfDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductSearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APISearchResultAllOfDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APISearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/SearchResultMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APISearchResultAllOfDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APISearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SearchResultMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml
We introduced this PR to add the new feature API tile enhancement to both the publisher & dev portals. The current API tile information lacks some necessary business details from a marketplace perspective. With this feature, we are extending the API tile information structure to accommodate optional properties such as business information, external APIs, and the monetization-enabled state of the APIs. These properties are displayed in the API tile through a config. Users can set the 'display' property of optional properties as per their preference. By default, the configuration for the 'display' property is set to 'false.' This configuration can be found in the 'settings.json' file in both portals.
For the publisher portal, the configuration is as follows:
```
"apis": {
"tileDisplayInfo": …
```
> [Feature] Api tile enhancement

- components/apimgt/org.wso2.carbon.apimgt.cache.invalidation/src/main/java/org/wso2/carbon/apimgt/cache/invalidation/APIMgtServerStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.common.jms/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.common.jms/src/main/java/org/wso2/carbon/apimgt/common/jms/JMSTransportHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSListenerStartupShutdownListener.java
- components/apimgt/org.wso2.carbon.apimgt.throttle.policy.deployer/src/main/java/org/wso2/carbon/apimgt/throttle/policy/deployer/utils/ThrottlePolicyStartupListener.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
The configuration below allows customization of Thread Pool settings of the JMS TransportHandler for the Event Hub. This can be configured by adding either of the following configs.
```
[apim.event_hub.listener]
min_thread_pool_size = 20
max_thread_pool_size = 100
keep_alive_time_in_millis = 1000
job_queue_size = 10
```
Or
```
[apim.throttling.jms]
min_thread_pool_size = 20
max_thread_pool_size = 100
keep_alive_time_in_millis = 1000
job_queue_size = 10
```
Precendence will be given to apim.event_hub.listener configs. Only if the values are not defined under apim.event_hub.listener configs, configs under apim.throttling.jms are considered.
Git Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4613
> Parameterize EventHub threadpool configurations

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/exception/DataNotFoundException.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/webhooks/DeliveryStatusUpdater.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/webhooks/SubscribersLoader.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/webhooks/SubscribersPersistMediator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/WebhooksUtils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtilsTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataStoreImpl.java
$subject 
Git Issue: https://github.com/wso2/api-manager/issues/2203
> Skip returning API when context is null

- components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/JaegerTelemetry.java
- components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/OTLPTelemetry.java
- components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/TelemetryConstants.java
- components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/TelemetryUtil.java
- components/apimgt/org.wso2.carbon.apimgt.tracing/src/main/java/org/wso2/carbon/apimgt/tracing/telemetry/ZipkinTelemetry.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
$Subject. Fixes https://github.com/wso2/api-manager/issues/2123
OTEL Resource attributes can be provided:
- Via `deployment.toml`
```
[[apim.open_telemetry.resource_attributes]]
name = "service.name"
value = "MyService"
[[apim.open_telemetry.resource_attributes]]
name = "deployment.environment"
value = "Production"
```
AND
- Via the `OTEL_RESOURCE_ATTRIBUTES` environment variable (as per the OpenTelemetry spec [1])
```
export OTEL_RESOURCE_ATTRIBUTES=deployment.environment=Production,service.name=MyService
```
When a resource attribute is given via both the `deployment.toml` and the `OTEL_RESOURCE_ATTRIBUTES` env variable, the value of the attribute given via the env variable will replace the value given via deployment.toml.
Reading the Config - j2 file change: **TODO**
[1] …
> Add Implementation to provide OTEL Resource Attributes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/ApiCategoriesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/KeyManagersApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
Issue :https://github.com/wso2/api-manager/issues/1187
**Business Problem:**
Any admin user  can view all the sections (Rate limiting policies, Gateways, API Categories, Key Managers, Settings except Tasks) in the admin portal and users who have apim:admin can login to admin portal.
**Solution:**
Restrict each section based on the scopes and enhance modular view and give permission to login to the admin portal based on each functionality.
> added sub level scopes for admin APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
Duplicate app already exists exception message added when renaming to the already existed app name.
Fixed: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4182
Related PRs: https://github.com/wso2-support/carbon-apimgt/pull/6106
> Duplicate app already exists exception message added 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- Fixes https://github.com/wso2/api-manager/issues/2166
When creating an API Product using an API resource which has following,
- parameters given as references in path level,
- response headers given as references,
those references were not added to the API product swagger definition. This fixes the above issue by adding those references to the swagger definition.
> Add missing references to api product swagger definition

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/config/APIMConfigServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/ThrottlingApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
This fix includes
- rename throttling policy related scope name in the admin api. Existing `apim:tier_manage` and `apim:tier_view` roles are already used in publisher rest api. Fixing https://github.com/wso2/api-manager/issues/2255
- Fix for https://github.com/wso2/api-manager/issues/2256
> Admin portal API scopes related fixs

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/client/OAuthClient.java
To fix the 500 error response when invoking the API after expiring the generated refresh token for the endpoint security with client credentials grant.
Fixes: https://github.com/wso2/api-manager/issues/2261
Change the order of checking the refresh token availability to prevent this behavior with client credentials grant.
> Fix returning the 500 error response when invoking the API after expiring the generated refresh token for the endpoint security

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fixes : https://github.com/wso2/api-manager/issues/2268
> Add success info log where applicable when several retry attempts to internal API calls failed initially.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
Fix the issue of config value not properly set while enabling to retrieve federated user claims during backend JWT generation.
> Fix config issue in retrieving federated user claim

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestAPIStoreUtils.java
Public fix for issue: https://github.com/wso2/api-manager/issues/2265
> Check for multi groups

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- pom.xml
- Upgrade graphql-java version from 19.2.wso2v2 to 19.6.wso2v1
- Related PR: https://github.com/wso2/orbit/pull/981
> Upgrade graphql-java version

- components/apimgt/org.wso2.carbon.apimgt.output.adapter.http/src/test/java/org/wso2/carbon/apimgt/output/adapter/http/ExtendedHTTPEventAdaptorTestCase.java
The test class `ExtendedHTTPEventAdaptorTestCase` tries to set the System Property before every test method runs. There are 6 tests in this test class. However, these tests are not trying to modifying the System properties. Besides, `testDir` is also a static field that is only initialized once in this test class. This `testDir` is also utilized to set properties every time.  These is no need to set the properties repeatedly to increase the test runtime.
> add set the property once in the test class ExtendedHTTPEventAdaptorTestCase

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
https://github.com/wso2/api-manager/issues/1508 has introduced a new system property that change the sub claim of backend jwt with tenant aware username. However this improvement will change the enduser claim as well. Therefore this new improvement address the request in https://github.com/wso2/api-manager/issues/1788 which handles this claim manipulation properly.
> Fix the enduser claim of backend jwt to adher with enable.tenant.aware.subclaim property

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/gateway/GatewayAPIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.common.jms/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.common.jms/src/main/java/org/wso2/carbon/apimgt/common/jms/JMSConnectionEventListener.java
- components/apimgt/org.wso2.carbon.apimgt.common.jms/src/main/java/org/wso2/carbon/apimgt/common/jms/JMSTaskManager.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/DataHolder.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/ServiceReferenceHolder.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayJMSMessageListener.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/SubscriptionDataHolder.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/API.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapseArtifactGenerator.java
Fixes https://github.com/wso2/api-manager/issues/1590
> Implement recall mechanism for gateway data refreshing

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/SynapseAnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/SynapseAnalyticsDataProviderTestCase.java
This PR adds null checks and default values for backend related metric properties.
When a respond mediator is included in the request path, the gateway will not forward the request to the backend. In such cases, we need to populate the metrics related to backend in order to avoid errors in the flow. The following metrics were handled through this PR.
- backend latency
- request and response mediation latency
- proxy response code
- request destination
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5285
Fixes https://github.com/wso2/api-manager/issues/2364
> Add null checks and default values for backend related metric properties

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/OrganizationKeyManagerDto.java
With this update the resident key manger will be the first in the order of retrival.
Resolves :  https://github.com/wso2/api-manager/issues/2048
> Rearrange key managers retrieval order to prioritize the Resident Key Manager

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- Resolves https://github.com/wso2/api-manager/issues/2342
- Filter gateway labels when deploying an API to get the intersection between gateway labels from API deploy event and gateway labels from configurations.
> Fix an API deploy issue when deploying in multiple gateways 

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- Resolves https://github.com/wso2/api-manager/issues/2432
- When importing API products with overwrite query parameter set to true in the API request, default API product version value ("1.0.0") was used. In this PR it is changed to the correct version of the API product.
> Fix an issue when importing API products with overwrite query parameter set to true

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
This PR adds a null/empty check for the targetStatus in API import flow.
Fixes https://github.com/wso2/api-manager/issues/2423
> Add null/empty check for the targetStatus in API import flow

- pom.xml
This PR upgrades IS components to latest versions
snakeyaml version is kept at 1.33 since it will be upgraded by the dependency upgrade team's PR.
> Upgrade IS components to latest versions

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationService.java
This PR fixes an issue where the endUser claim was not set properly in the backend JWT in a cross tenant scenario.
Fixes https://github.com/wso2/api-manager/issues/2418
> Fix endUser claim not setting properly for opaque tokens

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- pom.xml
Upgrade the poi dependency version to `4.1.2.wso2v1` to fix build issues with product build with the xmlsec version bump.
> [4.3.0-kernel-upgrade] Upgrade poi dependency version

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/publisher/ApisApiServiceImplUtils.java
When using Service Catalog to push Integration Services from Micro Integrator, although the securityType is set as "BASIC", it is getting changed to "OAuth2" after creating an API. With this PR it will fix this issue.
Resolves: https://github.com/wso2/api-manager/issues/2457
> Fix the issue of Publishing APIs via Service Catalog with Basic Authentication

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayTokenRevocationMessageListener.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/factory/KeyManagerHolder.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/impl/RegistrationServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/OAuthJwtAuthenticatorImpl.java
Fixing https://github.com/wso2/api-manager/issues/2496
https://github.com/wso2/api-manager/issues/2495
> Change default token type of portal apps to JWT.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/GraphQLSchemaDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
This will modify  graphQL operation retrieval logic in import schema flow(This is already fixed in the API Creation flow). 
After this fix, it is not necessary to define the type as   Query, Mutation or Subscription. User can have own namespace and he should map that inside the schema.
- https://github.com/wso2/api-manager/issues/2424
> Modify graphQL operation retrieval logic in import schema flow

- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.devops/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.gateway/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/exception/GlobalThrowableMapper.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/servlet/impl/CustomCXFNonSpringJaxrsServlet.java
- components/apimgt/samples/org.wso2.carbon.apimgt.samples.calculator/src/main/webapp/WEB-INF/web.xml
- components/apimgt/samples/org.wso2.carbon.apimgt.samples.pizzashack/src/main/webapp/WEB-INF/web.xml
This PR removes spring dependency from APIM webapps.
- Instead of CXFServlet, CXFNonSpringJaxrsServlet is used as the servlet class. And the webapp configs are updated according to [1].
[1]. https://cxf.apache.org/docs/jaxrs-services-configuration.html#JAXRSServicesConfiguration-WithCXFNonSpringJaxrsServlet
> Remove Spring dependency from APIM webapps

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/DocumentIndexer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSPowerpointIndexer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSPowerpointIndexerTest.java
- pom.xml
This PR adds the following changes,
- [Bump POI version to 5.2.5.wso2v1](https://github.com/wso2/carbon-apimgt/commit/02d45828e906cbac95d146fc8621442b2951cba2)
- [Bump commons-io version to 2.15.1.wso2v1](https://github.com/wso2/carbon-apimgt/commit/ae9a54d15462489a5c11095f483149770538e5cb)
> Bump the POI version to 5.2.5.wso2v1

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/devportal-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/dto/RegistrationProfile.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/impl/RegistrationServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/resources/dcr.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/OAuthJwtAuthenticatorImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR changes opaque tokens to JWT for portal logins
Note:
This pr needs to be merged after https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2384 and https://github.com/wso2/carbon-identity-framework/pull/5547
After these PRs, Need to add following to the deployment.toml to enable JWT for portals
[apim.oauth_config]
enable_jwt_for_portals = true
[transport.https.properties]
maxHttpHeaderSize = "12288"
[oauth]
add_tenant_domain_to_access_token = true
> Add JWT as default token for portals

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixing : https://github.com/wso2-enterprise/wso2-apim-internal/issues/5635
Related PR: https://github.com/wso2-support/carbon-apimgt/pull/6374
> Add erroneous properties to the response message in API mandatory prop validation

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistrySearchUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SearchApiServiceImpl.java
Related Issues: 
https://github.com/wso2/api-manager/issues/2492
https://github.com/wso2/api-manager/issues/2462
> Fix search API issue when APIs have spaces.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS2ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS3ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas2/publisher/oas2_with_default_implicit_authorization_url.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas2/publisher/oas2_with_default_implicit_authorization_url_response.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas3/publisher/oas3_with_default_implicit_authorization_url.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas3/publisher/oas3_with_default_implicit_authorization_url_response.json
Fixes https://github.com/wso2/api-manager/issues/2478
> Override the default authenticationUrl value which added in the Implicit Grant type

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/FaultyRequestDataCollector.java
Fixes https://github.com/wso2/api-manager/issues/2504
When a request is failed due to a reason such as authentication failure, we do not log the user IP (X-forwarded header). With this PR the userIP is also added to faulty event response.
Without the fix
```
INFO ELKCounterMetric apimMetrics: apim:faulty, properties :{"apiName":"PizzaShackAPI","requestTimestamp":"2024-02-22T04:06:48.593Z","proxyResponseCode":401,"errorType":"AUTH","applicationOwner":"UNKNOWN","errorMessage":"AUTHENTICATION_FAILURE","errorCode":900902,"apiCreatorTenantDomain":"carbon.super","apiVersion":"1.0.0","gatewayType":"SYNAPSE","apiCreator":"admin","responseCacheHit":false,"regionId":"default","correlationId":"69f0ca19-3e38-4b5c-8da5-81bb4fa2a485","keyType":"UNKNOWN","applicationId":"UNKNOWN","apiId":"135cd373-56bd-4 …
```
> Add userIP to faulty event

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
Following error was returned on a graphql api invocation
```
[2024-03-20 20:16:43,230] ERROR - ServerWorker Error processing POST request for : /swapi/1.0.0.
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.generateAuthenticationContext_aroundBody46(GatewayUtils.java:739) ~[org.wso2.carbon.apimgt.gateway_9.29.47.jar:?]
at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.generateAuthenticationContext(GatewayUtils.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.47.jar:?]
at org.wso2.carbon.apimgt.gateway.handlers.security.apikey.ApiKeyAuthenticator.authenticate_aroundBody4(ApiKeyAuthenticator.java:170) …
```
> Fix: Type Casting Issue on GraphQL invocation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
Fixes https://github.com/wso2/api-manager/issues/2687
> Adding Portal Configuration Only Mode configuration

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/lifecycle/LCManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
> Using try-with-resources for closing the Input Stream, Input Stream Reader and Check canonical path of WSDL path 

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/TokenIssuerDto.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/factory/KeyManagerHolder.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/OAuthJwtAuthenticatorImpl.java
In Java 17, the javax.security.cert package has been removed. To work with X.509 certificates in Java 17 and beyond, we need to use the java.security.cert.X509Certificate class.
Fixes https://github.com/wso2/api-manager/issues/2665
> Change to java.security.cert.X509Certificate class

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/OAuthResponseMediator.java
Fixes https://github.com/wso2/api-manager/issues/2501.
With this PR OAuthResponseMediator is marked as content not aware.
> Mark OAuthResponseMediator as content-not-aware

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
When migrating from 2.6.0 to the latest versions, we can see the implementation_status flag in the registry. But in the latest versions, we only have production, sandbox and no API endpoint for prototype. So if the user needs to proceed using HTTP/REST endpoints or any other endpoint after the migration, in the next API update call we need to remove the implementation_status flag which used to identify prototype endpoints. This PR removes the implementation_status flag when updating APIs.
> [Master] Remove implementation_status flag when updating APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/GatewayPoliciesApiServiceImpl.java
To resolve the gateway policy deployment issues. An error occurs when a gateway has different names for name and display name.
```ERROR - GatewayPoliciesApiServiceImpl Invalid gateway labels: GW1```
> Fix gateway name validating issues

- components/apimgt/org.wso2.carbon.apimgt.throttle.policy.deployer/src/main/java/org/wso2/carbon/apimgt/throttle/policy/deployer/utils/ThrottlePolicyJMSMessageListener.java
This PR adds the following changes,
- [Add event waiting time configuration for throttle policy listener](https://github.com/wso2/carbon-apimgt/commit/bdafda3ec73b2238f0dbd6fe152e144e85913f2a)
- [Add a SingleThreadExecutor for the throttle policy listener](https://github.com/wso2/carbon-apimgt/commit/c39df9911b580c4f391aac97c4cc776d1bbd9ef5)
Fixes https://github.com/wso2/api-manager/issues/2349
> Add event_waiting_time config to throttle policy JMS listener

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/authenticator/MutualSSLAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/GatewayCertificateMgtUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- Resolves https://github.com/wso2/api-manager/issues/873
- In the current implementation of `MutualSSLAuthenticator` handler client certificate should exist in the truststore to a successful validation
- This PR introduces certificate chain validation to resolve the above limitation
- Following configuration is introduced to the `deployment.toml` to enable certificate chain validation
```
[apimgt.mutual_ssl]
enable_certificate_chain_validation = true
```
> Add certificate chain validation to MutualSSLAuthenticator handler

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/DocumentIndexer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/PDFIndexer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/PDFIndexerTest.java
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml
- pom.xml
pdfbox bump to 3.0.1 and add necessary pdfbox-io orbit jar
The reason to create pdfbox-io as a orbit jar is to remove sun-misc import
> pdfbox bump

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/SuccessRequestDataCollector.java
Fix https://github.com/wso2/api-manager/issues/2587
In the current implementation, an error occurs when APIM attempts to push Webhook API analytics to the apim_metrics.log file when ELK analytics is enabled. This issue stems from the lack of handling the scenario where the userName field is null and, this PR fixes this issue by handling the null.
> Fix error when pushing Webhook API analytics to apim_metrics.log with ELK enabled

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
In Mutual SSL, the API manager allows passing the client certificate in base64 encoded format and raw format via an HTTP header. When the certificate is passed in base64 encoded format, the validation happens correctly. However, if the certificate is passed as raw text, it throws the following exception while building the `X509Certificate` object.
Fixes https://github.com/wso2/api-manager/issues/1930
This PR fixes the issue by removing invalid characters and reconstructing the certificate before building the `X509Certificate` object.
> Fix validating raw MTLS certificates

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/constants/JWTConstants.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/JWTConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/AbstractAPIMgtGatewayJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/util/JWTUtil.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/test/java/org/wso2/carbon/apimgt/common/gateway/JWTUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/DefaultApiKeyGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/token/TokenGenTest.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/resources/amConfig.xml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR changes the default certificate hashing algorithm to SHA-256 instead of SHA-1. 
The following flows are affected due to this change.
1. The certificate hashing algorithm used in generating API keys will now use SHA-256 as the hashing algorithm
2. The certificate hashing algorithm used in generating backend JWTs for JWT and Opaque token SPs will now use SHA-256 as the default hashing algorithm. A config is provided to use SHA-1 as follows.
**api-manager.xml.j2**
```
<JWTConfiguration>
......
<UseSHA1Hash>{{apim.jwt.use_sha1_hash}}</UseSHA1Hash>
......
</JWTConfiguration>
```
To use SHA-1 instead of SHA-256, the following has to be added to the deployment.toml.
**deployment.toml**
```
[apim.jwt]
enable = true
use_sha1_hash = false
```
- The PR [1] has to be merged after merging this …
> Change Default Certificate Hashing Algorithm to SHA-256

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/JWTConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/AbstractAPIMgtGatewayJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/util/JWTUtil.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/test/java/org/wso2/carbon/apimgt/common/gateway/JWTUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/token/TokenGenTest.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/resources/amConfig.xml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
With [1], the default certificate hashing algorithm in Backend JWT generation was made as SHA-256. But we will revert this change and make SHA-1 as the default certificate hashing algorithm. A config will be provided to use SHA256 as the certificate hashing algorithm
**api-manager.xml.j2**
```
<JWTConfiguration>
......
<UseSHA256Hash>{{apim.jwt.use_sha256_hash}}</UseSHA256Hash>
......
</JWTConfiguration>
```
To use SHA-256 instead of SHA-1, the following has to be added to the deployment.toml.
**deployment.toml**
```
[apim.jwt]
enable = true
use_sha256_hash = true
```
[1] https://github.com/wso2/carbon-apimgt/pull/12365
> Use SHA-1 as Default Certificate Hashing Algorithm and Provide Config to Use SHA-256

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Fixing : https://github.com/wso2/api-manager/issues/2701
The tsreader (object in the `InputStream`) gets shared when `rs.getBinaryStream` is used to retrieve the `InputStream`. Therefore the subsequent calls should occur after finishing the `InputStream` reading.
> Fix MSSQL specific shared ts reader issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- This PR improves the generation of the API definition for API products
- The following improvement were done
- Support for $ref and nested entries of responses
- Support for $ref and nested entries of response headers
- Support for $ref and nested entries of examples
- Support for property entries included in allOf, anyOf and oneOf fields of schema objects
- https://github.com/wso2/api-manager/issues/2470
- https://github.com/wso2/api-manager/issues/2451
> Improve Generation of the API Definition for API Products

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/Constants.java
- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/AnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/SuccessRequestDataCollector.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/SynapseAnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/websocket/WebSocketAnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerAnalyticsConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- fixes: https://github.com/wso2/api-manager/issues/2296
> Improve: Analytics Event Data Masking

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistrySearchUtil.java
- Fixes https://github.com/wso2/api-manager/issues/2679
When multiple values are present for the same search key those are considered as an OR based search.
`ex: tags:sales tags:dev -> tags=(sales OR dev)`
When multiple search keys are present those are considered as an AND based search.
`ex: name:pizzashack version:1.0 -> name=pizzashack AND version=1.0`
> Enable mulitple filter options in API search

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Fixes https://github.com/wso2/api-manager/issues/2740
Related PRs: https://github.com/wso2-support/carbon-apimgt/pull/6432
> Populate default version only if the migration enabled

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java
This PR fixes https://github.com/wso2/api-manager/issues/2799.
Here we are registering the JavaTimeModule. There can be scenarios where customers already using a custom date/time format that conflicts with the default format used by the JavaTimeModule, might encounter issues with serialization or deserialization. For example, if the application expects dates in a specific format and the JavaTimeModule uses a different format by default, it could lead to inconsistencies or errors. Therefore we have introduced a system property **`register.timeModule`** and if only the property value is true we are registering the javaTimeModule. By default its value is `false`.
Related support PR : https://github.com/wso2-support/carbon-apimgt/pull/6449
> Register the JavaTimeModule in request path

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/EndpointCertificateDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/swagger.json
Approach : Previously we called trustore.store() after adding each certificate to the temporary trustore. With this fix the calls are reduced to one per each tenant.
> Fix certificate loading issues

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/MarketplaceAssistantApiPublisherNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/APIEvent.java
- Resolves: https://github.com/wso2/api-manager/issues/2835
Fixes the following issues:
- Api visibility of the apiEvent is null when it is hitting the notifier.
- API/ API product is not removed from vector db when making a public api private after publishing it.
> Fix update logic for marketplace assistant

- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/utils/SubscriptionValidationDataUtil.java
This PR will remove the security schema setting logic in the DTO for internal APIs other than websocket APIs, as the security schema is only necessary for them. This change aims to prevent unnecessary registry calls
- https://github.com/wso2/api-manager/issues/2855
> Update security schema setting logic in the DTO for internal APIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
Fix https://github.com/wso2/api-manager/issues/2745
An event is triggered when updating an application and updated information of the application will not be included in the event. Therefore, there can be inconsistencies between the application that is stored in the database and the application that is known by the Gateway.
This PR mitigates this issue.
> Add updatedApplication details to the application update event

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
Fix https://github.com/wso2-enterprise/wso2-apim-internal/issues/5811
This update addresses an issue encountered when attempting to access Policies(Specifically custom policies) within revisions. The problem stemmed from utilizing revision ID to retrieve API-associated data from the database, resulting in null returns and subsequent errors. To resolve this, the PR introduces a logic that verifies whether the received UUID corresponds to an API revision. If it does, a distinct SQL query is executed to fetch revision-related details, resolving the reported issue accurately.
> Added APIRevision checking logic for the getAPISpecificOperationPolicyByPolicyID function

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/handlers/APIEndpointPasswordRegistryHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryPersistenceUtil.java
In APIM 3.0.0, the endpoint password is saved in a registry field named as `endpointPassword`, but in all other versions the field is named as `endpointPpassword`. This causes issues while migrating APIs from 3.0.0 to the latest versions. 
This PR modifies the endpoint's basic auth credential retrieving logic to check for the `endpointPpassword` element as well as the `endpointPpassword` element. 
Resolves https://github.com/wso2/api-manager/issues/2881
> Fix endpoint basic auth retrieval logic 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/utils/ImportUtils.java
This will fix subscription update flow when importing existing application.
Additionally, a new improvement will be added to the subscription updating flow in the application import process. 
In this improvement, the current subscription will only be deleted if it is not available in the imported application. 
Also if only the subscription tier is different, it will update only the subscription tier.
- https://github.com/wso2/api-manager/issues/2328
- https://github.com/wso2/api-manager/issues/2874
> Fix subscription update flow when importing existing application

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/TagsApiServiceImpl.java
When the Devportal UI is loaded and the Tags/API categories section is selected, they can only see the 25 Tags which is the default value. With this update, it will show all the added tags in that section.
Fixes : https://github.com/wso2/api-manager/issues/2947
> Fix the issue of not showing all the tags under Tags/API categories in the devportal

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/template/RESTToSOAPMsgTemplate.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/template/SOAPToRESTConfigContext.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPToRESTConstants.java
Currently APIM only creates transformation configurations for SOAP 1.2. Even if the WSDL is describing a SOAP 1.1, internally the transformation configuration is hardcoded to be SOAP 1.2. 
2 new variables were added to the file [soap_to_rest_in_seq_template.xml](https://github.com/wso2/product-apim/blob/master/modules/distribution/resources/api_templates/soap_to_rest_in_seq_template.xml) in https://github.com/wso2/product-apim/pull/13511.
The mediaType should be `txt/xml` for SOAP 1.1 and it should be `application/soap+xml` for SOAP 1.2. The mediaType is determined by the `soapVersion` and passed to the `configContext` in order for it to be populated in the template.
https://github.com/wso2/api-manager/issues/2939
> Fixed transformation configuration for the 2 SOAP versions.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/publisher-api.yaml
Wrong endpoints display on the Document UI, Swagger definition, and Postman collection for third-party APIs. Production and Sandbox URLs need to be displayed on the Document UI and also need to add them into the Swagger definition
Check the current API is Advertised (Third-party) and assign the Production and Sandbox Endpoints for the server  field in the Swagger definition. This has implemented for both OAS2 and OAS3.
Resolves https://github.com/wso2/api-manager/issues/2601
> Solve invalid/incorrect URLs in Documents UI, OpenAPI/Swagger definition, and Postman collection for third-party APIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantOracle.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantPostgreSQL.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsDB2.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsH2MySQL.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java
API Developer Portal Application search is case sensitive and it does not search applications when case insensitive key words are provided. Searching process need to be case insensitive.
Change Application search queries for each DB type to search them case insensitively 
Resolves https://github.com/wso2/api-manager/issues/1434
> Add case-insensitive search capability to the Application search in the Devportal

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/Constants.java
- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/publishers/impl/AnalyticsDataPublisher.java
> To prevent `NullPointerException` when the `config_endpoint` of the `AnalyticsPublisher` is empty or null.
> Fixes https://github.com/wso2/api-manager/issues/2153
> If the `config_endpoint` is empty or null, throw a `MetricCreationException`.
> Handle NullPointerException for Empty or Null `config_endpoint` in `AnalyticsPublisher`

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS2ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OAS3ParserTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas2/oas2_paths_with_trailing_slash.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/oas3/oas3_paths_with_trailing_slash.json
This PR add a swagger validation to validate resource path names.
If there are two resource paths with the same name, one with and one without trailing slashes, it will be considered an error since those are considered as one resource in the API deployment.
With this fix, following internal REST APIs provide 400 Bad request in such cases
`PUT https://localhost:9443/api/am/publisher/v4/apis/<apiId>/swagger`
Response:
```
{
"code": 900754,
"message": "Error while parsing OpenAPI definition",
"description": "Multiple GET operations with the same resource path /menu found in the openapi definition",
"error": []
}
```
This validation executes in,
1. API creation
2. API update
3. Import swagger file
- https://github.com/wso2/api-manager/issues/2915
> Add swagger validation for paths with trailing slash

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
- fixes: https://github.com/wso2/api-manager/issues/2101
> Fix: Reserved character Issue in Certs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/admin-api.yaml
[FIX-01]
In order to fix the error when creating a new revision, we need to consider a situation where there is an API with two or more resources having the same resource method and the same resource path, but with different cases. This error occurs when attempting to create a new revision from this API.
Fixes: https://github.com/wso2/api-manager/issues/2999
Configuring resources in this way is not the best practice; however, we have addressed this by performing a case-sensitive URL_PATTERN search using Latin1_General_CS_AS collation on the URL mappings of the API during new revision creation.
[FIX-02]
Fixes StuckThreadDetectionValve issue while creating an API Product.
Fixes: https://github.com/wso2/api-manager/issues/3030
Introduced getPublishedDefaultVersion method to resolve the …
> Fix error creating new API revision  and StuckThreadDetectionValve issue while creating an API Product

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/DefaultKeyManagerConnectorConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/TokenValidationDto.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/jwt/TypeEnforcedJWTValidatorImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
Fixes https://github.com/wso2/api-manager/issues/2948
To enforce JWT `typ` header validation, a new configuration was introduced.
```toml
[apim.token.validation]
enforce_type_header_validation = true
```
Default: `false`
> Fix accessing API resources using id_token

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/configdto/HttpClientConfigurationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/util/CommonAPIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/test/java/org/wso2/carbon/apimgt/common/gateway/CommonAPIUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Fixing : https://github.com/wso2/api-manager/issues/3020
Sample config 
```toml
[apim.http_client]
connection_timeout = 5000
```
`-1` : System Default timeout
`0` : No timeout
`any other value` : Timeout in Milliseconds
[1] https://hc.apache.org/httpcomponents-client-4.5.x/current/httpclient/apidocs/org/apache/http/client/config/RequestConfig.html#getConnectTimeout()
> Add http client connection timeout tuning param config

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/SubscriptionValidationDAO.java
Fixes https://github.com/wso2/api-manager/issues/3076
> Add Ignore Case String check for APIProduct Type

- .github/workflows/main.yml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ThrottlingApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
> Bump APIM version to fix CTL test failures

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/LifeCycleUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIRevisionDeploymentDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/ImportExportAPIServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
This PR adds improvements to the following Publisher product rest api error responses.
1. `/apis/import-openapi` - POST
2. `/apis/change-lifecycle` - POST
3. `/apis/{apiId}/revisions` - POST
4. `/apis/{apiId}/deploy-revision` - POST 
5. `/apis/{apiId}/undeploy-revision` - POST
6. `/apis/import` - POST
7. `/api-products/{apiProductId}/revisions` - POST
8. `/api-products/{apiProductId}/deploy-revision` - POST
9. `/api-products/{apiProductId}/undeploy-revision` - POST
10. `/api-products/change-lifecycle` - POST
11. `/api-products/import` - POST
12. `/api-products` - POST
13. `/api-products/{apiProductId}` - PUT
14. `/apis/copy-api` - POST
15. `/apis/{apiId}/swagger` - PUT
> Improve product rest api error responses for publisher

- pom.xml
This PR adds the necessary changes to fix the issues with new synapse versions and changes required to bump gson, jackson, and cxf dependencies
Issue for dependency upgrades: https://github.com/wso2/api-manager/issues/3105
> Bump synapse and dependency versions

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
Handle Null value for Throttling_Tier retrieved from DB which causes due to removing tier update query at the server startup as an improvement.
> Handle Null value for Throttling_Tier retrieved from DB

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/Authentication/ApiKeyAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/ApiKeyAuthenticatorUtils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/DefaultApiKeyGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIKeyUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
The current API Key implementation in the API Manager includes several claims that are not essential for the API Key itself but are required during the API Key authentication process.
- Remove the unnecessary claims from the API Key.
- Modify the authentication process to retrieve API, Application, and Subscription-related details directly from the Data Store.
- Remove the subscription validation-related configuration from the configs, making it mandatory to validate the subscription during the authentication process.
Resolves https://github.com/wso2/api-manager/issues/3097
> [Improvement] Lightweight apikey

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/MarketplaceAssistantApiPublisherNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/APIEvent.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/LifeCycleUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/MarketplaceAssistantApiServiceImpl.java
> This will allow users to retrieve visibility controlled APIs from marketplace assistant.
> Following changes are introduced in this PR
- Upload visibility controlled APIs to vector-store with visibility roles.
- Include user roles to the prompt query for marketplace assistant.
> Adding role based access control to marketplace assistant

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/JWTConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/jwtgenerator/AbstractAPIMgtGatewayJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/util/JWTUtil.java
- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/test/java/org/wso2/carbon/apimgt/common/gateway/JWTUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Fixes https://github.com/wso2/api-manager/issues/2964
By default x5t value is encoded with padding to match the previous behaviour. Below configuration can be added if someone wants to disable padding for x5t.
```
[apim.jwt]
encode_x5t_without_padding=true
```
> Fix backend JWT x5t inconsistencies

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
This PR adds the improvement to yield error when the requested API is not available when exporting APIs.
Related issue: https://github.com/wso2/api-manager/issues/3070
> Add improvement to yield error when the requested API is not available when exporting APIs

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/logging/APILogHandler.java
Fixes https://github.com/wso2/api-manager/issues/3098
> Remove the extra forward slash from the resource name in api logs.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
The Key Manager Gateway's internal endpoint (internal/data/v1/keymanagers) lacked the ability to retrieve all key managers by passing the header xWSO2Tenant: "ALL".
- Resolves https://github.com/wso2/api-manager/issues/3180
When the tenant domain is set to "ALL", a query will be executed to retrieve all key managers from the AM_KEY_MANAGER table.
> [4.4.0] Get all key managers from all tenant domains

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/MicroGatewayArtifactGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryPersistenceUtil.java
Fix: https://github.com/wso2/api-manager/issues/2998
Fix: https://github.com/wso2/api-manager/issues/3056
> Fixing CC runtime artifacts retrieval issue and GW timeout issue during API subscription retrieval

- pom.xml
This PR upgrades the analytics event publisher client to 1.2.20.
Related PR: https://github.com/wso2/apim-analytics-publisher/pull/115
> Upgrade analytics event publisher client to 1.2.20

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/api_definitions/azure_api.yaml
$subject
Fix: https://github.com/wso2/api-manager/issues/3213
> Fix file references in api definition

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- $subject
- https://github.com/wso2/api-manager/issues/3236
Eliminate the use of CONCAT in the get block condition  by type and value SQL query, as it does not comply with older versions of the Oracle database.
> Fix Oracle Database Issue in Block Condition Search

- pom.xml
This PR Upgrades the swagger-parser version to 2.1.22.wso2v2.
Orbit bundles: https://github.com/wso2/orbit/pull/1140
carbon-mediation PR: https://github.com/wso2/carbon-mediation/pull/1734
> [APIM-4.4.0] Upgrade swagger-parser version

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/constants/HealthCheckConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/DefaultAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/LogsHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/AnalyticsMetricsHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/Constants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencySynapseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/sse/SseApiHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/webhooks/SubscribersPersistMediator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/GatewayArtifactSynchronizerProperties.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- Resolves https://github.com/wso2/api-manager/issues/3094
Implemented endpoints to retrieve the API health status through various traffic ports. This enables checking the health of APIs deployed on the Gateway. Following are the implemented Health Check Endpoints,
- https://localhost:8243/health-check
- http://localhost:9099/health-check
- https://localhost:8099/]health-check
- http://localhost:9021/health-check
- https://localhost:8021/health-check
Introduced a new configuration to add file-based API contexts. These file-based API contexts will no longer publish data to analytics. The following configuration is added to the `deployment.toml` file,
```
[apim.sync_runtime_artifacts.gateway]
file_based_api_contexts = ["/jwks", "/health-check"]
```
Add your file-based API contexts here to …
> Implement API Health Check Endpoints for the Traffic Ports and Avoid Publishing Analytics Data from File-Based APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
This PR fixes the NPE encountered when trying the download/export an API product
```
[2024-10-15 10:34:11,714] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:?]
at org.wso2.carbon.caching.impl.CacheImpl.containsKey(CacheImpl.java:286) ~[javax.cache.wso2_4.9.27.alpha.jar:?]
at org.wso2.carbon.governance.api.util.GovernanceUtils.getArtifactPath(GovernanceUtils.java:797) ~[org.wso2.carbon.governance.api_4.8.34.jar:?]
at org.wso2.carbon.governance.api.util.GovernanceUtils.retrieveGovernanceArtifactById(GovernanceUtils.java:976) …
```
> Fix NPE encountered during API Product export

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fixes the following error in a distributed setup
```
[2024-10-14 21:19:43,728] ERROR - APIUtil Error while creating axis configuration for tenant b.com
java.lang.RuntimeException: Cannot create tenant ConfigurationContext for tenant b.com
at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:160) ~[org.wso2.carbon.core_4.9.27.SNAPSHOT.jar:?]
at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantAxisConfiguration(TenantAxisUtils.java:108) ~[org.wso2.carbon.core_4.9.27.SNAPSHOT.jar:?]
at org.wso2.carbon.apimgt.impl.utils.APIUtil.loadTenantConfigBlockingMode_aroundBody364(APIUtil.java:4826) ~[org.wso2.carbon.apimgt.impl_9.30.46.SNAPSHOT.jar:?]
at org.wso2.carbon.apimgt.impl.utils.APIUtil.loadTenantConfigBlockingMode(APIUtil …
```
> Start tenant flow before creating tenant context

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/jndi2-cp.properties.j2
- pom.xml
- Broker connect timeout cannot be explicitly configured for TM duplication URLs.
- Upgrade Andes and the Carbon Broker versions.
Add a logic to the .j2 file to handle "connecttimeout" broker parameter.
- Related issue https://github.com/wso2/api-manager/issues/3125
> JNDI2 Config Upgrade for the Broker Connect Timeout and Upgrade Andes and Broker Versions

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
Fixes: https://github.com/wso2/api-manager/issues/3240
The current `tenant-conf.json` is missing the newly introduced LLM-related scope mappings `apim:llm_provider_manage` and `apim:llm_provider_read`. As a result, the following warnings are triggered,
```bash
[2024-10-10 18:47:26,442]  WARN - SystemScopesMappingUtil The scope apim:llm_provider_manage does not exist in tenant.conf
[2024-10-10 18:47:26,442]  WARN - SystemScopesMappingUtil The scope apim:llm_provider_read does not exist in tenant.conf
```
This pr resolves the issue by adding the necessary scope mappings, specifically `apim:llm_provider_manage` scope to role `admin` and `apim:llm_provider_read` scope to `admin`, `Internal/publisher`, and `Internal/creator`.
> Add llm related scope mappings to tenant-conf.json

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
- Fix https://github.com/wso2/api-manager/issues/3312
- Update validateCustomPolicy to check for the presence of CUSTOM_PROPERTY in messageContext
- Iterate through CUSTOM_PROPERTY Map to replace customProperty placeholders in the key template
> Add custom policy replacement handling in validateCustomPolicy method

- components/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension/src/main/java/org/wso2/carbon/apimgt/throttling/siddhi/extension/ThrottleStreamProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension/src/test/java/org/wso2/carbon/apimgt/throttling/siddhi/extension/ThrottleTimeBatchWindowTestCase.java
When the TM receives events, it currently places them into the current bucket without considering the original event generation timestamp. As a result, events generated before downtime are counted toward the active throttling period, leading to early throttling.
This PR adds a timestamp check to the throttling logic to ensure that each event is evaluated based on its generation time. By incorporating this timestamp, events generated before downtime are dropped, preventing them from causing premature throttling when a DC resumes operation.
- Resolves https://github.com/wso2/api-manager/issues/3322
> Fix Early Throttling by Adding Timestamp Check to Throttling Logic and Refine Throttling Related Unit Tests

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandlerTest.java
- Return retry-after header when throttled by burst control.
- Related to https://github.com/wso2/api-manager/issues/3128
- Get next access time stamp from CallerContext.
- Add the next access time stamp to the synapse context in the ThrottleHandler.
> Add nextAccess timestamp to synapse context when throttle by burst control

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
This PR increase the maximum length of the API Provider to overcome issues when the API Creator's username length is a larger value
Resolves https://github.com/wso2/api-manager/issues/3365
> Increase the Max Length of the API Provider Field

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandler.java
$Subject.
When analytics is enabled, after sending a websocket text message frame to `outboundhandler().write()` in `WebsocketHandler`, we read that WebSocket text message frame again to calculate the message length. This causes an `IllegalReferenceCountException` (which is thrown but absorbed) -  causing the analytics event not published afterwards.
This PR fixes the above issue by reading the text message frame first, and then sending it to `outboundhandler().write()`.
> Fix publishing analytics event after responseSize calculation in WebSocket messages

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/subscription/API.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/SubscriptionValidationDAO.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/utils/SubscriptionValidationDataUtil.java
- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/resources/api.yaml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/API.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataStoreImpl.java
This PR resolves an issue with generating the default version context for APIs. Previously, the implementation unintentionally removed multiple occurrences of /version-like segments from the API context, even when these segments were not part of the version.
The fix utilizes the CONTEXT_TEMPLATE stored in the database to generate the default version context. Specifically, all occurrences of /{version} and {version} are removed from the CONTEXT_TEMPLATE, and the resulting string is used as the context for the default version.
- Resolves https://github.com/wso2/api-manager/issues/3364
> Fix Default API Context Generation Issue

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/oauth/client/OAuthClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthClientTest.java
- This PR adds a null check to handle the scenario where the scope value returned by the token endpoint configured in endpoint security config is null
- Related Public Issue: https://github.com/wso2/api-manager/issues/3302
- Added a null check to handle the scenario where the scope value is null
> Add Null Check to Handle the Scenario Where the Scope Value is null

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
Fixes: https://github.com/wso2/api-manager/issues/3241
The current implementation of the `getAllAPIs` method in the admin REST API relies on the `searchPaginatedApis` functionality from `APIAdmin`. This performs a content-based search that retrieves all APIs, API Products, and Documents, subject to a predefined constraint on the number of search results. As outlined in the issue, this approach may result in an empty API result set if the returned list only contains API Products and Documents.
This pr addresses the limitation by leveraging the `APIProvider`'s `searchPaginatedAPIs` method, which directly retrieves all APIs from `APIPersistence`. This change ensures that the API results are not impacted by the presence of other entities such as API Products and Documents.
> Utilize `APIProvider` to retrieve all APIs in admin REST API

- components/apimgt/org.wso2.carbon.apimgt.common.jms/src/main/java/org/wso2/carbon/apimgt/common/jms/JMSListener.java
There is a need to log the currently connected TM of the GW server in the JMS connection for trouble shooting purposes.
Related to - https://github.com/wso2/api-manager/issues/3323
Log the `stm.getJmsConsumerName()`, `stm.getDestinationJNDIName()` and `connection` at `INFO` level.
> Log the connected TM server over the JMS connection during the start-up of the GW server

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/DefaultAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyDataStore.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/WSAPIKeyDataStore.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/DefaultAPIHandlerTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/ExtendedJWTConfigurationDto.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/dao/test/APIMgtDAOTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/amConfig.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/AbstractKeyValidationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/KeyValidationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationService.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/resources/amConfig.xml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- Provide the configuration support to disable the deployment of the in memory JWKS api.
- Update Unit tests to include the updated config for JWKS api enabling/disabling
- Fix sandbox invocation using API key is blocked when subscription is blocked for production only.
- Currently instead of key type, application token type  is used to determine if the API key is production or sandbox type in the above condition giving the incorrect behaviour.
- Fixes https://github.com/wso2/api-manager/issues/3136
- Fixes https://github.com/wso2/api-manager/issues/3395
- Add `EnableJWKSApi` configuration constant to enable/disable JWKS Api
- Using the set configuration value check the condition if to deploy the JWKS Api
- Add default value to `EnableJWKSApi` configuration in amConfig.xml
- Mock the …
> Add enable/disable deploying in-memory JWKS Api and Fix block subscription for production only bug

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
Currently, the comparison between the Policy Registry Resource Path and the API Registry Resource Path is case-sensitive. However, case sensitivity is not essential for this check and may cause unnecessary mismatches.
- Resolves https://github.com/wso2/api-manager/issues/3402
Update the comparison logic to be case-insensitive by converting both paths to lowercase before comparison. This ensures consistency regardless of case differences.
> Make Policy Path Comparison Case-Insensitive

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/DefaultAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
- pom.xml
- Resources having the OPTIONS method bring to the 0th index of the `acceptableResourcesList` to be selected in the `dispatcher.findResource` logic when routing the OPTIONS traffic to backend.
- Bump the Synapse version to `4.0.0-wso2v152`
- Set the current API object to the `MessageContext` from the `DefaultAPIHandler`
- Related Issue: https://github.com/wso2/api-manager/issues/2226
- Resolves https://github.com/wso2/api-manager/issues/3377
> Route OPTIONS Resource Traffic to the Backend

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/BasicAuthenticationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Fixes : https://github.com/wso2/api-manager/issues/3348
> Add Basic Auth Blocked URI configuration to RestAPIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/handlers/APIIndexingHandler.java
Editing old API revisions result in a Null Pointer Exception due to null being returned from [here](https://github.com/wso2/carbon-apimgt/blob/ba61afcd5ad4ddb2e058e6753bba99bd730c7cac/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/CustomAPIIndexer.java#L62) and that null being accessed [here](https://github.com/wso2/carbon-registry/blob/b62a7997e5ccdd8d719c115fcab4dea5c66b060a/components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java#L343)
This fix will create a new Indexing Handler that extends the Indexer handler in the carbon registry. it will check if the API being processed is an old revision, and will return immediately if so. 
If it's a current …
> Added custom API Indexing handler to bypass indexing of old API revisions.

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryPersistenceUtil.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistrySearchUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SearchApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
Fixes https://github.com/wso2/api-manager/issues/3406
> Implement organization support in unified search and fix bugs identified via integration tests

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/devportal-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml
This update introduces a capability that could represent a valid business requirement for certain customers. Consequently, the API-M product will include a system property that enables update access for users within the application-sharing group. This feature will be disabled by default to ensure the current behavior remains unchanged.
Fixes: https://github.com/wso2/api-manager/issues/3446
Introduced `orgWideAppUpdateEnabled` system property to enable this capability.
Ex.: `sh api-manager.sh -DorgWideAppUpdateEnabled=true`
Related PR: https://github.com/wso2/apim-apps/pull/843
> Add support for org-wide application update

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fix: https://github.com/wso2/api-manager/issues/3399
> Add audit logs for API documents

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandler.java
> - This PR fixes the issue of incorrect request validation when schemas are defined as composed schemas (`allOf`, `anyOf`, and `oneOf`). In the current code, the `setResolveCombinators` option is not set to `false` during parsing, which introduces this issue.
> - By default, the `setResolveCombinators` option is `true` during parsing, which transforms composed schemas into "non-composed" ones by merging all properties into a single resulting schema. Because of this, requests are not validated as intended when schemas are defined as composed schemas.
> - Resolves: https://github.com/wso2/api-manager/issues/3409
> - The `setResolveCombinators` option is explicitly set to `false`.
> - Additionally, the `setResolve` option is explicitly set to `true`. Although this is implicitly enabled with …
> Set setResolveCombinators to false when parsing OpenAPI/Swagger definition

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- Bump APIM version constant to 4.5.0. This change is done to support CTL test cases as well
> Bump APIM Version Constant to 4.5.0

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
This PR fixes an issue where restoring a revision to the working copy does not restore any of the attributes of the API.
Fixes https://github.com/wso2/api-manager/issues/3507
> Fix issues in restoring revision

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/OperationPolicy.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/OperationPolicyDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapsePolicyAggregator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/OperationPolicyMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
Public fix of https://github.com/wso2-enterprise/wso2-apim-internal/issues/7352
Previously when exporting an API which has an API policy (ex :policy1) and common policy (ex : policy1) with the same name and version, only one of them is exported. The import flow also didn't allow to import those policies. The PR fixes the above.
> Modify implementation to allow an API and a Common policies with same and version

- components/apimgt/org.wso2.carbon.apimgt.governance.api/src/main/java/org/wso2/carbon/apimgt/governance/api/ComplianceManager.java
- components/apimgt/org.wso2.carbon.apimgt.governance.api/src/main/java/org/wso2/carbon/apimgt/governance/api/error/GovernanceExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.governance.api/src/main/java/org/wso2/carbon/apimgt/governance/api/service/APIMGovernanceService.java
- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/ComplianceManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/service/APIMGovernanceServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/util/APIMUtil.java
- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/util/GovernanceUtil.java
- components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/java/org/wso2/carbon/apimgt/governance/rest/api/impl/ArtifactComplianceApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/resources/governance-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiCommonUtil.java
> [Gov Feature Branch] Update Sync Evaluation Flow

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/OrganizationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/OrganizationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/admin-api.yaml
1. Organization ID is the UUID assigned by apim side and it can't be a required field when registering new orgs.
2. Users without an organization should not be able to register orgs to apim.
1. Removed organizationId and add externalOrganizationId as required which is already created by the external IDP.
2. Throw a 403 error when user's parent organization is null.
> Fix minor bugs related to Organizations

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistrySearchUtil.java
> Currently when doing exact search with context it is required to append version to the query. eg - **context:"/test/1.0.0"**
> From this fix we will allow user to search all APIs which containing specified context. eg - **context:"test"** 
> Related issue - https://github.com/wso2/api-manager/issues/3554
- Modify search query for exact search when the query parameter is context.
- This fix will preserve the original behaviour of this search. (eg - **context:"/test/1.0.0"**)
- Search query as shown bellow when **context:"test"** is given.
> eg - `(*/test/* OR /test)`
> Improve behaviour of API search with context as the property

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/WorkflowMappingUtil.java
Resolves the issue of getting workflow type as null in the Subscription Update Workflow section of the admin portal.
Related to: https://github.com/wso2/api-manager/issues/3494
Internal: https://github.com/wso2-enterprise/wso2-apim-internal/issues/8378
> Fixed the throwing null value issue for subscription update workflow type

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/InboundWebSocketProcessor.java
This PR addresses a limitation in the resource matching logic for APIs that involve both wildcard paths (e.g., `/*`) and paths containing path parameters (e.g., `/resource-with-path-param/{path-param}`). 
Previously, when requests were made to paths containing parameters, the system would incorrectly prioritize `URLMappingBasedDispatcher` resource, leading to an unintended selection of wildcard resources over more specific path parameter resources.
The new implementation refines this by introducing a check that prioritizes `URITemplateBasedDispatcher` resources when both types of resources are present, ensuring that path-specific resources are matched before wildcard resources.
Issue: https://github.com/wso2/api-manager/issues/3307
Internal: …
> Fix scope validation issue with wildcard resources

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/APIInfoMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/APIInfoMappingUtilTest.java
The current implementation introduced in [1] to address issue [2] does not replace `-AT-` with `@` when listing APIs on the `Change API Provider` admin page for tenants. As a result, the process of changing the API provider has become unintuitive and inconsistent. This pull request aims to enhance the fix provided in [1] by addressing this gap. It is worth noting that the previous logic for listing APIs on the `Change API Provider` admin page followed a similar approach [3].
[1] https://github.com/wso2/carbon-apimgt/pull/12679 
[2] https://github.com/wso2/api-manager/issues/3241
[3] https://github.com/wso2/carbon-apimgt/blob/bf7e34db673c644cbd34faa7ed458c7acae1822d/components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl. …
> Replace `-AT-` with `@` in change API provider list

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistrySearchUtil.java
The current **DevPortal API search** supports multiple filter criteria, introduced in PR [1][2]. However, this update inadvertently broke the previous behavior where tags containing space characters were supported. For example, **APIM 3.2.0** allowed searches like `tag:Sample APIs - New`.  
This PR resolves the issue by restoring support for space-containing tags in search queries. Additionally, it ensures that both `tag` and `tags` filters function correctly when used with space characters.  
- `tag:Sample APIs - New`  
- `tags:Sample APIs - New tags:pizza`  
The solution modifies the search logic by concatenating the following search components into the previous filter criteria:  
1. **`tag:Sample APIs - New name:Google`** → `tag:Sample APIs - New && name:Google`  
2. **`Google …
> Fix for Filter-Based API Search with Space Characters in DevPortal

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/CertificateMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/dao/test/CertificateMgtDaoTest.java
Fix the issue where the 'General Endpoint Configurations' section in the Publisher Portal does not display applied certificates from other APIs with the same domain name.
The current implementation for retrieving certificates in the Publisher Portal relies on an exact match with the applied endpoint of the API. As a result, if another API shares the same domain name but has a different endpoint path, the associated certificate is correctly applied underneath during backend communication but does not appear in the UI.
Ex: `https://google.com` and `https://google.com/api/v1`
This PR addresses the issue by replacing the exact match (`=` operator) with the `like` operator and wildcard (`%`) syntax. This ensures that certificate retrieval is based on the fully qualified domain name (FQDN) …
> Fix endpoint certificate retrieval by using FQDN

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/ai/DesignAssistantConfigurationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/DesignAssistantAPIPayloadResponseDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/DesignAssistantChatQueryDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/DesignAssistantChatResponseDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/DesignAssistantGenAPIPayloadDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/DesignAssistantApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/DesignAssistantApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/DesignAssistantApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.yaml
> Implements two new resources (Chat and Generate API Payload) for API Design Assistant.
> Related issue: https://github.com/wso2/api-manager/issues/3564
> This PR implements REST API resources for the API Design Assistant, enabling it to retrieve text and session IDs from the frontend, forward them to the LLM backend, receive the response, and seamlessly return it to the frontend UI.
> Add chat and generate API payload REST API resources with token implementation for API Design Assistant

- pom.xml
This PR bumps the kernel and multi tenancy versions for APIM 4.5.0 Alpha release.
> Bump kernel and multi tenancy versions

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
This PR fixes an issue where the subscription availability could be changed from the REST API level (using an API update) even when the cross tenant subscription was disabled through the configurations.
Fixes https://github.com/wso2/api-manager/issues/3524
With this fix, the subscription availability change would be allowed only to CURRENT_TENANT when cross tenant subscription is disabled. There's no impact when subscription availability is not changed. It will stay the same regardless of the configuration.
> Remove the capability to change the subscription availability when cross-tenant subscription is disabled

- components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/java/org/wso2/carbon/apimgt/governance/rest/api/util/ComplianceAPIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
This pull request includes updates to the policy adherence logic and cleanup of unused imports. The most important changes include modifying the logic for setting policy adherence status and removing an unused import from `PublisherCommonUtils`.
Improvements to policy adherence logic:
* [`components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/java/org/wso2/carbon/apimgt/governance/rest/api/util/ComplianceAPIUtil.java`](diffhunk://#diff-57636ef562217be418d5dcbd0e9df2e9b7bbaf1ed69f8d0cd40c71df3d9eb7d3L230-R243): Modified the logic to set the policy adherence status based on the ruleset validation results. The new logic checks if any ruleset is violated, if all rulesets are unapplied, or otherwise sets the status to followed.
Codebase cleanup:
* …
> [Gov Feature Branch] Fix Codestyle Issue and Policy Status Minor Bug 

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/OrganizationTiers.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- Resolves https://github.com/wso2/api-manager/issues/3610
- Add implementation to work with subscription validation disabling feature
- Store root organization's subscription policies with its organization ID in the registry
- Add backend changes for default behaviour with subscription validation disabling feature
- When root organization  has subscription validation disabled, it will be disabled for other shared organization's as well
- When root organization needs subscription validation
- If there are subscription policies defined for a shared organization it will be used
- If it is not assigned root organization's subscription policies will be used for that organization
> [B2B] Add improvements to organization based subscription policies

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- SP name is created as a combination of application UUID and several other parameter from apim 4.0.0 onwards.
- Due to a need, this was revert back to application name instead of UUID when system property is passed.
- If the system property `sp.name.application` passed the normal behaviour is overridden.
- System property can be passed with `sh api-manager.sh -Dsp.name.application=true`
- Related to https://github.com/wso2/api-manager/issues/3368
- Changed service provider name application UUID part to application name when the system parameter is passed.
- Added application renaming fix.
- Test the fix manually and with integration test relevant to this fix. All the tests were passed.
> Add application name as a part of sp name when specified as system parameter

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/CredentialsCache.java
- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/restapi/publisher/ApisApiServiceImplUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
- pom.xml
This PR update AWS Lambda Mediator code to use AWS SDK 2.x.
> Migrate Lambda mediator to AWS SDK 2.x

- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/APIGovernanceHandler.java
- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/dao/constants/SQLConstants.java
- features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-policies/wso2_api_mgt_best_practices.yaml
- features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-rulesets/wso2_rest_api_design_guidelines.yaml
Fixes https://github.com/wso2/api-manager/issues/3650
This pull request includes changes to improve naming consistency and remove unnecessary SQL constraints. The most important changes include renaming a YAML file and updating policy descriptions to ensure uniformity.
Improvements to naming consistency:
* [`features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-policies/wso2_api_mgt_best_practices.yaml`](diffhunk://#diff-92338162d33d48117f63b047181a9577c23af9348f285d214f2544330f39d8c8L8-R16): Renamed from `wso2_api_best_practices.yaml` and updated the policy name and description to reflect "WSO2 API Management Best Practices" and "WSO2 REST API Design Guidelines".
* [`features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-ruleset …
> [Governance] Rename Default Ruleset, Policy and Fix Mssql Bug

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.devops/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.internal.service.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.admin.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.dcr.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.devops.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.gateway.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml
- pom.xml
To upgrade the hibernate-validator version from 6.0.23.Final to the non-vulnerable 6.2.5 version.
- Upgraded javax.validation-api version 2.0.1.Final to jakarta.validation-api version 2.0.2 to resolve API creation issues
> Upgrade hibernate-validator dependency

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/SynapseAnalyticsDataProvider.java
> AI API-related analytics are not presented in analytics dashboards because AI API-related properties are not written to `apim_metrics.log`. The issue was that the properties were accessed through `axis2MessageContext`, but they are no longer available there.  
>  
> Resolves: https://github.com/wso2/api-manager/issues/3700  
> AI API-related properties are available in `messageContext`. Hence, the code has been updated to access the properties from `messageContext` instead of `axis2MessageContext`.
> Fix Issue with Writing AI API-Related Properties to apim_metrics.log

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
Fixes a product apim test failure introduced with https://github.com/wso2/carbon-apimgt/pull/13006/files
- Have to return the added environment object back, otherwise the ID field will be empty.
> Fix product test failure

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AIAPIMediator.java
> Code reformatting issues in  AI APIs

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Environment.java
- components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/java/org/wso2/carbon/apimgt/governance/rest/api/SwaggerYamlApi.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SwaggerYamlApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.gateway/src/main/java/org/wso2/carbon/apimgt/rest/api/gateway/SwaggerYamlApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/SwaggerYamlApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/SwaggerYamlApi.java
Fixes wso2/api-manager#3730 
Fixes wso2/api-manager#3727
Close unclosed resource streams
This pull request includes various improvements and fixes across multiple files. The most important changes include adding permissions to the `Environment` class, ensuring case insensitivity in the `hasIntersection` method, and updating the `swaggerYamlGet` method to use `InputStream` for reading YAML files.
* Added a new field `permissions` to the `Environment` class and updated the constructor to initialize it. (`components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Environment.java`)
* Updated the `hasIntersection` method to convert elements to lowercase before adding to the set and checking for intersections. …
> Key Manager Visibility, Gateway Visibility Bug Fixes and Other Fixes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
The current implementation of the resident Key Manager configuration initially relies on the settings provided in the TOML files. However, once the resident Key Manager configuration is saved, subsequent configurations are read from the database. As a result, certain changes cannot be updated via the UI, nor are they affected by modifications in the TOML configuration.    
This pull request (PR) prioritizes TOML-based configurations over database-stored configurations for the resident Key Manager, ensuring that changes made in the TOML files take precedence. Additionally, it fixes the issue where the `openid-configuration` endpoint is not being updated in the resident Key Manager.  
https://github.com/wso2/api-manager/issues/3572
> Give precedence to toml configuration for the resident Key Manager

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapsePolicyAggregator.java
The current implementation does not handle trailing `/` in resources during operation policy aggregation, causing failures when enforcing an operation policies on such resources.
Ex: `/menu/`
This PR introduces functionality to properly handle and remove trailing `/` during operation policy aggregation, ensuring correct policy enforcement.
https://github.com/wso2/api-manager/issues/3624
> Remove trialing `/` in resource during operation policy aggregation

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/InternalServiceCall.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/listeners/ServerStartupListener.java
fixes: https://github.com/wso2/api-manager/issues/3297
> Fix: Server Starup Issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- There is a issue as follows due to improper formatting of a SQL query when running with Postgres DB
```
org.postgresql.util.PSQLException: ERROR: trailing junk after parameter at or near "$3WHERE"
```
- This PR fix the formatting issue of the SQL query
> Fix Formatting Issue of SQL Query

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/GlobalMediationPolicyImpl.java
In the previous implementation of operation policy migration, `OMException` was not handled, causing the API save functionality to be interrupted when encountering a corrupt mediation policy in the `in`, `out`, or `fault` directories. This occurred even if the corrupted policy was not assigned to the API.
This PR addresses the issue by logging a message when a corrupted mediation policy is detected, preventing it from disrupting the API save process. The details of the corrupted policy will be recorded in the logs.
```
[2025-02-19 14:24:57,804] ERROR - GlobalMediationPolicyImpl Error occurred while getting omElement out of mediation content from /apimgt/customsequences/in/authorization_pipeline.xml
org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected …
```
> Catch `OMException` type exception during operation policy migration

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
Fixes https://github.com/wso2/api-manager/issues/3453
This pull request includes an important change to the `OASParserUtil.java` file that enhances the handling of schema references in the `addSchemaOfSchema` method.
Enhancements to schema reference handling:
* [`components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java`](diffhunk://#diff-8a21aa587423ad2248a05927197442d9f98436f3997c52a507cd530c213258a8R887-R891): Added logic to check if a property schema has a `$ref` and, if so, add it to the `references` list. This ensures that all schema references are properly collected.
> Fix APIM Product Creation Bug with `allOf`

- features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-rulesets/owasp_top_10.yaml
- features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-rulesets/wso2_api_management_guidelines.yaml
- features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-rulesets/wso2_rest_api_design_guidelines.yaml
This pull request updates the documentation links in the OWASP Top 10, WSO2 API Management Guidelines, and WSO2 REST API Design Guidelines rulesets. The new links point to the latest version of the WSO2 API Management documentation.
Documentation updates:
* [`features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-rulesets/owasp_top_10.yaml`](diffhunk://#diff-3004b4ae7c97d3d7bb919329c5cb19ebb5f0ed9899e704d59c9f5e42edf98ef9L15-R15): Updated the `documentationLink` to the latest OWASP Top 10 documentation.
* [`features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-rulesets/wso2_api_management_guidelines.yaml`](diffhunk://#diff-fa68ce115dd73607a47a0058cd1f4ca04643287c1e98f191552fb0b5c31bb5f8L15-R15): Updated the `documentationLink` …
> Change Default Ruleset Doc Links

- components/apimgt/org.wso2.carbon.apimgt.governance.api/src/main/java/org/wso2/carbon/apimgt/governance/api/service/APIMGovernanceService.java
- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/PolicyManager.java
- components/apimgt/org.wso2.carbon.apimgt.governance.impl/src/main/java/org/wso2/carbon/apimgt/governance/impl/service/APIMGovernanceServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/java/org/wso2/carbon/apimgt/governance/rest/api/util/APIMGovernanceExceptionMapper.java
- components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.governance.rest.api/src/main/webapp/WEB-INF/web.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/LinterCustomRulesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/LinterCustomRulesApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/LinterCustomRulesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.governance.feature/src/main/resources/default-rulesets/wso2_rest_api_design_guidelines.yaml
This pull request introduces several new methods and changes to the API management governance service to support the retrieval of applicable rulesets for artifacts. Additionally, it updates the linter custom rules API to include parameters for filtering by API ID and API type.
These changes enhance the flexibility and functionality of the API management governance service by allowing more granular control and retrieval of rulesets based on specific artifact and API details.
> Update Spectral Linter Rulesets and Other Gov Bug Fixes

- components/governance/org.wso2.carbon.apimgt.governance.engine/src/main/java/org/wso2/carbon/apimgt/governance/engine/SpectralValidationEngine.java
This pull request includes a change to the `extractRulesFromRuleset` method in the `SpectralValidationEngine.java` file. The change simplifies the assignment of the `severity` variable by combining the null check and the `fromString` method call into a single line.
* Simplified the assignment of the `severity` variable by combining the null check and the `fromString` method call in the `extractRulesFromRuleset` method in `SpectralValidationEngine.java`.
> Handle Ruleset Severity `null` Scenario

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Fixes https://github.com/wso2/api-manager/issues/3593
> Allow policy name matching with "_imported" suffix

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/throttling/publisher/DataProcessAndPublishingAgent.java
Related issue: https://github.com/wso2/api-manager/issues/3759
> Fix x-forwareded-for header validation using apache commons-validation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
$subject
Fix: https://github.com/wso2/api-manager/issues/3821
> Skip retrieve application from external KM for MAPPED keys

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketUtil.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/Authentication/OAuthAuthenticator.java
This PR makes the REST API flow and WebSocket flow consistent for IS 7 client credentials opaque tokens.
Fixes https://github.com/wso2/api-manager/issues/3829
> Make the REST API flow and WebSocket flow consistent for IS 7 client credentials opaque tokens

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
This PR fixes the below problems.
- Fixes an export-import related issue on the migrated APIs from 3.2.0 to 4.x. Migrated APIs consist of mediation sequences and they were not properly handled to populate API level policies while exporting them (These migrated APIs are not SAVED)
- When update an API from the management console it set the gatewayVendor to null and later this null scenario handled when populating API object by getting the vendor from the DB.
Resolves https://github.com/wso2/api-manager/issues/3855
> Fix API Export-Import Error Due to Migrated Mediation Policies and Fix Gateway Vendor Retrieval for "Null" vendor

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
This PR addresses a **JWTTest failure** encountered during integration testing when using **Oracle 19c** as the database. The failure occurs due to a discrepancy in how **Oracle 19c** handles empty values compared to other databases.
- **Resolves**: [wso2/api-manager/issues/3846](https://github.com/wso2/api-manager/issues/3846)
- **Issue with Oracle 19c**: In Oracle, when an optional attribute has an empty value, the `APP_ATTRIBUTE` column is stored as `NULL`. This contrasts with other databases, which return an empty string (`""`) when the value is empty.
- **Impact**: The difference in handling empty values between Oracle and other databases causes inconsistencies in the returned response, leading to test failures during integration.
- **Solution**:
- A validation step was added to …
> Resolve Database Inconsistency for APP_ATTRIBUTE in Oracle 19c

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/FaultyRequestDataCollector.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/SynapseAnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/websocket/WebSocketAnalyticsDataProvider.java
Fix https://github.com/wso2/api-manager/issues/3811
This pull request includes several changes to enhance the analytics data collection and processing in the API management gateway. The most important changes include adding a new `Operation` field to the `FaultyRequestDataCollector`, fixing the order of method calls in `WebsocketHandler`, and updating the response size data type and retrieval method.
Enhancements to analytics data collection:
* [`components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/FaultyRequestDataCollector.java`](diffhunk://#diff-c3b3b1646fc318a345bf8564513fd8f2ffc9d4c2243537ed0fc0d81ecf74191dR35): Added `Operation` field to the `Event` object to capture more detailed analytics data. …
> Fix Analytics Throttle Event Publishing and responseSize Calculation in WebSocket Messages

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/utils/ImportUtils.java
> A Null Pointer Exception occurs when the application owner (subscriber) has never logged into the Developer Portal and trying to import applications using the APICTL.
Related Issue : https://github.com/wso2/api-manager/issues/3817
> Allow importing application importing when the application owner (subscriber) has never logged in the dev portal before.
> Add the application owner (subscriber) to the AM_SUBSCRIBER table if the subscriber not yet available when importing applications.
> Fix subscriber null issue when importing application

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java
Fix: https://github.com/wso2/api-manager/issues/3806
Make the auto-cleanup process configurable by introducing a system property, `autoTransportOperationCleanUp`. You can control whether to enable the auto-cleanup process when starting the API-M. Setting this property to false will disable the auto-cleanup mechanism.
ex. ./wso2server.sh -DautoTransportOperationCleanUp=false
> Make transport cleanup configurable

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataStoreImpl.java
Improvements to API resource cache invalidation:
Invalidating the resource cache when undeploying an API, and ensuring the resource cache is cleared when creating API revisions.
Fix: https://github.com/wso2/api-manager/issues/3843
> Clear APIResource cache on undeploy event

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/issuers/SystemScopesIssuer.java
Fixes https://github.com/wso2/api-manager/issues/3548
> Adding role based scope issuing for exchange grant

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/OperationPoliciesApiServiceImpl.java
fixes: https://github.com/wso2/api-manager/issues/2663
> Add: Validation for Policy Type

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
Fixes https://github.com/wso2/api-manager/issues/3569
> Fix role cache issue when CaseInsensitiveUsername is enabled in userstores

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
Fix the error in XML Schema Validation for Soap APIs, which occurs due to the incorrect retrieval of the Content-Type property. For Soap APIs, this is retrieved as null.
For Rest APIs Content-Type is correctly retrieved and therefore the XML validation works as expected.
Modified the code to get the correct property for Content-Type when it is null.
Fix: https://github.com/wso2/api-manager/issues/3596
> Fix XML Schema validation not working for Soap APIs

- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/Constants.java
- components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/publishers/impl/AnalyticsDataPublisher.java
To improve the flexibility of APIM analytics by allowing users to configure multiple reporter types. Previously, it was limited to a single reporter type specified in the configuration, defaulting to Choreo analytics if not explicitly set. This PR enables users to setup multiple analytics reporters simultaneously.
Fixes https://github.com/wso2/api-manager/issues/3099
The new implementation allows for multiple loggers to be enabled through configuration in the `deployment.toml` file. Users can now specify an array of reporter types, which the system will process and initialize accordingly.
**Enable both Choreo and ELK analytics:**
```toml
[apim.analytics]
enable = true
type = ["choreo", "elk"]
```
In this case, `type = "choreo, elk"` is also allowed.
**Enable only ELK analytics:**
```toml …
```
> Update AnalyticsDataPublisher to Handle Multiple Reporter Types

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapsePolicyAggregator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
This PR resolve issues caused by invalid characters in policy names for migrated mediation policies in distributions from APIM 3.x.x versions.
Fixes https://github.com/wso2/api-manager/issues/3776
Policy names are sanitized in the API and policy import/export flows.
> Fix Invalid Characters Causing Issues for the Policy Names

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SettingsApiServiceImpl.java
Adds mandatory API property validation when importing an API to the Publisher Portal.
Previously, mandatory properties were only validated when updating an API.
Ensures mandatory property validation happens at the rest api level when changing the lifecycle status to Publish. Previously, this was only validated from the UI.
Validated mandatory properties when updating an API's lifecycle status to Publish.
This ensures that mandatory properties are validated when both importing and changing lifecycle status.
Related public issue: https://github.com/wso2/api-manager/issues/3568
> Add mandatory property validation to API import flow

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
Fixes https://github.com/wso2/api-manager/issues/3836
> Fix issue in validating scopes for secondary userstore users

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/webhooks/DeliveryStatusUpdater.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/WebhooksUtils.java
Improves WebSub delivery traceability in the WSO2 API Manager gateway by introducing detailed logging for both successful and failed delivery attempts. These enhancements support better troubleshooting and issue correlation.
---
- Added debug logs in `DeliveryStatusUpdater`.
- Captures status, HTTP code, callback URL, topic, tenant domain, app ID, API UUID, and API name.
- Logs are shown when debug is enabled.
- Added always-on `<log>` mediator in `webhooksFaultSequence.xml`.
- Logs failed deliveries with key metadata regardless of log level.
---
Fixes: [#3874](https://github.com/wso2/api-manager/issues/3874) – WebSub delivery logging and traceability improvements
> Improved webhook delivery traceability through detailed fault and debug logging

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
- Create Unique ID of Certificate from Subject DN instead of Issuer DN
- Related Issue: https://github.com/wso2/api-manager/issues/3854
> Create Unique ID of Certificate from Subject DN

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Purpose
This PR addresses a validation gap in the Publisher REST API, where custom endpoint security types could be added through API creation, even if they were not part of the predefined set of supported security types.
Previously, there was no restriction on the endpoint security type, allowing users to specify any arbitrary value.
The new implementation introduces validation in the validateEndpointSecurityType method to ensure that only supported security types—None, Basic, Digest, and OAuth—are allowed. If an invalid security type is detected, an appropriate error message is returned.
Related to
Issue: [wso2/api-manager#3499](https://github.com/wso2/api-manager/issues/3499)
> Fix #3499: Restrict endpoint security type to only available ones

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
This PR enforces MIME type validation for documentation uploads in the Publisher REST API, addressing [Issue #3902](https://github.com/wso2/api-manager/issues/3902). It ensures that only supported MIME types are accepted for file uploads, with an appropriate error response for unsupported types. The API documentation and relevant tests have been updated accordingly.
> Implement strict MIME type validation for API and API Product documentation uploads.

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationService.java
**Summary**
Fixes an issue where `X-JWT-ASSERTION` is not generated for opaque tokens when using the **client credentials grant type** in IS 7. Since the application owner concept is removed in IS 7, `endUserName` is `null`, which skips JWT generation.
The fix updates the condition to allow JWT generation if the token is an **application token**, even when `endUserName` is missing.
**Related Issue**  
[wso2/api-manager#3882](https://github.com/wso2/api-manager/issues/3882)
> Fix JWT assertion not generated for client credentials grant with opaque tokens

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
- Subscriber claim info appears to be empty for tenant users in publisher portal
- Fix: [wso2/api-manager/issues/3884](https://github.com/wso2/api-manager/issues/3884)
- In the subscriber existence checking method, username is now passed without tenant by using `MultitenantUtils.getTenantAwareUsername()`.
- As a result, user existence check returns correctly `true` instead of the previously returned `false` value.
> Fix empty subscriber claim info on tenant users issue

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ThrottlingApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/RestApiAdminUtils.java
Backend fix for https://github.com/wso2/api-manager/issues/3764
> Validate quota limits to be non-negative in throttling policies

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/webhook/WebhooksAnalyticsDataProvider.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/WebhooksUtils.java
> Publishing custom analytics data is only available for Synapse APIs. This PR extends this support to webhook APIs.
Related Issue: https://github.com/wso2/api-manager/issues/3887
> Enable publishing custom analytics for webhook APIs in both successful and faulty flows.
> A new constructor is added to WebhooksAnalyticsDataProvider to accept an AnalyticsCustomDataProvider, allowing injection of custom analytics logic.
A new method getProperties() is implemented to extract custom properties from the injected provider, and additionally append the api.context.
In WebhooksUtils, check for the availability of an AnalyticsCustomDataProvider via the ServiceReferenceHolder and initializes the provider accordingly.
> Enable custom analytics for webhook APIs

- components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/JWTValidationInfo.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/APIKeyValidationInfoDTO.java
This PR introduces support for adding token details and invalidation reasons to the Synapse Message Context when a token is **invalid** or **expired**.
🔧 **Enabled via:**
Set the system property `-DincludeTokenInfoInMsgCtx=true` to activate this feature. By default this is disabled.
📌 **Adds context properties:**
* `ACCESS_TOKEN`: Raw token from the request
* `ACCESS_TOKEN_INVALID_REASON`: Reason for token rejection ("Access token expired" or "Access token invalid")
✅ Useful for debugging, logging, or custom mediation flows.
Issue: https://github.com/wso2/api-manager/issues/3881
---
✅ The following scenarios were tested and confirmed to work as expected for **both JWT and Opaque tokens**:
1. **Empty token** – `ACCESS_TOKEN_INVALID_REASON`: "Access token invalid"
2. **Incorrect token** – …
> Include token and token invalid reason in the message context

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/InboundWebSocketProcessor.java
Related issue: https://github.com/wso2/api-manager/issues/3905
By default, the following flow occurs when the default version of a websocket API is invoked without the version, with authorization as a query parameter. (`wscat -c "ws://localhost:9099/notifications?access_token=<token>"`)
1. The URI of the request is set as the `fullRequestPath` of the `inboundMessageContext` via `setUris()`. The URI of the request currently does not contain the version, hence the `fullRequestPath` of the `inboundMessageContext` also does not.
2. `setMatchingResource()` is called, which will add the version to the URI of the request.
3. `isOauthAuthentication()` is called. Which will set the authorization query parameter value as a request header.
4. The URI of the request (which now contains the version …
> Set the fullRequestPath of the inboundMessageContext after the default version is resolved in the request in InboundWebsocketProcessor.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
Related issue: https://github.com/wso2/api-manager/issues/3903
Whitespace sanitization should be added to the Key Manager configs in the add and update flows. Otherwise backend will try to call wrong endpoints with leading or trailing whitespaces.
> Sanitize Key Manager Configs before adding and updating KM

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
This PR ensures that only the application owner can delete OAuth keys for an application. Previously, any user in the organization could delete these keys. Now, the DELETE endpoint checks ownership and returns a 403 Forbidden if the user is not the owner, matching the behavior of key generation and update.
**Related issue:** [wso2/api-manager/issues#3919](https://github.com/wso2/api-manager/issues/3919)
> Restrict OAuth key deletion to application owner only

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
This PR adds `apikey` type to the endpoint security type validation logic introduced by [1].
1. https://github.com/wso2/carbon-apimgt/pull/12829
> Add apikey to endpoint security type validation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
This PR refactors the key manager configuration retrieval logic by moving the check for an empty or null kmId to the start of the method. This change prevents unnecessary calls to getKeyManagerConfigurationById when kmId is empty or null.
Previously, the code attempted to fetch a key manager configuration by kmId even when kmId was empty or null, relying on fallback logic afterward. This refactoring:
- Avoids redundant calls.
- Makes the intent clearer by explicitly handling empty kmId cases upfront.
Fixes: https://github.com/wso2/api-manager/issues/3970
> Refactor key manager configuration retrieval to check kmId early

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
Improve the application update logic to block updates on applications that are in the UPDATE PENDING state. This ensures that no conflicting updates occur while a previous update is awaiting approval.
> Prevent app update calls when it's in the UPDATE PENDING state

- .github/workflows/log-pr-comment-analyzer.yml
- .github/workflows/pr-reviewer-for-logs.yml
This will introduce new git action on PR merge to analyze the status of the added comments by AI Log Agent
This pull request introduces a new GitHub Actions workflow to notify an AI Log Agent about merged pull requests and modifies an existing workflow by removing unused parameters. The changes aim to enhance automation and simplify the configuration of workflows.
* [`.github/workflows/log-pr-comment-analyzer.yml`](diffhunk://#diff-ab8d1c48027cc34c29131aba70591bf017d962b7657dddf6c2910a7166fb1482R1-R49): Added a new workflow named "Notify Merged PR to AI Log Agent." This workflow triggers on pushes to the `master` branch, retrieves details of the merged pull request, and invokes the AI Log Agent with the PR URL.
* [`.github/workflows/pr-reviewer-for-logs.yml`](diffhunk://#diff-293a18629002f …
> Add log PR comment analyzer

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/WebSocketExtensionHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/websocket/WebSocketApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/gatewayFeatureCatalog/synapse-gateway-feature-catalog.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/operationPolicy/operation-policy-specification-schema.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapsePolicyAggregator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/TemplateBuilderUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.spec.parser/src/main/java/org/wso2/carbon/apimgt/spec/parser/definitions/AsyncApiParser.java
This PR introduces dynamic endpoint support for WebSocket APIs, allowing users to define dynamic endpoints through a policy, similar to other API types.
Onboarded WebSocket as a new supported API type for operation policies.
Introduced a new handler for message mediation in WebSocket APIs and integrated it into the Synapse API configuration.
Enabled setting operation-level policies during API update calls for WebSocket APIs.
Implemented support for the default endpoint type in WebSocket APIs by skipping endpoint validation.
Fixes:
https://github.com/wso2/api-manager/issues/3893
> Add Dynamic Endpoint support for websocket

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Add `guardrail_fault` to allowed error sequences.
https://github.com/wso2/api-manager/issues/4067
> Add guardrail_fault to allowed error sequences

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
This PR bumps the APIM version constant to 4.6.0 for the APICTL use cases.
> Bump APIM version constant to 4.6.0

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/model/OpenAPIRequest.java
Schema validation was being skipped for Accept headers because they were lowercased to "accept" but the Atlassian validator expects "Accept".
Preserve Accept header case (like Content-Type) in both:
- `OpenAPIRequest.java` - request header processing
- `APIMgtLatencyStatsHandler.java` - OpenAPI spec processing
- Accept header validation now works correctly when schema validation is enabled for an API
- Invalid Accept headers are rejected
https://github.com/wso2/api-manager/issues/3987
> Fix Accept header case preservation to prevent schema validation bypass

- pom.xml
This PR bumps the following dependencies for 4.6.0 M1 release.
- Carbon Analytics Common: 5.3.20 to 5.3.23
- Carbon Mediation:  4.7.245 to 4.7.254
- Synapse: 4.0.0-wso2v221 to 4.0.0-wso2v240
- Rule Validator: 1.0.0 to 1.0.1
> Bump dependency versions for 4.6.0 M1 release

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/gateway/GatewayAPIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/VHost.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/TemplateBuilderUtil.java
Adding Vhost details to the runtime artifact response to serve oauth protected resource metadata responses and WWW-Authenticate headers for MCP Servers
> Add vhosts to the runtime artifact response

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
In the existing implementation, only the first entry of the servers is considered. In the case where the first entry is http, and only https is listed in x-wso2-transports, none of the servers get sent to the front end, breaking the swagger UI.
This will consider all elements of the servers array.
> Fix devportal api console breaking for discovered Azure APIs.

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- pom.xml
This PR adds the following changes for the 4.6.0 Alpha release.
- Upgrade the following dependencies:
- Carbon Analytics Common: 5.3.23 ⟶ 5.3.25
- Carbon Kernel: 4.9.28 ⟶ 4.9.29-alpha
- Carbon Mediation: 4.7.254 ⟶ 4.7.255
- Carbon Identity: 5.25.724 ⟶ 5.25.729
- Carbon Identity Inbound Auth OAuth: 6.13.27 ⟶ 6.13.33
- Carbon Identity User WS: 5.7.5 ⟶ 5.7.6
- Carbon Deployment: 4.11.18 ⟶ 4.11.19
- Carbon Multitenancy: 4.9.34 ⟶ 4.9.36
- Axis2: 1.6.1-wso2v102 ⟶ 1.6.1-wso2v105
- Orbit Version JSON: 3.0.0.wso2v1 ⟶ 3.0.0.wso2v7
- json-smart: 2.5.2 ⟶ 2.6.0
- Tomcat: 9.0.53 ⟶ 9.0.108
- [Add commons-io as an import package for gateway component](https://github.com/wso2/carbon-apimgt/commit/7e99812a7f51b3d1225c4163fb8988072ee32c10)
> Upgrade kernel version and other dependencies

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
$subject
Currently MCP tools returns in a random manner which cause the order of the tools to change with every request. This fix sort the tools alphabetically.
> Sort MCP tools alphabetically

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/mcp/McpInitHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/authenticator/InternalAPIKeyAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mcp/request/MCPRequestDeserializer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mcp/request/McpRequest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mcp/request/McpRequestProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mcp/response/InitializeResult.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mcp/response/ToolListResult.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/McpMediator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/MCPPayloadGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/MCPUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR,
- removes unsupported capabilities from init response
- Fixes issue with MCP jsonrpc ID field being converted to a double string
- introduces a ` _mcp_failure_handler_` sequence : product-apim change https://github.com/wso2/product-apim/pull/13820
- fixes issue with invoking EXISTING_API subtype MCPs via internal-key Authentication : fixes https://github.com/wso2/api-manager/issues/4127
- fixes issues while calling MCP tools via an MCP client  : fixes https://github.com/wso2/api-manager/issues/4156
> Add MCP GW fixes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
Related issue: https://github.com/wso2/api-manager/issues/4080
The following issues are resolved:
The error occurring when a user with admin permissions tries to add a role from the publisher portal for an API is now fixed.
When a role with capital letters is created from the publisher portal and added to an API, the API can now be successfully updated with no errors.
> Fix case sensitive user roles for publisher access control

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/DBRetriever.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapseArtifactGenerator.java
Refactored `SynapseArtifactGenerator.generateGatewayArtifact()` to process API runtime artifacts asynchronously, improving performance for bulk operations while maintaining thread-safety and proper error handling.
Fix: https://github.com/wso2/api-manager/issues/4012
Implemented parallel processing using `CompletableFuture` with a `custom thread pool` while preserving the original method signature and behavior.
Carried out 10 APIM clustered setup startups, first half without the improvement and the rest with the async improvement (with a `custom thread pool`).
- Total APIs deployed per run: 1,500
- **Time Reduction:** 37s (21.5% faster)
- **Throughput Increase:** 2.39 APIs/second (27.2% improvement)
-  **Standard deviation:** 3.75 s (Very consistent runtimes)
- **Most Consistent:** Async …
> Process gateway artifacts asynchronously with a custom thread pool

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
This PR adds the missing `PaginationContext.destroy()` call for initiated paginations. The pagination value needs to be reset before starting a new PaginationContext to ensure correctness.
I verified the fix by testing API search functionality in both the Publisher and Developer Portals, covering search queries, URL patterns, and contents.
- Resolves https://github.com/wso2/api-manager/issues/4173
> Add Missing Pagination Context Destroys

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/CORSConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.spec.parser/src/main/java/org/wso2/carbon/apimgt/spec/parser/definitions/OAS3Parser.java
This pull request introduces an improvement to how CORS configuration is handled when parsing OpenAPI specifications. The main change ensures that only non-empty CORS configurations are set on the API object
CORS configuration handling:
Added an isEmpty() method to the CORSConfiguration class to check if all fields are unset or empty.
Updated the logic in OAS3Parser so that api.setCorsConfiguration() is only called if the CORS configuration is not empty, avoiding the assignment of default or empty configurations.
Fixes https://github.com/wso2/api-manager/issues/4140
> Fix missing default CORS configuration value

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantPostgreSQL.java
This PR fixes the issue where applications in the Dev Portal are always shown in created order, ignoring the selected sort option (e.g., by name, owner, or policy). This happens only when the db type is postgreSQL.
Applied an `ORDER BY` clause at the outermost query level to ensure the chosen sorting option is reflected in the results.
> Fix sort issue in application listing for postgreSQL

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
This PR fixes an issue where a migrated API cannot be invoked when it has mTLS enabled.
The issue was caused by a difference in folder structures for APIs with mTLS before and after the migration. With this fix, the flow will fall back to the legacy folder structure in order to check whether any client certificates are available for the API and will add them as the PRODUCTION certificates to the truststore in order to comply with the new implementation.
Related issue: https://github.com/wso2/api-manager/issues/4209
> Fix invocation issue for migrated APIs with mTLS

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/api_definitions/azure_openai_api_v2.yaml
- SDKs like langchain_openai automatically append `/openai` to the base URL, which breaks APIM proxy usage due to duplicate `/openai` in the URL.
- Proposed fix: remove `/openai` from the base URL in the OpenAPI spec and include it in the resource paths instead. This ensures SDKs work correctly with APIM proxies.
> Fix Azure OpenAI version 2.0 Spec for SDK Compatibility

- features/apimgt/org.wso2.carbon.apimgt.federated.gateway.feature/pom.xml
- pom.xml
- Resolves https://github.com/wso2/api-manager/issues/4313
- Updates the project dependencies to include several Netty modules in the federated gateway feature, and introduces a new property for the Netty version in the root `pom.xml`. 
**Federated gateway dependency enhancements:**
* Added the following Netty modules as bundle dependencies in `features/apimgt/org.wso2.carbon.apimgt.federated.gateway.feature/pom.xml`:
* `netty-codec-http`
* `netty-codec-http2`
* `netty-codec-socks`
* `netty-handler-proxy`
> Add Netty dependency to federated gateway feature

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
Fixes https://github.com/wso2/api-manager/issues/4368
- The plain text env ID is first searched in the readonly GW set, if a match is not found
- The plain text env ID is then searched in the DB, if a match is not found then also,
- The base64 decoded text env ID is first searched in the readonly GW set, if a match is not found then also,
- The base64 decoded text env ID is then searched in the DB, is no env is found after all these 4 checks, `APIMgtResourceNotFoundException` will be thrown.
Related admin UI improvement PR : https://github.com/wso2/apim-apps/pull/1135
> Add backend support for env ID path param to be base64 encoded

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/LifeCycleUtils.java
This PR fixes the issue where discovered apis cannot be published when they do not have tiers attached or no backend endpoints are present. It should not be prevented from publishing if this information is not available.
> Fix publishing discovered apis

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ExternalGatewayNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/FederatedGatewayArtifactGenerator.java
revision fixes for gateway deployment
This pull request introduces significant improvements to the external gateway deployment process in the API Manager, primarily by refactoring the `ExternalGatewayNotifier` logic and adding support for federated gateway artifact generation. The changes enhance modularity, reliability, and extensibility for federated deployments.
* Added new class `FederatedGatewayArtifactGenerator` to generate gateway artifacts for federated gateway deployments, supporting multiple API types and handling extraction and mapping from DTOs to API models.
* Refactored `ExternalGatewayNotifier` to remove direct dependencies on `APIProvider` and `ApiMgtDAO`, and now uses the federated artifact generator to obtain API artifacts for deployment, improving separation of concerns …
> revision fixes for gateway deployment

- components/apimgt/org.wso2.carbon.apimgt.spec.parser/src/main/java/org/wso2/carbon/apimgt/spec/parser/definitions/AsyncApiParser.java
When creating a **Server-Sent Events (SSE) API** without specifying an endpoint configuration, the system fails with the following error:  
```
JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
```
This occurs during the execution of `generateAsyncAPIDefinition()` in the **AsyncApiParser** class.
The `generateAsyncAPIDefinition()` method directly attempts to parse the endpoint configuration returned by `api.getEndpointConfig()` as JSON.  
- When the endpoint configuration is **null** or an **empty string**, the `JSONObject` constructor fails because it expects a valid JSON object string starting with `{`.  
- A similar safeguard exists in the `updateAsyncAPIDefinition()` method but was missing here.
Added a **null/empty check** for the endpoint configuration …
> fix: prevent JSONException when creating SSE API without endpoint config

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/inbound/websocket/InboundWebSocketProcessor.java
When APIM(4.6.0-alpha2) is not able to establish connection with websocket client, current error does not include the invalid url.
```
ERROR - InboundWebSocketProcessor No matching API found to dispatch the request.
ERROR - InboundWebSocketProcessor No matching resource found to dispatch the request 
```
This fix improve it by adding the url.
```
ERROR - InboundWebSocketProcessor No matching API was found to dispatch the request for path : /websocket2/1.0.9
ERROR - InboundWebSocketProcessor No matching resource was found to dispatch the request for path : /websocket/1.0.0/chat2
```
Fixes wso2-enterprise/wso2-apim-internal/issues/6382
> Improving Websocket logging by adding API URI into logs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ExternallyDeployedApiNotifier.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
API Deletion aws not properly happen due to event failure
This pull request introduces improvements to how externally deployed APIs are undeployed when an API is deleted, as well as some minor code cleanups and refactoring. The main change is a more robust mechanism for retrieving and handling external API mapping references in multiple gateway environments during API deletion, which helps ensure all relevant deployments are properly cleaned up.
* Refactored the undeployment logic in `ExternallyDeployedApiNotifier` to retrieve all external API mapping references for the API and iterate through them, undeploying from each relevant environment. This replaces the previous logic that only handled one environment at a time and improves reliability when an API is mapped to multiple gateways. …
> API Deletion aws not properly happen due to event failure

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/dto/PublisherAPIProductInfo.java
Fixes https://github.com/wso2/api-manager/issues/4247
Adds a description field to the PublisherAPIProductInfo and populate the field when fetching Api products
> Fix API product description being null

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapseArtifactGenerator.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR introduces configurability for the thread pool parameters used by the **SynapseArtifactGenerator**.
Previously, the thread pool executor was initialized with hard-coded constants for core pool size, max pool size, keep-alive time, and queue capacity. This limited flexibility when tuning performance in different deployment environments.
With this change, these parameters can now be configured using the `default.json`, allowing operators to optimize resource usage for different workloads and scale based on API artifact generation demand.
The following values are the configurable parameters in the `default.json` file, and by default they use the tested & verified values shown below:
```
"apim.synapse_artifact_generator.thread_pool.core_pool_size": "10", …
```
> Add configurable thread pool parameters for SynapseArtifactGenerator

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/EnvironmentsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/resources/admin-api.yaml
- pom.xml
This pull request updates the API documentation and implementation to clarify that environment IDs containing special characters should be base64 encoded. Additionally, it bumps several dependency versions in the `pom.xml` file.
**API Documentation and Implementation Updates:**
* Updated the description for the `environmentId` parameter in the OpenAPI spec (`admin-api.yaml`) and all related REST API methods in `EnvironmentsApi.java` to specify that IDs with special characters must be base64 encoded. [[1]](diffhunk://#diff-b7ab56914046a69c7b2902826d6f7914b510d4b3d033fda751ada6ca51b9cf35L7231-R7232) [[2]](diffhunk://#diff-55d65d2a16cde277ce2bc43573e3cf007c98df132457f5edb37cd1ca91f4753bL54-R54) [[3]](diffhunk://#diff-55d65d2a16cde277ce2bc43573e3cf007c98df132457f5edb37cd1ca91f4753bL73-R73) …
> Upgrade dependencies

- pom.xml
This pull request updates dependency versions in the `pom.xml` file to keep the project up to date with the latest compatible releases.
Dependency version upgrades:
* Updated `carbon.identity.version` from `5.25.733` to `5.25.734` to incorporate the latest improvements and fixes.
* Updated `analytics.event.publisher.client.version` from `1.2.29` to `1.2.32` for enhanced stability and features.
> Upgrade carbon-identity and apim-analytics-publisher versions
