components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fix for APIMANAGER-5804
-
ASAP
=> Fix for APIMANAGER-5804

gateway-modules/apim-ballerina-native-component/src/main/java/org/wso2/carbon/apimgt/ballerina/util/SetProperty.java
=> fixing set property

components/web/services/org.wso2.carbon.apimgt.authenticator/src/main/java/org/wso2/carbon/apimgt/authenticator/AuthenticatorAPI.java, components/web/services/org.wso2.carbon.apimgt.authenticator/src/main/java/org/wso2/carbon/apimgt/authenticator/utils/bean/AuthResponseBean.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Auth.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
- Return JS accessible access token chunk in the `/token` response body itself
environments.]
-
=> Send JS accessible access token segment in the response body

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/APIMgtConstants.java, components/web/services/org.wso2.carbon.apimgt.authenticator/pom.xml, components/web/services/org.wso2.carbon.apimgt.authenticator/src/main/java/org/wso2/carbon/apimgt/authenticator/AuthenticatorAPI.java, components/web/services/org.wso2.carbon.apimgt.authenticator/src/main/java/org/wso2/carbon/apimgt/authenticator/LoginTokenService.java
=> remove scopes from auth req at js level and add scopes in java layer

analyzer-modules/org.wso2.carbon.apimgt.throttling.siddhi.extension/src/main/java/org/wso2/carbon/apimgt/throttling/siddhi/extension/ThrottleStreamProcessor.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/ThrottlerUtil.java
=> commit changes on javadoc

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
=> add review related changes

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/internal/ServiceReferenceHolder.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/impl/OAuth2Authenticator.java, components/web/services/org.wso2.carbon.apimgt.authenticator/src/main/java/org/wso2/carbon/apimgt/authenticator/LoginTokenService.java
=> scope validation - review changes 

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js
- Change working directory for npm build in mvn executor plugin
environments.]
-
=> Code refactoring in publisher web app POM and app.js

features/apimgt/org.wso2.carbon.apimgt.core.feature/resources/template/template.xml
=> Adding Throttling function to template.xml

gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/holders/CacheHolder.bal
=> fixing constants

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/RegistrationSummary.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/utils/MappingUtil.java
=> Add analytics enabled property

gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/Authentication.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/holders/CacheHolder.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/utils/Utils.bal
=> commit constant related fixes

components/apimgt/pom.xml
- Adding missing webserver module
environments.]
-
=> Adding missing webserver module

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
=> comment swagger2msf4j plugin

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImpl.java
=> Fixed some sql query isssues

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/APIMConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/APISubscriptionDAO.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/APISubscriptionDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIGatewayPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/BrokerImpl.java
=> Subscription event at application key generation

components/web/apps/org.wso2.carbon.apimgt.admin.app/src/main/fragments/sidebar-elements/sidebar-elements.hbs
=> remove throttling UIs in admin portal for m3

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImplIT.java
=> Fixed integration tests issues

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImpl.java
refactoring - remove non-required private methods in the PolicyDAOImpl and adding the logic to the API methods.
-
environments.]
-
=> removed non-required private methods in the PolicyDAOImpl 

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
=> commit changes on endpoints when creating new version of api

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImplIT.java
=> updating test cases in PolicyDAO tests

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/api/IdentityProvider.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/auth/SCIMServiceStub.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultIdentityProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/DefaultIdentityProviderImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java, components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-details/public/js/details.js
- Implementation changes of the Publisher API Permissions feature after integrating with IS.
- Test case additions for code coverage.
=> Publisher API Permission changes after integrating IS

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIDefinitionFromSwagger20.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/impl/OAuth2Authenticator.java
https://redmine.wso2.com/issues/6404
-
environments.]
-
=> Product REST APIs security header moved to a configuration in deployment.yaml

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/exceptions/UnsupportedThrottleConditionTypeException.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/mappings/CommonThrottleMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/mappings/CommonThrottleMappingUtilTestCase.java
Unit tests for commonly used throttle policy DTO to model conversions.
-
environments.]
-
=> unit test cases for common policy DTO to model conversion

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Swagger/ApiCreateSwagger.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NavBar.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js
=> Updating look and feel of overview page and adding empty Resources page

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApplicationDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/policy/ApplicationPolicy.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImplIT.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ApplicationDAOImplIT.java, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/Authentication.bal
=> api policy related fixes for gateway

components/apimgt/org.wso2.carbon.apimgt.rest.api.webserver/src/main/java/org/wso2/carbon/apimgt/rest/api/webserver/impl/PublisherApiServiceImpl.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/index.html, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js
=> renaming publisher_new to publisher

components/web/components/org.wso2.carbon.apimgt.auth.ui/src/main/fragments/auth-manager/auth-manager.hbs
=> rename js path of store

gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/event/analytics/response/response.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/event/analytics/util/utils.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/event/holder/EventPublisherHolder.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/event/publisher/publisher.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/holders/CacheHolder.bal, gateway-modules/native-data-publisher/pom.xml, gateway-modules/native-data-publisher/src/main/ballerina/org/wso2/carbon/apimgt/ballerina/publisher/natives.bal, gateway-modules/native-data-publisher/src/main/java/org/wso2/carbon/apimgt/ballerina/publisher/AbstractEventPublisherAction.java, gateway-modules/native-data-publisher/src/main/java/org/wso2/carbon/apimgt/ballerina/publisher/Constants.java, gateway-modules/native-data-publisher/src/main/java/org/wso2/carbon/apimgt/ballerina/publisher/EventPublisher.java, gateway-modules/native-data-publisher/src/main/java/org/wso2/carbon/apimgt/ballerina/publisher/Init.java, gateway-modules/native-data-publisher/src/main/java/org/wso2/carbon/apimgt/ballerina/publisher/Publish.java, gateway-modules/native-data-publisher/src/main/java/org/wso2/carbon/apimgt/ballerina/publisher/service/BuiltinConnectorPackageRepository.java, gateway-modules/pom.xml
=> added native data publisher action

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/impl/BasicAuthAuthenticator.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/impl/OAuth2Authenticator.java
https://wso2.org/jira/browse/APIMANAGER-5806
-
environments.]
-
=> fix APIMANAGER-5806

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/gen/java/org/wso2/carbon/apimgt/rest/api/core/dto/EndpointListDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/impl/EndpointsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/resources/apim-core-api.yaml, features/apimgt/org.wso2.carbon.apimgt.core.feature/resources/template/endpoint.xml, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/gatewayInit.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/utils/APICoreUtil.bal
=> add global endpoint support

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-details/api-details.hbs
- Fix for the issue in editor app due to null-pointer exception when loading permissions
- Remove access-control tab from editor
=> Fix editor issue due to permissions - Null pointer

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- Add new resources to admin API for label management use cases
ASAP
- Run swagger codegen to generate code for the new APIs
=> Add admin API resources for label management

analyzer-modules/org.wso2.apimgt.analytics.feature/src/main/resources/execution-plan/analytics_events_pre_process.siddhi, analyzer-modules/org.wso2.apimgt.analytics.feature/src/main/resources/execution-plan/request_summarization.siddhi, analyzer-modules/org.wso2.apimgt.analytics.feature/src/main/resources/execution-plan/response_summarization.siddhi, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/event/util/simulate.bal, gateway-modules/native-data-publisher/src/main/java/org/wso2/carbon/apimgt/ballerina/publisher/EventPublisher.java
=> fixed event publishing bugs

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/impl/ApisApiServiceImpl.java
=> Fix PR comments

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/impl/ApisApiServiceImpl.java
=> Fix formatting issues in ApisApiServiceImpl.java

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NavBar.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Permission.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js
=> start permission model UI

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
=> fixing oracle related issue

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
=> fixing APIMANAGER-5838

analyzer-modules/pom.xml
=> commit siddhi import version range

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/index.html, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/login.css
=> C5 reactjs development - login page layout

analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/app_10PerMin.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/app_20PerMin.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/app_50PerMin.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/app_Unlimited.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/requestPreProcessorExecutionPlan.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/resource_10KPerMin_default.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/resource_20KPerMin_default.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/resource_50KPerMin_default.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/sub_Bronze.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/sub_Gold.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/sub_Silver.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/sub_Unauthenticated.siddhi, analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/sub_Unlimited.siddhi, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/event/analytics/util/utils.bal
=> remove unwanted attribute form throttle event

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/ComposeHeader.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Loading/Loading.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js
=> overview / loading page content update

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Swagger/ApiCreateSwagger.js
=> Fixing the Swagger upload issue

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
Add missing npm dependencies
- react-dropzone
- react-toastify
environments.]
-
=> Add missing npm dependencies

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/index.html
=> react app pre-loader added

gateway-modules/apim-ballerina-configs/build.xml, gateway-modules/apim-ballerina-configs/configs/main/BAL_INF/ballerina.conf, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/Authentication.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/CoreThrottleEventListener.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/Throttling.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/holders/CacheHolder.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/throttleEventListner.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/utils/Utils.bal, gateway-modules/apim-ballerina-configs/configs/service/BAL_INF/ballerina.conf, gateway-modules/apim-ballerina-configs/pom.xml, gateway-modules/apim-ballerina-configs/src/assembly/bin.xml
=> fixed auth map shared issue

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Swagger/ApiCreateSwagger.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleHistory.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/Policies.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/api.test.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/utils.js
- Add lifecycle update capabilities and update policy(tiers) details in lifecycle tab
environments.]
-
=> Improvements to lifecycle UI

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/WorkflowsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/SubscriptionDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- Reverted the property "status" back to "subscriptionStatus" and modified the get setSubscriptionTier() as setPolicy() as per the code update.
ASAP
=> Fixing publisher REST API definition mismatch

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/APIThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/ApplicationThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/CustomThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/SubscriptionThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/template/ThrottleTemplateBuilderTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/gen/java/org/wso2/carbon/apimgt/rest/api/core/ExportApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/gen/java/org/wso2/carbon/apimgt/rest/api/core/ExportApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/factories/ExportApiServiceFactory.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/impl/ExportApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/utils/PolicyExportManager.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/resources/apim-core-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/PolicyExportManagerTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/resources/resources/template/policy_templates/throttle_policy_template_app.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/resources/resources/template/policy_templates/throttle_policy_template_global.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/resources/resources/template/policy_templates/throttle_policy_template_resource.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/resources/resources/template/policy_templates/throttle_policy_template_resource_default.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/resources/resources/template/policy_templates/throttle_policy_template_sub.xml, features/apimgt/org.wso2.carbon.apimgt.core.feature/resources/template/policy_templates/throttle_policy_template_app.xml, features/apimgt/org.wso2.carbon.apimgt.core.feature/resources/template/policy_templates/throttle_policy_template_global.xml, features/apimgt/org.wso2.carbon.apimgt.core.feature/resources/template/policy_templates/throttle_policy_template_sub.xml
Created new API for execution plans export
-
environments.]
-
=> Export api for execution plans.

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/SingleClient.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/api.test.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/auth/login.test.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/utils.js
- Fix hardcoded hostnames and related tests
- Add follow referrer after login
environments.]
-
=> Follow referrer after login & Fix hardcoded hostnames and related tests

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/login/js/login.js
=> fixing goto_url issue

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js
- Api card view improvements
- Fixed header when scrolling
- fab now sticks to respective paper width instead of window (need to implement affix)
- minor styling fixes
environments.]
-
=> api card view / header / fab improvements

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/api.test.js
- Add `endpoint` input field to create api page, to provide endpoint URL(inline) when creating an API
environments.]
-
=> Add define endpoints inline capability when creating an API with tests

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js
Added the Documents tab related React components. 
-
environments.]
-
=> Adding publisher documents tab with react

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GenericEndpointInputs.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/ComposeHeader.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js
- Add endpoint configuration page for global endpoint definitions
- Add endpoint configuration page for individual API details page
- Add `path` directive to `document.cookie` storage when preserving a cookie
environments.]
-
=> Improve set cookie method to accept path and add endpoint config pages

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jagg.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jagg/jagg.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jagg.jag
=> Fix csrf cookie issue

gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/Throttling.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/gatewayInit.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/holders/ThrottleHolder.bal
=> C5 gateway implementation - Throttling fixes for new ballerina version

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/ExtendedSAML2BearerGrantHandler.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/ResourceConstants.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIKeyMgtUtil.java
=> Fix for APIMANAGER-5831

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/DAOFactory.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/LabelDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/APIMgtConstants.java
1. Creating "Default" label when APIM starts.
2. Adding "Default" label when no label specified when creating an API.
-
environments.]
-
=> Default label creation when APIM starts

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.webserver/pom.xml
=> Commented swagger2msf4j plugin for m4 release

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/api.test.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/endpoint.test.js
- Add global endpoints listing page
- Add name attribute to inline endpoint definitions
- Add test cases for global endpoint creation and delete
environments.]
-
=> Add global endpoints page, add name property to inline endpoint definitions when creating an API

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
=> Fixing Default label addition to empty set issue

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Create/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Listing/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/endpoint.test.js
- Add endpoint listing and create pages and modify inline endpoint
environments.]
-
=> Add endpoint listing and creation pages and modify inline endpoint

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Create/index.js
- Refactor defining inline endpoints
- Add create global endpoint page
environments.]
-
=> Refactor defining inline endpoints, Add create global endpoint page

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/api.test.js
Added a mocha test case for API update with endpoints. Updated pakage.json to include babel-register
-
N/A
environments.]
-
=> API update operation test cases

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/ResourceConfigContext.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/jquery.endpointUi.js
=> Fixed APIMANAGER-5850 and APIMANAGER-5843

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/APIMConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/AnalyticsConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/BrokerConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/CredentialConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/DataPublisherConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/IdentityProviderConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/JMSConnectionConfiguration.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/JWTConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/KeyMgtConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/PolicyDeployerConfiguration.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/ThrottlingConfigurations.java
- Added setter methods for configuration beans
=> Added setter methods for configuration beans

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/user/user-info/ajax/user-info.jag
=> Add user validation before chcnging the password in store

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/LabelDAOImplIT.java
- Test failure fix for LabelDAOImplIT test case.
environments.]
-
=> Fix for LabelDAOImplIT test failure

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantOracle.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java
Fixing APIMANAGER-5860: migrated app deletion issue
Fixing APIMANAGER-5855: Applications with groupID null are not shown for the owner
-
environments.]
-
=> Fixing APIMANAGER-5860 and APIMANAGER-5855

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
=> Adding react-modal dependancy to publisher package.json

build-scripts/JenkinsFile, build-scripts/README.md
=> jenkins configurations changes for node

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorAPI.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/configuration/APIMConfigurationService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/configuration/models/APIMConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/configuration/models/EnvironmentConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/internal/ConfigurationActivator.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/internal/ServiceReferenceHolder.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/utils/bean/EnvironmentConfigBean.java
-Done with creating the environment configuration part .
-Created an infoenvs service to fetch the environment details.
environments.]
-
=> Done setting the Environment Configuration part [GSOC 2017] [Environment Support]

gateway-modules/apim-ballerina-native-component/pom.xml
=> adding jacoco plugin to native componets of ballerina

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/APIThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/ApplicationThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/CustomThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/SubscriptionThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/ThrottlePolicyTemplateBuilder.java
- This PR removes unused method  getThrottlePolicyTemplate() from parent and subclasses
environments.]
-
=> Removing unused method getThrottlePolicyTemplate()

components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/interceptors/RESTAPISecurityInterceptor.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApplicationsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/EndpointsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/EnvironmentsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ExportApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ImportApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/LabelsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/PoliciesApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/SubscriptionsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/WorkflowsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/SingleClient.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/api.test.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/endpoint.test.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/utils.js
- Upgrade the SwaggerJs library version to 3.0.19(Current [stable](https://github.com/swagger-api/swagger-js/releases/tag/v3.0.19))
>  \-    "swagger-client": "2.1.27",
>  \+    "swagger-client": "3.0.19",
- Swagger spec changes from @nuwand also included
- Refactor _SingleClient_  class
environments.]
-
=> C5 swaggerclient js library migration from 2.x to 3.x

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/APIThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/ApplicationThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/CustomThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/SubscriptionThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/ThrottlePolicyTemplateBuilder.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/ApplicationThrottlePolicyDTO.java
=> Fixing build issues reported by checkstyle

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIStoreImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/template/APIConfigContextTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/template/ThrottleTemplateBuilderTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/util/APIComparatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/util/EndpointComparatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/util/URITemplateComparatorTestCase.java
This PR contains unit tests for org.wso2.carbon.apimgt.core.template and org.wso2.carbon.apimgt.core.util packages
-
environments.]
-
=> Test cases for core.template and core.util packages

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/utils/MappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/MappingUtilTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java
- Add MappingUtil unit tests
environments.]
-
=> Add MappingUtil unit tests

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIMgtAdminServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIMgtAdminServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImplTestCase.java
- Test cases for APIPublisherImpl
- Test cases for APIMgtAdminServiceImpl
ASAP
environments.]
-
=> Test cases for org.wso2.carbon.apimgt.core.impl component

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, gateway-modules/native-data-publisher/src/test/java/org/wso2/carbon/apimgt/ballerina/publisher/EventPublisherTestCase.java, gateway-modules/native-data-publisher/src/test/java/org/wso2/carbon/apimgt/ballerina/publisher/util/DataPublisherTestUtil.java
=> fixing minor variable issue

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, gateway-modules/apim-ballerina-native-component/pom.xml
=> changes to jacoco plugin

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Documents.js
Fixed the following issues related to api documents tab in publisher
- https://github.com/wso2/product-apim/issues/1443
- https://github.com/wso2/product-apim/issues/1450
- https://github.com/wso2/product-apim/issues/1462
- https://github.com/wso2/product-apim/issues/1463
environments.]
-
=> Fixing backend issues in API Document editing, source type changing, etc.

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/template/APIConfigContext.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/template/APIConfigContextTestCase.java
This PR contains fix for https://github.com/wso2/product-apim/issues/1470 with test scenarios. 
-
environments.]
-
=> Fixing issue #1470 and added relevant test cases

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorAPI.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/configuration/models/APIMStoreConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
- Get appName from Path parameters
- Set ssoEnabled = false by default
ASAP
environments.]
-
=> Modified getting app context in AuthenticatorAPI

components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/test/java/org/wso2/carbon/apimgt/rest/api/commons/util/RestApiUtilTestCase.java
Adding some more tests to RestApiUtil.java
ASAP
=> TestCase modifications to RestApiUtil Class

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImplTestCase.java
=> Fixing build failure

build-scripts/JenkinsFile, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/pom.xml
=> Jenkins buildfile configurations

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java
- Remaining unit tests for AuthenticatorService class
ASAP
environments.]
=> Add AuthenticatorService remaining tests

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
=> Updating document tab related swagger client method names to work with SwaggerClient upgrade

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/factories/GatewaysApiServiceFactory.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/impl/GatewaysApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/GatewaysApiServiceImplTest.java
=> adding test cases for GatewaysApiService

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/pom.xml, pom.xml
o org.wso2.carbon.apimgt.rest.api.core.impl pom.xml.
-
environments.]
-
=> Added org.mockito, org.powermock to org.wso2.carbon.apimgt.rest.api.core.impl pom.xml.

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/ApplicationsApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java
=> Adding unit tests for ApplicationsApiServiceImpl.java.

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/BlacklistApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java
=> Adding unit tests for BlacklistApiServiceImpl.java.

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIMgtAdminServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/FunctionTriggerTestCase.java
- Test cases for APIMgtAdminServiceImpl.java
- Test cases for FunctionTrigger.java
- ASAP
=> Test cases for APIMgtAdminServiceImpl and FunctionTrigger classes in apimgt.core.impl

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/EndpointsApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java
=> Adding unit tests for EndpointsApiServiceImpl.java.

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/ApisApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java
=> Adding unit tests for ApisApiServiceImpl.java class.

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIStoreImplTestCase.java
- Test cases for APIStoreImpl
- ASAP
environments.]
-
=> Test cases for APIStoreImpl

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/PoliciesApiServiceImplTestCase.java
=> Adding unit tests for PoliciesApiServiceImpl.java.

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/ExportApiServiceImplTestCase.java
=> Adding unit tests for ExportApiServiceImpl.java.

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jaggery_acs.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/recently-added/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/sso/filter/template.jag
=> fixed public jiras

components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/CompositeApisApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/LabelInfoApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/PoliciesApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/SelfSignupApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/SubscriptionsApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/TagsApiServiceImplTestCase.java
=> fixing content type issues

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/impl/LabelsApiServiceImplTest.java
=> Added error scenario testcase.

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/GatewaysApiServiceImplTestCase.java
=> Adding unit tests for GatewaysApiServiceImpl.java.

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Documents.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocumentsTable.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/NewDocSourceDiv.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
- Swagger upgrade related client api method name updated
- Replaced '==' with '===' in string comparison in js files
- Document source type changing related fix
environments.]
-
=> Swagger upgrade related change and some other fixes in API documents

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/ResourcesApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java
=> Adding unit tests for ResourcesApiServiceImpl.java.

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/SubscriptionsApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/utils/SampleTestObjectCreator.java
=> Adding unit tests for SubscriptionsApiServiceImpl.java.

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resource.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
=> Adding client api changes to the api.js

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImplIT.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImplIT.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/Policies.js
-Moved policy applying to API creatio page
-Add missing test statements to policyDaoimpl
environments.]
-
=> Moving policy applying to API creation page from LC page.

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GenericEndpointInputs.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.js
This PR contains API endpoint association feature, which enables a (defined) global endpoint or an inline endpoint to be associated with an API as a production or sandbox endpoint.
-
environments.]
-
=> Associating endpoints with an API in publisher UI

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.js
Fixing issue when submit with empty endpoint textbox
-
environments.]
-
=> Fixing issue when submit with empty endpoint textbox

analyzer-modules/org.wso2.apimgt.throttling.feature/src/main/resources/execution-plan/requestPreProcessorExecutionPlan.siddhi, build-scripts/JenkinsFile
=> fixing das error

features/apimgt/org.wso2.carbon.apimgt.rest.api.commons.feature/pom.xml, pom.xml
=> removed keymanager component jar

components/web/components/org.wso2.carbon.apimgt.auth.ui/src/main/fragments/auth-manager/public/js/auth/auth-check.js
- Remove SSO login alert
ASAP
environments.]
=> SSO login alert removed

components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/resources/wsdl/stockQuote.wsdl
=> Adding store API WSDL test resources

components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/interceptors/RESTAPISecurityInterceptor.java
- Add serving swagger.yaml
- Keep swagger.json serving logic to keep old UUF app working
environments.]
-
=> Add check to serve swagger.yaml for store app

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/H2GenericSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/H2SubcontextSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/H2TagSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MssqlGenericSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MssqlSubcontextSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MssqlTagSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MysqlGenericSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MysqlSubcontextSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MysqlTagSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/OracleGenericSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/OracleSubcontextSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/OracleTagSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PostgresGenericSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PostgresSubcontextSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PostgresTagSearchImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java
- Setting securityScheme value to 3 (to support both oauth and apikey) until security scheme selection from UI is supported
environments.]
-
=> APIKEY Feature - (Temporary fix until UI is finalized)

docs/index.html
=> Adding temporary docs folder

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java
This is a ByteArrayInputStream so findbugs does not report this as an error.
But to make the code consistent, InputStreams needs to be closed.
-----------------------------------------------------
environments.]
-
=> Closing InputStream

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/api/APIMgtAdminService.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/WorkflowDAO.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/WorkflowDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIManagerFactory.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIMgtAdminServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/WorkflowDAOIT.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIMgtAdminServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/WorkflowsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/WorkflowsApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/WorkflowDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/WorkflowListDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/WorkflowRequestDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/WorkflowResponseDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/factories/WorkflowsApiServiceFactory.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/mappings/WorkflowMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/mappings/WorkflowMappingUtilTest.java
Moving workflow related apis to admin apis. This is done as a part of the improvement done to introduce simple approval process to admin portal for workflows
- Moving workflow approval related api to admin api 
- Add additional apis to list pending workflows
environments.]
-
=> Adding workflow related apis to admin api

components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/test/java/org/wso2/carbon/apimgt/usage/client/test/APILastAccessDateTestCase.java
=> trigger the build

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/api/APIDefinition.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIDefinitionFromSwagger20.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Swagger/ApiCreateSwagger.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ScopeValidation.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/SingleClient.js
-getScopes from swagger when vendor extensions are removed
-scope based buttons enabling for publisher api adding, policy applying, deleting api, publish api and editing api
environments.]
-
=> Button Enabling in Publisher Based on Scopes

components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/test/java/org/wso2/carbon/apimgt/usage/client/test/APILastAccessDateTestCase.java
=> trigger jenkin build

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml
Renaming publisher and store feature in pom file
Before this fix, the build description can't specifically identify the component..output looks like follows..
[INFO] WSO2 Carbon - API web apps Feature ................. SUCCESS [02:53 min]
[INFO] WSO2 Carbon - API web apps Feature ................. SUCCESS [01:57 min]
environments.]
-
=> Renaming publisher and store feature in pom file

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Documents.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocumentsTable.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/InlineEditor.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Permission.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ApiPermissionValidation.js
- UI component for specifying role based permissions for an API.
- Disabling API edit, delete options based on role permissions.
- API delete option is moved into the API's overview page.  
ASAP
=> UI for API role based permissions in API Publisher

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ApiPermissionValidation.js
=> Fixed issue with UPDATE rights UI - API Publisher permission model

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIDefinitionFromSwagger20.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/APIMgtConstants.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIDefinitionFromSwagger20TestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/sampleApi.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java
- Added missing tests for issue https://github.com/wso2/carbon-apimgt/issues/4414
- modify scope retrieval
environments.]
-
=> Modify OAuth2Security definition scope retrieval and tests for them.

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/DataPublisherConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/JMSConnectionConfiguration.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/PolicyDeployerConfiguration.java
- Add Configuration annotation for bean classes.
environments.]
-
=> Fix deployment.yaml generation

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java
=> Fix Authenticator test failure

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/SingleClient.js
-remove api delete buttons from Thumb and list view
-fixed warnings.
environments.]
-
=> Publisher UI changes.

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java
- Update the description and removed unnecessary information
environments.]
-
=> update description for update application

pom.xml
- Update license header year
environments.]
-
=> Fix license header

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Tasks/TasksListing.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Tasks/index.js
- fix task nagvigation issue in Admin Portal UI
environments.]
-
=> fix task nagvigation issue in Admin Portal UI

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
Adding the fix of key generation exception for Applications through REST API in which an update operation has not executed
The DEFAULT CURRENT_TIMESTAMP value takes 0000-00-00 00:00:00 and throw SQL exception in the situation.
This is for APIM 2.1.0 with MySQL 5.6 and 5.5 versions.
ASAP
=> Fixing https://wso2.org/jira/browse/APIMANAGER-5878

components/sso-hostobject/org.wso2.carbon.hostobjects.sso/pom.xml, components/sso-hostobject/pom.xml
=> correct sso hostobject group id

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml, pom.xml
=> correcting hostobject usage poms

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NavBar.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Confirm.js
=> Left menu and overview page materialized

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/BlacklistApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/BlacklistApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/LabelsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/LabelsApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/PoliciesApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/PoliciesApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/WorkflowsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/WorkflowsApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/AdvancedThrottlePolicyDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/ApplicationThrottlePolicyDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/LabelDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/LabelListDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/ThrottlePolicyDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/WorkflowDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/BlacklistApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/LabelsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/PoliciesApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/mappings/AdvancedThrottlePolicyMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/mappings/CommonThrottleMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/impl/BlacklistApiServiceImplTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/impl/PoliciesApiServiceImplTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/mappings/AdvancedThrottlePolicyMappingUtilTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/mappings/ApplicationThrottlePolicyMappingUtilTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/mappings/CustomPolicyMappingUtilTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/mappings/SubscriptionThrottlePolicyMappingUtilTest.java, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/api.js
- Fix for #4433 Regenerate the implementation code for the update api-admin.yaml swagger definiiton.
environments.]
-
=> Admin rest api code re-generation

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/swagger/swagger-ui.js
=> Fix for APIMANAGER-5795 and APIMANAGER-5778

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/usage/template.jag
- Fix https://wso2.org/jira/browse/APIMANAGER-5827 
- Fixed description of the graph table.
environments.]
-
=> Fix APIMANAGER-5827

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag
Incorrect URLs shows for default version of the API, when the custom URL is enabled for tenant Mode.
This issue is fixed in template.jag by this fix
ASAP
=> Fixing APIMANAGER-4851

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/events/APIMgtWorkflowDataPublisher.java
Fix for https://wso2.org/jira/browse/APIMANAGER-5881
environments.]
-
=> adding check for skipEventReceiverConnection in APIMgtWorkflowDataPublisher

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/externalstores/default-external-api-stores.xml
=> Fix for APIMANAGER-5664

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery.pot, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/master.pot, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/template.jag
Fixing Typo In Edit Advanced Throttle Policy view of doubling the word Throttle.
ASAP
=> Fixing APIMANAGER-5883

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/app-registration-task/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/application-task/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/signup-task/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/subscription-task/template.jag
=> Fixing APIMANAGER-5740

components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSConstants.java, components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSTaskManager.java, components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSUtils.java
=> fix for APIMANAGER-5880

components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/test/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSUtilsTestCase.java
=> test for APIMANAGER-5880

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
=> Fix for APIMANAGER-5877

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtGoogleAnalyticsTrackingHandler.java
=> Fixing https://wso2.org/jira/browse/APIMANAGER-5886

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java
=> Fixing https://wso2.org/jira/browse/APIMANAGER-5715

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
=> fix for APIMANAGER-4673

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/load-tabs.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/life-cycles/template.jag
=> APIMANAGER-4970: Fixing lifecycle graph ui issues

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
=> Fixing APIMANAGER-5719

pom.xml
The dependency "powermock-module-junit4" was duplicated in the root pom.xml and removed it in this PR
-
environments.]
-
=> Removed "powermock-module-junit4 duplicate" depedency

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java
=> Fixing APIMANAGER-5727

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIInfoDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIInfoDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java
=> fixing https://wso2.org/jira/browse/APIMANAGER-5872

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-keys/template.jag
=> Fixing https://wso2.org/jira/browse/APIMANAGER-5783

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/load-tabs.js
=> Fix for https://wso2.org/jira/browse/APIMANAGER-5545

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/js/api-info.js
=> Fixing APIMANAGER-4995: Spinner icon when subscribe button is clicked

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
=> Fixing wso2/product-apim#1535

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/menu/primary/template.jag
=> Fixing APIMANAGER-5008: Manage Alerts to seperate main tab in Store

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
=> Fix for APIMANAGER-5845

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-prototyped/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/provider-apis/template.jag
=> fix for https://github.com/wso2/product-apim/issues/1542

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
When specifying tags, '/' is not allowed from the publisher UI. Tags with '/' is considered as related to Taxonomy feature in registry, and hence does not appear in Store as normal tags.
Fixes: https://wso2.org/jira/browse/APIMANAGER-5310
-
environments.]
-
=> disallowing front slash '/' for tags

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
=> Fixing APIMANAGER-5759

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/template.jag
=> Fixing APIMANAGER-5021: Latency graph buttons issues

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-resource-path/js/stats.js
=> Fixing APIMANAGER-4976: Hyperlinks in Usage by Resource Path

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/block.jag
=> Fixing APIMANAGER-5657: Remove SDK Generation Support for Web Socket APIs

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/js/stats.js
=> Fixing APIMANAGER-5020: fault count graph success icon hides the faults

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/ui-messages.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/user/login/js/login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/user/login/js/login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/add.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-add/ajax/application-add.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/ui-messages.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/login/js/login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/sign-up/redirector.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/user-info/redirector.jag
=> Security fixes for XSS and Open Redirect Vulnerabilities

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/ui/validation/custom-validation.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/sign-up/template.jag
- Fix user sign up validation issues in https://wso2.org/jira/browse/APIMANAGER-5040 and https://wso2.org/jira/browse/APIMANAGER-5041
environments.]
-
=> Fix APIMANAGER-5040 and APIMANAGER-5041

README.md
=> small touch-ups for style

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
- Did a required fix for the API Publisher permissions feature.
environments.]
-
=> Added missing constant to check read permission in query

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
=> fixing resource loosing after thumbnail update

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
Fix for APIMANAGER-5575
--
-
environments.]
-
=> Fix for APIMANAGER-5575

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java
=> update descriptions for workflows

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/initializer.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
Fix for wso2/product-apim#1563
After PR review
=> Update conflicting element IDs of design and implement pages

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
=> fix for https://wso2.org/jira/browse/APIMANAGER-5540

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
=> Revert returning null to fix breaking endpoint validation

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/custom-validation/custom-validation.js
=> fix for APIMANAGER-5896

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/api/APIDefinition.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIDefinitionFromSwagger20.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIDefinitionFromSwagger20TestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java
- scope retrieving with vendor extensions and with Oauh2security definitions are modified.
-test cased added to cover them.
-populate config map was modified
- Scope object model mapping for OAuth2Security definition done.
environments.]
-
=> adding api OAuth2 Security definition are present in definition.

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Swagger/ApiCreateSwagger.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Documents.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Permission.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js
- Scope based enabling for adding endpoint, adding documents, creating api, permission creation
environments.]
-
=> Scope based fields enabling for publisher UI

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/login.css
- remove ant and update the page with material-ui 
environments.]
-
=> remove ant from admin portal login page

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Tasks/TasksListing.js
- remove ant and add material-ui table for workflow approval task page
environments.]
-
=> remove ant from admin portal workflow task approval page

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorAPI.java
- Fix the issue when enabling SSO for react Store
ASAP
=> Fix issue when enabling SSO for react Store

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/AuthManager.js
- Fixed the issue in logout after merging react store
ASAP
environments.]
=> Fix issue in logout after merging react store

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImplIT.java
- Fix broken test case 
environments.]
-
=> Fix broken test case

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/images/lifecycle.svg, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleHistory.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/TransitionStateButton.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Message.js
=> Removing ant from Lifecycle page and adding material design

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtUsageHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/APIMgtCommonExecutionPublisher.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AlertTypesPublisher.java
Removed unnecessary skipEventReceiverConnection checks, before initializing data publishers.
-
environments.]
-
=> Fixing APIMANAGER-5900

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/ui/validation/custom-validation.js
=> Reverted APIMANAGER-5041 fix and fixed regression in APIMANAGER-4851 fix

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/index.js
=> fixing tab loading issue after npm update

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Shared/Confirm.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Shared/Message.js
=> Add generic  way to show messages in admin portal

components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApisApi.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Documents/Documents.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Documents/DocumentsTable.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
=> adding store api documents UI

components/apimgt/org.wso2.carbon.apimgt.core/pom.xml, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/APIMConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/SdkLanguageConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ApiStoreSdkGenerationException.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIDefinitionFromSwagger20.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/ApiStoreSdkGenerationManager.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/ApiStoreSdkGenerationManagerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/swagger.json, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/swaggerPetStoreCorrect.json, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApisApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApisApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SdkGenApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SdkGenApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/factories/SdkGenApiServiceFactory.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/SdkGenApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/SdkGenApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/resources/swaggerPetStoreCorrect.json, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/resources/swaggerPetStoreIncorrect.json, features/apimgt/org.wso2.carbon.apimgt.core.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator.feature/pom.xml, pom.xml
Reverts wso2/carbon-apimgt#4538
Do not merge till orbiits released
=> [DO NOT MERGE]Adding SDK generation feature for APIs in API Manager Store

components/apimgt/org.wso2.carbon.apimgt.core/pom.xml, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/ApiStoreSdkGenerationManager.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, features/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator.feature/pom.xml, pom.xml
This PR is for the snakeyaml version upgrade.
Dependency changes are as follows
- org.wso2.orbit.org.yaml (1.18.0.wso2v1) --> org.yaml (1.18)
-
environments.]
-
=> Snakeyaml version upgrade

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/.npmrc, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/package.json
=> update material-ui version for admin portal

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/OracleSQLStatements.java
=> Fix test break

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Documents/Documents.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Create/ApplicationCreate.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Listing/Listing.js
=> Redirect to application list after app creation

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/api/Analyzer.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/AnalyticsDAO.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/AnalyticsDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/AnalyzerImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/TestUtil.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/AnalyticsDAOImplIT.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/AnalyzerDaoImplIT.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/testngDAO.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.analytics/src/main/java/org/wso2/carbon/apimgt/rest/api/analytics/impl/ApiApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.analytics/src/main/test/java/org/wso2/carbon/apimgt/rest/api/analytics/mappings/AnalyticsMappingUtilTestCase.java
- Adding test cases for DAO impl.
- Fix test cases for time conversion.
environments.]
-
=> Add analytics integration test cases

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/NotifierConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultIdentityProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/NewApiVersionMailNotifier.java
=> fixed issues in email notification

components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/testngDAO.xml
- Revert test case execution to fix the issue with oracle DB.
environments.]
-
=> Revert test cases execution

components/apimgt/org.wso2.carbon.apimgt.rest.api.webserver/src/main/java/org/wso2/carbon/apimgt/rest/api/webserver/impl/PublisherApiServiceImpl.java
=> resolves #1559

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Create/ApplicationCreate.js
=> Show selected option in dropdown menu (API subscription)

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/BusinessPlans.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Create/CreateBusinessPlan.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Shared/GeneralDetails.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Shared/QuotaLimits.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Shared/Shared.css, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/api.js
- page to add subscription tier policy
environments.]
-
=> add page to add subscription tiers

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/ExtendedSubscriptionDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/SubscriptionsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/SubscriptionMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
=> fixing APIMANAGER-5898

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/ProductionKeys.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
Add new UI to generate keys for applications
ASAP
environments.]
-
=> Add key generation UI

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/AnalyticsDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/AnalyticsDAOImplIT.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/testngDAO.xml
- Analytics test fixes to run tests in oracle db
environments.]
-
=> Analytics test fixes to run tests in oracle db

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/AnalyzerImplTestCase.java
- Add analytics impl unit tests.
environments.]
-
=> Add more analytics unit tests

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js
=> disabling version input

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.js
- Fixed login issue due to hard-coded "localhost" in url 
ASAP
environments.]
=> Fix login issue due to localhost

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js
=> fixing api creation issue due to version skip

pom.xml
=> Edit license header.

components/apimgt/org.wso2.carbon.apimgt.rest.api.analytics/pom.xml
=> Commented swagger2msf4j-maven-plugin

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Tasks/TasksListing.js
- Add error handling for task approval
- Use generic messages to display messages
add error handling for task approval
--
environments.]
-
=> Add error handling for task approval

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/ApiStoreSdkGenerationManager.java
Change '/' to File.separator in APiStoreSdkGenerationManager
-
environments.]
-
=> Change '/' to File.separator

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json
=> fix package json description in store web app

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Permission.js
This PR fixes the following issue
https://github.com/wso2/product-apim/issues/1598
UI changes
environments.]
-
=> fix setting api visibility functionality in publisher

components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml, components/apimgt/org.wso2.carbon.apimgt.hostobjects/pom.xml, components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml, pom.xml
=> Adding jacoco plugin for apimgt components

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImplWrapper.java
=> Adding unit tests for AMDefaultKeyManagerImpl

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImplWrapper.java
=> Adding missing overrides in AMDefaultKeyManagerImplWrapper

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/util/test/APIUtilTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java
=> fix for APIMANAGER-5903

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
=> Fix for https://github.com/wso2/product-apim/issues/1623

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/HandlerConfig.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/SecurityConfigContext.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/TemplateUtilContext.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/APIConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/BAMMediatorConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/EndpointBckConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/EndpointConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/EnvironmentConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/HandlerConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/HandlerConfigTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/JwtConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/ResourceConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/ResponseCacheConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/SecurityConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/SecurityConfigContextWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/TemplateUtilContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/TransportConfigContextTest.java
=> Include unit tests for apimgt.impl.template module.

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/ApiStoreSdkGenerationManager.java
=> Return empty HashMap instead of null object

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObjectTest.java
=> adding more tests

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClient.java
=> fixes https://github.com/wso2/product-apim/issues/1631

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/HandlerConfig.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/TemplateUtilContext.java
This reverts commit e331ae4dab8fccd705870d06566412d4c0ea7750.
-
environments.]
-
=> Revert "Remove unused methods : e331ae"

components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/internal/APIKeyMgtServiceComponentTest.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/internal/ServiceReferenceHolderTestCase.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/util/APIKeyMgtUtilTestCase.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/util/APIManagerOAuthCallbackHandlerTestCase.java
=> Adding key manager test cases

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIKey.java, components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/ApplicationKeysDTO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApisApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApplicationsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApplicationsApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SubscriptionsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SubscriptionsApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TagsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TagsApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TiersApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TiersApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIBusinessInformationDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIEndpointURLsDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIEnvironmentURLsDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIInfoDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationKeyDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationKeyGenerateRequestDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/SubscriptionsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/ApplicationKeyMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/store-api.json
Added grant type and callback url update API to Store REST API.
Fixes https://github.com/wso2/product-apim/issues/1628 
-
ASAP
-
=> Added grant type and callback url update API to Store REST API.

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/documentation/js/docs.js
=> Fixing APIMANAGER-5910

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSExcelIndexer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/PDFIndexer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notification/NewAPIVersionEmailNotifier.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notification/NotificationExecutor.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSExcelIndexerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/PDFIndexerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/PlainTextIndexerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/WSDLIndexerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/XMLIndexerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/util/MSExcelIndexerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/util/PDFIndexerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/notification/NewAPIVersionEmailNotifierTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/notification/NotificationExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/notification/util/NewAPIVersionEmailNotifierWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/notification/util/NotificationExecutorWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/log4j.properties
- Add impl.notification package unit tests
- Add impl.indexer.index package unit tests 
ASAP
-
=> Add unit tests for impl.notification and impl.indexer.index

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/listeners/KeyManagerUserOperationListener.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/listeners/KeyManagerUserOperationListenerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/listeners/KeyManagerUserOperationListenerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/resources/log4j.properties
=> KeyManagerUserOperationListener test cases

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerWrapperExtended.java
AbstractAPIManager class test cases
-
environments.]
-
=> AbstractApiManager Test cases

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/index.html, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/ApiCreate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js
=> Adding the webpack chunking

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ApiMgtDAOMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ConfigurationMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ConfigurationServiceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/RealmServiceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/RegistryServiceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ResourceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ServiceReferenceHolderMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/TenantManagerMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/UserRegistryMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTierTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
=>  Tier Tests including reusable power mocks 

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/.babelrc, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js
=> Adding missing dynamic config  for bablerc, and removed the prod configs for now for better optimization.

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
=> Test name and provider extraction from REST api name

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerCacheExtensionHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerExtensionHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerCacheExtensionHandlerTest.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerCacheExtensionHandlerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerExtensionHandlerTest.java
=> add unit test for org.wso2.carbon.apimgt.gateway.handlers.ext

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
=> Test for getHttpClient

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/recently-added/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/search/api-search/template.jag
This PR contains fixes for,
- Enable API serach on enter key press
- Fix text padding issue for recently added APIs
Refer https://wso2.org/jira/browse/APIMANAGER-5930
ASAP
environments.]
-
=> Fixed APIMANAGER-5930

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jagg/jagg.jag
This PR fixes the session invalidation issue in admin application.
environments.]
-
=> Fixing session invalidation issue

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSPowerpointIndexer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSWordIndexer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSPowerpointIndexerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/MSWordIndexerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/PDFIndexerTest.java
- Add remaining impl.indexing.indexer unit tests
After review
environments.]
-
=> Add remaining impl.indexing.indexer unit tests

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/sso/logout/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/sso/logout/template.jag
- This PR contains the fix for https://wso2.org/jira/browse/APIMANAGER-5551
ASAP
environments.]
=> Fixing APIMANAGER-5551 - Capability to configure SAML2 SSO IDP logout url

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTierTest.java
=> Tests for adding defualt tiers to tenants

components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/events/APIMgtWorkflowDataPublisher.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/caching/CacheInvalidatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/service/APIConsumerAdminTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/service/RegistryCacheInvalidationServiceTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/service/TierCacheServiceTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/token/DefaultClaimsRetrieverTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/events/APIMgtWorkflowDataPublisherTestCase.java
Unit tests for 
impl.service
impl.token
impl.caching
impl.workflow.events
-
environments.]
-
=>  unit tests for impl packages

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml, components/apimgt/org.wso2.carbon.apimgt.throttling.service/pom.xml
=>  Removed jackson-dataformat-xml dependancy from store, publisher, admin, dcr and throttling webapps

components/apimgt/org.wso2.carbon.apimgt.hostobjects/pom.xml, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObject.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObjectTest.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jaggery.conf, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/pages/error-pages/error-page.html, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/pages/error-pages/error-page.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jaggery.conf, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/theme-upload-task/block.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/error-pages/error-page.html, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/error-pages/error-page.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/theme-upload-task/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jaggery.conf, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/error-pages/error-page.html
- Adding error pages for different error codes
- Fixed exe file upload in API docs
- Fixed tenant theme upload with unsupported file types
environments.]
-
=> Fixing file upload issue

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ConfigurationMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ConfigurationServiceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/RegistryServiceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ResourceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/ServiceReferenceHolderMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/UserRegistryMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/sampleSequence.xml
=> Add more tests

components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/AbstractScopesIssuer.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuer.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopesIssuerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerWrapper.java
PR adds unit tests for PermissionBasedScopeIssuer
environments.]
-
=> Adding PermissionBasedScopeIssuer test cases

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObjectTest.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/util/JsonSerializationTest.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/util/TestUtils.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/resources/swagger/Pet.json
=> adding utils test case

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
=> Added more tests

components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftAPIDataStoreTest.java
=> Test cases for ThriftAPIDataStore

components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
=> Adding powermockito dependancies to org.wso2.carbon.apimgt.gateway

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisher.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisherTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisherWrapper.java
- Adding test cases for WSO2APIPublisher
ASAP
environments.]
=> Adding test cases for WSO2APIPublisher

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerWrapperExtended.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AuthorizationManagerMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/RealmServiceMockCreator.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/UserRealmMockCreator.java
This PR contains test cases for Abstract api manager class.
This will bring the test coverage up to 96% for the class
-
environments.]
-
=> Local 6.1.x unit test

components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml, components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponentAddRxtConfigsTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponentAddTierPolicyTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponentImagePermissionTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponentPermissionsTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponentTest.java
- Fix "already instrumented" error in gateway tests
- Add happy path test for APIManagerComponent#activate
- Add several ApiManagerComponent private method unit tests 
After review
environments.]
-
=> Add more impl.internal unit tests

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/util/test/APINameComparatorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/util/test/APIVersionComparatorTest.java
Unit tests for APINameComparator and APIVersionComparator
-
ASAP
-
=>  Unit tests for APINameComparator and APIVersionComparator

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityUtils.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandlerTestCase.java
=> unit tests for gateway.handlers

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIClientGenerationManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplWrapper.java
=> Add more APIConsumerImpl unit tests

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ApplicationThrottleController.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ApplicationThrottleControllerTest.java
=> test cases for ApplicationThrottleControllerTest

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIMRegistryServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIMRegistryServiceImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIMRegistryServiceImplWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/DefaultGroupIDExtractorImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImplWrapper.java
=> Add tests for registryServiceImpl,IDExtractorImpl

components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/service/APIGatewayAdmin.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/service/APIGatewayAdminTest.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/service/APIGatewayAdminWrapper.java
=> API KeyValidator Client Tests

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jagg/jaggery_acs.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/user/login.jag
=> Fixing sso and workflow for admin app session

components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRdbmsClientImpl.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/statistics/usage.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/stats/topUsers/ajax/stats.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/topUsers/js/stats.js
- add  limit based stats selection based on a config
- add server side processing of chart data
environments.]
-
=> fix for APIMANAGER-5942

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/EndpointConfigContextTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/HandlerConfigTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/ResourceConfigContextTest.java
=> Improve unit tests in org.wso2.carbon.apimgt.impl.template

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/service/APIAuthenticationService.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/service/APIAuthenticationServiceTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
=> fix for #1656

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/TestUtils.java, pom.xml
- When publishing a new API version,the notifications will be sent to the subscribed uses for the API
environments.]
-
=> Fix for APIMANAGER-5905

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
=> Fix for APIMANAGER-5955

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/css/custom.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/menu/left/template.jag
- adds a left navigation to navigate through all stat pages [APIMANAGER-5935](https://wso2.org/jira/browse/APIMANAGER-5935)
- collapsable sub stat categories
- added navbar vertical scrolls
- fixes left nav slow redraw problem
environments.]
-
=> Fixes for APIMANAGER-5935

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/ApiImportExportManager.java
- APIs that had no endpoints couldn't be exported before.
- Fixes https://github.com/wso2/product-apim/issues/1455
=> fix: Export APIs Which Have No Defined Endpoints

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
- Fix  https://wso2.org/jira/browse/APIMANAGER-5954
- Fix  https://wso2.org/jira/browse/APIMANAGER-5953
environments.]
-
=>  Fix APIMANAGER-5953 & APIMANAGER-5954

components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java
This PR fix the issue when getting apis using "x-wso2-tenant" for specific tenants. 
-
environments.]
-
=> Fix store rest api anonymous user apis get for tenant

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/utils/AuthUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/impl/OAuth2Authenticator.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/main/java/org/wso2/carbon/apimgt/rest/api/configurations/models/EnvironmentConfigurations.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ConfigManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/DefaultConfigs.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/auth/login.test.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/test/configmanager.test.js
- Edit `ConfigManager` to read environment configurations from  `org.wso2.carbon.apimgt.rest.api.configurations` REST api
- Authenticate user from environment instance
- Add test-cases for `ConfigManager`
- Make `org.wso2.carbon.apimgt.rest.api.configurations.models.EnvironmentConfigurations` returns one default environment in `List<Environment> environments`
- Implement the feature https://github.com/wso2/carbon-apimgt/issues/4691
=> [C5][environment] Read configurations and authenticate user in proper environment [publisher][feature][data]

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/overview/template.jag
- Fix publisher UI encode issues
environments.]
-
=> Fix publisher UI encode issues

components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSTaskManager.java
=> fixed APIMANAGER-5968

components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftKeyValidatorClientPoolTest.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftKeyValidatorClientTest.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftUtilsTest.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleConditionEvaluatorTest.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/overview/template.jag
=> Adding org.wso2.carbon.apimgt.gateway.handlers.security.thrift test cases

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/utils/AuthUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/impl/OAuth2Authenticator.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/main/java/org/wso2/carbon/apimgt/rest/api/configurations/ConfigurationService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/main/java/org/wso2/carbon/apimgt/rest/api/configurations/models/EnvironmentConfigurations.java
- Edit `AuthenticatorAPI`'s utility class that extract and build cookies with appending environment name.
- Filter cookies with appended environment name in `OAuth2Authenticator`.
- Add `getEnviornmentName` static method in `ConfigurationService` class.
- Remove duplicate and circular dependencies in `Configurations API`'s `pom.xml` file.
- Implement the feature https://github.com/wso2/carbon-apimgt/issues/4701.
=> [C5][environment] Append environment name to cookies' names

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
- Fix wso2/product-apim#1684
zclip requires flash to manipulate the clipboard. Since we can't
expect all users have flash installed, native JS clipboard API is
used to provide the copy action.
After review
-
=> Replace zclip based clipboard actions with native JS

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
Related issue : wso2/product-apim#1683
There is a service method on the APIKeyMgtProviderService class called removeScopeCache().
This method and its usage have to be removed since the scope cache no longer exists.
-
environments.]
-
=> Removed calling unnessary cache invalidation call

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/js/i18nResources.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-geolocation-usage/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-subscriptions/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-resource-path/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-user-agent-usage/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/page/base/js/jagg.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/js/i18nResources.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/js/i18nResources_fr.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/perAppAPICount/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/topUsers/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/login/js/login.js
=> APIMANAGER-5966 - Fix api walkthrough not working issue

pom.xml
Changing the identity-inbound-auth-oauth version to 5.3.35
-
ASAP
=> Changing the identity-inbound-auth-oauth version

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtUsageHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/APIMgtCommonExecutionPublisher.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtUsageHandlerTest.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/APIMgtUsageDataBridgeDataPublisher.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeExecutionTimePublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeFaultPublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeRequestPublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeResponsePublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/ExecutionTimePublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/PublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/ThrottlePublisherDTO.java
=> add key type and correlationID to analytics events

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
- Fix array index names (in api.js) as in [store-api.yaml](https://github.com/wso2/carbon-apimgt/pull/4598/files#diff-d57584a9984a31c3ce18f54bd17bbda3)
- `client.apis["API Collection"]` to `client.apis["API (Collection)"]`
- `client.apis["API (individual)"]` to `client.apis["API (Individual)"]`
- Make key unique when listing APIs (in Listing.js)
```javascript
<Grid container>
{this.state.apis.list.map(api => {
return <ApiThumb api={api} key={api.id}/>
})}
</Grid>
```
- Remove `this.props.setLeftMenu()` (in index.js)
- Fix issue https://github.com/wso2/carbon-apimgt/issues/4708
=> Fix Store not rendering API list issue #4708

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstantsTest.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/UtilsTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketThriftClientTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketUtilTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketWSClientTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtGoogleAnalyticsTrackingHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityConstantsTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityExceptionTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/ResourceNotFoundExceptionTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponentTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/internal/ExtendedAPIHandlerServiceComponent.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/internal/ServiceReferenceHolderTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/ThrottleDataHolderTest.java
=> unit tests for apimgt.gateway

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIListDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIListPaginationDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIListDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIListPaginationDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
=> adding pagination section for store and pub rest apis get

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jaggery_acs.jag
- if the SAML response state not authorized from IDP, we log out from web app
- Address the issue [APIMANAGER-5975](https://wso2.org/jira/browse/APIMANAGER-5975)
environments.]
-
=> Fix for APIMANAGER-5975

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImplTest.java
Fixed the jenkins build failure. Added javax.ssl.truststore.password to system properties in CertificateManagerImplTests.
-
environments.]
-
=> Fixing build failure.

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/internal/APIKeyMgtServiceComponentTest.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtProviderServiceTest.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberServiceTest.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationServiceTest.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/thrift/APIKeyValidationServiceImplTest.java
=> Added test cases

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Add validation to prevent adding api name,version with illegal characters. This validation had been already added in UI level but had not been added for rest api invocation flow.
-
environments.]
-
=> Add validation to prevent adding api name,version with illegal characters

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketWSClient.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClient.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/clients/OAuth2TokenValidationServiceClient.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIGatewayAdminClient.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/RemoteAuthorizationManagerClient.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/RemoteUserManagerClient.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/UserSignUpWorkflowExecutor.java, components/apimgt/org.wso2.carbon.apimgt.keymgt.client/src/main/java/org/wso2/carbon/apimgt/keymgt/client/SubscriberKeyMgtClient.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/RestAPIStoreUtils.java
=> Fixing APIMANAGER-5976: removing unwanted "rememberMe"s in Admin Service calls

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/TestUtils.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTierTest.java
=> Add api tier tests

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/SampleLoginPostExecutor.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/UserAwareAPIConsumerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/SampleWorkFlowExecutor.java
=> Add test for APIConsumerImpl

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-add/ajax/remove.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/url-validation/url-validation.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/key.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-list/ajax/application-list.jag
=> Adding some UI validation and fixes

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/enjoyhint-3.1.0/enjoyhint.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/enjoyhint-3.1.0/src/jquery.enjoyhint.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/enjoyhint.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/src/jquery.enjoyhint.css
- This PR changes the text color for words which needs to be typed in when using tutorial
- Highlight the word containing the action user have to perform
environments.]
-
=> APIMANAGER-5992 - Improving the user experience of the API manager interactive tutorial

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- Change `apiGatewayEnvironments` variable data type from Map type to LinkedHashMap to preserve the order of the elements
environments.]
-
=> Change apiGatewayEnvironments datatype

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/handlers/APIEndpointPasswordRegistryHandler.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
=> Fix UI and registry password issue

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
Star Ratings Bar 
Comments
-
environments.]
-
=> Ratings comments UI for Store

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisher.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisherWrapper.java
This fixes the limitation to enable/disable hostname verification while publishing APIs to external stores
-
environments.]
-
=> Fixing APIMANAGER-5970

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIGatewayAdminClientTest.java
=> Unit tests for APIGatewayAdminClient

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- Introduce (not fully implemented) Multi-attribute search for Publisher (No DAO changes)
- Research possible designs in database layer to support queries on aforementioned functionality
- Implement DAO methods to support Multi-attribute search
=> feat: Introduce Multi Attribute Search for Publisher

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/APIMConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/GoogleAnalyticsConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/RegistrationSummary.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/gen/java/org/wso2/carbon/apimgt/rest/api/core/dto/RegistrationSummaryDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/java/org/wso2/carbon/apimgt/rest/api/core/utils/MappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/main/resources/apim-core-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/test/java/org/wso2/carbon/apimgt/rest/api/core/impl/GatewaysApiServiceImplTestCase.java, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/constants/Constants.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/dto/GatewayConfDTO.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/ganalytics/GoogleAnalyticsTracking.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/holders/CacheHolder.bal, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/utils/Utils.bal, gateway-modules/apim-ballerina-configs/pom.xml
- This pull request contains the source of google analytics intercepter, which allows you to publish gateway analytics to google analytics service
- When the google analytics ballerina interceptor is capable of publishing API access data into google analytics API
- Needs to generate tracking ID and configure it in APIMConfiguration, in order to access google analytics API
=> Google Analytics Interceptor

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- Move delimiters (string constants) to class level to fix the build.
- Setup a continuous integration to be run on every pull request
=> fix(publisher): move delimiter constants to class level

components/apimgt/org.wso2.carbon.apimgt.rest.api.core/src/gen/java/org/wso2/carbon/apimgt/rest/api/core/dto/GoogleAnalyticsTrackingInfoDTO.java, gateway-modules/apim-ballerina-configs/configs/org/wso2/carbon/apimgt/gateway/ganalytics/GoogleAnalyticsTracking.bal
- This fixes the build failure due to missing GoogleAnalyticsTrackingInfoDTO 
- Verify the build
=> Adding GoogleAnalyticsTrackingInfoDTO

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/RegularExpressionProtector.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/mediators/RegularExpressionProtectorTest.java
- This PR fixes https://github.com/wso2/product-apim/issues/1701
- This PR includes sql threat protector to thwart sql injections. We have created a custom mediator 
called RegularExpressionProtector which matches the vulnerable keywords over the request 
headers, path parameters and request body. 
- The custom sequence called regex_policy.xml contains 
1. the matching keywords
For an instance: 
**|.*DELETE.*|.*DROP DATABASE.*|.*DROP PROCEDURE.*|.*DROP.*|.*SELECT.*|**
2. ask do we need to validate the path paratmeters from a property
_enabledCheckPathParams_
3. ask do we need to validate the request headers
_enabledCheckHeaders_
4. ask do we need to validate the request body
_enabledCheckBody_
- API developer can apply the regex policy in per API basis through the publisher inflow …
=> [Improvement] Threat protector for APIM Gateway 

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/RegularExpressionProtector.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/mediators/RegularExpressionProtectorTest.java
- If the request message body doesn't contain a soapBody or a soapElement, It will be getting failed.
Added multiple null checks to avoid error scenarios.
List all changes you want to add here. If you fixed an issue, please
- Added multiple null checks. If the message body doesn't contain SOAPEnvelope, SOAPBody and Element, just returned and exit from the method.
N/A
=> Fixed issues in regex mediator

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Fixing Error on PostGres when cleaning up Application Registration with autocommit set to true
ASAP
=> Fixing APIMANAGER-4886

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/listing/js/samples.js
This fix changes the swagger definition of pizza shack sample. This is done to make the swagger definition match with the actual back end implementation. Otherwise when generated sdks using this sample will not work
-
environments.]
-
=> Fix SDK generatting wrong response model class for pizza shack sample

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-listing-all/block.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/interactiveTutorial.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/enjoyhint.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-functions.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/menu/header/template.jag
This PR contains the code for the Interactive tutorial for API Store. It will help the users who visit the API Store and will guide them to subscribe and invoke the APIs at the first time. This tutorial contains, 
1. How to create an application and how to subscribe that application to an API.
2. How to generate the production Keys.
3. How to invoke an API using access tokens.
-
environments.]
-
=> Added Interactive tutorial to the API Store

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/API.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/sampleApi.yaml, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/swagger.json, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
Removed CONTROLLED visibility level from API definition which is not used in current visibility model of API 
ASAP
=> Removing CONTROLLED visibility level from API definition

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReaderTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/wsdls/stockQuote.wsdl, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/wsdls/wsdl2-sample.wsdl, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-add/ajax/remove.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/page/base/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/user/login/js/login.js
- Improved validations in Publisher App to avoid Open Redirection and CSRF issues.
- Improved XML parser configurations for avoiding XXE issues.
=> Adding fixes for open redirection, xxe, csrf issues

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/interactiveTutorial.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/menu/header/template.jag
This PR contains some changes for Interactive tutorial configuration variable name. This variable name renamed from  "blackListedTenantDomainsFor_IntractiveTutorial"  to "blackListedTenantDomains" since it is too long.
Configuration File : store/site/conf/interactiveTutorial.json
N/A
N/A
=> Changing Interactive tutorial configuration variable name

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.analytics/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
=> fixing release build

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.analytics/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
Reverts wso2/carbon-apimgt#4774
=> Revert "fixing release build"

components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
Fixing Already Instrumented error in unit tests
=> fix already instrumented error

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
Fixed API creation failure issue in firefox.
=>  Fixed API creation failure issue in firefox

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
-  Change the `lifecycleChecklist` data sending to `/apis/change-lifecycle` endpoint in POST to update the lifecycle state of an API
- Add validators to `ApisApiServiceImpl` class -> `apisChangeLifecyclePost` method to send response with `400` Bad Request when request contains invalid  lifecycleChecklist format.
=> Fix for: APIs can't publisher without selecting lifecycle checklist items

gateway-modules/pom.xml
=> fixing release

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json
- Change the `material-ui-icons` version to latest beta
environments.]
-
=> changel the material-ui-icons version to latest beta

components/apimgt/org.wso2.carbon.apimgt.core/pom.xml, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/EnvironmentConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/main/java/org/wso2/carbon/apimgt/rest/api/configurations/models/APIMUIConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/test/java/org/wso2/carbon/apimgt/rest/api/configurations/internal/ServiceReferenceHolderTestCase.java
=> Fix enviromet feature conflicts with kernel upgrade

pom.xml
Updating the carbon governance version
environments.]
-
=> Upgrading carbon governance

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
=> Change "SDK Language list" to "SDK Languages"

components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml, features/apimgt/org.wso2.carbon.apimgt.core.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.rest.api.configurations.feature/pom.xml, gateway-modules/apim-ballerina-configs/pom.xml, pom.xml
#https://github.com/wso2/product-apim/issues/1946
-
Immediate
This pr can merge after msf4j 2.4.3 released
environments.]
-
=> upgrde msf4j version to 2.4.3

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/EnvironmentConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/Notifier.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/Application.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/Label.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/WorkflowUtils.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/notification/NotificationTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/util/APIFileUtilsTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/util/EndpointComparatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/dto/ErrorDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/test/java/org/wso2/carbon/apimgt/rest/api/commons/impl/OAuth2AuthenticatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/main/java/org/wso2/carbon/apimgt/rest/api/configurations/models/APIMUIConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/main/java/org/wso2/carbon/apimgt/rest/api/configurations/models/EnvironmentConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/test/java/org/wso2/carbon/apimgt/rest/api/configurations/ConfigurationsAPITestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.configurations/src/test/java/org/wso2/carbon/apimgt/rest/api/configurations/internal/ServiceReferenceHolderTestCase.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/EnvironmentMenu.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIClient.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ApiPermissionValidation.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ConfigManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ScopeValidation.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
- Add material-ui drop-down box for environment selection on the login page.
- Refactor `configManager.js` for future configurations.
- Remove unnecessary dependencies in `ConfigurationsAPI`.
- Remove unused imports (Optimize imports).
- Set User with respect to the environment.
- Fix format issues in `org.wso2.carbon.apimgt.publisher.feature` `publisher/source/src/app/data`
- Fix issues in comments (comments in Configurations)
=> [C5][environment] Manage User with the Environment.

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
This PR contains fixes in invalidating cache entry of super-tenant users. This is because when we add a cache entry for super-tenant users, we add them without domain name. however, when trying to clear the cache entry , we are appending the domain name. So it clears wrong cache entry.
N/A
N/A
-
=> Fixing PublisherRoleCache invalidation issue in super-tenant

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/EnvironmentConfigurations.java
- Fix check style issue exceeding no of chars in one line
environments.]
-
=> Fix check style issue exceeding no of chars in one line

components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/utils/FileBasedApplicationImportExportManagerTestCase.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
=> Removing unnecessary test cases

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json
- Fix for showing Null value for Download Source button name in API view page in publisher
N/A
=> Fix: Showing null value for download source button

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/Header.js
- Fix https://github.com/wso2/carbon-apimgt/issues/4811
=> Fix the issue Logout not working as expected

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
Fixes wso2/product-apim#1966 
-
N/A
N/A
-
=>  Fix wso2/product-apim#1966 

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java
This PR fixes the issue reported in [APIMANAGER-6027](https://wso2.org/jira/browse/APIMANAGER-6027)
environments.]
-
=> Fix APIMANAGER-6027

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/FileEncryptionUtilityTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/resources/security/someFile, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
=> fixing test failure in FileEncryptionUtilityTestCase

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag
This PR fixes https://github.com/wso2/product-apim/issues/1983
-
environments.]
-
=> Fix product-apim/#1983

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ThreatProtectionDAOImplIT.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/testngDAO.xml
- Fixed the integration test failure in ThreatProtectionDAOImplIT
environments.]
-
=> Fix: ThreatProtectionDAOImplIT test failure

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Logout.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
- Fix API listing page method not found issue
- Fix API Details(Overview) page styling(Horizontal alignment) issue
environments.]
-
=> [Store] API listing and details page 

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/load-tabs.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/users-api/template.jag
Fixing pagination issues exists in "Users" tab of API-info page in API Publisher
- sorted the subscribers by username
- fixed the null pointer issue which breaks setting the selected tab to be reloaded when page refresh.
ASAP
=> Fixing Public JIRA APIMANAGER-6035

gateway-modules/apim-ballerina-native-component/pom.xml
Changes for threat protection dependencies
environments.]
-
=> Changes for threat protection dependencies

features/apimgt/org.wso2.carbon.apimgt.admin.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml
- Upgraded feature plugin.
- Removed node_modules from react apps from features
environments.]
-
=> Improving feature installation time

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- Swagger editor definition update based on the resource parameter description, data type, is required fields
N/A
N/A
=> Fixing : Resource parameter updates are not getting reflected in swagger editor

features/apimgt/org.wso2.carbon.apimgt.admin.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/p2.inf, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/p2.inf, features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/p2.inf
- Fixing regression in https://github.com/wso2/carbon-apimgt/pull/4829
- Adding missing feature configurations for store/admin/publisher webapps
=> Adding missing feature configurations

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/pages/index.html, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/Header/ComposeHeader.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/LoginBase.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/p2.inf
- Adding admin app to new web-ui server.
=> Adding admin app to web-ui server

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/Header.js
- Fix https://github.com/wso2/carbon-apimgt/issues/4811
=> Fix Menu items are not working as expected

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
Fixes following issues reported in API design phase
- https://github.com/wso2/product-apim/issues/1986
- https://github.com//wso2/product-apim/issues/1702
- https://wso2.org/jira/browse/APIMANAGER-6004
- https://github.com/wso2/carbon-apimgt/issues/4840
=> Fixing API Design phase issues

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
- Adding test cases for Adding API with API Version and API name including Illegal Characters
environments.]
-
=> Adding test cases for Adding API with API Version and API name including Illegal Characters

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/user/login.jag
Fixes wso2/product-apim#2018
environments.]
-
=> Fixing product-apim/#2018

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- Added support for httpclient.hostnameVerifier=AllowAll/Strict
=> Added support for httpclient.hostnameVerifier

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/ApiCreate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/Policies.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Footer/Footer.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Alert.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Message.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ScopeValidation.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json
- Add common alerting mechanism for Publisher app
- Update `material-ui` library version
- Add page footer to application base, Fix alignment issue caused by not setting the spacing property
- Improve/Fix Design new API page UI/UX issues (Address the issue in https://github.com/wso2/product-apim/issues/2009)
- Check basic API create operation
- Check for Alert messages in case of error creating the API
- Enable network throttling and check for loading animation and status update alert messages
- Need to update the following documentation with new UI change.
- - [Create and Publish an API](https://docs.wso2.com/display/AM300/Create+and+Publish+an+API)
=> Make improvements to Publisher Design new API UI 

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
- Fixed https://github.com/wso2/carbon-apimgt/issues/4855 and https://github.com/wso2/carbon-apimgt/issues/4856
- ASAP
=> Fixed semi manual client registration related UI issues

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplWrapper.java
=> Fixed a unit test

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NavBar.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
- The issue has occurred due to conflicting in `Antd` and `Material-UI`, Change the `Details` component layout using MUI `Grid` layout component.
- Address the issue in https://github.com/wso2/product-apim/issues/1949
- Need to refactor other subcomponent when addressing https://github.com/wso2/product-apim/issues/1951 issue
=> Fix publisher API details page alignment issues

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js
- Show `Deploy a sample API` button when there are no created APIs in Publisher
- When click on `Deploy a sample API` button
- Create API using Swagger Pet-Store sample [swagger definition](http://petstore.swagger.io/v2/swagger.json)
- Update Sample API business plans with some random plans(policies)
- Publish the Pet Store API
- Address the https://github.com/wso2/product-apim/issues/2032 issue
- This feature requires new additions/changes to API Manager 3.0.0 Documentations
- Need to add following instruction(reviewing checklist) on how it's work
- Login to the Publisher app
- Make sure no APIs are listed in APIs listing page or landing page
- If any API(s) listed, delete all the APIs
- Now you should be able to see the `Deploy a sample API` button as follows
- Click the `Deploy a …
=> [Publisher] Add sample API deploy feature

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/message/clustering/TenantLoadMessage.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/observers/TenantLoadMessageSender.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/observers/TenantLoadNotifier.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/message/clustering/TenantLoadMessageTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/observers/TenantLoadMessageSenderTest.java
A user loges into its tenant in one of the node every time and create their APIS in publisher. If that user at some point gets into the next node at some point, APIs will not be visible until the indexing completes. This PR provided a solution based on HZ clustering to load tennats and start indexing in remote nodes.
https://github.com/wso2/product-apim/issues/2035
-
environments.]
-
Doc jira to track the changes: …
=> Fix for https://github.com/wso2/product-apim/issues/2035

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/oidc/filter/template.jag
- Fix the issue mentioned in https://github.com/wso2/carbon-apimgt/issues/4864
ASAP
-
=> fix for #4864

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/petstore/pet/1.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/petstore/pet/2.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/Application.js
- Fix for https://github.com/wso2/product-apim/issues/2052
- Update endpoint and securityScheme when deploying sample API
- Add mock endpoints for use with sample `Pet-Store` API
- Needs to update the documentation on how to invoke the sample Pet-Store API
=> Improvements to sample API deploying feature

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/url-validation/url-validation.js
- This fixes the issue https://github.com//wso2/product-apim/issues/1915 . As the fix, Test button is disabled till the validation happens and re-enable it once the validation is over.
environments.]
-
=> fix two valid message showing issue for url validation #1915

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- Fixed https://github.com//wso2/product-apim/issues/1593
=> Fixed https://github.com//wso2/product-apim/issues/1593

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/ui/validation/custom-validation.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/sign-up/template.jag
- Contains UI validations
No pre conditions needed
None
=> UI validations

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js
- Update webpack version to latest stable
- Change Publisher initial landing page UI
- Add [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) as dev dependency for analyzing the publisher load time
- Improve code spliting/chunking using the dependency analysis
- Login to Publisher
- Check `Deploy sample API` option and `Create new API`
- `Deploy sample API` should create and publish an API with one click
-   `Create new API` option should redirect to api creation simplified page
- [ x ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description.
- [ x ] **Is the PR labeled correctly?**
- [ x ] **Does the UI work as …
=> Improve sample deploy and add bundle analyser

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/js/stats.js
fixes  wso2/product-apim#1655
environments.]
-
=> Fix faulty invocation chart's tooltip and x axis labelling

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/custom-validation/custom-validation.js
- This fixes the issue reported in https://github.com//wso2/product-apim/issues/1892 . A new validation is added to both Business user and technical user email address field
environments.]
-
=> fix for email validation UI issue

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationRegistrationSimpleWorkflowExecutor.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java
- Fix https://wso2.org/jira/browse/APIMANAGER-5894
- Returns proper error message to client as below:
```
{
"code": 409,
"message": "Resource Already Exists",
"description": "Keys already generated for the application 8d0b6f5c-ca14-4be0-9690-c552f6f8f9b9",
"error": []
}
```
environments.]
-
=> Fix APIMANAGER-5894 - Internal Server Error if the key already exists

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/users-api/template.jag
Fix for APIMANAGER-5985
-
NA
NA
-
=> APIMANAGER-5985 fixing styling issue

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/listing/template.jag
=> Fix for https://github.com/wso2/carbon-apimgt/issues/4867

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleHistory.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/LifeCycle/LifeCycleHistory.js
https://github.com/wso2/product-apim/issues/2138
environments.]
-
=> Fixing incorrect life cycle state change

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/js/policy-designer-new.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/template.jag
- Input field validation for advanced throttle policy creation UI
- Fixed following issues
-https://github.com/wso2/carbon-apimgt/issues/4883
-https://github.com/wso2/carbon-apimgt/issues/4884
-https://wso2.org/jira/browse/APIMANAGER-5305
N/A
environments.]
-N/A
=> Fix for Advanced throttle policy input validation for #4884 #4883

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/custom-validation/custom-validation.js
This PR fixes following issues
- https://github.com//wso2/product-apim/issues/1901 
- https://wso2.org/jira/browse/APIMANAGER-2884
- https://github.com/wso2/carbon-apimgt/issues/4886
=> Fixing role validation failures in API visibility restrictions

README.md, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json
- Fix npm dependency github url issue
- Fix `carbon-apimgt` README.md travis build status badge link
- N/A
- Run `mvn clean install` locally and tested, no npm issues found 
- N/A
- N/A
=> Fix npm build issues

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.js
- Fix text overflow issue in adding role tag when adding scope
- N/A
- N/A
=> Fix text overflow issue

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.js
- Fix inputs not getting cleared after adding new scope
- Remove redundant input handles
- N/A
- N/A
- Login to Publisher
- Create new API
- Goto scopes tab
- Fill inputs and click `Add scope to API`
=> [Publisher] input not getting cleared after adding a scope

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java
=> Fixes for application url missing when configuring with workflow and pagination issue with publisher and store rest apis

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/password-reset/initiate/js/initiate.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/password-reset/verifier/js/verifier.js
Fixing #2264 and #2268
-
ASAP
environments.]
-
=> Fixing #2264 and #2268

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-user-agent-usage/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/apis-time/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/apis-time/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/application-throttledcounts/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/application-throttledcounts/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/applications-time/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/applications-time/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/developers-time/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/developers-time/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/subscriptions-time/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/subscriptions-time/template.jag
- Removed hour/time range granularity from publisher analytics
- Fix showing null value in publisher analytics for  top API users.
- https://github.com/wso2/product-apim/issues/2258 issue if fixed.
- https://github.com/wso2/product-apim/issues/2218 issue is fixed.
- N/A
- N/A
=> Fixed issues product-apim/2258 and product-apim/2218

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/apis-time/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/applications-time/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/developers-time/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/subscriptions-time/js/stats.js
- Fixed the below mentioned issues which is not allowing edit time range for the second time unless page is reloaded
- Issues:
- https://github.com/wso2/product-apim/issues/2282
- https://github.com/wso2/product-apim/issues/2282
- N/A
environments.]
- N/A
=> Fixing not allowing edit date range for the second time in publisher

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/datepicker/js/daterangepicker.js
- Fix navigating issue (#4907) in publisher analytics UI
- Replaced fa fa-arrow-left & right classes with fw fw-right
After the fix
- N/A
- N/A
=> Fix navigating issue in date range picker in publisher analytics: #4907

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/user/login.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/edit/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/js/policy-designer-new.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/template.jag
This PR consists the fixes for the below mentioned github issues. These issues are basically based on the UI of the Admin web app.  
https://github.com//wso2/product-apim/issues/1909
https://github.com//wso2/product-apim/issues/1908
https://github.com//wso2/product-apim/issues/1768
https://github.com//wso2/product-apim/issues/1737
https://github.com//wso2/product-apim/issues/1770
-
No pre-conditions.
No follow up actions.
-
=> Fix Github issues - 1909,1908,1768

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
This issue fixes the [product-apim/2193](https://github.com/wso2/product-apim/issues/2193)
-
ASAP
environments.]
-
=> Fix: Cannot add resources for the APIs which created through REST API #2193

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/password-reset/initiate/js/initiate.js
- Fixing #2262
ASAP
environments.]
-
=> Fixing #2262

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js
Added react-notification-system package 
Fix issue https://github.com/wso2/product-apim/issues/1924
Prevent users to subscribed API to the same application multiple times. 
give Notification message to users whether they have successfully subscribed.
=> Fix https://github.com/wso2/product-apim/issues/1924

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/.babelrc, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/ProductionKeys.js
- Remove `disabled` attribute in store application token input fields, Since it prevent copying/ selecting text in [FF ](https://support.mozilla.org/en-US/questions/1190785)
- Now all the tokens are selectable
- Replace deprecated BabelJs plugin with new `env` preset
- Remove unwanted headers from user login axios request
- Use FireFox 56+ browser and Login to API Manager Store
- Create new Application
- Generate keys and access token
- Try to copy any keys/token using keyboard shortcut and by right clicking on the selected text
- [ x ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description.
- [ x ] **Is the PR labeled correctly?**
- [ x ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ x ] …
=> Fix for product-apim#2256

components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java, pom.xml
This PR contains the fixes for below issues.
- https://wso2.org/jira/browse/APIMANAGER-5901
- https://wso2.org/jira/browse/APIMANAGER-4038
environments.]
-
=> Fix for APIMANAGER-5901 and APIMANAGER-4038 issues

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json
- Add missing i18n entries
- Fix for https://github.com/wso2/product-apim/issues/2302
environments.]
-
=> Add missing i18n entries

components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java, pom.xml
Reverts wso2/carbon-apimgt#4919
=> Revert "Fix for APIMANAGER-5901 and APIMANAGER-4038 issues"

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/alert-table/ajax/alert-table.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/alert-table/template.jag
This PR fixes https://github.com/wso2/product-apim/issues/2296.
The issue was, using two different names (Health Availability/Availability of APIs) for an alert type in the Alerts dashboard
No preconditions
No follow up actions
-
=> Fix https://github.com/wso2/product-apim/issues/2296

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
This fixes the [wso2/product-apim/2281](https://github.com/wso2/product-apim/issues/2281)
Seems like "Allow Multiple" has been removed in swagger 2.0. Could not find it in [1]
[1] - https://github.com/swagger-api/swagger-core/wiki
This PR also fixes the issue [wso2/product-apim/2278](https://github.com/wso2/product-apim/issues/2278)
-
environments.]
-
=> Fix: Default created swagger has errors when the resource has a path param #2281

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/KeyMgtConfigurations.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/KeyManagerConstants.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImplTest.java
- Changing key manager resource paths/payloads compatible to latest carbon-auth
- Fixing test failures
environments.]
-
=> Changes for latest carbon-auth and fixing test failures

components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/sample/handlers/entitlement/APIEntitlementCallbackHandler.java, pom.xml
Fix for APIMANAGER-6048. This involves moving the sample entitlement mediator used by the XACML usage example[1] into the carbon-apimgt code base to remove the burden of updating dependency versions in new product releases 
[1] https://docs.wso2.com/display/AM210/Enabling+Role-Based+Access+Control+Using+XACML
-
environments.]
-
=> Fix for APIMANAGER-6048

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/alert-table/js/alert-table.js
This PR fixes https://wso2.org/jira/browse/APIMANAGER-5053. The issue was showing abnormal backend response time in alerts without mentioning if its seconds/minutes or milliseconds. 
Ex: Backend Time42
No preconditions
No follow up actions
=>  Fix https://wso2.org/jira/browse/APIMANAGER-5053 

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/KeyManagerConstants.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImplTest.java
fixed missing auth header in DCR request
=>  fixed missing auth header in DCR request

pom.xml
Upgrade fasterxml.jackson to latest 2.9.3 version
-
environments.]
-
=> Upgrade fasterxml.jackson to latest 2.9.3 version

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
This contains the fix for https://wso2.org/jira/browse/APIMANAGER-5752 issue.
environments.]
-
=> Fix for APIMANAGER-5752

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/user/login.jag
* Fix swagger parser issue with yaml files
* Modify checkWorkFlowStatus() function to use a http get instead of a post to check whether BPS is running
environments.]
-
=> 6.x original

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js
Added react-notification-system package
Added delete option to API list and grid view with scope validation
Fix issue https://github.com/wso2/product-apim/issues/2305
=> Fix https://github.com/wso2/product-apim/issues/2305

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultIdentityProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/WSO2ISKeyManagerImpl.java
- Fixes: https://github.com/wso2/product-apim/issues/2361
environments.]
-
=> Fixing #2361: Issue with switching to IS as the Key Manager

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
* Correcting error message for invalid swagger URL
Github Issue URL : https://github.com/wso2/product-apim/issues/2354 
environments.]
-
=> Correcting error message

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/listing/js/samples.js
…README.md properly
- fixes wso2/product-apim#1620
environments.]
-
=> Fixes for the PizzaShackAPI swagger to create the generated sample in sample in README.md with OAuth2 configuration. 

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/README.md, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/README.md, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/README.md
This PR contains adding readme.md files on how to generate rest apis for publisher/admin and store rest apis
-
environments.]
-
=> Read me files on how to generate rest apis

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js
Add new delete option to API overview
Fix https://github.com/wso2/product-apim/issues/2366
=> Fix https://github.com/wso2/product-apim/issues/2366

pom.xml
=> Upgrade snake yaml version

pom.xml
This PR upgrades following vulnerable jars
- cxf-xjc-dv-3.0.2.jar
- httpasyncclient-4.0-beta3.jar
- httpclient-4.2.5.jar
- spring-core-3.0.7.RELEASE.jar
-
environments.]
-
=> upgrading carbon.deployment version

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jaggery_oidc_acs.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jaggery_oidc_acs.jag
- fix for https://github.com/wso2/carbon-apimgt/issues/4947
ASAP
environments.]
-
=> Fix OIDC login permission issue 

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-add/js/item-add.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-add/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/sign-up/redirector.jag
- Fixing merge conflicts of PR 4818
ASAP
environments.]
-
=> Fixing merge conflicts of PR 4818

components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApisApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApplicationsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApplicationsApiService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SubscriptionsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TagsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TiersApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIListDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIListPaginationDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationScopeDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ScopeListDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/store-api.json
- This PR fix the issue [wso2/product-apim/2334](https://github.com/wso2/product-apim/issues/2334).
Now it will send the 400 bad request if the request body is missing.
- This will also correctly generate the store rest api, which was generated without following the correct steps.
-
environments.]
-
=> Fix: Null pointer thrown if generate token endpoint is called without the request body #2334

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantOracle.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantPostgreSQL.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsDB2.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jagg.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-edit/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag
DB query changes to support multiple databses
Minor spelling corrections
displaying message instead of displaying null when group id is null
No Pre Conditions
None
=> Multi group Application Sharing Fixes

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/pages/index.html, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/pages/index.html
Source path change to /public/app/theme/defaultTheme.js both publisher and store.
=> Change defaultTheme.js src path

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js
Change URL path to "/api/create/home"
=> Fix https://github.com/wso2/product-apim/issues/2380

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Using getInt instead of getShort to support large tenant Ids
NONE
NONE
=> Using getInt instead of getShort to support large tenant Ids

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/ServiceDiscovererKubernetes.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
Fix https://github.com/wso2/product-apim/issues/2409
ASAP
N/A
=> Fixing SA token new line issue

components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/API.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/operations/APIIndividual.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/operations/ApplicationIndividual.html
Fixing the POST request of Generating SDK for an API by adding query parameters listed below.
1. apiId
2. language
ASAP
=> Fixing DOCUMENTATION-4743

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
Clearing the system property after it is used in a unit test since it is referred in other unit tests.
NONE
NONE
=> Fixing Intermittent failures in unit tests

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json, features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml, features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/rxts/api.rxt, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/api/list.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/api/api.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/ajax/api-info.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/block.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
This PR is for the feature to customize the authorization header used to send the access token in an API call. With this feature, users can have custom authorization headers as API, Tenant and global levels where the priority is given in the said order.
-
environments.]
-
=> Custom authorization header

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/block.jag
Adding null check for api object which causes null pointer when api is not accessible
NA
NA
=> Adding null check for api

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/ApiConsole.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Documentation.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Documents/Documents.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Forum.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Sdk.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/index.js
-Fixing API Overview UI improvements https://github.com/wso2/product-apim/issues/2459
-
-
-
=> Fixing API Overview UI improvements #4965

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Create/EndpointTableRows.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Create/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Listing/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/index.js
Remove ant functionality from publisher Endpoint
Add theme provider to store app
=> Remove ant functionality from publisher Endpoint

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/CertificateMgtDAO.java
* Setting autocommit to false before carrying out connection.commit in CertificateMgtDAO.java
ASAP
=> Setting autocommit to false before carrying out connection.commit

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml, features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/operations/APIIndividual.html
Adding sample request in the description to demonstrate the use of life cycle checklist items in ChangeAPIStatus REST API
-
ASAP
=> Fixing Public JIRA DOCUMENTATION-6645

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Changing the Role Updating Logic for change owner admin API
-
N/A
N/A
-
=> Changing the Role Updating Logic

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js
Application subscribe action in API overview page triggered from a "Subscribe to an Application" button in Form Dialog
=> Fix https://github.com/wso2/product-apim/issues/2460

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Create/ApplicationCreate.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/ProductionKeys.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/SandboxKeys.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/Subscriptions.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/Header.js
- Fixing https://github.com/wso2/product-apim/issues/2484
environments.]
-
=> Fixing APIM Store Applications UI improvements #2484

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.old.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/FileUpload.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/WSDLFillAPIInfoStep.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/WSDLValidation.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Footer/Footer.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Alert.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Message.js
- Remove `antd` dependencies from `Creat API using SOAP endpoint`
- Address the https://github.com/wso2/product-apim/issues/1951 issue
- Improve `Alert` library to replace with `antd`'s [message](https://ant.design/components/message/) feature
environments.]
-
=> Improvements to API Manager Publisher

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js
Fix https://github.com/wso2/product-apim/issues/2461
=> Fix https://github.com/wso2/product-apim/issues/2461

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiTableRow.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/Header.js
-Fixing https://github.com/wso2/product-apim/issues/2498
environments.]
-
=> API Listing UI fixes #2498

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObjectTest.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/block.jag
This PR addresses the issue[1] and fix showing null for auth header in API Console that emerged because of the PR[2]
[1]https://github.com/wso2/carbon-apimgt/issues/4980
[2]https://github.com/wso2/carbon-apimgt/pull/4968
-
environments.]
-
=>  Fix showing null for auth header in API Console

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json
Fix for : https://github.com/wso2/product-apim/issues/2185
ASAP
environments.]
=> Fix 'mouse hover text for API Store walkthrough is shown as null'

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js
Fixing https://github.com/wso2/product-apim/issues/2573
-
environments.]
-
=> Fixing #4993: Fixing sample endpoint url

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/menu/actions/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
This PR fixes the wso2/product-apim/issues/2516. The issue was swagger JSON of APIs are not available in APIM 2.1.0 for the APIs which has "/" in API name. These APIs were created in APIM 1.7.0.
No pre conditions.
No follow-up actions.
=> Fix wso2/product-apim/issues/2516

features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/guide.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/models/APIList_pagination.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/guide.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/APIList_pagination.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/ApplicationScope.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/ScopeList.html
=> Fixing product-apim/issues/2304 and product-apim/issues/2306

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/public/theme/defaultTheme.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Apis.css, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Sdk.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Create/ApplicationCreate.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Footer/Footer.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/Header.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Shared/redirecting.css
- Adding customized themes + UI fixes
- Fixing https://github.com/wso2/product-apim/issues/2546
environments.]
-
=> APIM3 Theme UI fixes

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/menu/header/template.jag
Fix for https://github.com/wso2/product-apim/issues/2593
ASAP
environments.]
=> Fix API Store Walkthrough Issues

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/public/theme/defaultTheme.js
- Address the following issue https://github.com/wso2/product-apim/issues/2614
- Enable the MUI Theme pallet text styling with version update including this fix https://github.com/mui-org/material-ui/issues/9750
=> Fix store app bar text not visible issue

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/documentation/guide.html, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/documentation/guide.html, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/documentation/guide.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.admin.feature/src/main/resources/api-docs/docs/guide.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/guide.html, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/guide.html
We do not use "tokenScope" when registering the auth app. It is something redundant in the payload.json
Therefore removing tokenscope key value pair from payload.json used in auth app registration
-
ASAP
=> Fixing https://github.com/wso2/product-apim/issues/2273

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js
- Fixed invalid use of spreat operator
environments.]
-
=> Fix invalid use of spread operation

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftUtils.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftUtilsTest.java
=> Fix for https://github.com/wso2/carbon-apimgt/issues/4978

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Security/AddPolicy.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Security/SecurityOverview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js
- Replace previously used `Message` library with `Alert`
environments.]
-
=> Replace depricated Message class with Alerts library

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtilTest.java
Fix CertificateMgtUtil test case failure due to expired certificate.
-
environments.]
-
=> Fix test case failure due to expired certificate.

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/TenantWorkflowConfigHolder.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/WorkflowExecutorFactory.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIGatewayManagerTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/TestUtils.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/APIStateChangeSimpleWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationCreationSimpleWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationCreationWSWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationDeletionSimpleWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationRegistrationSimpleWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationRegistrationWSWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionCreationSimpleWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionCreationWSWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionDeletionSimpleWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/TenantWorkflowConfigHolderTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/UserSignUpSimpleWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/UserSignUpWSWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/UserSignUpWorkflowExecutorTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/WorkflowExecutorFactoryTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/workflow-configs/default-workflow-extensions.xml, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/workflow-configs/workflow-extensions.xml
- Test cases
-When the build is successful with test cases
=> Unit test cases for 6.x

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- This PR includes the fixes for not closing the tenant-flow correctly. 
- Fixes https://github.com/wso2/product-apim/issues/2424
Relevant test case related with this PR https://github.com/wso2/product-apim/blob/2.x/modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/hostobject/HostObjectTestCase.java
environments.]
-
=> Fixing issues of not closing the tenant flow correctly

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/forum/forum-new/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/forum/js/forum-list.js
Fixing https://github.com/wso2/product-apim/issues/2499
ASAP
=> Fixing https://github.com/wso2/product-apim/issues/2499

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.js
In WSDL based API creation wizard, API type radio buttons (Passthrough or HTTP binding selection) are not working due to this.
environments.]
-
=> Fixing typo with 'event'

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObjectTest.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/manager/manager.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jagg.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/manager/manager.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
This PR adds hostname validation and whitelisting to store and admin apps.
environments.]
-
=> Add hostname validation and whitelisting to store and admin apps

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/CustomAPIIndexer.java
This PR fixes the exception thrown during API creation [issue](https://github.com/wso2/product-apim/issues/2632).
environments.]
-
=> Fix for exception thrown during API Creation

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIStoreImplTestCase.java
- Fixes https://github.com/wso2/product-apim/issues/1554: APIs with created state are visible in store when direct URL is entered
- Fixes https://github.com/wso2/product-apim/issues/2056: Cannot create API with same name once deleted
- Added some test cases.
environments.]
-
=> Fixing issues with APIs retrieval in Store and API deletion 

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidatorTestCase.java
=> Fix for APIMANAGER-5720

.gitignore, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorAPI.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/constants/AuthenticatorConstants.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIClient.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json, package-lock.json
- Implement token refresh in `SwaggerJs` interceptor for regenerate access token when it's about to expire in pre-defined buffer time (default to 60Sec)
- At the same time, trigger refresh token call from a JS `setTimeout` method , to regenerate access token before it's expire
- 
- Implement request handling for refresh_token grant type in `DefaultKeyManagerImpl`
- Address the following issues
- https://github.com/wso2/product-apim/issues/2419
- https://github.com/wso2/product-apim/issues/1988
- This PR depends on the changes in https://github.com/wso2/carbon-auth/pull/98 
- Need impliment this improvment https://github.com/wso2/product-apim/issues/2653
- N/A
=> SPA app login, keep active access token while user is interacting

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/Footer/Footer.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/LoginBase.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/ApiCreate.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/InputForm.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Footer/Footer.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Landing/Landing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/LoginBase.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Footer/Footer.js
- Address following issues:
- https://github.com/wso2/product-apim/issues/2647
- https://github.com/wso2/product-apim/issues/2652
-  https://github.com/wso2/product-apim/issues/2649
- Needs to update the documentation with new screenshots
=> Fix typo issues

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml, components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.json
- fixes wso2/product-apim#2388
- This is to enable add api level throttling policy using Rest API
environments.]
-
=> Adding api level policy parameter for API object

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/CustomAPIIndexer.java
- Remove Store_View_Roles part from CustomAPIIndexer to avoid test failures as a temporary fix. We need to fix this. This will be tracked via https://github.com/wso2/product-apim/issues/2666
environments.]
-
=> Remove Store_View_Roles part from CustomAPIIndexer

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
- fixes https://github.com/wso2/carbon-apimgt/issues/5029
environments.]
-
=> fix https://github.com/wso2/carbon-apimgt/issues/5029

components/apimgt/org.wso2.carbon.apimgt.rest.api.util/pom.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/test/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtilTest.java
=> Fix for https://github.com/wso2/product-apim/issues/2676

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/CustomAPIIndexer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/indexing/indexer/CustomAPIIndexerTest.java
This PR fixes the below issues.
https://github.com/wso2/product-apim/issues/2666
https://github.com/wso2/product-apim/issues/2680
environments.]
=> Fix registry deadlock issue in CustomAPIIndexer

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
=> Fix for https://github.com/wso2/carbon-apimgt/issues/5035

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
This PR fixes below issue.
- When trying to delete any throttling policies (i.e: advanced throttling, application tiers, subscription tiers) using the API Manager Admin Portal UI and restart the server, the deleted policies are still existing.
- 
- Fix is preventing writing the default policies into the database, if Application level 'Unlimited' policy is already there is the database.
environments.]
-
=> Fixes https://github.com/wso2/product-apim/issues/2671

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/package.json, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/APIClient.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIClient.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/APIClient.js
- Remove patched version of swagger-js
- fix https://github.com/wso2/product-apim/issues/2675
- https://github.com/swagger-api/swagger-js/pull/1189
- https://github.com/swagger-api/swagger-js/pull/1236
- issue: https://github.com/swagger-api/swagger-js/issues/1186
- Credits to @tmkasun
=> Replace swagger-js patch with swagger-js 3.4.8

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/oidc/filter/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/oidc/logout/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/oidc/filter/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/oidc/logout/template.jag
fixes wso2/product-apim#2701
-
environments.]
-
=> OIDC bug fixes with KeyCloak IDP support

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/Header/EnvironmentMenu.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/Utils.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/EnvironmentMenu.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/EnvironmentMenu.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/Utils.js
- change the environment with a query parameter.
eg: `?environment=Production`
=> Change environment with "environment" query parameter

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/CertificateMgtDAO.java
=> Setting db auto commit before closing the connection

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImpl.java
Fixes below error which is logged while generating keys:
```
[2018-02-07 09:52:05,374] ERROR {org.wso2.carbon.apimgt.rest.api.store.impl.ApplicationsApiServiceImpl} - Error occurred while generating application keys for application: 92f39d3f-663d-4bfe-bb22-7491a9756a3c org.wso2.carbon.apimgt.core.exception.KeyManagementException: Error occurred while DCR application creation. Error:  Status Code: 500
at org.wso2.carbon.apimgt.core.impl.DefaultKeyManagerImpl.createApplication(Unknown Source)
at org.wso2.carbon.apimgt.core.impl.APIStoreImpl.generateApplicationKeys(APIStoreImpl.java:320)
at org.wso2.carbon.apimgt.rest.api.store.impl.ApplicationsApiServiceImpl.applicationsApplicationIdGenerateKeysPost(ApplicationsApiServiceImpl.java:151)
at …
```
=> Aviod sending empty redirect urls

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
- fixing the issue with Resource Add UI is not getting loaded in API edit page
environments.]
-
=> fix https://github.com/wso2/carbon-apimgt/issues/5044

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- Fix for https://github.com/wso2/product-apim/issues/2721
=> Fix Web socket apis cannot be viewed from store

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/usage/template.jag
This PR conatins fix for https://github.com/wso2/product-apim/issues/2250
=> Fix github2250

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/datepicker/js/daterangepicker.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/faultCount/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/faultCount/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/perAppAPICount/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/perAppAPICount/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/topUsers/js/stats.js
- fixes wso2/product-apim#2720
environments.]
-
=> Removing the time selection from store analytics UI

pom.xml
PR updates
- carbon-commons 4.5.4->4.6.16
- carbon-mediation 4.6.10->4.6.58
- synapse 2.1.7-wso2v10 -> 2.1.7-wso2v39
https://github.com/wso2/product-apim/issues/2732
environments.]
-
=> update carbon-mediation components #2732

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/api-availability/ajax/api-availability.jag
This PR contains fix for https://github.com/wso2/product-apim/issues/2574
=> Fix https://github.com/wso2/product-apim/issues/2574

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resource.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
- Main layout is change in order to host the material design concepts to the components.
- Styled components introduced to facilitate the theming with React Material Design. 
- Resource page updated with material design
This does not have external requirements 
All the other components must be applied with material design concepts.
=> Layout and resource view changes according to material design concepts 

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/EnvironmentOverview/EnvironmentPanel.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/EnvironmentOverview/EnvironmentPanelMessage.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NavBar.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/ConfirmDialog.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js
- Show all environments.
- Show 'User is not logged in' and 'feature is not enabled' on the environment overview page.
- Enable UI to handle SSO fix https://github.com/wso2/product-apim/issues/2735
No Apis
Feature is not enabled
Unauthenticated environment
=> Multi-Environment API Overview page with all environments

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js
Added the ability to go to different create api page without going to the multiple circle page.
This does not depend on any previous conditions
Different create API pages have to be converted to material design.
=> Adding new create api menu

pom.xml
Remove newline
-
environments.]
-
=> Remove newline

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/RestApiPublisherUtils.java
Include a correct error message when an error occurs at API creation. (https://github.com/wso2/product-apim/issues/2469)
=> Fix https://github.com/wso2/product-apim/issues/2469

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
This PR fixes throwing NPE when invoking a web socket API with Analytics enabled.
Refer https://github.com/wso2/product-apim/issues/2748
ASAP
environments.]
=> Fix throwing NPE when invoking a web socket API with Analytics enabled

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/pom.xml
This PR is to update the versions of parent module of the following micro API gateway components:
- org.wso2.carbon.apimgt.micro.gateway
- org.wso2.carbon.apimgt.micro.gateway.common
- org.wso2.carbon.apimgt.micro.gateway.tenant.initializer
N/A
N/A
=> Update version of parent modules in micro gateway components

pom.xml
Updating carbon.identity-inbound-auth-openid.version
-
environments.]
-
=> Updating carbon.identity-inbound-auth-openid.version

pom.xml
update carbon registry version
reference:  https://github.com/wso2/product-apim/issues/2689
environments.]
-
=> update carbon.registry version

pom.xml
Reverts wso2/carbon-apimgt#5077
=> Revert "update carbon.registry version"

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- soap to rest feature ui fix due to swagger api doc variable change 
environments.]
-
=> fix ui issue in soap to rest resource ui

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/AddNewMenu.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ImageGenerator.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/MoreMenu.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js
Added thumbnail generation logic to the publisher.
Update the create api menu
Add new menu to each thumbnail to go to each of it's sub pages
-
This PR is not depending on any other change
We need to let user select change generated image. 
Save the generated image to the db.
Show the generated image @ the store.
Expose the color combinations in the thumbnail background to the theme.
=> Added new thumbnail generation for publisher

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Documents.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/EnvironmentOverview/EnvironmentOverview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Permission.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Errors/ResourceNotFound.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ConfigManager.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/ProductionKeys.js
- fix refresh token with environments
- fix change environment with the query param
- display API not found 404 instead of not Resource found 404 when there are multiple environments.
when a single environment
when multi environments
- refactor message when switching the API to another version or environment
switching versions in same environment
switching environments
- fix https://github.com/wso2/product-apim/issues/2753
- fix https://github.com/wso2/product-apim/issues/2756
- fix https://github.com/wso2/product-apim/issues/2757
=> [C5] Environment feature fixes

components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml, components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/pom.xml, components/apimgt/org.wso2.carbon.apimgt.throttling.service/pom.xml, features/apimgt/org.wso2.carbon.apimgt.rest.api.admin.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml, pom.xml
Removing duplicate dependencies and fixing versions
-
environments.]
-
=> Removing duplicate dependencies and fixing versions

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReaderTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/download.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag
- Changes for generating WSDL with appropriate endpoints for multiple Gateway environments: https://github.com/wso2/product-apim/issues/2727
environments.]
-
=> Fix https://github.com/wso2/product-apim/issues/2727

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/webapp/WEB-INF/beans.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/webapp/WEB-INF/beans.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/webapp/WEB-INF/beans.xml, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/webapp/WEB-INF/beans.xml, components/apimgt/org.wso2.carbon.apimgt.throttling.service/src/main/webapp/WEB-INF/beans.xml, pom.xml
Existing spring and cxf versions are identified as vulnerable. As a result upgrade them 
- Upgrade spring-web from 4.1.6.RELEASE to 4.3.14.RELEASE
- Upgrade cxf from 3.1.7 to 3.2.2
environments.]
-
=> upgrade cxf and spring versions

pom.xml
Fixing plugin declaration in parent pom
-
environments.]
-
=> Fixing plugin declaration in parent pom

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/pom.xml
Removing multiple excludes
-
environments.]
-
=> Removing multiple excludes

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.rest.api/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.throttling.synchronizer/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/pom.xml, pom.xml
Fixing carbon.apimgt.version usage issue in inside pom
-
environments.]
-
=> Fixing carbon.apimgt.version usage issue in inside pom

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.rest.api/pom.xml, pom.xml
Removing carbon.apimgt.imp.pkg.version from dependency declaration
environments.]
-
=> Removing carbon.apimgt.imp.pkg.version from dependency declaration

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java, components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Tier.java, components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/TierPermission.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApisApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApplicationsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SubscriptionsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TagsApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TiersApi.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIInfoDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ScopeInfoDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/SubscriptionDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/TierDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/TierPermissionInfoDTO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/TiersApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/TierMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
syncing PR #5047 with latest changes
-
environments.]
-
=> syncing PR #5047 with latest changes

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java
Fixing https://github.com/wso2/product-apim/issues/2761
-
environments.]
-
=> Fixing https://github.com/wso2/product-apim/issues/2761

components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml, features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml, pom.xml
pdfbox version upgraded to 1.8.13 from 1.8.0.wso2v2.
The direct bundle has been referred instead of orbit.
environments.]
-
=> upgrading pdfbox version to fix vulnerability

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIConsumer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantOracle.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantPostgreSQL.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsH2MySQL.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/RestAPIStoreUtils.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-keys/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-list/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/menu/actions/template.jag
=>  Fix for https://github.com/wso2/product-apim/issues/2690

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/amConfig.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/test/resources/carbon-home/repository/conf/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/test/resources/carbon-home/repository/conf/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.rest.api/src/test/resources/carbon-home/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/test/resources/carbon-home/repository.conf/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/test/resources/carbon-home/amConfig.xml, features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
This excludes unsupported languages for SDK generation. (https://github.com/wso2/product-apim/issues/2292)
-
environments.]
-
=> Fix https://github.com/wso2/product-apim/issues/2292

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/DeleteApi.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NavBar.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/CustomTheme.js
Following UI changes are done.
-
Remove any color references from the implementation and get all colors from the palate.
-
=> Adding theme change feature and changing the api details menu in a user friendly manner 

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
=> Fixing #2788

pom.xml
- Fixes https://github.com/wso2/product-apim/issues/2613
=> Upgrade swagger code-gen to 2 2.3

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java
This PR modifies the assert statement to check the exception code in AuthenticatorServiceTestCase.
environments.]
=> Modify assert statement in AuthenticatorServiceTestCase

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json
Fixed https://github.com/wso2/product-apim/issues/2801
ASAP
=> Fixed https://github.com/wso2/product-apim/issues/2801

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/js/api-manage.js
- Fix for https://github.com/wso2/product-apim/issues/2184
- ASAP
=> Fix for https://github.com/wso2/product-apim/issues/2184

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleImage.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.js
Introduced new lifecycle interactive user experience 
-
environments.]
-
=> Adding new lifecycle user experiance

features/apimgt/org.wso2.carbon.apimgt.micro.gateway.feature/pom.xml, pom.xml
This PR adds micro-gateway configurator and status-checker to the micro-gw feature.
environments.]
=> Add micro-gateway configurator and status-checker to the micro-gw feature

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/alert/AlertTypesPublisher.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/AlertTypeDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeAlertTypesPublisherDTO.java
=> To send alert emails to admin user as well

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
https://github.com/wso2/product-apim/issues/2832
-
environments.]
-
=> Fixing https://github.com/wso2/product-apim/issues/2832

components/apimgt/org.wso2.carbon.apimgt.hostobjects/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/pom.xml, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
- Fixes some issues with the swagger url import error messages
=> Fixing swagger url import error messages

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.status.checker/pom.xml
- Fixing release build failure
ASAP
environments.]
-
=> Fixing release build failure

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
=> fixing https://github.com/wso2/product-apim/issues/2815

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
Fix for https://github.com/wso2/product-apim/issues/2832
In this case the application owner was getting returned conditionally based on if multi group sharing was enabled.
This has been fixed by ensuring that the application owner will be populated by the backend at all times regardless of multi group sharing being enabled.
environments.]
-
=>  Fix for wso2/product-apim#2832

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/left/template.jag
- Deprecate log analyzer . Disable it from the admin portal and add a property to enable it. By default it is set as false.  
https://github.com/wso2/product-apim/issues/2696
environments.]
-
=> Disable log analyzer from admin portal

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerTestCase.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/api/add.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/api/module.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-add/ajax/add.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/js/i18nResources.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/css/custom.css, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/edit/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/manage/template.jag
- Downloading Mediation Policies
Fix wso2/product-apim#2786
- Role-based restricting the Unlimited Subscription Tier. 
Fix wso2/product-apim#2790
environments.]
-
=> Add the capability of Downloading Mediation Policies and Role based restricting the Unlimited Tier 

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/test/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/internal/APIUsagePublisherComponentTest.java
- Add proper mocks for APIUsagePublisherComponentTest.java class
environments.]
-
=> Fix the micro-gateway test case failure.

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/api-doc/ajax/get.jag
Fixes swagger definition download issue in APIM publisher
=> Fixing swagger definition download issue

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/micro/gateway/configurator/ConfigConstants.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/micro/gateway/configurator/Configurator.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.status.checker/src/main/java/org/wso2/carbon/apimgt/micro/gateway/status/checker/StatusChecker.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.status.checker/src/test/java/org/wso2/carbon/apimgt/micro/gateway/status/checker/StatusCheckerTest.java, features/apimgt/org.wso2.carbon.apimgt.micro.gateway.feature/src/main/resources/bin/cloud-init.bat, features/apimgt/org.wso2.carbon.apimgt.micro.gateway.feature/src/main/resources/bin/cloud-init.sh
- Reduced the size of configurator jar (using class paths in scripts)
- Fixing wrong auth header in configurator and status checker
- Fixing password issue in sh script and improvements
- Windows batch script and improvements
ASAP
None
None
=> [Micro Gateway] Improvements to Configurator

components/apimgt/org.wso2.carbon.apimgt.core/pom.xml, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIGatewayPublisherImpl.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIManagerFactory.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIGatewayPublisherImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/KubernetesGatewayImplTestCase.java, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/resources/template/container_gateway_templates/container_deployment_template.yaml, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/resources/template/container_gateway_templates/container_ingress_template.yaml, components/apimgt/org.wso2.carbon.apimgt.core/src/test/resources/resources/template/container_gateway_templates/container_service_template.yaml
Improved the test cases for Private jet mode.
Fix https://github.com/wso2/product-apim/issues/2847
environments.]
-
=> Improving test cases for private jet mode

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/test/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/APIMgtUsageFileDataPublisherTest.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/test/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/FileDataPublisherTest.java
This PR contains the fix for api-usage-data.dat file has not been cleared after running test cases issue.
environments.]
=> Fix api-usage-data.dat file issue

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/test/resources/carbon-home/api-usage-data/api-usage-data.dat, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/api-doc/ajax/get.jag
=> Performance improvement

components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImplIT.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js
- For PRs #4331 & #4518, a few code changes were requested.
- This PR will fix those changes.
- N/A
- N/A
=> Fixes for requested code changes in PR #4518 & #4331

components/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension/src/main/java/org/wso2/carbon/apimgt/throttling/siddhi/extension/ThrottleStreamProcessor.java, pom.xml
- upgrade siddhi, analytics-common and carbon-event-processing versions
relates to https://github.com/wso2/product-apim/issues/2637
environments.]
-
=> Update siddhi and related components

components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/auth/SCIMServiceStubFactory.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImpl.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
=> commit GDPR related changes

pom.xml
- update carbon.deployment to the latest version
reference: https://github.com/wso2/product-apim/issues/2689 
environments.]
-
=> update carbon.deployment version

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/test/resources/carbon-home/api-usage-data/api-usage-data.dat
=> Remove changes in api-usage-data.dat file

components/apimgt/org.wso2.carbon.apimgt.core/pom.xml, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/TestUtil.java
=> fixing database test failure in ecs

build-scripts/JenkinsFile, components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/AnalyticsDAOImplIT.java
- Removed docker host from JenkinsFIle 
- Increased delay time for Analytics DAO integration tests
environments.]
-
=> JenkinsFile update and delay time increase in Analytics DAOIT 

.travis.yml
Fixing the travis build failure
-
ASAP
environments.]
-
=> Updating travis m2

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- Fix some error handling in REST API
=> Fix some error handling in REST API

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.status.checker/src/main/java/org/wso2/carbon/apimgt/micro/gateway/status/checker/internal/StatusCheckerServerStartListener.java
This PR changes the log statement by removing cloud specific wordings.
environments.]
=> Change log statement

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/alert/AlertTypesPublisher.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AlertTypesPublisher.java
- fixes wso2/analytics-apim#457 
-
environments.]
-
=> Fixing admin portal alert unsubscribing

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/CustomAPIIndexer.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProviderTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/RestApiPublisherUtils.java, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/user/login.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/user/login/ajax/login.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/layout/login/js/login.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/user/login/js/login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/user/login.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/user/login/ajax/login.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/layout/login/js/login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/user/login/js/login.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/user/login.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/user/login/ajax/login.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/login/js/login.js
This PR fixes the issue https://github.com/wso2/product-apim/issues/2845 and https://github.com/wso2/product-apim/issues/2844
-
ASAP
environments.]
-
=> fix product apim issues #2844 #2845

pom.xml
update synapse and carbon-mediation
environments.]
-
=> update synapse and carbon-mediation

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
Fix to retrieve the access token via KeyManager API instead of directly retrieving from the database.
-
environments.]
-
=> Fix to retrieve accesstoken via KeyManager API

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilSearchCriteriaTest.java
=> Fix search isuue when searching with tags for tags with spaces.

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/download.jag
=> Validate download URL specified

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/APISynchronizer.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/util/APIMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/APISynchronizerTest.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/tasks/APISynchronizationTaskTest.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/internal/ServiceDataHolder.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/internal/TenantInitializerServiceComponent.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/listener/ServerStartupListener.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/utils/TenantInitializationConstants.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/constants/Constants.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/listener/ServerStartupListenerTest.java
This PR removes time wait added prior to throttling and api synchronization hence resolving issue #1581 (Fix for mandatory wait condition required prior to tenant creation upon server startup.)
-
N/A
N/A
-
=> Fix for wait condition required prior to throttling and API synchronization in micro gateway

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jaggery_acs.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jagg/jaggery_acs.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jaggery_acs.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/header.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/sso/filter/template.jag
Fix https://github.com/wso2/product-apim/issues/2807
Fix https://github.com/wso2/product-apim/issues/2848
Fix https://github.com/wso2/product-apim/issues/2849
Fix https://github.com/wso2/product-apim/issues/2850
=> Fix sso enabled issues

pom.xml
upgrade kernel version to latest
environments.]
-
=> update carbon.kernel version to 4.4.24

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java
- Fixes: wso2/product-apim#2870
environments.]
-
=> Fixing API Type NULL issue when retrieving from Publisher REST API

pom.xml
Upgrading carbon.commons version 
-
environments.]
-
=> Upgrading carbon.commons version 

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- Improve get-application related APIs
=> Improve get application related APIs

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Fixing https://github.com/wso2/product-apim/issues/2948
environments.]
-
=> Fixing git issue - 2948

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/css/policy-pages-custom.css
Remove horizontal scroll bar appearing in policy pages
environments.]
-
=> Remove horizontal scroll bar appearing in policy pages

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jagg.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_en.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/login/template.jag
- Make 'Forgot Password' link visibility depend on it's configurations
=> Make 'Forgot Password' link visibility depend on it's configurations

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- Fixed application update bug
=> Fixed application update bug

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java, components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
This change is required to resolve the dependency conflicts when creating IS as key manager for IS version 5.5.0. Two versions of wsdl4j jar is getting packed into IS when features are installed, which causes the IS workflow feature failures. So we have to remove the additional jar getting included when features are installed. 
-
environments.]
-
=> Resolving IS as KM dependency conflicts

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
Fixing the api-manager.xml reading file location
=> Fix the api-manager.xml read

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- Added keys back to subscripbed APIs API as it's required for Swagger UI
=> Added keys back to subscripbed APIs API as it's required for Swagger UI

components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/internal/util/Util.java
- Improve the XML parsing capability in  `org.wso2.carbon.hostobjects.sso` Utility
environments.]
-
=> improve xml parsing for SSO

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-info/css/lifecycles.css
- Fix https://github.com/wso2/carbon-apimgt/issues/5198
=> Fix https://github.com/wso2/carbon-apimgt/issues/5198

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-edit/template.jag
- Fix Application Name valdation message issue
=> Fix Application Name valdation message issue

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
fix oracle related queries
environments.]
-
=> fix oracle related queries

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
=> Add JWT grant to store UI

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerCacheExtensionHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerCacheExtensionHandlerTest.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/ext/APIManagerCacheExtensionHandlerWrapper.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidatorTestCase.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
This will resolves #https://github.com/wso2/product-apim/issues/2931
-
environments.]
-
=> fixing Possible to use access token after revoke

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/api-doc/ajax/get.jag
- Fixing https://github.com/wso2/carbon-apimgt/issues/5193
=> Fix :Download Source button does not work on publisher

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java, components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java
Check if the user is null in the response returned by third party key manager
-
environments.]
-
=> Fix third party key manager fails when KM does not sent user in introspect call

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/pom.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/internal/TenantInitializerServiceComponent.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/tenant/initializer/listener/ServerStartupListener.java
This PR adds a missing dependency and a reference to tenant initialization component in micro API gateway. 
-
N/A
N/A
-
=> Add missing dependency and reference required for tenant initialization

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
Updating api.rxt in startup for Authorization Header.
This is to avoid rxtMigration and to do the api.rxt update in the startup with changes from 2.1.0 to 2.2.0 if not exist.
-
ASAP
environments.]
-
=> Updating api.rxt in startup for Authorization Header

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
This PR fix the issue when access control roles are updated using jaggery api, it does not update the role list correctly.
-
ASAP
environments.]
-
=> Fix publisher access control update roles issue

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisher.java
- fix https://github.com/wso2/product-apim/issues/2984
environments.]
-
=> fix for image display issue in external API store

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/jquery.certUi.js
- fix dynamic cert import issue for same host
environments.]
-
=> fix dynamic cert import issue for same host

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/menu/left/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/template.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/css/custom.css
Fixing issues 
https://github.com/wso2/product-apim/issues/2330
https://github.com/wso2/product-apim/issues/2289
https://github.com/wso2/product-apim/issues/2285
https://github.com/wso2/product-apim/issues/2276
-
environments.]
-
=> Fixing UI/UX issues 

pom.xml
- Upgrading identity framework version
ASAP
environments.]
-
=> Upgrading identity framework version

components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/internal/util/Util.java, pom.xml
inbound.auth.saml version upgrade and fixing SSO login
ASAP
environments.]
-
=> inbound.auth.saml version upgrade and fixing SSO login

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json
- add missing element which was needed to render delete task button for api approval workflow
environments.]
-
=> add missing element to locale_default.json

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/APISynchronizer.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/test/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/internal/APIUsagePublisherComponentTest.java
This PR fixes micro gateway related issues including https://github.com/wso2/product-apim/issues/2956
ASAP
environments.]
=> Fix microgateway related issues

pom.xml
=> Upgrading identity version

pom.xml
=> Upgrading the event processor and siddhi versions

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js
- Addition to the following issue
-- https://github.com/wso2/product-apim/issues/1997
- Include `.jsx` or `.js` files which are re-factored according to eslinting rules to following webpack loader include list of files to enforce style checking
```javascript
{
enforce: 'pre',
test: /\.(js|jsx)$/,
/* Add .js or .jsx files after refactoring */
include: [/.*\/Apis\/Details\/NavBar.jsx/, /.*\/Apis\/Details\/index.jsx/],
loader: 'eslint-loader',
options: {
failOnError: true,
quiet: true,
},
}
```
=> Add eslint validation to build process to enforce js standards

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
fix for https://github.com/wso2/product-apim/issues/3016
environments.]
-
=> fix token generation with scope in oralce issue #3016

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Forum.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiThumb.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Create/ApplicationCreate.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Listing/Listing.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Shared/DarkTheme.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Shared/LightTheme.js
Fixing issues https://github.com/wso2/product-apim/issues/3010 https://github.com/wso2/product-apim/issues/3005 https://github.com/wso2/product-apim/issues/3003 https://github.com/wso2/product-apim/issues/3002 https://github.com/wso2/product-apim/issues/2943
Following changes are done in order to fix the issues given above.
-
environments.]
-
=> Fixing UI issues

pom.xml, service-stubs/apimgt/org.wso2.carbon.apimgt.handlers.security.stub/pom.xml, service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/pom.xml, service-stubs/apimgt/org.wso2.carbon.apimgt.registry.cache.stub/pom.xml, service-stubs/apimgt/org.wso2.carbon.apimgt.statsupdate.stub/pom.xml, service-stubs/apimgt/org.wso2.carbon.apimgt.tier.cache.stub/pom.xml, service-stubs/oidc-authenticator/org.wso2.carbon.apimgt.authenticator.oidc.stub/pom.xml
version upgrade
-
environments.]
-
=> version upgrade

pom.xml
Upgrade identity.framework version
-
environments.]
-
=> Upgrade identity.framework version

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/CustomAPIIndexer.java
- In this PR, additional check is added before adding new properties introduced with publisher access contol to the custom API Indexer. By doing this redundant registry.put can be avoided, and we can make sure that particular code segment will execute during the 1st time of the migration of old APIs
N/A
N/A
-
=> Fix un-wanted to registry.put while creating the API 

pom.xml
Upgrade identity framework
-
environments.]
-
=> Upgrade identity framework

pom.xml
=> Upgrade multiteancy and identity.framework versions

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
Revert validation of creating apis with same name and different case, which was added to fix issue [1]
[1] - https://wso2.org/jira/browse/APIMANAGER-3226
-
environments.]
-
=> Revert validation of creating apis with same name and different case

pom.xml
upgrade inbound.oauth version
-
environments.]
-
=> upgrade inbound.oauth version

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/template.jag
Fixed by Moving down the labels and input elements down.
-
environments.]
-
=> Fix for the issue https://github.com/wso2/product-apim/issues/2476

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/policy-pages/cookie-policy.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/policy-pages/privacy-policy.jag, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/css/policy-pages-custom.css
This PR fixes some UI issues in the Cookie and Privacy Policy pages.
environments.]
-
=> Fix UI issues in Cookie and Privacy Policy pages

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
=> Fixing double submit Firefox issue

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/test/resources/carbon-home/repository/conf/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/test/resources/carbon-home/repository/conf/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/test/resources/carbon-home/repository/conf/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.rest.api/src/test/resources/carbon-home/api-manager.xml, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/test/resources/carbon-home/repository.conf/api-manager.xml, features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
- Removed unused configuration
=> Removed unused configuration

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag
Fixing the logic of enabling API Store walkthrough
=> Fixing APIWalkthrough enable logic in API Store

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java, components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/utils/APIMappingUtilTestCase.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag
- Fixing https://github.com/wso2/product-apim/issues/3013
- Unit tests added for addFileToDocumentation method in APIProviderImpl
environments.]
-
=> Fix for https://github.com/wso2/product-apim/issues/3013

components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/main/java/org/wso2/carbon/apimgt/micro/gateway/common/dao/OnPremiseGatewayDAO.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/main/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/dao/UploadedUsageFileInfoDAO.java, components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/main/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/util/MicroGatewayAPIUsageConstants.java
This will fix the Oracle and Postgresql related issues in micro-gateway usage publishing component.
=> [Micro-gateway] Fixing PostgreSQL and Oracle related issues

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- Application info page is not getting viewed if a token is generated by de-selecting client credential grant type
environments.]
-
=> fix application load issue when client-credential grant is not selected

features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml, features/apimgt/org.wso2.carbon.apimgt.micro.gateway.default.feature/src/main/resources/stream-definitions/org.wso2.analytics.apim.alertStakeholderInfo_1.0.1.json
=> Fixing alerts not sending emails

pom.xml
upgrade synapse and carbon.mediation version
-
environments.]
-
=> upgrade synapse and carbon.mediation version

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- Fixed https://github.com/wso2/product-apim/issues/2978
=> Fixed https://github.com/wso2/product-apim/issues/2978

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- Remove unwanted existence check of scope
=> Remove unwanted existence check of scope

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java, components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/SelfSignUpUtil.java, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/user/sign-up/block.jag
This PR changes signup configuration read when retrieving consent purposes.
environments.]
-
=> Change signup configuration read when retrieving consent purposes

pom.xml
Upgrade synapse and carbon-mediation
-
environments.]
-
=> Upgrade synapse, identity-framework, analytics-common

pom.xml
=> update auth-oauth version

pom.xml
=> Upgrading versions

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
-Fix https://github.com/wso2/product-apim/issues/2586
=> Fix https://github.com/wso2/product-apim/issues/2586

pom.xml
=> Upgrading auth version

features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/pom.xml
- Included GSON to org.wso2.carbon.apimgt.throttling.siddhi.extension.feature
environments.]
-
=> Included GSON to org.wso2.carbon.apimgt.throttling.siddhi.extension.feature

pom.xml
upgrade carbon.mediation version
-
environments.]
-
=> upgrade carbon.mediation version

pom.xml
update carbon.mediation and synapse versions
-
environments.]
-
=> update carbon.mediation and synapse versions

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
Remove scopes from a resources after deleting the scope
-
environments.]
-
=> [Publisher] Remove scopes from a resources after deleting the scope

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
=> fixing configuration issue

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/site.json, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/sso/filter/template.jag
This fixes admin app login failure, in SSO flow https://github.com/wso2/product-apim/issues/3077
=> Fixing SSO login failure in Admin App

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/ajax/api-info.jag
This PR fixes exception throwing in add ratings for an API in APIM Store.
ASAP
environments.]
=> Fix exception throwing in add ratings

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js
- Add API Description to the Overview page
=> Add API Description to Overview page

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Subscribe.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/index.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ImageGenerator.js, features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Create/ApplicationCreate.js
Fixing issues https://github.com/wso2/product-apim/issues/3087 and https://github.com/wso2/product-apim/issues/3101
=> Fixing issues https://github.com/wso2/product-apim/issues/3087 and https://github.com/wso2/product-apim/issues/3101

components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeExecutionTimePublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeFaultPublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeRequestPublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeResponsePublisherDTO.java, components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java
=> fixed https://github.com/wso2/product-apim/issues/3123

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
=> Fix application sharing feature issue for Oracle

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json, features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.jsx
- Add Tag add/remove support for APIs
=> Add Tag add/remove support for APIs

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.jsx
- Add tooltip and placeholder for tags
=> Add tooltip and placeholder for tags

components/apimgt/org.wso2.carbon.apimgt.core/pom.xml, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/internal/BrokerManager.java, components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/internal/BundleActivator.java, pom.xml
=> Broker upgrade
