wso2/carbon-apimgt

- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
- Previously this stub was packed to the pack through carbon.mediation.ui feature. But it imported UI features to the carbon console. This fix would remove that unnecessary features 
environments.]
-
> Bundle endpoint admin stub

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImpl.java
Fixing https://github.com/wso2/product-apim/issues/3147
-
ASAP
environments.]
-
> Fixing https://github.com/wso2/product-apim/issues/3147

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.jsx
- Add Transport update support
- Improve some other code
> Add Transport update support and improve some other code

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/EnvironmentConfigurations.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Login/Login.js
- pom.xml
upgrade apache.commons.lang3 to 3.5.0
upgrade snakey.yaml to 1.19.0
upgrade google.code.gson.version to 2.8.2
> Upgrade dependencies

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.jsx
- Make API description editable and fix other UI issues
> Make API description editable and fix other UI issues

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImpl.java
Fixing usage of old method for SAML response check
-
environments.]
-
> Fixing usage of old method for SAML response check

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImplTest.java
> Adding unit tests for #/3147

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/CertificateMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMgtDBUtil.java
* Correct the way Exceptions were handled in CertificateMgtDAO earlier.
environments.]
-
> Correct Exception handling in CertificateMgtDAO

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
https://github.com/wso2/product-apim/issues/3162
> Fix https://github.com/wso2/product-apim/issues/3162

- README.md
Updated the content in the Readme file by improving the grammar.
-
Immediately, so that the changes are captured in APIM 2.2.0.
N/A
-
> Improved grammatically.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NavBar.jsx
- This was due to MUI upgrade
- We have used deprecated menu component for building a dropdown menu
- [MUI Docs](https://material-ui-next.com/demos/menus/)
- Fix for https://github.com/wso2/product-apim/issues/3171
environments.]
-
> Fix for menu overlap issue in publisher overview page

- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/impl/RegistrationServiceImpl.java
Unable to use DCR rest API to create application for secondary domain tenant users.
(cherry picked from commit 273d7bf)
> Fix product-apim/3170

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats-list/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-geolocation-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledtime/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-user-agent-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/page/base/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/js/stats.js
> Fix doc urls

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/APIPolicies.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/ApplicationPolicies.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/BusinessPlans.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Create/CreateApplicationPolicy.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Create/CreateBusinessPlan.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Create/CreateCustomRulePolicy.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/CustomRules.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Details/CustomRule.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/Shared/CustomRuleDetails.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ThrottlingPolicies/index.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/api.js
Following new UI features are available in the admin app with this PR
- Add new custom rule policy
- List  custom rule policies
- Delete custom rule policy
- Update custom rule policy
- View custom rule policy
> [Admin] - CRUD Operations for custom rule policies

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketWSClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClientPool.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftKeyValidatorClientPool.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/ServiceReferenceHolder.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClientTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClientWrapper.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftAPIDataStoreTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftKeyValidatorClientPoolTest.java
resolves #https://github.com/wso2/product-apim/issues/3185
> resolves #3185

- gateway-modules/apim-ballerina-native-component/src/main/java/org/wso2/carbon/apimgt/ballerina/threatprotection/Analyze.java
Request is terminated when there are no policies defined for the API. The correct behavior is to let the request thru the gateway when there are no policies associated with that API.
-
environments.]
-
> Threatprotection: bugfix

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ApplicationNameWithInvalidCharactersException.java
* Correct License header year in carbon-apimgt/components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ApplicationNameWithInvalidCharactersException.java
environments.]
-
> Correct License Header Year

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
This PR adds functionality to allow duplicate scopes to different APIs through UI and the Swagger payload field.
environments.]
-
> Allow duplicate scopes to different APIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
>  Fix product-apim issue 2658:Consistancy in reading lifecycle state

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js
- Changes were done in cloud-enjoyhint-script-data.js in store web app.
Scenario 1
Above highlighted area was reduced to the API thumbnail so that it would avoid accidental walk-through stops.
Scenario 2
Here, the text content was changes to indicate to click on the API link itself. 
- N/A
- N/A
> UI store walkthrough fixes for wso2/product-apim/issues/3194

- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/APISynchronizer.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/APISynchronizerTest.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/tasks/APISynchronizationTaskTest.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/main/java/org/wso2/carbon/apimgt/micro/gateway/common/util/OnPremiseGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/main/java/org/wso2/carbon/apimgt/micro/gateway/common/util/TokenUtil.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/test/java/org/wso2/carbon/apimgt/micro/gateway/common/util/TokenUtilTest.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.status.checker/src/main/java/org/wso2/carbon/apimgt/micro/gateway/status/checker/StatusChecker.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.throttling.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/throttling/synchronizer/ThrottlingSynchronizer.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.throttling.synchronizer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/throttling/synchronizer/ThrottlingSynchronizerTest.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.throttling.synchronizer/src/test/java/org/wso2/carbon/apimgt/micro/gateway/throttling/synchronizer/tasks/ThrottlingSyncTaskTest.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/main/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/tasks/APIUsageFileUploadTask.java
This PR fixes the hostname verification issue in Microgateway 2.2.0.
ASAP
environments.]
> Fix hostname verification issue in Microgateway

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Scope.java
Fix https://github.com/wso2/product-apim/issues/3193
> Fix https://github.com/wso2/product-apim/issues/3193

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/listing/block.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/listing/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-listing-all/block.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag
- Fix for #3181
ASAP
environments.]
-
> Fix for #3181

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/js/application-add.js
Fixed https://github.com/wso2/product-apim/issues/3218
Fixed https://github.com/wso2/product-apim/issues/3208
-
environments.]
-
> Fixing git issue 3208 and 3218

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/mappings/ApplicationKeyMappingUtil.java
Set callback URL to applicationkeysDTO
> Set callback URL to applicationkeysDTO

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/SelfSignUpUtil.java
This PR fixes "hostname in certificate didn't match" issue when loading signup page in store[1].
[1] https://github.com/wso2/product-apim/issues/3214
environments.]
-
> Fix product-apim issue #3214

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js
> Fix ui issue in API store walk through at api invoke stage.

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImplTestCase.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js
> Fix Publisher Login issue

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Create/ApplicationCreate.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Shared/Alert.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Shared/Message.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/webpack.config.js
> Add alert to store app

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/SubscriptionsApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
This Resolves https://github.com/wso2/product-apim/issues/3239
> Fix API Couldn't delete after creating new version of the API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIKeyMgtUtil.java
- Fixes for https://github.com/wso2/product-apim/issues/3243
- Setting the status of the API via "overview_status" if getLifecycleState() is null
- N/A
- N/A
> Fixing wso2/product-apim/issues/3243

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/Ballerina.toml
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.constants/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.dto/introspect.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/oauthn_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/oauthz_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.handlers/oauthn_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.handlers/oauthz_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.listeners/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.utils/utils.bal
- This contains oauth authentication and authorization filters for ballerina based micro gateway
> Ballerina based gateway initial commit

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.constants/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/oauthn_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/oauthz_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.handlers/oauthn_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.handlers/oauthz_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.listeners/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.utils/utils.bal
> Fix compilation failures to match new ballerian distribution

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/SubscriptionTableData.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/Subscriptions.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/Subscription.js
Fix https://github.com/wso2/product-apim/issues/3111
> Implement subscription UI

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.dto/api_key_validation.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/oauthn_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.handlers/oauthn_handler.bal
This PR contains sample key validation soap service call
> Add key validation service call

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
Used solr to retrieve the API artifacts to speed up the process
-
environments.]
-
> Fixing APIs with business owner details are slow to load in the stor

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.caching/api_gateway_cache.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.dto/api_key_validation_req.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/oauthn_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.handlers/oauthn_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.listeners/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.sample.services/pizza_shack_api.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.utils/utils.bal
- Added improvements to authentication handler based on the key validation layer
- Introduce cache layer for key validation object
> Ballerna gateway auth filter improvements

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/jquery.certUi.js
- This PR address the following issue https://github.com/wso2/product-apim/issues/3248
- Polyfill added for `Array.from` in https://github.com/wso2/product-apim/issues/2830 is not in use
> Fix for #3248, Remove IE11 incompatible methods, Improve loadbalanced endpoint certificate UI

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.caching/api_gateway_cache.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.constants/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.handlers/oauthn_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.utils/utils.bal
- Add local cache to maintain invalid tokens
> Gateway auth handler improvements

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/subscription/subscribed-apis/template.jag
This fix the issue : https://github.com/wso2/product-apim/issues/3257
-
environments.]
-
> product-apim-issues-3257 - Fix url redirection issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Check whether the user has access to the application before processing subscription add/remove.
> Add application validation

- pom.xml
> Upgrading synapase, commons and mediation versions

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.constants/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.dto/global_throttle_stream.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.dto/request_stream.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/oauthn_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.filters/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.utils/throttle_util.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.utils/utils.bal
Throttling initial implementation
-
environments.]
-
> Add initial Throttling Filter implementation

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
- Add inline style to Resources table to fix table cell expand in chrome browser.
environments.]
-
> Fix api resource table cell width change in Chrome.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/.eslintrc.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointsSelector.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/EnvironmentOverview/EnvironmentPanel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Create/EndpointForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Create/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Discover/ButtonCell.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Endpoints/Listing/EndpointTableRows.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/LoginForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Message.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Endpoint.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
- Repalced the deprecated [componentWillMount](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount) method with componentDidMount as recommended by react documentation
- Fix for https://github.com/wso2/product-apim/issues/3238
environments.]
-
> [Publisher] Refactor react lifecycle methods and global endpoints UI

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/event_publisher.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_util.bal
- features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventreceivers/throttleEventReceiver.xml
Added HTTP throttle event publisher
Added HTTP event receiver configs
-
environments.]
-
> Added throttle event publisher

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/utils.bal
> Add Throttle Related changes

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/auth_context.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/oauthn_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/oauthn_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_util.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/utils.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/java/org/ballerina/gateway/GatewayAnnotationPlugin.java
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/java/org/ballerina/gateway/models/TierModel.java
- Add authentication context to filter context attribute
- Change gateway package as **wso2/gateway** from **ballerina/gateway**
- Change tier annotation as follows
`@gateway:RateLimit{policy : "Gold"}`
ASAP
> Add authentication context

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/template.jag
- Avoid double encoding API name, version and provider values.
- 
- N/A
> Fixing wso2/product-apim/issues/3269

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_endpoint.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/oauthn_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/oauthn_handler.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_util.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/utils.bal
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- pom.xml
Upgrade carbon.mediation,carbon.databridge,wso2.synapse version
Implement Block condition Retrieval on startup in micro gateway
-
environments.]
-
> Implement Block Condition Retrieval in microgateway

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/event_publisher.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/global_throttle_stream.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/request_stream.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/sample_gold_policy.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_util.bal
Added throttle policy to ballerina
-
environments.]
-
> Added throttle policy to ballerina

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerTestCase.java
- fixed https://github.com/wso2/product-apim/issues/3273 
environments.]
-
> fixed https://github.com/wso2/product-apim/issues/3273

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/java/org/ballerina/gateway/siddhi/extension/EmitOnStateChange.java
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/java/org/ballerina/gateway/siddhi/extension/ThrottleStreamProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/test/java/org/ballerina/gateway/siddhi/extension/ThrottleTimeBatchWindowTestCase.java
- pom.xml
- Added ballerina siddhi extension for throttling
environments.]
-
> Added ballerina siddhi extension

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/sample_gold_policy.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_util.bal
- Fixed multiple slf4j bind issue
environments.]
-
> Fixed multiple slf4j bind issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
> https://github.com/wso2/product-apim/issues/3277

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/resources/ballerina.conf
> Update to work with latest ballerina distribution

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/EligibilityStreamDTO.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/ThrottleConf.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/gateway_conf.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/resources/ballerina.conf
- Added configs for thorttling
- Added header publishing
- Added query paras publishing
- Added remote address publishing
environments.]
-
> Added throttle related fixes

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/event_publisher.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_dtos.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/throttle_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/resources/ballerina.conf
- Added jwt claim publishing
- Added config to enable to publish to global TM
environments.]
-
> Added jwt claim publishing

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/clients/Util.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
- components/oidc-authenticator/org.wso2.carbon.apimgt.authenticator.oidc/pom.xml
- components/oidc-authenticator/org.wso2.carbon.apimgt.authenticator.oidc/src/main/java/org/wso2/carbon/apimgt/authenticator/oidc/OIDCAuthenticator.java
- components/oidc-authenticator/org.wso2.carbon.apimgt.authenticator.oidc/src/main/java/org/wso2/carbon/apimgt/authenticator/oidc/util/Util.java
- components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/pom.xml
- components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/src/main/java/org/wso2/carbon/apimgt/hostobjects/oidc/OIDCRelyingPartyObject.java
- components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/src/main/java/org/wso2/carbon/apimgt/hostobjects/oidc/internal/Util.java
- features/oidc-authenticator/org.wso2.carbon.apimgt.authenticator.oidc.server.feature/pom.xml
- features/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc.feature/pom.xml
- pom.xml
- Update identity component versions
- Update nimbus orbit bundle version
- Update andes and carbon business messaging version
ASAP
- Update product-apim with the latest version once this is released.
> Update component versions

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/KeyManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/clients/OAuthAdminClient.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/factory/FakeKeyManagerForTest.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberServiceTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/impl/RegistrationServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-keys/template.jag
Hash access token, refresh token, client secret and authorization code before store it in the database.
environments.]
-
> Add hashing support for oauth keys

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/ApplicationUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/ApplicationUtilsTestCase.java
- Fix failing tests
- Remove unused methos
> Fix failing tests

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/DigestAuthMediator.java
- Fixes the issue https://github.com/wso2/product-apim/issues/3290
This PR fixes the issue where Digest Authentication doesn't work when the realm contains the word "Digest".
environments.]
-
> Fixes wso2/product-apim#3290

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/css/custom.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-keys/template.jag
Fixes for wso2/product-apim#3293 and wso2/product-apim#3292
> Fixing application scopes and mediation policy dropdown menu UI issues

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
This PR checks the existence of gatewayLabels property before adding Labels.
> Checking gatewayLabels property before adding Labels.

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/test/resources/carbon-home/repository/conf/on-premise-gateway.properties
- features/categories/gateway-manager/pom.xml
- features/categories/gateway-worker/pom.xml
- features/categories/publisher/pom.xml
- features/categories/store/pom.xml
- pom.xml
>  Upgrade dependencies

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
- Fixes https://github.com/wso2/product-apim/issues/3296
> Adding swagger definition validations in swagger editor

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/APIMJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIMTokenIssuerUtil.java
This improves the JWT response and adds the subscribed apis to it
> Improved JWT generation.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/manager/manager.jag
- This PR fix the issue : https://github.com/wso2/product-apim/issues/3288 
ASAP
> product-apim #3288 - Fix sdk zip extract issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImplTest.java
> adding empty cert unit test

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
This PR checks the newly added configuration is specified in api-manager.xml and uses it when displaying the cURL command in API Store application page.
Fix for : https://github.com/wso2/product-apim/issues/3307
> Fix product-apim/issues/3307

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationServiceTest.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/thrift/APIKeyValidationServiceImplTest.java
- pom.xml
1. Dependency version upgrade
2. Unit test improvements.
> Dependency version upgrade and unit test improvements.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Fix wrong string comparison which was leading to a test failure
> Fixing string comparison in updateAPI

- pom.xml
Upgrade carbon mediation httpclient version
> Upgrade carbon mediation httpclient version

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIConsumer.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/add.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/remove.jag
Fixing https://github.com/wso2/product-apim/issues/3352
-
environments.]
-
> Fixing https://github.com/wso2/product-apim/issues/3352

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
Backward compatibility for older import/export tool
> Backward compatibility fix for import export tool

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/FileBasedApplicationImportExportManager.java
Validate zip achives before processing upload requests in the following scenarios.
* Tenant theme uploading
* Application import
> Validate files in zip archives

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/throttling/publisher/ThrottleDataPublisher.java
- Fix https://github.com/wso2/product-apim/issues/2630
> Fix https://github.com/wso2/product-apim/issues/2630

- pom.xml
-Upgrading fasterxml.jackson.version to 2.9.5
> Upgrading fasterxml.jackson.version to 2.9.5

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
Fix https://github.com/wso2/product-apim/issues/2496
> Fix API search by sub context

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/user/login.jag
> Add login failure audit log

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/template.jag
Encoding UUID
-
environments.]
-
> Encoding UUID

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.json
> Fixing #2162

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> Fix for #3379

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/add.jag
Fixing  group ID issue
-
environments.]
-
> Fixing  group ID issue

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-edit/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag
This PR contains fixes for some mis-alignment of labels in API Store. (In add, view and edit application pages)
environments.]
-
> Add formatting changes in UI of API Store

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- Adding validations for file names in tenant theme archive, uploaded from the admin app
> Adding validations for tenant theme archive files

- pom.xml
upgrading carbon.registry version
-
environments.]
-
> upgrading carbon.registry version

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/test/resources/carbon-home/repository/conf/on-premise-gateway.properties
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIDetailedDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SubscriptionsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TagsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/TiersApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/store-api.json
- Adding per-api authorization header for publisher rest api
- Adding per-api authorization header for store rest api
- Removing endpoint password exposure from Publisher REST API
environments.]
-
> Adding per-api authorization header for Publisher/Store REST APIs, Removing EP password

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/css/custom.css
- https://github.com/wso2/product-apim/issues/3393: Store UI breaks when listing 100+ tags
Next v2.x wum update
> Store UI breaks when listing 100+ tags

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-list/template.jag
> Improve label UI

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats-list/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-geolocation-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledtime/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-user-agent-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/js/stats.js
Fix for : https://github.com/wso2/product-apim/issues/3389
> Update display URLs

- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.rest.api/src/main/java/org/wso2/carbon/apimgt/micro/gateway/rest/api/utils/UploadServiceConstants.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.rest.api/src/test/java/org/wso2/carbon/apimgt/micro/gateway/rest/api/MicroGatewayRestAPITest.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/main/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/UploadedUsagePublisher.java
- Change GZIP into ZIP formats in uploaded file publisher
> Modifying uploaded usage publisher to support ZIP instead of GZIP.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
This PR includes fixes to Blocked the API invokation using JTI if the token type is JWT.
> Blocked the API invokation using JTI if the token type is JWT.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
> Removing additional Authorization header addition to CORS properties

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
Fix for https://github.com/wso2/product-apim/issues/3404
> Adding resource HTTP method validations in swagger editor

- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/models/APIBusinessInformation.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/models/APICorsConfiguration.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/models/APIDetailed.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/models/APIEndpointSecurity.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/models/APIMaxTps.html
Publisher Rest API doc changes introduced by gateway label feature.
environments.]
-
> Add Publisher Rest API Doc Changes

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/README.md
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/README.md
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/libs/bootstrap-rating/README.md
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/bootstrap-rating/README.md
-
Reviewed the 6.x/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/README.md
Immediately.
This readme (6.x/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/README.md) needs to be updated further as it has not been updated for APIM 2.2.0 or APIM 2.5.0 for more information see https://github.com/wso2/product-apim/issues/3408
-
> Updated Readme files

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/add.jag
Adding groupId check to fix the regression issue occurred in application group sharing feature
-
environments.]
-
> Adding grouId check to fix the regression issue occured

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/README.md
Updated based on v0.13 - APIM 2.5.0.
-
environments.]
-
> Updated Readme

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/Environment.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag
fixes wso2/product-apim#3422
This PR introduces a config in api-manager.xml to config the websocket endpoint of the gateway.
**GatewayWSEndpoint**
If the server is started with a port offset. The websocket port needs to be changed manually.
> Introducing websocket gateway URL config

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
Fix null pointer if config is not specified
> Fixing null pointer if WSEndpoint is not configured in api-manager.xml

- pom.xml
Upgrade registry version
-
environments.]
-
> Upgrade registry version

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java
Bloked sending token through REST api for applicartion get REST API.
> Bloked sending token through REST api for applicartion get REST API.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/js/edit.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/template.jag
> Fix host required UI

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
> Show warning when micro gateway label selection

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/js/i18nResources.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/js/api-info.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/js/application-add.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-edit/js/application-edit.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-edit/template.jag
- We should give a info message when jwt app type is used for an new subscription
> Add info message when jwt type app is used to subscribe to an api

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/left/template.jag
> Change microgateway icon

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-edit/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag
- Adding microgateway label support in API console
- Fixing public API's detail tab load failure in anonymous mode
> Adding microgateway label support in API console

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/js/edit.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-list/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/actions/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag
> Changing occurrences of Microgateway Label as Microgateway

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/WSDL11SOAPOperationExtractor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReaderTest.java
> Fixing external xsd issue when downloading WSDL from Store

- features/apimgt/org.wso2.carbon.apimgt.keymanager.feature/pom.xml
Fix for https://github.com/wso2/carbon-apimgt/issues/5493
> FIx for #5493. - JWT Token generation fails in Distributed setup

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/js/i18nResources.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/custom-validation/custom-validation.js
> Fix error message

- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/test/resources/carbon-home/repository/conf/api-manager.xml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
> Remove unused configuration

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/TiersApiServiceImpl.java
The permission update changes do not reflect when Advanced Throttling is enabled. This is to fix it.
environments.]
-
> Fixes #3441: Update tier permissions endpoint fix for advanced throttling

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/SequenceGenerator.java
This will fix the issue on changing the resource method from swagger editor when creating an api using soap to rest option.
environments.]
-
> fix swagger resource method edit issue in soap to rest conversion

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
This PR adds details on API search by gateway labels.
environments.]
-
> Modify API docs with label search details

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/common/common.js
Fix label attach issue in IE 11
> Fix label attach issue in IE 11

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml
Add label information to admin.yaml for documentation.
> Add label information to yaml

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/internal/HostObjectComponent.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/internal/ServiceReferenceHolder.java
> Fix for #3464

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
This PR fixes https://github.com/wso2/product-apim/issues/3475.
environments.]
-
> Fix https://github.com/wso2/product-apim/issues/3475

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
> fix for https://github.com/wso2/product-apim/issues/3476

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
https://github.com/wso2/product-apim/issues/2176
-
> fix for https://github.com/wso2/product-apim/issues/2176

- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/APISynchronizer.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/main/java/org/wso2/carbon/apimgt/micro/gateway/common/util/MicroGatewayCommonUtil.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/main/java/org/wso2/carbon/apimgt/micro/gateway/common/util/TokenUtil.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/micro/gateway/configurator/Configurator.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.throttling.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/throttling/synchronizer/ThrottlingSynchronizer.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.usage.publisher/src/main/java/org/wso2/carbon/apimgt/micro/gateway/usage/publisher/tasks/APIUsageFileUploadTask.java
This PR fixes the issues mentioned in https://github.com/wso2/product-apim/issues/3487.
environments.]
-
> Fixing https://github.com/wso2/product-apim/issues/3487

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
> Fix for https://github.com/wso2/product-apim/issues/3488

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/test/resources/carbon-home/repository/conf/on-premise-gateway.properties
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag
This fix the issue of allowing anonymous users to browse the swagger definition of an API
https://github.com/wso2/product-apim/issues/3480
> Adding API's permission to API's swagger resource

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtilTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/utils/APIMappingUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/store-api.json
Fix for https://github.com/wso2/product-apim/issues/3407
environments.]
-
> Modify Store REST and Jaggery APIs to get list of environments of an API configured with non empty URLs.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiTableRow.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/StarRating.js
Fix for https://github.com/wso2/product-apim/issues/3086
Add sorting functionality to api list table.
Add user rating column to api list table.
Add collapsible api detail row to each row of api list table.-
environments.]
-
> Fix for https://github.com/wso2/product-apim/issues/3086

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProviderTest.java
> Fix for https://github.com/wso2/carbon-apimgt/issues/5369

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiThumb.js
This PR contains changes to add rating info in API thumbnail. 
It fixes the issue - [Rating missing from the API thumbnails #3085](https://github.com/wso2/product-apim/issues/3085).
environments.]
-
> Add Rating in API thumbnail

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/APIMTokenIssuer.java
This pR include the fix for https://github.com/wso2/product-apim/issues/3510
> Fix for - Token request call generates a new token even the previous token is still valid.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractKeyManager.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationKeyGenerateRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js
This PR contains changes to fix issue - [Ability to create an application with provided client id / client secret](https://github.com/wso2/carbon-apimgt/issues/5521). 
environments.]
-
> Fix for https://github.com/wso2/carbon-apimgt/issues/5521

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js
This PR contains changes for fixing issues in the population of API Latency statistics. It fixes the issue -  [API Latency Statistics not working properly #3492](https://github.com/wso2/product-apim/issues/3492)
environments.]
-
> Add fix for issue#3492

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-add/js/application-add.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-edit/js/application-edit.js
Please note that white space character validation is still existing in APIM and it will not get affected by this fix.
This fix will modify Application name validation in Application creation/edit to be matched with Service provider Creation.
-
environments.]
-
> Fixing https://github.com/wso2/product-apim/issues/3515

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/JwtTokenInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/APIMTokenIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/APIMJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIMTokenIssuerUtil.java
This PR adds the consumerKey, applicationOwner and sets the correct value for sub field.
> Adding required fields for JWT token

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
Expanding the restriction of  application name with invalid characters for REST API
-
environments.]
-
> Expanding the restriction of  application name with invalid characters for REST API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
Adding unit test for add Application with invalid character
-
environments.]
-
> Adding unit test for add Application with invalid character

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
> Fix for https://github.com/wso2/carbon-apimgt/issues/5535

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
Reverting unit test for invalid characters
-
environments.]
-
> Reverting unit test for invalid characters

- components/apimgt/pom.xml
- features/apimgt/pom.xml
Comment out the microgateway component and features from the build.
> Comment microgateway modules from the build

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
Fixing https://github.com/wso2/product-apim/issues/3528
-
ASAP
environments.]
-
> Adding query parameter support for websocket API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
When query params are not available in the url for websocket endpoint, the query param value get undefined.
To avoid that this fix included a condition check and set the queryprams to the message context to construct an accurate url
-
ASAP
environments.]
-
> Adding check for undefined result of query param

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
Removing log mediator from web socket sequence
-
ASAP
environments.]
-
> Removing redundant  log mediator from websocket sequence

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationService.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationServiceTest.java
- Generate the jwt token in WS key validation.
- Attach the jwt token as a custom header.
- Add test cases.
Please merge the PR after merging wso2/carbon-mediation/pull/1068
environments.]
-
> Add jwt header to websocket handshake.

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
> Fix missing dependency issue.

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java
> Fix for https://github.com/wso2/product-apim/issues/3538

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeRequestResponseStreamPublisherDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java
> Add missing parameters

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/js/stats.js
Added a checkbox to deselect and select all APIs shown in the table and clear/show API's in the graph accordingly
-
environments.]
-
> Feature Request- "Select All" checkbox in Publisher Analytics UI table

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeFaultPublisherDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java
- Re-ordered the stream definition parameters to suit the new stream
- update version parameter
> Re-order stream and update version parameter

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtUsageHandler.java
Add missing clientIp and useragent values
> Add missing clientIp and useragent values

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/tiers/tiers.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/block.jag
This PR contains changes for fixing issue - [Error when retrieving denied tiers for certain tenant](https://github.com/wso2/product-apim/issues/3534)
> Add fix for isse #3534

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/enjoyhint-3.1.0/js/cloud-enjoyhint-script-data.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/template.jag
Fix for the issue https://github.com/wso2/product-apim/issues/3563
> Fix for https://github.com/wso2/product-apim/issues/3563

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
This Fix the wrong error message come from API creation
> fixing minor issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
Fix array index out of bounds issue in label search. Addresses review comments in https://github.com/wso2/carbon-apimgt/pull/5405
> Fix possible array index out of bounds issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/DefaultClaimsRetriever.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
This PR fixes https://github.com/wso2/product-apim/issues/3558.
Currently we only have claim cache expiry config.
Setting that to 0 does not disable cache as the kernel uses a scheduled task to cleanup cache.
So we introduce a config like this, with this PR
<EnableJWTClaimCache>true</EnableJWTClaimCache>
-
environments.]
-
> Make JWT claim cache enable/disable configurable - fix product-apim#3558

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jagg.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-info/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/view/template.jag
> fix for Persistent XSS in WSO2 Api Manager Store via Publisher

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/dao/test/APIMgtDAOTest.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberServiceTest.java
- components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/SAMLSSORelyingPartyObject.java
- components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/internal/SSOConstants.java
- service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/src/main/resources/APIKeyMgtSubscriberService.wsdl
1. https://github.com/wso2/carbon-apimgt/issues/5571
2. https://github.com/wso2/carbon-apimgt/issues/5573
environments.]
-
> Fix #5571 and #5573

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/API.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/Application.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/ApplicationKeyGenerateRequest.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/ApplicationKeyReGenerateRequest.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/models/ApplicationKeyReGenerateResponse.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/api-docs/docs/operations/ApplicationIndividual.html
- pom.xml
This PR is adding documentation changes that reflects the changes made to Store REST API resource in [Fix for https://github.com/wso2/carbon-apimgt/issues/5521](https://github.com/wso2/carbon-apimgt/pull/5530)
> Add docs changes for the changes made in REST API resource in #5530

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/ApiCreate.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI.js
This is the initial commit to provide i18n support for publisher web app.
We need to find all the places and include this support.
ASAP
- We need to find all the places where we need to add i18n texts in the current admin,store and publisher web apps.
> Fix product-apim 1989: Add i18n support for publisher app

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js
- Fix eslint rule violations
environments.]
-
> Fix regression issues in methods rename in Utils.js

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
> Fix not reading the billing plan for subscription policies

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/stats/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/api-availability/ajax/api-availability.jag
- Implement "Availability of APIs" ui to work with SP
- add temporary fix for alert table sorting
> Add Availability of APIs UI to work with SP

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
> Fix not rendering  elements of parameters of API designer resource

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/stats/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/api-availability/ajax/api-availability.jag
> Fix api availability alert

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/reportgen/util/ReportGenUtil.java
Update siddhi app name to the latest
> Update siddhi app name to the latest

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js
This PR fixes https://github.com/wso2/product-apim/issues/3591
ASAP
environments.]
> Fix mediation sequence upload issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/factories/BlacklistApiServiceFactory.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/factories/LabelsApiServiceFactory.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/factories/PoliciesApiServiceFactory.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/factories/ThreatProtectionPoliciesApiServiceFactory.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/factories/WorkflowsApiServiceFactory.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/BlacklistApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/LabelsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/PoliciesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ThreatProtectionPoliciesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/LabelsApiServiceImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ThreatProtectionPoliciesApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/impl/BlacklistApiServiceImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/throttling/impl/PoliciesApiServiceImplTest.java
> Removed powermock dependency from rest.api.admin

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClient.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClientConstants.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRdbmsClientImpl.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
This PR adds stat data display functionality to Publisher and Store stats with new schema.
environments.]
-
> Add stat data display functionality to Publisher and Store

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
This PR contains fix for solving issue - [Error on searching for APIs when Debug logs enabled](https://github.com/wso2/product-apim/issues/3587)
> Add fix for #3587

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/JsonSchemaValidator.java
> fixed wso2/product-apim#3569

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java
> Fix for https://github.com/wso2/product-apim/issues/3624

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java
Update throttle-out event stream param
> Update throttle-out event stream param

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
- Used the same gateway admin client with same session for api deploying, sequence deploying and un deploying operations
ASAP
> Use same gateway admin client for api and sequnce updates

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/dto/CertificateInformationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/ResponseCode.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/CertificateMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/dao/test/CertificateMgtDaoTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/CertificateMgtUtilTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/CertificatesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/CertificatesApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/CertMetadataDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/CertificateInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/CertificateValidityDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/CertificatesDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/factories/CertificatesApiServiceFactory.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/CertificatesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/CertificateRestApiUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/jquery.certUi.js
Add the Certificate Management Rest API.
Fixes wso2/product-apim/issues/3504
environments.]
-
> REST API support for Dynamic Certificate Management.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
This PR is to add a Popup when saving a Prototyped API
ASAP
environments.]
> Add Popup when saving a Prototyped API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
This PR fixes https://github.com/wso2/product-apim/issues/3517
ASAP
environments.]
> Fix Prototype API issues

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/stats/stats.jag
Add pagination for alert history table
> Add pagination for alert history table

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClientConstants.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-resource-path/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-resource-path/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-user-agent-usage/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/application-throttledcounts/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/application-throttledcounts/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/faultCount/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/faultCount/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/perAppAPICount/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/perAppAPICount/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/topUsers/js/stats.js
This PR re-enables hour granularity in stat graphs in Publisher and Store.
environments.]
-
> Add Hours granularity support to the relevant graphs in publisher and store

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js
Adding i18n support for Store app.
This is based on the PR - https://github.com/wso2/carbon-apimgt/pull/5583/files
Fixing https://github.com/wso2/product-apim/issues/3161
-
environments.]
-
> Adding i18n support for Store app

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/ThrottlePublisherDTO.java
Add hostname to throttle out event stream
> Add hostname to throttle out event stream

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/page/base/template.jag
Update store footer for 2.6.0
For 2.6.0-beta
> Update store footer for 2.6.0

- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
Reverts wso2/carbon-apimgt#5602
> Revert "Fixing #3622"

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Add logs to print the query done to retrieve data from sp
> Add debug log to capture sp request payload

- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
Reverts wso2/carbon-apimgt#5634 . Adding the fix back
> Revert "Revert "Fixing #3622""

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
> Fix for https://github.com/wso2/product-apim/issues/3638

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-last-access-times/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-resource-path/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/application-throttledcounts/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/faultCount/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/perAppAPICount/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/topUsers/js/stats.js
This PR fixes https://github.com/wso2/product-apim/issues/3652
environments.]
-
> Fix https://github.com/wso2/product-apim/issues/3652

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR fixes Fix https://github.com/wso2/product-apim/issues/3651
environments.]
-
> Fix https://github.com/wso2/product-apim/issues/3651

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
This fixes the issue in https://github.com/wso2/product-apim/issues/3663
> Fixing error while updating OAS3 definitions in swagger editor

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
Fixing : https://github.com/wso2/product-apim/issues/2763
> Fixing product-apim/issues/2763

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/EndPointDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/EndPoint_endpointConfigDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/EndPoint_endpointConfig_circuitBreakerDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/EndPoint_endpointConfig_circuitBreaker_rollingWindowDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/EndpointConfigDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/EndpointConfig_attributesDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/common/SampleTestObjectCreator.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/AdvanceEndpointDetail.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointDetail.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- Re design endpoint page
- Add endpoint update capabilty 
ASAP
- Support global endpoints
> Add endpoint editing capability

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerAnalyticsConfiguration.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/reports.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/left/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/reports/download.jag
Enable report gen for super tenant users. additionally fix page title and add date to pdf file name
> Enable report gen for super tenant users

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
Fix for https://github.com/wso2/product-apim/issues/2763 is provided along with the PR
https://github.com/wso2/carbon-apimgt/pull/5649
> Fix possible NPE

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/api-doc/ajax/get.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
Fixes the issue reported in https://github.com/wso2/product-apim/issues/3668
> Fixing role restricted API's swagger definition download issue

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR fixes the issue where the Stats UI hangs when the analytics server is not up and running in the situation where analytics is enabled.
environments.]
-
> Fix getFirstAccessTime method

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/util/SequenceUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/soaptorest/SequenceUtilsTestCase.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-info/block.jag
Fix 
[1] - https://github.com/wso2/product-apim/issues/3686
[2] - https://github.com/wso2/product-apim/issues/3687
[3] - https://github.com/wso2/product-apim/issues/3688
> Fixing some minor issues

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR fixes the issue where data is not shown in Hour button stats in analytics graphs. No documentation changes will be there.
environments.]
-
> Fix issue with hour button on stats

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR fixes the issue where the throttling stats are not shown sometimes as we pick the _SECONDS table for querying data. This is due to data purging. This PR does not have any documentation impact.
environments.]
-
> Fix throttling granularity issue in stat graphs

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClientConstants.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR fixes the success count changes for throttled out graphs and the geo location graphs in publisher based on the changes done to the siddhi apps. There will be documentation changes with this PR.
There is another minor fix for throttling application retrieval in query.
environments.]
-
> Fix success count and geo location graphs

- pom.xml
This PR upgrades identity component versions
environments.]
-
> Upgrade Identity Component Versions

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/application/list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/application/module.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/configure-alert/alerts.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/configure-alert/ajax/configure-alert.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/configure-alert/js/configure-alert.js
Hide other's apps in alert config ui
No Impact
> Hide other's apps in alert config ui

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats-list/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-geolocation-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledtime/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-user-agent-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/js/stats.js
> Change urls to new docs

- pom.xml
This PR upgrades axis2, synapse and carbon multitenancy versions.
environments.]
-
> Upgrade component versions

- pom.xml
This PR upgrades identity component versions to latest ones.
environments.]
-
> Upgrade new identity component versions

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ApiPermissionValidation.jsx
> Fix eslint issues

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> Fix autocommit bug

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/alert/AlertTypesPublisher.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/alert/AlertTypesPublisher1Test.java
Fix error generated during unsubscribing to alerts
> Fix alert email unsubscribe issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-resource-path/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/application-throttledcounts/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/template.jag
This PR changes the default granularity button of analytics graphs to active state.
environments.]
-
> Make default granularity button active in analytics graphs

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/stats/stats.jag
fix an issue where total count of alerts are not retrieved correctly for tenant
> Fix alert history pagination issue for tenants

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/api/add.jag
- Fix duplicate API error message
> Fix duplicate API error message

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/APIInputForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Endpoint/ApiCreateEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Swagger/ApiCreateSwagger.css
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Swagger/ApiCreateSwagger.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Documents.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js
- Add an alias to webpack resolve to avoid using relative path imports with Publisher app
- unified api create pages according to wireframes
- Add save() and publish method to `API` class
- Need to Fix https://github.com/wso2/product-apim/issues/3700
> [APIM3] Publisher API create pages

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR removes direct _SECONDS table querying for analytics.
environments.]
-
> Remove direct _SECONDS table querying

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/observers/CommonConfigDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/observers/CommonConfigDeployerTestCase.java
Fix https://github.com/wso2/product-apim/issues/3628
> Fix https://github.com/wso2/product-apim/issues/3628

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
- This will include the fix for issue in api edit resource view not rendering after session clear. 
environments.]
-
> Fix api edit resource view after session clear in soap to rest feature

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClientConstants.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR fixes the issue of selecting the granularity for the Latency Graph.
environments.]
-
> Fix granularity issue in Latency graph

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClientConstants.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR adds seconds granularity to Latency graph.
environments.]
-
> Add seconds granularity to Latency graph

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
This PR provides a fix for https://github.com/wso2/product-apim/issues/3449
> fix for issue with getAllTags api #3449

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/edit/template.jag
- Fix wso2/carbon-apimgt/issues/4721
- Screenshots can be updated. But it's a minor thing.
> Fix wso2/carbon-apimgt/issues/4721

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/reportgen/ReportGenerator.java
Improve the generated summary report for micro gateway.
Before 2.6.0-RC2
No impact on docs
> Improvement for summary report

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR adds minute level granularity to throttling and faulty invocation graphs.
> Link to the PR for changes to the training …
> Add Minute level granularity to throttling and faulty invocation graphs

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
Fix last access time related graph
> Fix last access time related graph

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jagg.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jagg/jagg.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jagg.jag
- Fix wso2/product-apim/issues/3662
> Fix wso2/product-apim/issues/3662

- pom.xml
> Upgrade components

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/SubscriptionsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationKeyGenerateRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationKeyReGenerateRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationKeyReGenerateResponseDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/store-api.json
https://github.com/wso2/carbon-apimgt/pull/5581/files
> generated source for store-api.yaml changes done in PR 5581

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/EndpointAdminServiceClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/utils/EndpointAdminServiceClientTestCase.java
> Fixes the issue :https://github.com/wso2/product-apim/issues/3701
> Product apim - 3702 Fix

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
> Fixing DB2 issue

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/AdvanceEndpointDetail.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointDetail.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.jsx
> Changes the publisher endpoint UI/UX based on the suggestion by @chanaka3d 
> Support inline and global endpoints
> Support endpoint editing capability
> https://github.com/wso2/carbon-apimgt/pull/5611
> https://github.com/wso2/carbon-apimgt/pull/5622
> Publisher endpoint page improvements

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClientConstants.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/stats/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/alert-table/ajax/alert-table.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/alert-table/js/alert-table.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/configure-alert/alerts.jag
Siddhi apps related to APIM was updated to work with oracle database. changed the queries to work with this modifications
> Link …
> Update stats to work with new siddhi apps

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/left/template.jag
Remove alert configuration section from admin portal. this is now done from SP side. 
Remove configuration sections from docs
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated …
> Remove alert config from admin dashboard

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsDB2.java
Fix for https://github.com/wso2/product-apim/issues/3723 …
> Fixing https://github.com/wso2/product-apim/issues/3723

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/DAOFactory.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIGatewayPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIMgtAdminServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/internal/BundleActivator.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/DAOIntegrationTestBase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/util/RestApiUtil.java
This PR fixes the Error messages come when starting up the server. …
> Fixing config provider becomes null

- features/apimgt/org.wso2.carbon.apimgt.rest.api.admin.feature/src/main/resources/api-docs/docs/index.html
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/api-docs/docs/index.html
This PR updates REST API docs.
> Update REST API docs

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/auth/OAuth2ServiceStubs.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/auth/OAuth2ServiceStubsFactory.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/KeyMgtConfigurations.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIManagerFactory.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/WSO2ISKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/auth/OAuth2ServiceStubsTest.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIStoreImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/AbstractAPIManagerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/ServiceDiscoveryInPublisherTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/TestMappingUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/mappings/CommentMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/mappings/RatingMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/mappings/SubscriptionMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/mappings/ApplicationMappingUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/mappings/CommentMappingUtilTestCase.java
- pom.xml
Fix #https://github.com/wso2/product-apim/issues/3760
Fix #https://github.com/wso2/product-apim/issues/3761
Fix UserName shows as UUID in UI 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
> Fix Username shown in APIS

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/public/theme/defaultTheme.js
The store webapp is broken without the new theme changes.
This fix is adding those changes.
> Added missing theme file to the store webapp

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
This PR fixes shared subscriptions population error for role restricted APIs
> Fixing shared subscriptions population error for role restricted APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/mappings/APIMappingUtilTestCase.java
Fix Travis build failue + refresh_token not retrieved into ui issue
> Fix Travis build failue + refresh_token not retrieved into ui issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/APITemplateBuilderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/ThrottlePolicyTemplateBuilder.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplWrapper.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/ThrottlingPolicyTemplateBuilderTest.java
> Fixing #3767

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
fix for https://github.com/wso2/product-apim/issues/3772 …
> Fix for product-apim/issues/3772

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/avatar/Avatar.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Logout.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIClientFactory.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Resource.js
> Fix logout feature

- components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/SAMLSSORelyingPartyObject.java
Fix a logical error in the fix done for #5571 via d2bfa10f270808c2a94f494b994a6305718a10c9
> Link to the PR for changes to the …
> Fix error in fix for #5571

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/SynapsePropertiesHandler.java
To fix handling POST request without Content-Type for Token API to support backward compatibility of the product eventhough the Content-Type header is a required header as per the HTTP specs. (Issue #3773)
Fix is done in SynapsePropertiesHandler which is used in Token API. So handler will check whether the Content-Type header is available in the request message context, and then if it is not available, and if the request is a POST or PUT type, it will add the Content-Type header with the value "application/x-www-form-urlencoded".
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Fixing #3773-Handling POST request without Content-Type for Token API

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/ApiDAO.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/SecondarySearchType.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOVendorSpecificStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiFileDAOImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/H2SQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MssqlSQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MysqlSQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/OracleSQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PostgresSQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/APIMgtConstants.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImplIT.java
> This PR provides the capability to search APIS based on secondary level attributes like gateway label
> This PR provides initial capability to search based on meta data which are not stored in AM_API table
> Provides the micro gateway to pull the APIs based on the label.
> Publisher -  search apis based on gateway label

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOVendorSpecificStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/H2SQLStatements.java
> Fixes the attribute search related integration test failures
> Fix integration test failures

- components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/SAMLSSORelyingPartyObject.java
This fixes the issue with assigning logout url for sso. …
> Fix sso logout url issue

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClientConstants.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/UsageClient.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/stats/api-latencytime/ajax/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/stats/api-throttledcounts/ajax/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-geolocation-usage/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-throttledcounts/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-destination/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-resource-path/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage-user/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-usage/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-user-agent-usage/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/apis-time/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/application-throttledcounts/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/applications-time/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/developers-time/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/faulty-invocations/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/subscriptions-time/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/faultCount/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/perAppAPICount/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/topUsers/js/stats.js
- fix timezone based stats display issue
- fix granularity selection issue for weekly data
- fix invalid stats display issues
- fix button click issues
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
> Fix timezone issues and stats display issues

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/dto/AppCallTypeDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRdbmsClientImpl.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/template.jag
Add hit count info to api resource usage chart
> Add hit count info to api resource usage chart

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
Created API scopes landing page in publisher
> Created API scopes landing page in publisher.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
Formated defaultMessage to be under the line charachtor count.
> Formatted defaultMessage to be under the line charachtor count.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jaggery_acs.jag
> Fix Auth issue in SAML SSO

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MssqlSQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/MysqlSQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/OracleSQLStatements.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PostgresSQLStatements.java
> Fix Integration test NPE issue
> Fix Integration test NPE issue

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java
Prevent null values for clientid, consumerkey, application name in the event stream.
> Link to the PR for changes to the training …
> Prevent null values sending in event streams

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
append fix for https://github.com/wso2-support/carbon-apimgt/pull/ …
> Append fix for carbon-apimgt/pull/5767

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/overview/template.jag
The PR includes changes to fix the issue of tag styling (The tags going out of the layout instead of getting displayed in a new line)
> Fixing Tags Styling [ui Issue]

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/executors/APIExecutor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/executors/APIExecutorTestCase.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/life-cycles/template.jag
> Fixes the https://github.com/wso2/product-apim/issues/3791 and https://github.com/wso2/product-apim/issues/3784
> Fix life cycle related issues

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/ThrottlePolicyTemplateBuilder.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/ThrottlingPolicyTemplateBuilderTest.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/user/login.jag
This fixes the following.
https://github.com/wso2/product-apim/issues/3799
https://github.com/wso2/product-apim/issues/3796
> …
> Fixing Admin dashboard login and customize velocity log

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/download.jag
Fix https://github.com/wso2/product-apim/issues/3795
> Fix https://github.com/wso2/product-apim/issues/3795

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- Handle workflow response null and empty cases
> Handle workflow response null and empty cases

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js
Fixed https://github.com/wso2/product-apim/issues/3778 
Fixed https://github.com/wso2/product-apim/issues/3805
> Bug Fixes for https://github.com/wso2/product-apim/issues/3778 and https://github.com/wso2/product-apim/issues/3805

- pom.xml
> Upgrade carbon.auth.version

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocCreateMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocRow.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocTableHeader.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocTableToolBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocTableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Documents.jsx
This is the listing page for API Documentations
> Adding Documentation Listing

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/CertificateMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
Fix issues that conflicts with dynamic SSL feature for sender and listener
Fix issues that conflicts with dynamic SSL feature for sender and listener
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
https://github.com/wso2/carbon-apimgt/pull/5793
N/A
Ubuntu 16.04
N/A
> Fix issues that conflicts with dynamic SSL feature for sender and listener

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImpl.java
Deleting certificates from the trust store is allowed for any tenant admin
> Link to the PR for changes to the training content …
> Fix for allowing only admin tenant to delete certificates

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Create.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Details.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocRow.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/DocTableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
> Adding Document view for URL
> Adding Document view for URL

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
> Fixing : https://github.com/wso2/product-apim/issues/3855
> Encode URL for swagger UI.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointDetail.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/index.jsx
> Fix the endpoint update issue
> Add UI improvements to endpoint page.
> Fix endpoint update issue and refactor endpoint page

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/auth/dto/DCRClientInfo.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/KeyMgtConfigurations.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/DefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/OAuthAppRequest.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/APIMgtConstants.java
- pom.xml
Implement audience related changes
> Implement audience related changes

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Security/AddPolicy.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Security/SecurityOverview.js
This PR fixes the error thrown in 3.0 publisher when navigating to API security tab.
> Fix broken UI in 3.0 publisher security tab

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
Fixing https://github.com/wso2/product-apim/issues/3700
> Fixing https://github.com/wso2/product-apim/issues/3700

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/exception/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImplTestCase.java
Fix https://github.com/wso2/product-apim/issues/3881
> Fix API Access Control feature issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/page/base/js/jagg.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/download.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/page/base/js/jagg.js
Fix for https://github.com/wso2/product-apim/issues/3842
> fix for documentation download issue.#3842

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> Fixing #3899

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/src/main/java/org/wso2/carbon/apimgt/hostobjects/oidc/OIDCRelyingPartyObject.java
- components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/src/test/java/org/wso2/carbon/apimgt/hostobjects/oidc/OIDCRelyingPartyObjectTest.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jaggery_oidc_acs.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jaggery_oidc_acs.jag
This PR fixes https://github.com/wso2/product-apim/issues/3942
New configuration(i.e. usernameClaim) was introduced under "oidcConfiguration" of site.json, if that parameter specified the username will be picked up from relevant claim.
By default, the username will be picked up from "preferred_username" claim, to pick up the username from different claim, "usernameclaim" property can be added as follow under "oidcconfiguration" of site.json which resides in  "<APIM_HOME>/repository/deployment/server/jaggeryapps/store/site/conf" .
"oidcConfiguration" : {
.....
"usernameClaim":"email",
}
Add support for getting username from different claims
Add support for getting username from different claims
By default, the username will be picked up from "preferred_username" claim, to pick up the …
> Improve OIDC login flow

- components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberServiceTest.java
Fixed https://github.com/wso2/product-apim/issues/3745
> Fixed https://github.com/wso2/product-apim/issues/3745

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/Environment.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-view/block.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-keys/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag
> Fix for Showing the same production gateway endpoint in both Production Keys and Sandbox Keys tabs
A new tag name isDefault has been introduced for the Environments configuration in api-manager.xml.
E.g : <Environment type="production" isDefault=“true”>
If multiple production or sandbox environments are introduced the isDefault= true tag can be used to define the default sandbox/ production environment.
The default production/ sandbox environments will then be shown in the relavant tab.
<Environment type="production" isDefault=“true”>
<Name>Production</Name>
<ServerURL>https://localhost:${mgt.transport.https.port}/services/</ServerURL>
<Username>admin</Username>
<Password>admin</Password>
<GatewayEndpoint>http://production234:${http.nio.port},https://production234:${https.nio.port}</Gate …
> Fix https://github.com/wso2/product-apim/issues/3883

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreatorTestCase.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
Fixes, 
https://github.com/wso2/product-apim/issues/3927
https://github.com/wso2/product-apim/issues/3880
> Issue fixes

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/user/add.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/user/sign-up/block.jag
- pom.xml
> This PR fixes the issue of Super Tenant admin claims being displayed in Tenant Sign up form.
> Tenant claims fix

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleHistory.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleImage.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/ApiContext.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/headersearch/HeaderSearch.jsx
Took the lifecycle image out from the build and made it configurable. Fixed some of the issues with the lifecycle page.
> fixing lifecycle page issues and making the lifecycle image configurable.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/template.jag
This PR fixes issue - [UI issue in displaying bandwidth unit while editing an Advanced throttling policy
](**https://github.com/wso2/product-apim/issues/3981**)
N/A
> Add fix for issue #3981

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
fixes wso2/product-apim#3975
fixes wso2/carbon-apimgt#5862
> Fixing product-apim#3975 & #5862

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> Fixing #5874

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
Reverts wso2/carbon-apimgt#5870
> Revert "Fixed the 'visible to Roles' in an API configuration issue"

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
This fixes for an issue in role visibility when multiple roles separate with spaces after the comma.
related Issues :
[#3980](https://github.com/wso2/product-apim/issues/3980)
[#5812](https://github.com/wso2/carbon-apimgt/issues/5812)
[#3858](https://github.com/wso2/product-apim/issues/3858)
> Fixed the issue in role visibility

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/js/i18nResources.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/life-cycles/template.jag
Resolves https://github.com/wso2/product-apim/issues/3625
Add confirmation message window for Block option in API life-cycle tab. 
the confirmation window will pop up with following text once they click on "Block" button.
text = "Are you sure you want to block this API ?"
If the user clicks on "yes" it will execute the Block functionality otherwise no.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> Add confirmation message window for Block option in API life cycle tab.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
> Removed the duplicated code

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
Display order fix for tenant claims
> Display order fix

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> Prevent JDBC deadlocks when updating API scopes.
> https://github.com/wso2/product-apim/issues/4012
> Prevent JDBC deadlocks when updating API scopes.

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/APIMgtUsageDataBridgeDataPublisher.java
Change the access modifier from private to protected to support extending the class 
Change the access modifier from private to protected to support extending the class  …
> Change the access modifier from private to protected to support extending the class 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/DefaultGroupIDExtractorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/DefaultGroupIDExtractorImplTest.java
This PR fixes the issue reported in https://github.com/wso2/product-apim/issues/3355.
> Fix https://github.com/wso2/product-apim/issues/3355

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
Resolved the wso2/product-apim#4060
Provide visibility attribute to docs
> Fix the exporting doc visibility

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java
> Resolves https://github.com/wso2/product-apim/issues/4077
> This PR adds the UUID of a particular application to the JWT claims.
> Add the UUID of a particular application to the JWT claims

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
Fix for [1]
[1] - [https://github.com/wso2/product-apim/issues/4121](https://github.com/wso2/product-apim/issues/4121)
> fix double submit to manage state

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/js/api-manage.js
Fixes https://github.com/wso2/product-apim/issues/4147
> Fix faulty null check in item-manage js

- components/apimgt/org.wso2.carbon.apimgt.api/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
Fix for [1]
[1] - [https://github.com/wso2/product-apim/issues/4154](https://github.com/wso2/product-apim/issues/4154)
> fix null issue when api type is null

- pom.xml
> This PR upgrades the pdfbox version to 1.8.16.
> Upgrade pdfbox version to 1.8.16

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/WSDL11SOAPOperationExtractor.java
Fix for ref property
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable …
> Fix for ref property in RPC WSDL for 6.x

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReaderTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/wsdls/wsdl-with-EndpointReference.wsdl
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
Add unit test for EndpointReference elements in wsdl. This tests the fix done for https://github.com/wso2/product-apim/issues/2763
> Add unit test for EndpointReference elements in wsdl

- components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/src/main/java/org/wso2/carbon/apimgt/hostobjects/oidc/OIDCRelyingPartyObject.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jaggery_oidc_acs.jag
Enabling application sharing feature with OIDC SSO. Application sharing feature was not implemented to work with the OIDC SSO previously. 
Fixes https://github.com/wso2/product-apim/issues/4122
> Enabling application sharing feature with oidc SSO

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/api-implementation.js
Fix issue [#4170](https://github.com/wso2/product-apim/issues/4170)
> Fix In/Out/Fault Flow's setting to 'None' when editing API

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
> Fix for https://github.com/wso2/product-apim/issues/4197

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/util/APIMgtConstants.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImplIT.java
Fix for [1]
[1] - [wso2/product-apim/issues/3680](https://github.com/wso2/product-apim/issues/3680)
> Fix [REST API] Publisher Throttling Tier (Individual) missing information issue

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/jquery.endpointUi.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag
>  Fix for wso2/product-apim#4192 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag
Remove provider from docPath URL
> Remove provider from docPath URL

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
Fix testAddApplication test failure in APIConsumerImpTest
> Fix testAddApplication test failure in APIConsumerImpTest

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
This PR contains fix for https://github.com/wso2/product-apim/issues/4315
Enable search by providing multiple query terms separated by a space
> Add support for multiple term search

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
Reverts wso2/carbon-apimgt#5941
> Revert "Bump xml-apis from 1.4.01 to 2.0.2"

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
This configuration is related for the fix of [1]
[1] - [https://github.com/wso2/product-apim/issues/4301](https://github.com/wso2/product-apim/issues/4301)
> add configuration for updating null throttling tier

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/HostObjectUtils.java
Reverts wso2/carbon-apimgt#5968
> Revert "Fix for - Proxy configurations are ignored when calling publisher 'Test' button behind a proxy"

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
.
Fix for issue - SOAP Advance endpoint configuration values not displayed
> Fix for issue - SOAP Advance endpoint configuration values not displayed

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/util/SOAPToRESTConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/util/SequenceUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/ResourcePolicyInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/ResourcePolicyListDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/RestApiPublisherUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
> This pr includes fix for imported schemas in wsdl for swagger generation for soap to rest feature.
> Link to the PR for changes …
> REST api support for update conversion policies

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/add.jag
Fix the issue in subscribing to an API for **tenanted** user.
> Fix subscription issue in tenant mode

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-remove/ajax/application-remove.jag
> Fixing #4351

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/css/custom.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-all/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/api-listing-prototyped/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/menu/actions/template.jag
> This PR provides fixe for multiple issue in APIM Store portal mobile view.
Issues are described in https://github.com/wso2/product-apim/issues/4328
> fix for https://github.com/wso2/product-apim/issues/4328

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
> Add logs to track the time taken to publish an API to the gateways
> Fix formatting issue in publishToGateway method
> Log time breakdown for API publication to gateway and fix formatting issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/user/login/js/login.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/user/login/js/login.js
This PR contains changes to use encodeURIComponent to mitigated XSS issue
N/A
> Add fix for XSS issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/test/resources/carbon-home/repository/conf/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.common/src/test/resources/carbon-home/repository/conf/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.configurator/src/test/resources/carbon-home/repository/conf/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.rest.api/src/test/resources/carbon-home/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.tenant.initializer/src/test/resources/carbon-home/repository.conf/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
> Fixing issue related to - Application Sharing by roles instead of organization
> have to add the detail about the following new configuration in api-manger.xml
<RESTApiGroupingExtractor>org.wso2.carbon.apimgt.impl.DefaultGroupIDExtractorImpl</RESTApiGroupingExtractor>
>  Fix for - #5966. Fix for - Sharing applications  not working in SAML SSO flow

- .travis.yml
> Fix exit command

- pom.xml
Reverts wso2/carbon-apimgt#6004
> Revert "Bump jacoco.version from 0.7.9 to 0.8.3"

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/application-owner/get-applications/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/page/base/initializer.jag
Fix [product-apim/issues/4405](https://github.com/wso2/product-apim/issues/4405)
> Add handlebars js header to admin site templates

- pom.xml
> Upgrade Kernel version to 4.4.37

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityUtils.java
> Fix for https://github.com/wso2/product-apim/issues/3968
> Fix NPE in APIMgtFaultHandler when analytics is enabled

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/application/application-view/template.jag
> Fixing #4441

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
> Fixing https://github.com/wso2/carbon-apimgt/issues/6026
> Fixing unblocked subscriptions not getting copied to new API version

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/api/add.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/tag/ajax/tag.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/tiers/ajax/tiers.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/usage/ajax/usage.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/users-api/ajax/subscriptions.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/policy/subscription-policy-manage.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/tier/tier-manage.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/user/login/ajax/login.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/api-info/ajax/api-info.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/listing/ajax/list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/recently-added/ajax/list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-list/ajax/application-list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/billing/ajax/billing.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/comment/comment-add/ajax/comment-add.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/sdk/ajax/sdk-create.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/subscription/subscription-list/ajax/subscription-list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/subscription/subscription-remove/ajax/subscription-remove.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/tag/tag-cloud/ajax/list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/user/login/ajax/login.jag
Resolves  https://github.com/wso2/product-apim/issues/3788
This PR avoids stackrace getting propagated to the front end.
In the cases where we propagate the error to the front end, with this PR we have set error to true either in the module layer or in the block layer.
> Fix for product-apim#3788

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag
Fix for https://github.com/wso2/product-apim/issues/3598
> Link(s) to product documentation that addresses the changes of this …
> API Console is not visible after configuring a custom url

- features/apimgt/org.wso2.carbon.apimgt.store.feature/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/.eslintrc.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/webpack.config.js
> Removing es-lint style check for now.

- pom.xml
Reverts wso2/carbon-apimgt#6003
> Revert "Bump json-smart from 1.3 to 2.3"

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiTableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ImageGenerator.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/StarRating.jsx
Update the api listing page table view with mui-datatables to provide feature rich experience to the user.
> Improvements to the API Listing page

- components/apimgt/org.wso2.carbon.apimgt.rest.api.core/pom.xml
This PR updates the checkstyle config file location.
> Update checkstyle config file location

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/taskmanager/get-bpmn.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/apistate-task/js/apistate.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/apistate-task/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/app-registration-task/js/application.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/app-registration-task/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/application-task/js/application.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/application-task/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/signup-task/js/signup.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/signup-task/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/subscription-task/js/subscription.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/subscription-task/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
This commit will fix the issue of access token loading in the UI
> This commit will fix the issue of https://github.com/wso2/product-apim/issues/4432
> Fix the template.jag file located in the /repository/deployment/server/jaggeryapps/store/site/themes/wso2/templates/api/swagger/ directory.
> JDK8
> fix the access_token loading issue in UI

- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
> Fixing webapp name

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java
Fix custom claim populate flow and incorrect gateway response issue
> Fix custom claim populate flow and incorrect gateway response issue

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag
> fix having wrong scehems value in store swagger

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api/documentation/view/block.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/item-info.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/download.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/overview/template.jag
This PR fixes issue https://github.com/wso2/product-apim/issues/4189 for Store WSDL Download url.
> Remove provider from Store WSDL url

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
> Add configuration to provide blocking condition retriever service URL

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Fix for https://github.com/wso2/product-apim/issues/4554
> Fix issue in creating an application with case sensitive username

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
Reverts wso2/carbon-apimgt#6107
> Revert "Fix invalid token cache initialization issue"

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/index.jsx
Remove unwanted components in sample index.jsx file.
> Removing components in sample

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml
This PR is to remove duplicate plugin.
> Removing duplicate plugin

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/stats/stats.jag
Alert view page in admin app throws an error when viewing with latest SP 4.4.0 pack
Update queries with the latest app names introduced in https://github.com/wso2/analytics-solutions/pull/271
Changed queries
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
N/A
https://github.com/wso2/analytics-solutions/pull/271
N/A
JDK 1.8
N/A
> Fix Alert view page due to changes in analytics apps

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/p2.inf
Fix build issue due to missing APILifecycle.xml
> Fix build issue due to missing APILifecycle.xml

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
Add SuppressStaticInitializationFor annotation for PrivilegedCarbonContext
> Add SuppressStaticInitializationFor annotation for PrivilegedCarbonContext

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApplicationsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIListDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationListDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/PaginationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SubscriptionDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
Adding implementation for store REST API applications get
> Adding implementation for store applications get

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/src/main/resources/p2.inf
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/src/main/resources/p2.inf
> Changing publisher, store contexts v1->v1.0

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIIdentifier.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProduct.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProductIdentifier.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Identifier.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/SubscriptionWorkflowDTO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionDeletionSimpleWorkflowExecutor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/SubscriptionsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/RestAPIStoreUtils.java
> API product subscription get and removal implementation
> API product subscription get and removal implementation 

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/service/APILocalEntryAdmin.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/LocalEntryClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/resources/META-INF/services.xml
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/LocalEntryAdminClient.java
- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- pom.xml
- service-stubs/apimgt/org.wso2.carbon.apimgt.localentry.stub/pom.xml
- service-stubs/apimgt/org.wso2.carbon.apimgt.localentry.stub/src/main/resources/APILocalEntryAdmin.wsdl
- service-stubs/apimgt/pom.xml
> Adding swagger as a local entry in the APIM Gateway while including the resource to user role mapping in the swagger
> Adding swagger as a local entry in the APIM Gateway

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/APIClient.js
Fixing swagger.yaml loading by setting accept header to "text/yaml"
> Fixing swagger.yaml loading

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
> Store REST API v1.0 loading correct swagger for scope validation

- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/APISynchronizer.java
This PR contains the fix for a PR review comment in the PR:[6079](https://github.com/wso2/carbon-apimgt/pull/6079)
> Link to the …
> Fix PR review comments for the PR:6079

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/TokenMergeInterceptor.java
1. Excluding `jsr311-api` dependency to avoid NoSuchMethodExceptions
2. Adding GlobalThrowableMapper for REST APIs
3. Fixing NPE when cookie not present
4. Support Publisher GET /apis/{id}
> Improvements for REST APIs

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.js
Shows API Details in overview page
> Showing API details

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Application.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/SubscriptionsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/RestAPIStoreUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestAPIStoreUtils.java
Support Store GET /applications/{id}
```
GET https://localhost:9443/api/am/store/v1.0/applications/be5d77ad-3dde-49f3-be9d-d64b4bd40c94 HTTP/1.1
Authorization: Bearer 64de2afc-3907-3b5d-bbfa-2e8a774bf1bb
```
```
HTTP/1.1 200 OK
{
"applicationId": "be5d77ad-3dde-49f3-be9d-d64b4bd40c94",
"name": "DefaultApplication",
"subscriber": "admin",
"throttlingTier": "Unlimited",
"description": null,
"tokenType": "OAUTH",
"status": "APPROVED",
"groupId": "",
"owner": null,
"subscriptionCount": 1,
"keys": [],
"attributes": {}
}
```
>  Support Store GET /applications/{id}

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestAPIStoreUtils.java
1. Support Store REST API POST /applications
```
POST https://localhost:9443/api/am/store/v1.0/applications HTTP/1.1
Content-Type: application/json
Authorization: Bearer 93a5d2f3-2350-3e86-a620-a0c4e5b014fc
{
"name": "MoreInfoApp",
"throttlingTier": "Unlimited",
"description": "Description of app",
"tokenType": "JWT",
"groups": ["org1"]
}
```
```
HTTP/1.1 201 Created
Location: https://localhost:9443/api/am/store/v1.0/applications/e83006eb-4b1a-4129-a452-4899e816961e
Content-Type: application/json
{
"applicationId": "f002cb45-08f8-4fc9-8fef-e71787e0e35d",
"name": "MoreInfoApp",
"subscriber": "admin",
"throttlingTier": "Unlimited",
"description": "Description of app",
"tokenType": "JWT",
"status": "APPROVED",
"groups": ["org1"],
"subscriptionCount": 0,
"keys": [],
"attributes": {}
}
```
2. …
>  Store Application REST API improvements

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/validators/APIResourceScopeValidator.java
This PR fixes formatting issues in https://github.com/wso2/carbon-apimgt/pull/6210
> Fix Formatting Issues in https://github.com/wso2/carbon-apimgt/pull/6210

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/introspect.jag
prodcut-apim - https://github.com/wso2/product-apim/issues/4653
product-apim - https://github.com/wso2/product-apim/issues/4652
Resolving requested changes to add refresh token grant to DCR and creating a userinfo call to get token user info PR.
#6238
> Resolving Requested Changes for Add refresh token grant to DCR and creating a userinfo call to get token user info.

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIIdentifier.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Identifier.java
> Add Identifier interface. APIIdentifer will implement this.
> Add  interface Identifier

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIIdentifier.java
> Remove deprecated notice

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Overview/Overview.jsx
> Fixing api detials page

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
> add api_delete scope

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Copying the Swagger put and Swagger get implementation from v0.14 api to v1.0
> Copying the Swagger put and Swagger get implementation

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/DocumentationMappingUtil.java
Copied the content to the documentation related Publisher API implementation
> Copying document rest API implementation parts

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
> change the type of the scopes in API from string to Scope
> fix scope in publisher rest api

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/App.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/index.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Utils.js
product-apim : https://github.com/wso2/product-apim/issues/4662
Adding changes to the store login feature code grant initial commit
- Adding the TokenMergeInterceptor to the bean.xml in store.
- Adding login button redirection to the "services/configs" endpoint.
- Implementing logic to validate the logged in user in ProtectedApp.js , AuthManager.js and Utils.js.
User should be able to login to the store.
#6256
> Adding changes to the store login feature code grant

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package-lock.json
https://github.com/wso2/product-apim/issues/4686
> enforce mandatory fiels name context version only.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
* Use the subscription status from the latest api version.
* Fix adding blocked subscriptions as unblocked.
* Fixes https://github.com/wso2/product-apim/issues/4639
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Fix adding blocked subscriptions as unblocked

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/js/applications.js
Fixes https://github.com/wso2/product-apim/issues/4609
> Fixing the issue of not picking the scopes from store UI while generating keys

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
> Fixing URITemplate API change

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
> Update product create api to work with minimum data
> Update product create api to work with minimum data

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/DocumentationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Copying the document related rest API implementation content for Store v1.
> Adding comments rest API implementation to the new store v1.0 rest API

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/documentation/download.jag
Fixed https://github.com/wso2/product-apim/issues/4478
> Removed provider username from the downloaded WSDL file name

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Update the UPDATED_BY column in AM_API table of AM_DB when a developer updates an API
Fix https://github.com/wso2/product-apim/issues/4689
> Add updated_by entry for API update

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Application.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Subscription.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.js
Creates and Lists applications
User needs to login from the sign-in button to create and list applications.
TODO: Needs to be fixed with the automatic login.
> Create and List applications

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/APIKeyValidationInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/AbstractKeyValidationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/TokenValidationContext.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/validators/APIResourceScopeValidator.java
- service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/src/main/resources/APIKeyValidationService.wsdl
This PR,
* Fixes API and API Product Invocation Flow with WSClient.
* Fix scope validation for resources not protected by scopes.
* SubscriptionType attribute is removed from token validation context as it is redundant.
> Fix API Invocation Flow Fixes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/LocalEntryAdminClient.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
> Add code review fixes for [https://github.com/wso2/carbon-apimgt/pull/6128](https://github.com/wso2/carbon-apimgt/pull/6128)
> Set API uuid as local entry key of swagger

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
> endpoint_type is missing in the endpointConfig json string
> fix endpoint_type in endpointConfig json string

- pom.xml
synapse jar comes with mediation feature. to update synapse in apim upgrading mediation.
> upgrade mediation

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/store-api.json
> Reverting changes to publisher-api.json, store-api.json to fix test failures

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionUsingOASParser.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Components/APICreateForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
1. API adding changes for publisher-new App
2. Modifications to sample API to deploy Pizzashack API
3. API POST operations improvements
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> API adding changes for publisher-new App

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/validators/APIResourceScopeValidator.java
This PR fixes Product Subscription Flow and adds some improvements to code.
> Fix Product Subscription Validation Flow

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIProductDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIProductInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/APIProducts/Details/InfoBar.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/APIProducts/Details/Overview.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/APIProducts/Details/index.js
>Add product scope info to the rest api
> Add product scope info to the rest api

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
> ESLint issue fixes

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/throttling/publisher/DataProcessAndPublishingAgent.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/validators/APIResourceScopeValidator.java
Refactor code
* Move constants to APIConstants file
* Use util method to construct api product scope
* refactor validateSubscriptionDetails methods
> Refactor Code

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProduct.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
> Add api product properties. This is similar to API properties
> Add api product properties

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/AdditionalProperties.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/BusinessInformation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Documents.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Policies.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Scopes.jsx
Re-organize the overview page.
> Revamping overview page

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationKeyMappingUtil.java
issue https://github.com/wso2/product-apim/issues/4758
> add rest api for getting all application keys

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
> Changed default value

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreate.jsx
Fix application create issue after adding throttlingPolicy parameter name change
> fix application create issue

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreate.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Application.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
- Connect the react UI with the application key generation REST API
- Improve code quality and comments.
> connect ui with application key generation

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/sdk/ajax/sdk-create.jag
Fixes https://github.com/wso2/product-apim/issues/4778
> Fix tenant domain null issue when downloading SDK.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
This PR fixes subscribing to an API with an existing Application
> Fix subscribing to API with existing application

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java
Add REST API to add multiple subscriptions
Fix https://github.com/wso2/product-apim/issues/4650
> Add REST API to add multiple subscriptions

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package-lock.json
The missing package-lock is breaking the build.
> Adding missing package lock file

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/SubscribeToApi.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
List throttling policies when subscribing to API
> List throttling policies when subscribing to API

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionUsingOASParser.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/server-templates/apiServiceImpl.mustache
**update API support for Publisher REST API**
Fixes: https://github.com/wso2/product-apim/issues/4654
```
PUT https://localhost:9443/api/am/publisher/v1.0/apis/6c64d19e-420d-4055-a410-19079dc10312 HTTP/1.1
Content-Type: application/json
Authorization: Bearer 709ec101-5607-3e11-96a6-ef156bd8f0c4
{
"id": "bea1e4fd-7cbf-43d3-be7a-766976eaf78f",
"name": "PizzaShackAPI",
"description": "This is a simple API for Pizza Shack online pizza delivery store.",
"context": "/pizzashack",
"provider": "admin",
"lifeCycleStatus": "PUBLISHED",
"wsdlUri": null,
"responseCaching": "Disabled",
"cacheTimeout": 300,
"destinationStatsEnabled": null,
"hasThumbnail": null,
"isDefaultVersion": false,
"type": "HTTP",
"transport":    [
"http",
"https"
],
"tags": ["pizza", "123"],
"policies": …
```
> Update API support for Publisher REST API

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
Enable CORS header "Access-Control-Expose-Headers" configuration in to APIM
Fixed #4461
> Configured CORS header "Access-Control-Expose-Headers" to APIM

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionUsingOASParser.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIEndpointDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/EndpointConfigDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
1. PUT /apis/{id} changes to use APIDefinitionFromOpenAPISpec (a json based parser). This will avoid the need of fully parsing the swagger with a swagger parser which might have performance and security issues. 
2. GET /apis/{id} improvements to return endpoint details 
Fixes: https://github.com/wso2/product-apim/issues/4831
> Improvements to Publisher PUT and GET /apis/{id} 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java
Fixes : https://github.com/wso2/product-apim/issues/4818
Fixes : https://github.com/wso2/product-apim/issues/4833
Fixes : https://github.com/wso2/product-apim/issues/4777
> Fix handling null values when using oracle db.

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationKeyGenerateRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
add missing part of https://github.com/wso2/carbon-apimgt/pull/6336.
> add providing clientid and clientSecret during key generation

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationTokenGenerateRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
Add REST API for application token generation
Fix https://github.com/wso2/product-apim/issues/4816
> Add REST API for application token generation

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
- pom.xml
Updates jackson version in plugins directory to 2.9.9. 
A separate PR will be sent(carbon-deployment) to address the version upgrade in cxf3 directory.
> Update jackson from 2.9.8 to 2.9.9

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Lifecycle.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
Fixing the update API from the UI side and adding more options to edit.
> Fixing the update API from the UI side and adding more options to edit.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Wizard.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/Tokens.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewToken.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Application.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
Enable generating access token from UI
> Generate access token from UI

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationKeyMappingRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
Add the rest api for 
POST ​/applications​/{applicationId}​/map-keys | Map application keys
https://github.com/wso2/product-apim/issues/4758
> add rest api for generating keys using an existing service provider 

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/stats/api-usage-destination/ajax/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/stats/api-usage-resource-path/ajax/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/stats/api-usage/ajax/stats.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/stats/faulty-invocations/ajax/stats.jag
This PR adds improvements to the Stream processor related analytics queries.
**Issue fixed :** https://github.com/wso2/product-apim/issues/4836
> Improve Publisher analytics queries

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClient.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRdbmsClientImpl.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/statistics/usage.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/stats/api-usage-by-applications/ajax/stats.jag
This PR fixes the issue https://github.com/wso2/product-apim/issues/4839
> Fix API Usage by Applications Stats

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
This PR fixes the issue https://github.com/wso2/product-apim/issues/4837
> Fix destination stats with query parameters

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClient.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
This PR fixes the issue https://github.com/wso2/product-apim/issues/4838
> Fix analytics not showing in Store issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/LabelDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/LabelDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ThrottlingPolicyMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
Returning `endpointURLs` and `labels` properly from the REST APIs.
```
{
"id": "a6f8988b-6526-4ae5-80cc-ad5cc82b7553",
"name": "PizzaShackAPI",
"description": "This is a simple API for Pizza Shack online pizza delivery store.",
"context": "/pizzashack/1.0.0",
"provider": "admin",
"wsdlUri": null,
"lifeCycleStatus": "PUBLISHED",
"isDefaultVersion": false,
"transport":    [
"http",
"https"
],
"authorizationHeader": null,
"securityScheme": ["oauth2"],
"tags": ["pizza"],
"tiers": ["Unlimited"],
"hasThumbnail": false,
"additionalProperties": {"a": "1"},
"endpointURLs": [   {
"environmentName": "Production and Sandbox",
"environmentType": "hybrid",
"environmentURLs":       {
"http": "http://172.18.0.1:8280/pizzashack/1.0.0",
"https": …
```
> Setting label and endpoint details properly in Store Publisher REST APIs

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
Fixes : https://github.com/wso2/product-apim/issues/4932
> Supporting swagger 2.0 required fields for /swagger endpoint for store try-it

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
fix for https://github.com/wso2/product-apim/issues/4828
> fix issue in configurable resource cache timeout for tenants

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resource.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Fixes : https://github.com/wso2/product-apim/issues/4937
> Support adding resources to APIs

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
Reverts wso2/carbon-apimgt#6414
> Revert "fix issue in configurable resource cache timeout for tenants"

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx
> Remove layout definition

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
> Fix dependency issues

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/ResourcePath.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ResourcePathDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ResourcePathListDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIProductDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
This PR,
* Adds a rest api to retrieve resource paths of an API
* Removes scope mappings from store components
> Add REST API To Retrieve Resource Paths of an API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
This PR fixes DefaultVersionAPITestCase failures due to query inconsistencies.
> Fix test failures in api product branch

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/configs/config.jag
Username and password are read from the user-mgt.xml
> Remove hardcoded authorization header

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
When adding custom attributes to an application, the JWT generator retrieves the JSON object values.
Fixed https://github.com/wso2-support/carbon-apimgt/pull/1450/files
> Fixed JWT formatter issue when adding custom application attributes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Fixed https://github.com/wso2/product-apim/issues/4845
> Fix resource paths are not preserved order in new versioned API

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
This PR formats application details displayed in application page. 
Fix issue https://github.com/wso2/product-apim/issues/4969
> Displaying app details

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIClientGenerationManager.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/sdk/template.jag
- pom.xml
* Add openapitools-generator dependancy.
* Update the dependent classes in APIClientGenerator src.
> Add OAS 3.0 support for Client SDK Generation.

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewVersion/NewVersion.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/CreateNewVersionButton.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Creating a new Version of an Existing API (with/without default version)
Fixes: https://github.com/wso2/product-apim/issues/4755
> Adding create new version implementation + UI

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/rxts/product.rxt
This PR,
1. Fixes NPE for environments when adding a new product.
2. Update registry product artifact upon updating api product.
3. Change api product registry location to /apimgt/applicationdata/products/@{overview_provider}/@{overview_name}/@{overview_version}/product
> Product API Improvements

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/APIList.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/SubscriptionPolicySelect.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/Subscriptions.jsx
This PR enable subscribing to/unsubscribing from an API from the the subscriptions tab of an application.
> Subscribing to an API from application subscription page

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/ExpressMode.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreate.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/SubscribeToApi.jsx
> Fix eslint errors

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SdkGenApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Sdk.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
* Add the sdk generation rest api implementation
* Add the UI integration.
> Support api sdk generation.

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
Fix formatting issue from PR https://github.com/wso2/carbon-apimgt/pull/6336
> fix formatting issue

- pom.xml
Reverts wso2/carbon-apimgt#6454
> Revert "Bump guava from 27.0-jre to 27.1-jre"

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/jest.config.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/Publisher.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/Protected.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Login/InitLogin.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/Alert.test.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/CustomIcon.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/MenuButton.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/Progress.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/Redirecting.test.jsx
In this PR:
- Fix test regression issues and publisher login issue
- Add license headers
> Fix test regression issues and publisher login issue

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/constants.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/login_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/token_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/logout/logout.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/logout/logout_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/index.jsx
When a logged out user returns to a protected page or if the user's current access token expires, the user is redirected to the intended page upon login.
Fix issue https://github.com/wso2/product-apim/issues/4960
> Redirect user to intended page upon login

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
This PR fixes the issue wso2/product-apim#4950
> Fix throttling does not work with resourceKey template

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityConstantsTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityUtilsTestCase.java
Fix test cases for [carbon-apimgt/pull/6477](https://github.com/wso2/carbon-apimgt/pull/6477)
> Fix test cases

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/constants.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/basic.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/introspect.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/login_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/logout/logout.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/logout/logout_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/index.jsx
Port PR  https://github.com/wso2/carbon-apimgt/pull/6466 (issue wso2/product-apim#4960)
This also includes PR #6385(issue wso2/product-apim#4865)
> Port PR https://github.com/wso2/carbon-apimgt/pull/6466

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Wizard.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Application.jsx
- This will allow to update application keys to update its grant type and callback url after its been generated.
- This will remove the token type selection option from key generation UI
- This will fix key generation issue in through api using wizard
https://github.com/wso2/product-apim/issues/5040
> fix issue in updating keys

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Fix sandbox regeneration UI related to https://github.com/wso2/product-apim/issues/5040
> fix sandbox keygen and update

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/TenantWorkflowConfigHolder.java
- pom.xml
Implement New Securevault Config
> Implement New Securevault Config

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/.npmrc
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/Tests/README.md
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/Tests/Utils/MockAPIModel.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Apis.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/ApiCreate.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/ApiCreate.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/Listing.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/Progress.test.jsx
In this PR:
- Add new readme guide about testing
- Refactor API Listing page test
- Fix for https://github.com/wso2/product-apim/issues/5062
Related to the following issue:
https://github.com/wso2/product-apim/issues/3892
> Refactor and cleanup the Listing tests

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/dto/AppCallTypeDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRdbmsClientImpl.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/template.jag
This PR fixes wso2/product-apim#5072
With the fixes, the new Store graph will look like below with the version column.
> Add version column to Store Analytics graph and optimize the Publisher Analytics queries

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProduct.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
This PR adds store visibility and access control for api products.
> Add store visibility and access control for api products

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
Fixes https://github.com/wso2/product-apim/issues/4980
> Fixing #4980

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
This PR contains the following;
- View the access token from the application page
- Add new inputs to the API console(API test page) to enable user to select the application, key type and the environment.
> Display access token and add additional inputs to API console

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/SubscriptionsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/introspect.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/SubscriptionPolicySelect.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/ScopeValidation.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/AuthManager.jsx
Add scope validation for following store UI operations
- Subscriptions - Add, Delete
- Applications - Add, Delete, Edit, Token generation
Fix issue https://github.com/wso2/carbon-apimgt/issues/6543
> Add scope validation for subscriptions and applications

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/Tokens.jsx
Retrieve scopes of subscribed APIs into the Application and use these scopes when generating access tokens.
This PR also removes unused methods, fix eslint errors and add internationalization.
> Add subscription scopes for access token generation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationCreationWSWorkflowExecutor.java
fix for https://github.com/wso2/product-apim/issues/5110
> fix null in application creation workflow

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantOracle.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantPostgreSQL.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java
Fixes https://github.com/wso2/product-apim/issues/5073
> Optimize Oracle, PostgreSQL and MSSQL queries to support case insensitivity of a username

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java
Related issue https://github.com/wso2/product-apim/issues/5015
> Validate scopes with default validator according to the configuration

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java
> Fix scope validation path

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
Fixes https://github.com/wso2/carbon-apimgt/issues/5992
> Fix for https://github.com/wso2/carbon-apimgt/issues/5992

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIManager.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApiProductsApiServiceImpl.java
Store the API product related swagger file in the registry. add rest api in publisher to retrieve and add/update and rest api in store to retrieve
> Update Product swagger upload api to work with registry resource

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/clients/UtilTest.java
- pom.xml
identity components are updated to nimbus 7.3.x. Hence upgrading APIM components.
> Upgrade nimbus version

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
Remove class name with package name
> Remove class name with package names

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Edit/ApplicationEdit.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
This PR adds the UI for Application Edit functionality in Store.
Changes added include
- Ability to edit the Application from the Application Listing Page.
- Ability to edit the Application from the Info Page of the particular application.
> Add Application Edit UI

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
This PR fix
- issue when adding multiple resources from a single API to a product
- Add a Check to publish to gateway only if the state is in Published.
- Handle invalid apis and resources scenario
> Fix adding multiple resources in same api for api product

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
Minimum payload to create an API Product is following
`{
"name": "APIProdudctTest",
"context": "/test",
"policies":["Bronze","Silver","Unlimited"]
}`
> Create API product with minimum properties

- pom.xml
Fixes [1],[2]
[1] FasterXML/jackson-databind#2334
[2] FasterXML/jackson-databind#2341
> Update jackson-databind and deployment version

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/ExpressMode.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Wizard.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/ApplicationTableHead.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreate.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/WaitingForApproval.jsx
this will fix https://github.com/wso2/product-apim/issues/5161
> application creation, subscription and registration workflow related UI

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/Tests/Integration/login/UserLogin.test.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/avatar/Avatar.jsx
Add integration test for the following
- Redirect upon login
- Logout
> Integration test for publisher login and logout

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
> customize the add restApi

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/util/APIUsageClientUtil.java
> Fixing #5124-Issue in querying granularity tables for anlytics of given time ranges

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APIProductCreateWrapper.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/ProductResources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
> Add API Product resource view in overview section.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
Fixed https://github.com/wso2/product-apim/issues/5190
> Added scope add/update support

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/ApiCreate.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Components/APIProductCreateTopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APICreateWrapper.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APIProductCreateWrapper.jsx
> Fix api product top menu

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jaggery_oidc_acs.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/oidc/filter/template.jag
Fix OIDC publisher login
Fix issue: https://github.com/wso2/product-apim/issues/5173
> Fix OIDC publisher login

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
> Add api product delete

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Create.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Delete.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Download.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Edit.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/MarkdownEditor.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/TextEditor.jsx
This PR adds localization support for following files.
- publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- publisher-new/source/src/app/components/Apis/Details/Documents/Create.jsx
- publisher-new/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- publisher-new/source/src/app/components/Apis/Details/Documents/Delete.jsx
- publisher-new/source/src/app/components/Apis/Details/Documents/Edit.jsx
- publisher-new/source/src/app/components/Apis/Details/Documents/Listing.jsx
- publisher-new/source/src/app/components/Apis/Details/Documents/MarkdownEditor.jsx
- publisher-new/source/src/app/components/Apis/Details/Documents/TextEditor.jsx
> Add localization support for configuration ui and documents ui

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationTokenGenerateRequestDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
Fix as per reviews of https://github.com/wso2/carbon-apimgt/pull/6374
> Fix as per reviews of https://github.com/wso2/carbon-apimgt/pull/6374

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
Fixing https://github.com/wso2/product-apim/issues/5168
> Fix for Incorrect documentation of RESTful API search/retrieve

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java
Append API context and version to the resource cache key used for basic authentication.
> Fix basic auth resource cache key

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
This PR fixes an issue in Publisher internationalization in API Details index.jsx and SubscriptionsTable.jsx
> Fix internationalization issues in Publisher

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/introspect.jag
product-apim: https://github.com/wso2/product-apim/issues/5224
> Fixing token introspection issue in Store

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- docs/apidocs/publisher/v1/models/API.html
Fixing https://github.com/wso2/product-apim/issues/5207
> Fix for the supporting the inline implementation method for prototype API creation using REST API

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/login_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/logout/logout_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/refresh/refresh.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resource.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Scope.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Errors/ResourceNotFound.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Footer/Footer.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIClient.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Resource.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Utils.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Token refresh on expired
Support selecting resource throttling policy and auth type
> Token refresh, throttle, auth type selection support

- components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/UserPostSelfRegistrationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/internal/APIKeyMgtServiceComponent.java
- pom.xml
product-apim: https://github.com/wso2/product-apim/issues/5226
Added a CustomUserSelfRegistrationHandler class which extends AbstractEventHandler and expose it as a OSGI component.
> Adding custom user registration handler to add specific role

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- docs/apidocs/publisher/v1/models/API.html
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/login_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/logout/logout_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/refresh/refresh.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resource.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Errors/ResourceNotFound.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Footer/Footer.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIClient.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Resource.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Utils.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/APIProduct.js
Include API Product store REST API in white list config template and minor style fixes
> Include API Product store REST API in white list config template

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
> Add environment details to the store UI

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
Need for validating multiple scopes in Publisher/Store new REST API.
> Add getAllScopes method to return scopes array list.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/impl/RegistrationServiceImpl.java
product-apim: https://github.com/wso2/product-apim/issues/5241
Included  skip consent SP property when creating a new SP using DCR request.
> Disable consent for applications created using DCR request

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
Fix as per PR review of 
- https://github.com/wso2/carbon-apimgt/pull/6365
- https://github.com/wso2/carbon-apimgt/pull/6541
> PR improvements

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
Reverts wso2/carbon-apimgt#6745
> Revert "Add getAllScopes method to return scopes array list."

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
Fix as per PR review of https://github.com/wso2/carbon-apimgt/pull/6374
> Fix as per PR review of https://github.com/wso2/carbon-apimgt/pull/6374

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
product-apim: https://github.com/wso2/product-apim/issues/5249
> Disabling revoked token persistent notifier by default

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/refresh/refresh.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resource.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Delete.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/EditScope.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIClient.js
> Fixed scope update and delete

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
Change the name of a column of table AM_MONETIZATION_USAGE_PUBLISHER in SQL queries.
> Fix column name  in SQL Constants

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIDefaultVersionURLsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIEndpointURLsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIURLsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- docs/apidocs/store/v1/index.html
- docs/apidocs/store/v1/models/API_URLs.html
- docs/apidocs/store/v1/models/API_defaultVersionURLs.html
- docs/apidocs/store/v1/models/API_endpointURLs.html
- docs/apidocs/store/v1/models/ApplicationTokenGenerateRequest.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
> Add default version and WS support

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Apis.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/BusinessInformation/BusinessInformation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Create.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Delete.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Details.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/TextEditor.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/ApiContext.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/APIListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/APIProductListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/CardView/CardView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/TopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIProduct.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
This PR,
Adds initial implementations of API Product Overview, Configurations, Documents and Business Details views.
issues fixed: API Product document content path in the registry is properly fixed.
> Improve Publisher UIs to support API Product display

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ImportApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- docs/apidocs/publisher/v1/operations/APIIndividual.html
- docs/apidocs/publisher/v1/operations/ImportConfiguration.html
- docs/apidocs/publisher/v1/operations/ScopeIndividual.html
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json
- This PR update the tenant-conf.json RESTAPIScopes with the updated scope list.
- Removes apim:api_update scope from Publisher REST API.
- Fix issue in viewing tenant APIs in Store.
> Update REST API Scopes. Fix API visibility issue in tenant store. 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
Add 'apiType' to add subscription
> Add 'apiType' to add subscription

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/ApiSecurity.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx
Adds Transport Security and Authentication selection to the Configurations
> API Security Configuration UI 3.0

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ThrottlingPolicyMappingUtil.java
Refactor per pr reviews https://github.com/wso2/carbon-apimgt/pull/6398
> Refactor per pr reviews https://github.com/wso2/carbon-apimgt/pull/6398

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Edit/EditApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
This PR fixes some issues with validating hidden application attributes and es lint errors.
> Fix issues with Application attributes

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/App.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/SubscriptionPolicySelect.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Applications.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/Subscriptions.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Edit/EditApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewToken.jsx
this PR will fix https://github.com/wso2/product-apim/issues/5024
> add support for token type jwt for applications

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/SubscriptionBlockedException.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Fixing issue [ #5276](https://github.com/wso2/product-apim/issues/5276)
Handling Blocked API error when creating a new version of the API
> Fix rejected subscriptions moving to active state for new version apis

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/PostAuthenticationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/SubscriberRegistrationInterceptor.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Edit/EditApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/AuthManager.jsx
product-apim: https://github.com/wso2/product-apim/issues/5292
- check if the application sharing enabled from config and retrieve that information using Settings API. 
- Storing Settings API response in browser local storage.
- Checking if the application group sharing feature enabled from those stored configs and render user application create view with a field to add/edit/remove groups.
- Application listings changed to show owner of the application prepend to the application name when this feature enabled and only when the application have groups.
- Sending application owner from the GET Application response.
- Before enabling application group sharing feature
- After enabling feature
- logged in with a user who belongs to a shared application group
> Adding Application Group Sharing Feature

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Comments/Comment.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/Listing.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx
> Fix publisher listing page tests

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/Tests/Comments/Comments.test.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/AnonymousView/SignUp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Comments/Comment.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Comments/CommentReply.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Comments/Comments.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/SubscribeToApps.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Wizard/Wizard.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Sdk.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Subscribe.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/CommonListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Edit/EditApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Alert.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Header/GenericSearch.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewCurl.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewToken.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/InlineMessage.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/Message.jsx
Remove materila-ui icons svg imports from the store app to reduce the bundle size.
> Removing material-ui/icons

- docs/apidocs/publisher/v1/models/ApplicationInfo.html
> Add ApplicationInfo doc

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/CORSConfiguration.jsx
> Adding CORS Configurations UI

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
fixing https://github.com/wso2/product-apim/issues/5289
> Fix Websocket API Endpoint settings do not replicate to synapse artifact

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Fix REST APIs calls for monetization tab
> Fix REST APIs calls for monetization tab

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/js/jquery.endpointUi.js
Fix https://github.com/wso2/product-apim/issues/5325
> Fix section in advanced endpoint configs is missing for HTTP/SOAP

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionUsingOASParser.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
Fixes:
Sample API deploy issue: https://github.com/wso2/product-apim/issues/5312
OpenAPI 2.0 Import failure: https://github.com/wso2/product-apim/issues/5317
Swagger Update issue: https://github.com/wso2/product-apim/issues/5314
> Fixing swagger update issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Operations/Operations.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Fixes:
https://github.com/wso2/product-apim/issues/5318
https://github.com/wso2/product-apim/issues/5311
https://github.com/wso2/product-apim/issues/5320
https://github.com/wso2/product-apim/issues/5321
> Fixed issues identified in publisher-new

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java
Porting the commit[1] to master branch 
[1] https://github.com/wso2/carbon-apimgt/commit/3102f0e14ef2f6abe86716f97c2b6904dd97d409
> fix for JWT generation fails when the username itself contains the tenant domain

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtUsageHandler.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Operations.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Overview.jsx
Fixes: 
https://github.com/wso2/product-apim/issues/5365
https://github.com/wso2/product-apim/issues/5372
https://github.com/wso2/product-apim/issues/5373
https://github.com/wso2/product-apim/issues/5334
> Fixed Scope redirection issue and store style issues

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/ApiTableView.jsx
This PR fixes the issue with rating UI not showing in the API table view and changes the icon color at rating add UI.
> Fix ratings UI issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
Fix issue https://github.com/wso2/product-apim/issues/5360
> Fixing the error when creating a new version of an API using REST API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/MeApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/MeApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/RolesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/RolesApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/MeApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/RolesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
- docs/apidocs/publisher/v1/index.html
- docs/apidocs/publisher/v1/operations/Roles.html
This PR contains changes to add Publisher REST APIs to 
- check whether if a given role exists in the system
- check whether the logged-in user has the given role
> Add REST API for role validation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- docs/apidocs/store/v1/models/Settings.html
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ProvideOAuthKeys.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Application.jsx
Add support for Provisioning Out-of-Band OAuth Clients
> Provisioning Out-of-Band OAuth Clients

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
Fix issue https://github.com/wso2/product-apim/issues/5385
> Fix issue Custom subscription workflow redirection is not working

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/site/public/locales/fr.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
This PR will fix https://github.com/wso2/product-apim/issues/5366
This PR will also be adding clonedeep [1] and isempty [2]  methods from loadash as two utility functions. 
Following issues have been identified and reported when during this fix
https://github.com/wso2/product-apim/issues/5370
https://github.com/wso2/product-apim/issues/5371
[1] - https://lodash.com/docs/4.17.15#cloneDeep
[2] - https://lodash.com/docs/4.17.15#isEmpty
> fix not updating ui state when resources paths are removed

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
This PR will fix 
https://github.com/wso2/product-apim/issues/5328
https://github.com/wso2/product-apim/issues/5330
> fix application create and delete ux issues

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/BasicAuthenticationInterceptor.java
> Move RESTAPIScope check to APIUtil. Load tenant during Basic Auth login interceptor.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/SubscriberRegistrationInterceptor.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/App.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Create/NewApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Edit/EditApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/ApplicationTableHead.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/ProvideOAuthKeys.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/SettingsContext.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/AuthManager.jsx
This PR includes following,
- Removing application "subscriber" field from the REST api.
- Adding new owner column in applications listing page instead of appending owner to the application name.
- Not allow generating keys both from UI ,If the user is not the owner.
- Use context hooks to store and retrieve "Settings" without using the local storage for storing settings. 
- Other Minor changes to UI components.
> Adding changes to the application group sharing feature

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/endpointUtils.js
Fixes https://github.com/wso2/product-apim/issues/5319
> Deep copy endpoints before adding advance configurations.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/AccessControl.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/AuthorizationHeader.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/CORSConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/DefaultVersion.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/Description.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/SchemaValidation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/Tags.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
Improve configuration page user experience
Fixes: https://github.com/wso2/product-apim/issues/5332
Related: https://github.com/wso2/product-apim/issues/5303
> Improve configuration page user experience

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SubscribedAPI.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIType.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/SettingsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/SubscriptionsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/SubscriptionsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIProductInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SubscriptionDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SubscriptionMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- docs/apidocs/store/v1/models/APIProductInfo.html
- docs/apidocs/store/v1/models/Application.html
- docs/apidocs/store/v1/models/ApplicationInfo.html
- docs/apidocs/store/v1/operations/Subscriptions.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/APICardView.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/Subscriptions.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/APIProduct.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
Ability to display Application subscriptions for APIs and API Products separately 
Display existing subscriptions in Credentials menu for API Products
> Support for subscribing for API Products from store

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
This PR provides the ability to search as "Bank API" vs Bank API
- "Bank API" --> search for exact string Bank API
- Bank API --> search for either Bank or API
> Fix  backend rest api issues of search

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APICreateDefault.test.jsx
Disabled test since it require refactoring
> Disabled test since it require refactoring

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
Fix https://github.com/wso2/product-apim/issues/5404 cannot unsubscribe to API in the credentials page
> Fix issue cannot unsubscribe in credentials page

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/AdvancedConfig/AdvanceEndpointConfig.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/EndpointListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GenericEndpointAdd.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/LoadBalanceConfig.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Prototype/GenericResource.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Prototype/PrototypeEndpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/EndpointsNew/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/LifeCycle/Policies.jsx
Commit https://github.com/wso2/carbon-apimgt/pull/6908/commits/fa2b2c03cff75f59087e266b5fde5e0d2f9481d0 Fixes https://github.com/wso2/product-apim/issues/5350
> Fix styling issues in Endpoints ui.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/Publisher.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Utils.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/AuthManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Utils.jsx
Fixing issue https://github.com/wso2/product-apim/issues/5400 of  Removing the Context Const and use the one from Configuration object in Publisher and Store.
> Remove the Context Const and use the one from Configuration object

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Properties/Properties.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
1. https://github.com/wso2/product-apim/issues/5403
2. https://github.com/wso2/product-apim/issues/5341
> Fix error when saving endpoint configuration and api properties

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
Fixing https://github.com/wso2/product-apim/issues/5388
> Fix API Resource with dot (.) not displaying properly on API publisher issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/application-owner/change-owner/js/change-owner.js
Fixes 
-https://github.com/wso2/product-apim/issues/5446
-https://github.com/wso2/product-apim/issues/5449
> Removing unwanted space validation for app name in app ownership change page

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
Fixes https://github.com/wso2/product-apim/issues/5462
> Fix API update failure when the endpoint config is null.

- components/apimgt/org.wso2.carbon.apimgt.broker.lifecycle/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.jms.listener/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt.client/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/pom.xml
- components/forum/org.wso2.carbon.forum/pom.xml
- components/oidc-authenticator/org.wso2.carbon.apimgt.authenticator.oidc.ui/pom.xml
- components/oidc-authenticator/org.wso2.carbon.apimgt.authenticator.oidc/pom.xml
- components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/pom.xml
- components/sso-hostobject/org.wso2.carbon.hostobjects.sso/pom.xml
> add osgi.service version

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
> Refactor OAS3 functions

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEdit.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIProduct.js
Intention of this PR is to update the api product resources page to have it's required functionality and fix the save issue.
> Completion of the API Product resource editing page

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPOperationBindingUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SequenceUtils.java
Fix issue https://github.com/wso2/product-apim/issues/5463
> Fix issue Soap to REST Mapping section missing for tenant APIs

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/TopMenu.jsx
Fixes: https://github.com/wso2/product-apim/issues/5466
> Disable grid/list change button when there are no data

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleConditionEvaluator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleConditionEvaluatorTest.java
This PR fixes https://github.com/wso2/product-apim/issues/5459
> Fix throttling not working when default policy exhausted

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Comments/Comments.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Sdk.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.jsx
https://github.com/wso2/product-apim/issues/5337
https://github.com/wso2/product-apim/issues/5346
> Fix Publisher and Store issues

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/AccessControl.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
> Re-factor API call to validate user roles and system roles

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEdit.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Properties/Properties.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/Alert.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/Message.jsx
Fix the property page responsiveness.
Errors when saving from api product and apis.
> Fixing property page issues

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ImportApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/TenantsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/TenantsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/TenantDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/TenantListDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/TenantsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/docs/examples/tenants/tenants.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SearchApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/TagsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ThrottlingPoliciesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/SearchApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/TagsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/TiersApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/RestAPIStoreUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- docs/apidocs/publisher/v1/index.html
- docs/apidocs/publisher/v1/models/Tenant.html
- docs/apidocs/publisher/v1/models/TenantList.html
- docs/apidocs/publisher/v1/operations/Tenants.html
This PR includes REST API implementation  for making APIs visible to specific tenants in APIM-3.0.0.
- List Tenants
- Validate Tenants
Fixing #6784 https://github.com/wso2/product-apim/issues/5480
> List tenants and validate tenants API in publisher

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
This PR fixes https://github.com/wso2/product-apim/issues/5004
> Add fix for wso2/product-apim#5004

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProduct.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductBusinessInformationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- docs/apidocs/publisher/v1/models/APIProduct.html
- docs/apidocs/publisher/v1/models/APIProductBusinessInformation.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/BusinessInformation/BusinessInformation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/ProductResourcesView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIProduct.js
This PR has been doing the following fixes.
1. Fixed issues related to the publisher UI
2. Adding missing properties in api Product
2. Refactor the code by moving api product changes from product.rxt to api.rxt
> Refactor the product related codebase and fixed issues related to the APIProduct

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
This fixes the below error occurrend in integration tests, causing failure in CORSHeadersTestCase
```
org.wso2.am.integration.test.utils.APIManagerIntegrationTestException: Error in API Subscribe. API Name:CorsHeadersTestAPI API Version:1.0.0 API Provider Name :admin Response Code:200 Response Data :{"error" : true, "message" : "org.wso2.carbon.apimgt.api.APIManagementException: Error while adding subscription for user: admin. Reason: Can not retrieve OAuth application for the given consumer key : 8Wzvydch7dz6cbhZhK6JmW11ylca"}
at org.wso2.am.integration.tests.header.CORSHeadersTestCase.setEnvironment(CORSHeadersTestCase.java:126)
```
Getting complete application is not required here. So dropped getting OAuthApp details along with the Application object.
> Fixing error in CORSHeadersTestCase in setEnvironment

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
> Fixed test failure

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/SettingsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- docs/apidocs/store/v1/operations/Settings.html
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/site/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Wizard/GenerateKeysStep.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
This PR 
- Updated the settings rest api to retrieve the supported grant types
- Modified the front end to populate the UI using the retrieved grant types
- Fix ES-Lint issues in the related files
> Retrieve grant types using backend rest api

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/ContentSearchResultNameComparator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/DocumentSearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SearchApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/SearchResultMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- docs/apidocs/publisher/v1/index.html
- docs/apidocs/publisher/v1/models/DocumentSearchResult.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/headersearch/SearchUtils.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/CustomIcon.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIProduct.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Header/Search/SearchUtils.jsx
> Modified unified search for API,API Doc,Product, Product Doc

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Subscriptions/SubscriptionAvailability.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Subscriptions/TenantAutocomplete.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Constants.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
This PR includes the UI for making API subscription available for tenants. https://github.com/wso2/product-apim/issues/5479
**To Do** : Save button needs to be brought to the bottom of the page once issues [#5544](https://github.com/wso2/product-apim/issues/5544) is fixed
> API subscription visible to tenants UI

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/BusinessInformation/BusinessInformation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/AccessControl.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/AuthorizationHeader.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/CORSConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/DefaultVersion.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/Description.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/ResponseCaching.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/SchemaValidation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/Tags.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/AdvancedConfig/AdvanceEndpointConfig.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GenericEndpointAdd.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/LoadBalanceConfig.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Environments/Environments.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Monetization/BusinessPlans.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Monetization/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/BusinessInformation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Properties/Properties.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Delete.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/AuthManager.js
This PR adds API life cycle status based API update restrictions.
This is related to a part of task on https://github.com/wso2/product-apim/issues/5471
> Add life cycle status based API update restrictions

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/BusinessInformation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Policies.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
Fix: https://github.com/wso2/product-apim/issues/5572
> Fix overview page UI

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/LabelsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/LabelsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/LabelsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/LabelMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- docs/apidocs/publisher/v1/index.html
- docs/apidocs/publisher/v1/operations/LabelCollection.html
This PR includes the Publisher REST API to GET the list of gateway labels #https://github.com/wso2/product-apim/issues/2900
> GET gateway labels Publisher REST API

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/site/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPIProduct.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPIProductWizard.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/apiProduct.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/calculator.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/math.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIProduct.js
> API Product Sample Deployment

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/ProductResources.jsx
> Fix overview page product resources UI

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProduct.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
PR fixes in followings.
https://github.com/wso2/carbon-apimgt/pull/6285
https://github.com/wso2/carbon-apimgt/pull/6305
https://github.com/wso2/carbon-apimgt/pull/6460
https://github.com/wso2/carbon-apimgt/pull/6990
> Review requests fixes

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR adds the required configuration for application attributes.
Fixes https://github.com/wso2/product-apim/issues/5524
> Add application attributes configuration

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
This PR fixes issue reported in wso2/product-apim#5507
> Add fix for wso2/product-apim#5507

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObjectTest.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/App.jsx
Fix : https://github.com/wso2/product-apim/issues/5569
> Per tenant theme support

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
Fix https://github.com/wso2/product-apim/issues/5588
> Fix same message in both Application level security and Transport level security error

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Components/SelectPolicies.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/APISecurity.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Adding the Mutual SSL support for Publisher UI.
> Adding Mutual SSL UI support

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIManagementException.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIMgtResourceNotFoundException.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIClientGenerationManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/ZIPUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/AbstractWSDLProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11ProcessorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL20ProcessorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDLProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/model/WSDLValidationResponse.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ThrottlingPoliciesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/docs/examples/apis/wsdl/apiId_wsdl_get.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- docs/apidocs/publisher/v1/operations/ThrottlingPolicies.html
- docs/apidocs/store/v1/index.html
- docs/apidocs/store/v1/operations/APIs.html
* Support downloading the WSDL/WSDL Archive from Store by providing the gateway environment.
* Examples are provided at :
https://github.com/wso2/carbon-apimgt/blob/0cea14f9fc45677e67835402e73435fc021a93e2/components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/docs/examples/apis/wsdl/apiId_wsdl_get.yaml
> Adding WSDL retrieval Store REST API

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Components/SelectPolicies.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
Changing the delete icon color. Note: need to change the global error color upon agreeing on a color.
> Changing delete icon color

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java
Fixes https://github.com/wso2/product-apim/issues/1532
> Renaming WWW-Authenticate header error code for expired tokens

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/WorkflowsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/WorkflowsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/dto/WorkflowDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/factories/WorkflowsApiServiceFactory.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/admin-api.json
This PR will add a REST API to update the status of the workflow.
> add rest api to update workflow status

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/GraphQLSchemaDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Operations.jsx
Fix issue https://github.com/wso2/carbon-apimgt/issues/7032
> Fix Cannot Create Graphql APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
/Since same APIInfoDTO is used for APIProduct in StoreUI set default AdvertisedInfo to the DTO
> Add AdvertisedInfoDTO to APIDTO and APIInfoDTO in for API Products

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
Fix : https://github.com/wso2/product-apim/issues/5604
> Add swagger download to store UI

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Environments/Environments.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Environments.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Labels.jsx
This PR includes the Publisher and Store UI for Microgateway labels. https://github.com/wso2/product-apim/issues/2900
**Publisher UI**
**Store UI**
> Microgateway Labels Publisher and Store UI

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApplicationsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- docs/apidocs/store/v1/index.html
- docs/apidocs/store/v1/operations/ApplicationKeys.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Application.jsx
This PRs provide the capability to clean up application keys that has been created partially. Following is the UI in the store application.
> Add application keys clean up feature

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Wsdl.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Environments.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Utils.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Wsdl.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/api.jsx
* Support creating SOAP APIs by URL, file or zip archive via UI
* Downloading the WSDL per environment
> Wiring Publisher SOAP UI with REST API and Download WSDL from Store

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
Moving upload certificate to a new component
> Moving upload certificate to a new component

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/site/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/AppRouts.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Apis.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/ApiTagCloud.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/ApiTagThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/CommonListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/ImageGenerator.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/TagCloudListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Header/GlobalNavbar.jsx
Adding Tag Cloud in Store 
When Click Health Group
> Adding Tag Cloud in to Store

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
> Fix 2 Cannot Create Graphql APIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
> Fixed NPE issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
This will fix https://github.com/wso2/product-apim/issues/5622
> fix error printed when endpoint null issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
improve fix from [1] to use isblank since it checks for empty spaces as well,
[1] - https://github.com/wso2/carbon-apimgt/pull/7097
> use isblank check for enpoint null issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/site/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
- Modified the warning message in certificate delete.
- Modified the certificate upload dialog box
> Fixing product-apim/issues/5550

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
This PR will fix https://github.com/wso2/product-apim/issues/5621
> fix error printed when creating api

- pom.xml
Reverts wso2/carbon-apimgt#7075
> Revert "Bump jaggery.version from 0.14.10 to 0.14.11"

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json
This PR adds all the scopes needed for analytics apim distribution.
> Add scopes related to analytics apim

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/APISecurity.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/CORSConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/ResponseCaching.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/SchemaValidation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx
Improve configuration page UX
TODO: Move design section to a subpage, Add Mediation policies
> Improve configuration page UX

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
> Fixed scope delete issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/ProductResources/APIProductOperations.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/APIOperations.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/components/operationComponents/DescriptionAndSummary.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/operationUtils.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIProduct.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Resource.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Update the api product resource view
> Update api product resource page

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Environments.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Labels.jsx
This PR facilitates users to download the Swagger of an API (REST APIs and SOAP to REST APIs) by environment and label.
> Download swagger by environment and label

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/CreateNewVersionButton.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
Fix top menu typography issues
> Fix top menu typography issues

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/5627
> Allow updating API when tiers are not present in CREATED/PROTOTYPED

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
This is a temporary fix. We need to add the tier to the method signature and update each places accordingly.
> Fixing the test case failure

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/AlertTypeDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/AlertsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/docs/examples/alerts/alerts.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/docs/examples/alerts/alerts_config.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/docs/examples/alerts/alerts_subscriptions.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/AlertTypeDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/AlertsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/docs/examples/alerts/alerts.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/docs/examples/alerts/alerts_config.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/docs/examples/alerts/alerts_subscriptions.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- docs/apidocs/store/v1/models/AlertType.html
- docs/apidocs/store/v1/operations/AlertConfiguration.html
- docs/apidocs/store/v1/operations/AlertSubscriptions.html
- docs/apidocs/store/v1/operations/Alerts.html
* Rename isRequireConfiguration to requireConfiguration.
* Remove raw request definitions from the api examples
Fixing review comments in https://github.com/wso2/carbon-apimgt/pull/7110
> Restructure publisher and store alert rest api.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
Swagger resource selection not working since the getSwagger method is not accepting params.
> Fixing product resource page swagger resource selection

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
Display Available Microgateways only if there are labels
> Display Available Microgateways only if there are labels

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
Fixes: https://github.com/wso2/product-apim/issues/5652
> Fixing sample API publish issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
Fix https://github.com/wso2/product-apim/issues/5542
> Fix issue cannot edit business information of GraphQL API

- docs/apidocs/store/v1/operations/APIKeys.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/endpointUtils.js
* Fix styling issue in Certificate upload.
Fixes https://github.com/wso2/product-apim/issues/5640
> Fix API Publish issue when only one endpoint is provided.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Sdk.jsx
Fix issue https://github.com/wso2/product-apim/issues/5662 . Image loading issue is not fixed from this PR
> Fix Store SDK page download links not working issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Constants.js
Fix https://github.com/wso2/product-apim/issues/5606
> Fix Rest api resources are not shown in store when created using a WSDL

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/site/public/css/main.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Header/Search/SearchUtils.jsx
This PR will do the following styling.
Before :
After :
> Style store search result drop down

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
Fix Trailing spaces not allowed issue
> Remove whitespace

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIClient.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIValidation.js
In this PR
- Fix openAPO and WSDL create form validation issue
- Add validation status icon to indicate whether the given URL is valid or not
> Fix create openapi/wsdl validation issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
Reverts wso2/carbon-apimgt#7139
As this PR with other PR has introduced more issues
> Revert "Remove whitespace"

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
Reverts wso2/carbon-apimgt#7129
As this PR has introduced more issues
> Revert "Fix Rest api resources are not shown in store when created using a WSDL"

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
Fixing https://github.com/wso2/product-apim/issues/4453
> Removing subscription creation approval requests upon retired API deletion

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
fix for https://github.com/wso2/product-apim/issues/5699
> Fix WSDL SOAP to Rest Conversion issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
Fix https://github.com/wso2/product-apim/issues/5679
> Fix Swagger populating issue for Graphql APIs in Store

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.jsx
Fixing https://github.com/wso2/product-apim/issues/5709
> Fixing delete button disappearing issue in lifecycle tab

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
Fixed OAS bugs and fixed rest api yaml issues
> Fixed OAS bugs and fixed rest api yaml issues

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/EndpointListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/SelectEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GenericEndpointAdd.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Prototype/PrototypeEndpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/endpointUtils.js
This PR 
1. fixes https://github.com/wso2/product-apim/issues/5607
2. fixes https://github.com/wso2/product-apim/issues/5550
3. fixes https://github.com/wso2/product-apim/issues/5714
4. fixes https://github.com/wso2/product-apim/issues/5476
Add Endpoint Select for Endpoint Certificate upload.
Fix alignment
> Fix Endpoints UX issues.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/LifeCycle/LifeCycleImage.jsx
Fix for https://github.com/wso2/product-apim/issues/5721
> Fix LC state change image

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtUsageHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Operations/Operations.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
> Adding APIRateLimiting  configuration to operation page

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
Fixes: https://github.com/wso2/product-apim/issues/5692
create api form styles
> Fix delete api dialog ux & create api form styles

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- docs/apidocs/publisher/v1/index.html
Expands the matched APIs result when `expand=true` is present.
Example:
```
GET https://localhost:9443/api/am/publisher/v1.0/apis?expand=true HTTP/1.1
Authorization: Bearer f82832e9-19da-3694-bded-8d86330548d2
HTTP/1.1 200 
Content-Type: application/json
{
"count": 2,
"list":    [
{
"id": "72d61161-544d-4700-a0ba-027df7f45d0b",
"name": "PizzaShackAPI",
"description": "This is a simple API for Pizza Shack online pizza delivery store.",
"context": "/pizzashack",
"provider": "admin",
"lifeCycleStatus": "PUBLISHED",
"wsdlInfo": null,
"responseCachingEnabled": false,
"cacheTimeout": 300,
"destinationStatsEnabled": null,
"hasThumbnail": null,
"isDefaultVersion": false,
"enableSchemaValidation": false,
"type": "HTTP",
"transport":          [
"http",
"https"
],
"tags": …
```
> Support expand parameter in GET /apis for microgateway
