- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/templates/subscription/subscription-list-element/template.jag
Merge remote-tracking branch 'remotes/wso2/release-1.9.0' into release-1.9.0.
> removed default scope showing up on scope selection popup in API Store.

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
this is a small bugfix for https://github.com/wso2/carbon-apimgt/pull/43
> removed the possibility of passing an empty set of identifiers to getScopesBySubscibedAPIs()

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/thrift/ThriftUtils.java
In our deployment we store the server key in the keystore and certificates in the truststore. We get the following error when the API Gateway sets up a Thrift connection to the KeyManager (running on WSO2 Identity Server). 
```javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target```
> APIMANAGER-3416 - Use the TrustStore to verify the Thrift connection to the KeyManager.

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_es.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/templates/subscription/subscription-list-element/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/templates/subscription/subscription-list/js/subscription-list.js
- fixed the scope specific access token generation issue where user had to select scopes each time they regenerate keys. (APIMANAGER-3462)
- fixed generated scopes not showing up until the page is refreshed.
- added a label to scopes for clarity in viewing.
- removed the copy button for scope names.
> Fixed APIMANAGER-3462 + improvements.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/default/templates/item-manage/template.jag
removed the default "checked" status for HTTP checkbox and added a tool-tip stating the security vulnerabilities an API would face if HTTP is used.
> APIMANAGER-3413 fixed

- dependencies/synapse/modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java
This fixes the ConcurrentModificationException seen in APIMANAGER-2241 caused by the Axis2SynapseController when it attempts to use the DeploymentEngine without synchronizing the Axis2Config
> Fix for APIMANAGER-2241

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/css/styles-layout.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/subthemes/dark/css/styles-layout.css
Fix for APIMANAGER-3201 : API Store document links are not shown as links
> Fix for APIMANAGER-3201

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIManager.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/default/css/styles-layout.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/default/templates/api/documentation/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/css/styles-layout.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/subthemes/dark/css/styles-layout.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/fancy/templates/api/documentation/template.jag
Fix for APIMANAGER-3797 : When adding and updating existing documents via Publisher Rest api, proper message should be returned to the client and the backend exception should be handled
> Fix for APIMANAGER-3797

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/APIUsageStatisticsClient.java
Fix for APIMANAGER-4048 : API Last Access Times Statistics retrieved incorrectly when APIs with same name reside in multiple tenants
> Fix for APIMANAGER-4048

- features/apimgt/org.wso2.carbon.apimgt.core.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml
- pom.xml
…ndencies and making all throttle-consumer components to inherit the version of org.wso2.carbon.throttle.core from the top most parent of the repository
> Refactoring throttle core dependent poms.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin-dashboard/site/conf/site.json
Default config for BPS has 9445 as the port. If AM is configured to have port offset of 2, then errors are thrown when loging to the admin-dashboard
> remove default configuratons for BPS

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java
> Fixing APIMANAGER-4200: Adding RelayUtils.consumeAndDiscardMessage(axis2MC) into auth failure message flow

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/observers/CommonConfigDeployer.java
The logic for checking whether the gatewayType was "Synapse" before attempting to load custom sequences was missing in two classes. The changes were made to these classes
> Added logic to check gateway type before loading custom sequences

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/default/templates/item-add/js/jsonform.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/default/templates/item-implement/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/default/templates/utils/custom-validation/custom-validation.js
This is a simple fix for the above issues. (A basic check to see whether it is a url) So this prevents the user entering text like 'aaaaaa' for example, in the respective fields.
> Fixing APIMANAGER-2280 and APIMANAGER-4064

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-remove/ajax/application-remove.jag
*getApplications* method was used to get the correct application to
update. This method takes too much time to execute when number of
applications is high (fetches application key information per each
application from the database). Therefore *getApplicationByName*
was used to directly retrieve only the application required and
update/remove.
> Fix for APIMANAGER-4488

- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/src/main/resources/p2.inf
Reverts wso2/carbon-apimgt#1935 as Calculator API is required for tests
> Revert "Removed Calculator API webapp copying from gateway to webapps folder"

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin-dashboard/site/themes/wso2/templates/menu/left/template.jag
Fixing incorrect URL on admin dashboard "Subscription Creation" and "Application Registration".
Original issue was due to incorrect addition of URL while adding Log Analyzer links.
> Fixing incorrect URL on admin dashboard 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/user/sign-up/template.jag
Following three fields of user sign up page are required, but has not denoted by the required (*) notification. This fix is to add it to improve the user convenience.
1. First Name
2. Last Name
3. Email
> Adding the missing required notation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java
When API's are added to the API Manager via REST API, the scopes and uri-templates doesn't get added. Same happens when updating the API.
This fix addresses it.
> Fix for the APIMANAGER-4877

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Copying an API fails if the API is added via new REST API with a thumbnail URL
> Fix for APIMANAGER-4936

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/loganalyzer/css/custom.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/loganalyzer/js/loganalyzer-dashboard.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/loganalyzer/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/left/template.jag
- Adding loganalyzer dashboard pages.
- Refactoring loganalyzer dashboard pages names.
- Refactoring loganalyzer gadget dashboard pages names.
- Updating loganalyzer admin dashboard template by adding host name verification from the carbon configuration and request URL.
- Fixing loganalyzer page name headers styling and change **admin-dashboard** to **admin** in the loganalyzer dashboard template.
> Loganalyzer admin dashboard fixes.

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/AccessTokenInfo.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java
- service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/src/main/resources/APIKeyMgtSubscriberService.wsdl
This contains a feature for API manager for revoking access tokens issued for a given user (user tokens) under a given application. Key Manager server's admin service [1] should be called and it will revoke all the tokens and call gateway server so that key caches are invalidated.
> added a new admin service operation - revokeTokensOfUserByApp

- features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/configure-alerts/alerts-domain-edit.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/configure-alerts/alerts-domain-list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/configure-alerts/alerts-domain-manage.jag
- pom.xml
This pull contains changes w.r.t renaming of Execution Manger component to Template Manager. 
Please note that these changes are incorporated in following versions;
carbon.analytics.common: 5.1.0-SNAPSHOT
carbon.analytics: 1.0.6-SNAPSHOT
carbon.event.processing: 2.1.0-SNAPSHOT
Please review and merge
> Renaming Execution Manger to Template Manager

- components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/SAMLSSORelyingPartyObject.java
- components/sso-hostobject/org.wso2.carbon.hostobjects.sso/src/main/java/org/wso2/carbon/hostobjects/sso/internal/SessionInfo.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/site.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/sso/filter/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/sso/logout/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/sso/logout/template.jag
1. Support SSO without SLO
2. Support sending signed SAML requests for Publisher.
New config is added to publisher site.json ssoConfiguration to enable/disable this.
"signRequests" : "true"
3. Support sending ACS url with SAML requests in Publisher.
New config is added to publisher site.json ssoConfiguration to specify this.
"acsURL" : "https://localhost:9443/publisher/jagg/jaggery_acs.jag", //use only if Assertion Consumer Service URL needs to be sent along with SAML request
> SSO improvements 

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIManagerOAuthCallbackHandler.java
When issuing access token in implicit grant type, validateScope() of the ResponseTypeHandler class will be invoked. There only the scope validation callback having SCOPE_VALIDATION_AUTHZ callback type will be handled, since we are calling for authorize endpoint. 
If you are invoking token endpoint, as in authorization code grant, validateScope() of the AuthorizationGrantHandler will be invoked. And there scope validation callback having SCOPE_VALIDATION_TOKEN callback type will be handled.
So in api manager side when handling callbacks(in custom OAuthCallbackHandler), in a scenario where we are calling for authorize endpoint(as in implicit grant type), if the scope parameter is not specified in the request, need to assign the oauth default scope.
> Fixed IDENTITY-4834

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/api-doc/ajax/get.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/api-doc/block.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/menu/actions/template.jag
API creators need api definition to create copies of same API.
This feature allows API creators to download swagger definition
of an API from the API overview.
> Swagger definition download in publisher

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/logging/APILogMessageHandler.java
Current APILogMessageHandler does not show up the Status code due to the wrong use of StringUtil method. Further, this patch allow to log the HTTP method in the log as it is very useful for the monitoring activity via log analyzing tools
> Statuscode not showing up and introducing the HTTP mehtod in log

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APINameComparator.java
public jira: https://wso2.org/jira/projects/APIMANAGER/issues/APIMANAGER-5338
fix : make the APINameComprator to compare providers ignoring the case.
> Fixed APIMANAGER-5338

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/api/api.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/api/module.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/manager/manager.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/manager/module.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/listing/ajax/item-list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/listing/block.jag
In this PR:
- Add a new endpoint to store jaggery REST API named `listing/ajax/item-list.jag`
- Thorugh the above API users can retrieve API information by giving 
*action*, *API name*, *API version*, and *provider* information through POST data.
Address the following issue :  [APIMANAGER-5443](https://wso2.org/jira/browse/APIMANAGER-5443)
> Fix for APIMANAGER-5443: Add new endpoint to store api

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
When the endpoint we are accessing is behind an haproxy or any system that is based on the Host header to dispatch to the proper backend, the Host header is kind of "mandatory".
Not setting the Host header can lead to invalid TLS certificate served or inconsistent behaviour.
Anyway, the header is properly set when running the api manager but was missing when clicking the "Test" button on the GUI. It ends to an error in the UI that is not blocking. 
This PR get rid of this error and simulate the HEAD request with something more similar to the production behaviour
Hope it is clear
> Add Host header for sanity

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
Fix for https://wso2.org/jira/browse/APIMANAGER-5458.
If API Publishing takes time, EnjoyHint points to the corner of the window and not the Congratulations dialog box, and the hint text is thus under the dialog box and not readable.
> Fixing https://wso2.org/jira/browse/APIMANAGER-5458

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/statistics/module.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/statistics/usage.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-top-users/template.jag
This will prevent the error in APIMANAGER-5384, when there are multiple tenants. It will disable the hyperlink for the user profile so that it prevents viewing profile information across tenants.
> Improve the fix for : APIMANAGER-5384

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/manage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/app/manage/js/manage.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-list/js/policy-list.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/manage/js/manage.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/tier/manage/js/manage.js
In the admin dashboard, multiple 'No' buttons are getting added to the popup when trying to delete an item. This will not show up when trying to delete the item at the first time. This would happen if you click 'No' for the pop up for the first time and trying to delete the same item for the second time. This will keep adding 'No' buttons to the popup.
> Fix for APIMANAGER-5507

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/manage/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/app/manage/js/manage.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-list/js/policy-list.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/manage/js/manage.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/tier/manage/js/manage.js
In the admin dashboard, multiple 'No' buttons are getting added to the popup when trying to delete an item. This will not show up when trying to delete the item at the first time. This would happen if you click 'No' for the pop up for the first time and trying to delete the same item for the second time. This will keep adding 'No' buttons to the popup.
> Fix for APIMANAGER-5507: PR for master branch

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/dao/test/APIMgtDAOTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/amConfig.xml
Spike arrest limits are not properly retrieved in tenant basis. The underlying query does not filter out the tiers by tenant from subscription policy table. As a result, spike arrest limit of the very first tier with the same name is retrieved irrespective of the tenant.
> Fix for APIMANAGER-5509

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/dao/test/APIMgtDAOTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/amConfig.xml
Spike arrest limits are not properly retrieved in tenant basis. The underlying query does not filter out the tiers by tenant from subscription policy table. As a result, spike arrest limit of the very first tier with the same name is retrieved irrespective of the tenant.
> Fix for APIMANAGER-5509: Adding changes to the master branch

- components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/interceptors/RESTAPISecurityInterceptor.java
In this PR:
- Fix checking for Authorize header in none API HTTP requests for APIM publisher and store UUF apps
> Fix interference of RESTAPISecurityInterceptor with UUF apps

- components/web/apps/org.wso2.carbon.apimgt.store/pom.xml
In this PR:
- Remove previously used store utils component, It is no longer been used and instead we have renamed it to publisher.commons
> Remove unused dependency

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java
Fixed the revoked Access Token doesn't return the proper WWW-Authenticate header issue by adding required extra attributes.
> Fix for APIMANAGER-5533

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java
- components/web/apps/org.wso2.carbon.apimgt.editor.app/src/main/component.yaml
- components/web/apps/org.wso2.carbon.apimgt.editor.app/src/main/pages/apis/create.hbs
- components/web/apps/org.wso2.carbon.apimgt.editor.app/src/main/pages/apis/create.js
- components/web/apps/org.wso2.carbon.apimgt.editor.app/src/main/pages/apis/index.js
- components/web/apps/org.wso2.carbon.apimgt.editor.app/src/main/public/js/api/create.js
- components/web/apps/org.wso2.carbon.apimgt.editor.app/src/main/public/js/lib/api.js
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/component.yaml
In this PR:
- Add null checks in `Mappingutils` to avoid adding null values for optional parameters when creating an API
- Switch to swagger file exposed by APIM service rather than consuming the MSF4J Swagger service
- Implement API creation by giving a swagger URL
> Implement creating an API from swagger url 

- components/apimgt/org.wso2.carbon.apimgt.keymanager/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.keymanager/src/main/java/org/wso2/carbon/apimgt/keymanager/KeymanagerService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/interceptors/RESTAPISecurityInterceptor.java
- components/apimgt/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.commons.feature/pom.xml
This micro service bundle is introduced to mock the key manager services. Ones the key manager services are available we can remove this bundle.
> [C5] Adding new bundle to mock key manager APIs

- components/web/apps/org.wso2.carbon.apimgt.editor.app/src/main/pages/apis/index.hbs
- components/web/components/org.wso2.carbon.apimgt.auth.ui/src/main/fragments/auth-client-js/auth-client-js.hbs
- components/web/components/org.wso2.carbon.apimgt.auth.ui/src/main/fragments/auth-client-js/public/js/auth/auth-manager.js
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-client-js/public/js/lib/api.js
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-create/api-create.hbs
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-create/public/js/create.js
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-details/api-details.hbs
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-details/public/js/details.js
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-lifecycle/api-lifecycle.hbs
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-listing/api-listing.hbs
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/fragments/api-listing/public/js/index.js
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/src/main/layouts/main.hbs
- pom.xml
In this PR:
- Add noty JS notification library to show all type of notifications in UI
- Handle error cases in swagger client generation, api create and life cycle update actions
- Update Carbon-UUF-Commons to `m4`
- Add new AuthClient module to bundle auth related methods in front end
- Move commonly used api-client js library to layout page
> Improvements suggested  in code review

- components/web/apps/org.wso2.carbon.apimgt.editor.app/pom.xml
- components/web/apps/org.wso2.carbon.apimgt.publisher/pom.xml
- components/web/components/org.wso2.carbon.apimgt.publisher.commons.ui/pom.xml
In this PR:
- I have added `org.wso2.carbon.apimgt.auth` component as a dependency to `org.wso2.carbon.apimgt.publisher.commons` , so that js library fragments in auth component can be used in commons component context
> Add new dependency to APIM publisher commons component

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java
Fixing File Content Download for FILE type document Download Resource API in both Publisher and Store
> Fixing APIMANAGER-5637

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/AbstractAPIManagerTestCase.java
This PR contains 
1. Unit tests for  carbon-apimgt/components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/AbstractAPIManager.java class. 
2. Modifications to methods in AbstractAPIManager to prevent catching and throwing the same exception - APIMgtDAOException.
> Unit tests for AbstractAPIManager

- pom.xml
This Fix will change swagger-codegen version, due to previous version having osgi class loading issues.
> Changing the swagger-codegen version for iot

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java
The issue was:
- We have used the `MultitenantUtils.getTenantAwareUsername` method on already tenant aware username
- The issue get highlighted when the user has both email usernames and default tenanted usernames, In such scenario when user present with an email username for a tenanted(this is valid for super tenant as well refer: [this](http://xacmlinfo.org/2014/10/07/email-username-with-identity-server/)) user, this redundant  `MultitenantUtils.getTenantAwareUsername` call removes the domain part from the email username which makes the username invalid.
- Before calling the `getTenantAwareUsername` util method, the developer should have prior knowledge about the username which is passed to that method, whether it's a tenant aware username or not, and use the util method only for strip …
> Fix for APIMANAGER-5856 : Remove redundant getTenantAwareUsername util call

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/PolicyDAOImplIT.java
- fix for #4578
environments.]
-
> fix missing subscription policy parameter returning issue

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClientTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/util/BlockingConditionRetrieverTest.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/util/KeyTemplateRetrieverTest.java
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/test/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObjectTest.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/ResourceConstants.java
This changes commonly used ports (eg. 8080, 8081 etc) to different ones in unit tests to avoid port conflicts.
> Changed commonly used ports to different ones in unit tests

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.css
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Overview.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Permission.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/ApiThumb.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/ComposeHeader.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/LoginBase.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/pages/index.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/BasicInfo.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Overview.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Permission.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Details/Sdk.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Applications/Details/ProductionKeys.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/Header.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Login/Login.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Login/LoginBase.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/Application.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/api.js
- Update Store and Publisher static files relative path (Append `/app` context) to make compatible with Carbon UI server URL pattern
- Update Store Production Key generation UI to preserve generated keys between page refresh
- Add new `Generate Token` button to re-generate access token and show it in UI, Since Access Token data does not come along with Application information
- Add notification to user actions in Store App Key Generation page
- Generalize Key Generation component to make DRY use with both SandBox and Production key generation UIs
> Update store and publisher UI

- .travis.yml
- README.md
- Address the following issue https://github.com/wso2/product-apim/issues/2020
- ***There is a log size limitation in TravisCI which terminate the build job if the stdout log exceeds `4MB`
- In [this ](https://twitter.com/travisci/status/174904509754118144) Twitter post and 
- In TravisCI [documentation](https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/common-build-problems.md#log-length-exceeded)
they have mentioned about this limitation
- Need to activate TravisCI build for `carbon-apimgt` repo in https://travis-ci.org/wso2
@rumeshbandara
> Add TravisCI integration

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/configuration/models/EnvironmentConfigurations.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorAPI.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/constants/AuthenticatorConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/test/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorServiceTestCase.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/Utils.js
- Use the first host in the `allowedOrigins` list as UI Service.
- If the first host is empty use the `wso2.carbon.apimgt.application: apimBaseUrl` as UI Service
- Configurations are changed as below.
From:
```yaml
wso2.carbon.apimgt:
environmentConfigurations:
allowedHosts:
- 10.100.4.247:9292
- localhost:9292
environmentLabel: Development
```
To:
```yaml
wso2.carbon.apimgt:
environmentConfigurations:
environmentLabel: Default
allowedHosts:
- ''
```
- Remove the `uiService` query parameter from callback URL.
- Fix https://github.com/wso2/product-apim/issues/2205
> [C5][environment][sso] Replace uiService query parameter with a configuration

- components/apimgt/org.wso2.carbon.apimgt.rest.api.authenticator/src/main/java/org/wso2/carbon/apimgt/rest/api/authenticator/AuthenticatorAPI.java
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/Login.js
- Rename `httpOnlyCookieWithLogInContext` to `logoutContextCookie`.
(login context -> logout context)
- Remove `httpOnly` part since both `logoutContextCookie` and `restAPIContextCookie` are http only cookies.
> Refactor rename variable names in authenticator api

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/Login.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/Utils.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Login/Login.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/AuthManager.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/data/Utils.js
- Render the application back when selecting an environment that is already logged in.
Eg:
- Two environment: Development and Production
- User already logged-in to Development environment and switch the environment.
- Prompt the login page
- When selecting the Development environment go back to the application.
- Remove in-memory user AuthManager._user
- Add `environmentName` parameter to `getUser` and `setUser` methods in `AuthManager.js`
- Fix https://github.com/wso2/product-apim/issues/2530
> [C5][environment] Render the application back when selecting an already logged in environment in the login page.

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-add/template.jag
Showing 'seconds' in the unit time for advanced throttling. (https://github.com/wso2/product-apim/issues/2394)
> Fix https://github.com/wso2/product-apim/issues/2394

- components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/interceptors/RESTAPISecurityInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/util/RestApiUtil.java
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/App.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Login/Login.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/App.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/EnvironmentOverview/EnvironmentOverview.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/Header.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Logout.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/App.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Base/Header/Header.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Login/Login.js
- Remove hard coded `ACCESS_CONTROL_ALLOW_METHODS_HEADER` CORS preflighted header.
- Read defined HTTP headers from swagger definition and response only with readed headers.
- fix https://github.com/wso2/product-apim/issues/2792
> [C5] get defined http method headers from swagger content to handle CORS requests

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/APIStatus.java
Due to the case sensitivity of the life cycle statuses , we can not view the apis in the store. This PR fixes that issue
ASAP
> Fix can not view apis in store

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway.annotations/src/main/ballerina/wso2/gateway/annotation.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway.annotations/src/main/java/org/wso2/carbon/apimgt/ballerina/gateway/annotations/GatewayAnnotationPlugin.java
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway.annotations/src/main/java/org/wso2/carbon/apimgt/ballerina/gateway/annotations/GatewayExtensionProvider.java
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway.annotations/src/main/java/org/wso2/carbon/apimgt/ballerina/gateway/annotations/models/VersionModel.java
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway.annotations/src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/org.wso2.carbon.apimgt.gateway.sample.services/pizza_shack_api.bal
- We can support ballerina services with following annotation at service level
@gateway:Version { apiVersion: "1.0.0" }
ASAP
> Adding version annotation for ballerina services

- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/api_gateway_secure_listener.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/constants.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/ballerina/gateway/subscription_filter.bal
- components/apimgt/org.wso2.carbon.apimgt.ballerina.gateway/src/main/resources/ballerina.conf
- Added new secure gateway listener which wraps the gateway listener, which is used for https connections
- We can define two endpoints (http and https) and bind them to services as below
`endpoint gateway:APIGatewaySecureListener apiSecureListener {
authProviders:[gateway:basicAuthProvider,jwtAuthProvider]
};`
`endpoint gateway:APIGatewayListener apiListener {
authProviders:[gateway:basicAuthProvider,jwtAuthProvider]
};`
` @http:ServiceConfig {
basePath:"/pizzashack/1.0.0",
authConfig:{
authProviders:["oauth2"],
authentication:{enabled:true}
}
}`
` @gateway:Version { apiVersion: "1.0.0" }
service<http:Service> pizzashack bind apiListener,apiSecureListener {
}`
ASAP
> Add new secure gateway listener for https connections

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/GZIPUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIBusinessInformationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APICorsConfigurationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIEndpointSecurityDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
This PR contains publisher REST api changes to support api search by labelName attribute.
Other modifications to /apis GET resource
1. a parameter ‘expand’  was introduced to specify whether the returned response should contain APIDTOs or APIInfoDTOs.
Expand, true → APIDTO 
* APIDTO should be changed to APIDetailDTO, that change is not included in this PR for the moment.
2. added support for “Accept: application/gzip” header
sample curl to retrive API details of APIs under label1 as a gzip.
curl -k -H "Authorization: Bearer <access_token>" “https://localhost:9443/api/am/publisher/v0.12/apis?query=labelName:label1&expand=true” -H “Accept: application/gzip” > test.json.gz
> Add support for API serach by labelName attribute

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
Removed swagger2cxf-maven-plugin from rest.apit.store.pom.
> Removed swagger2cxf-maven-plugin from rest.apit.store.pom.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/ApplicationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
- Can send the token type when creating/updating an application using `tokenType`
- Default token type set to OAuth/Default
```
POST https://localhost:9443/api/am/store/v0.13/applications HTTP/1.1
Content-Type: application/json
Authorization: Bearer fb246525-23e0-324d-a6b6-628cabbf05a0
{
"name": "appjwt",
"throttlingTier": "Unlimited",
"callbackUrl": null,
"description": "",
"tokenType": "JWT",
"attributes": {}
}
```
```
HTTP/1.1 201 Created
Location: https://localhost:9443/api/am/store/v0.13/applications/824f7280-e5ed-4fef-96b4-2b5db81f3807
Date: Sun, 17 Jun 2018 15:28:25 GMT
Content-Type: application/json
{
"applicationId": "824f7280-e5ed-4fef-96b4-2b5db81f3807",
"name": "appjwt",
"subscriber": "subscriber",
"throttlingTier": "Unlimited",
"callbackUrl": null,
"description": "", …
```
> REST API Store: Adding token type for application get/update/add

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
NPE is thrown if the related property is not set if an external KM is integrated and that implementation does not fill assign value to this property
> fix NPE for external KM integration

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
Updating api.rxt in startup with labels - This will handle the change in api.rxt (w.r.t Labels) without migrating it externally.
Related (previous PR) : https://github.com/wso2/carbon-apimgt/pull/5215/files
> Updating api.rxt in startup with labels

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java
remove unnecessary parameter from the version value.  Version is extracted from synapse file. it is retrieved as `<apiprovider>--<apiname>:v<verison>` . modified the split character to get the exact version
> Fix version parameter in the event streams

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerAnalyticsConfiguration.java
This supports providing a specific value to the hostname property in the gateway generated event. this would help to group events based on a specific group of hosts (say to identify requests handled all the gateways in a datacenter )
Following is the method to provide this value (as a system property)
`./wso2server.sh -DdatacenterId=datacenter1`
> Add datacenter id support though system property for analytics stats events

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/APIsNavigation.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/CardView/CardView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/TopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/headersearch/HeaderSearch.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/headersearch/searchUtils.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/container/navigation/NavItem.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
- The users can search for APIs or Endpoint(TODO) from the top app bar search input
- Can't search endpoint using its name like it's possible with [APIs](https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml#L92)
- Improve global endpoint search and use it to suggest global endpoints in App bar search
> [APIM3 Publisher] Add global search capability

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/APIMJWTGenerator.java
Resolves #https://github.com/wso2/product-apim/issues/3562
This Fixes to read Issuer Url from **IDTokenIssuerID** in identity.xml
> Change Issuer Url in JWT

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/configure-alert/alerts.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/configure-alert/ajax/configure-alert.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/manage-alerts/block.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/conf/locales/js/i18nResources.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/configure-alert/js/configure-alert.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/manage-alerts/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/stats/api-latencytime/js/stats.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/manage-alerts/block.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/manage-alerts/template.jag
Minor UX improvements to alert configurations.
Publisher Latency graph's second drill down will only show up if the selected date is within 1day (seconds table data, older than 1day is purged by default). 
After merging this PR, siddhi query for alert config delete need be changed with alert type as a filter variable.
* Disable selecting unconfigured alerts
* Activate correct button on drilldown
* Improve latency graph drilldown
* Add alert type to delete request
> Improvements to latency graphs and Alerts

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/modules/configure-alert/alerts.jag
Fix publisher alert config delete issue. As the fix we insert '0' to the threshold value instead of deleting it. inserting 0 works as removing the alert config
> Fix publisher alert config delete issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
When using rs.first() PostgreSql and MsSql Dbs throw an exception
saying it requires a scrollable Resultset. Hence fixed this by
using a rs.next().
> Fix web socket API issue in validating keys for handshake

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java
Application import was broken due to an issue in subscription importing.
Cause of the issue was incorrectly comparing an ENUM with a String.
> Fix an issue in importing subscriptions

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java
Use of ENUM constant for API lifecycle was removed with an earlier fix.
> Remove the use of old lifecycle constant

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/api/APIPublisher.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/ApiDAO.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiFileDAOImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImplIT.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/ApiImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/FileBasedApiImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/MappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/TestMappingUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/APIImportExportTestCase.java
> /apis rest API of the publisher currently provided API list with summary of details for each API. The response json array contains few of the meta data of each api.
> With this PR we have introduced new parameter *expand* , so when we invoke the rest api with this parameter it will give api list, where each api have all meta data.
> sample curl command would be as follows
`curl -k -h "Authorization:Bearer <TOKEN> "https://localhost:9443/api/am/publisher/v1.0/apis?query=name:Sample&limit=25&offset=0&expand=true`
> This enables the micro gateway to fetch all the API data and to create a micro gateway project
> Support Extended API details when listing apis via publisher rest API

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
> Add type property to API dto to identify the extended API object and the summary API object
> Neglect the UUID sent in the API post request while creating the API.
> Add type property to API DTO

- pom.xml
To support APIM to be able to run on Java 10
Upgraded P2 Plugin, Carbon Kernel and Carbon Metrics dependencies
Please checkout and locally build following branches:
master_java10 branch in maven-tools repo
4.4.x_java10 branch in carbon-kernel repo
1.x.x_java10 branch in carbon-metrics repo
Please build with java 8. Built products can be run on java 10.
> Upgrade P2 plugin, C4 and Metrics versions to support Java 10

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/RestAPIStoreUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/utils/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
To fix https://github.com/wso2/product-apim/issues/3863 : When adding an app from the Store REST API where sharing apps between multiple groups are enabled, it adds the group id of the user irrespective of the input groupId value, in the payload. Due to this, when user1 adds a private app from the REST API, it is shared with user2 when both are in the same group (org is the claim). This PR fixes this issue.
When an application via Store REST API, groupId parsed in the body was not honored. So, as the fix, the parsed groupId is set to be honored, hence will be added in to the DB.
Added via https://github.com/wso2/product-apim/pull/3884
> Handling application post and put in the Store REST API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-manage/template.jag
Fix: wso2/product-apim#3873
Having 'summary', 'description' and extensions in PathObject of openapi definition is supported by OpenAPI spec. But APIM doesn't support it.
Several patch releases has gone out for openapi spec after 3.0.0 release. Supporting 3.0.x is possible as we only expect issue fixes through a patch release. It shouldn't break anything.
- Improve openapi path object support
- Make 3.0.x as supported range
> Improvements to Publisher OpenAPI support

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpecTest.java
Verifies the fix for wso2/product-apim#3873
OpenApi definitions provided with additional elements in Path Item Object should be correctly parsed when building URITemplates
- Unit tests
https://github.com/wso2/carbon-apimgt/pull/5837
> Add test case for openapi validation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpecTest.java
OpenAPI allow 'parameters' and 'servers' elements in PathItem Object. These two items needs to be skipped when building URI Templates using the openapi definition.
> Improve openapi validation

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/comment/comment-list/template.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/forum/js/forum-list.js
Fixing issues in forum comments
> Fixing issues in forum comments

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIAdmin.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ApplicationsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ExportApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ExportApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/admin-api.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/publisher-api.json
Adding cross tenant API/Application export support to the REST apis for APIM 2.x to 3.0.0 migration
This PR do the below changes which are required for APIM 2.6.0 to 3.0.0 migration
1) Get list of Applications For Applications export
- Change Admin REST API - /applications GET to  get list of apps for the given tenant/cross tenants too. 
- Validate special permissions to allow only the super tenant admin users, only when the server is started with migrationMode=true property, to get cross tenant application list
2) For exporting Applications 
- Change Admin REST API - /export/applications GET to export Apps of the given tenant/cross tenants too
- Validate special permissions to allow only the super tenant admin users, only when the server is started with migrationMode=true property, for …
> Adding cross tenant APIs/Apps export support to REST API for 3.0 migration

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jagg/jaggery_oidc_acs.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/jagg/jaggery_oidc_acs.jag
Fix issue in picking up a username claims
Fix issue in picking up a username claims
This is a bug fix
Fix issue in picking up a username claims
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain …
> Fix issue in picking up a username claims

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java
While using the API of API Manager 2.6.0, I got several NPEs as no proper validation was present.  
Added null checks and additional exception messages.
> avoid NullPointerExceptions

- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIStoreImpl.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/models/Comment.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/EndpointsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/API_additionalPropertiesDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/dto/CommentDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/mappings/CommentMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/mappings/CommentMappingUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/dto/CommentDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/mappings/CommentMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/mappings/CommentMappingUtilTestCase.java
- pom.xml
Earlier we had the ability only to retrieve the comments and replies as a single list. But it is a tedious task when displaying those in the UI. So, need a mechanism to retrieve the comments from the backend in a nested manner.
- After getting the comments list from the database, organize the comment replies in a nested manner under the particular parent comment.
Please refer the mail thread subjected as “[Dev] [APIM 3.0] Issue of retrieving nested API comments”.
- As a Consumer, someone can retrieve nested comments in API Store.
- As a Publisher, someone can retrieve nested comments in API Publisher.
N/A - since this is a modification to the already implemented functionality. (Check https://github.com/wso2/carbon-apimgt/pull/5832 - the closed PR)
- Unit tests 
Wrote and modified unit …
> Improves the back-end to retrieve nested comments

- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/SampleTestObjectCreator.java
- components/apimgt/org.wso2.carbon.apimgt.core/src/test/java/org/wso2/carbon/apimgt/core/dao/impl/ApiDAOImplIT.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImplTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImplTestCase.java
Modifies the unit tests and DAO  integration tests related to comments feature.
To test whether correctly functions when parentCommentId is null.
Please refer the mail threads subjected as “[Dev] [APIM 3.0] API Comments” and “[Architecture] Project 240: Communication channel between API Providers and API Consumers”.
N/A - since this is a modification to the already implemented functionality.
- Unit tests 
Modified some test cases to inlcude "null" as the parentCommentId.
-  carbon-apimgt/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/test/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImplTestCase.java
- carbon-apimgt/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/test/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImplTestCas …
> Modifies tests for comments feature

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
This fixes for the issue in the field of 'Visible to Roles' in an API configuration, is not acceptable for multiple roles with space after the comma separation.
The access control logic should work for multiple roles even when there is a space after the comma.  (Eg: health-subscriber, education-subscriber)
https://github.com/wso2/product-apim/issues/3980
> Fixed the 'visible to Roles' in an API configuration issue

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery/locale_default.json
> Resolves https://github.com/wso2/product-apim/issues/4055
> Correct the spelling mistake
> Change locale json file
- Checked the correct word present in the front end.
> Fix Wrong word: "Proper Value" in API Store Additional Property Table

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf/master-datasources.xml
>  Resolves https://github.com/wso2/product-apim/issues/4057
> When different threads access the DB concurrently some action may throw the aforementioned timeout error. We can tune H2 DB to overcome this problem.
> Set MVCC=TRUE in DB URL. The MVCC feature allows higher concurrency than using (table level or row level) locks. When using MVCC in this database, delete, insert and update operations will only issue a shared lock on the table. An exclusive lock is still used when adding or removing columns when dropping the table, and when using SELECT ... FOR UPDATE.
> Fix publishing new Versions of API's with "Deprecate Old Versions" throws a DB error.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-implement/template.jag
> Resolves https://github.com/wso2/product-apim/issues/4005
> Currently we have checkboxes to select the endpoint type: either Load balanced or failover. AFAIK, we do not need to select both configurations. But it is able to select both endpoint types while endpoint configurations displayed below belongs to Load balanced type.
> Introduce radio button instead of a checkbox.
> Fix UI improvement when selecting endpoint types

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIClientGenerationManager.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/blocks/item-design/ajax/add.jag
> Resolves https://github.com/wso2/product-apim/issues/4090
> Fix frontend freeze error when secure API deploy as a prototype in APIM.
> when the API is demoted from published state to the prototyped state the apiBackendPassword is set as null. Whereas it should be set to "*****". This is due to the element stored in the password field not being submitted via the form when the "Deploy as Prototype" button is clicked. Due to this reason, in this case, it does not hit the code block and goes into the else block causing the error to arise. Added an additional check to else block.
> Manual. Developer testing record.
> Fix frontend freeze error when secure API deploy as a prototype.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
> Resolves https://github.com/wso2/product-apim/issues/3491
> The underlying query does not return any data from the subscription policy table. As a result, API returns an error 900908 (forbidden). In the query, There is an equality check for policy subscriber tenant id and subscriber tenant id which fail in this scenario. The goal is to correct that sql.
> check equality for policy subscription tenant id with apiOwner tenant id instead of subscriber tenant id.
> If one tenant publishes an API and another tenant subscribe it with a tier that is not present in its own policies, every call to the API returns an error (forbidden). If a tier is created in the subscriber tenant with the same name, the API call works fine.
Also, the rate limit …
> Fix throttling policies/rate limit not working across tenants issue.

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/RegularExpressionProtector.java
- features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
- pom.xml
Purpose
These fixes improve the performance of the regex threat protector
Approach
* Adding optional system property (-DregexThreatProtectorEnabledTenants) to define tenants who are allowed to use the regex threat protector mediator.
* Add an optional global system property (i.e. -DregexThreatProtectorPayloadSizeLimit) to drop the request flow, if the payload size is exceeding the provided size.
* Using rej2 third-party library instead of java.util.regex library for regex operations to improve regex operations.
* Skipping checking the regex pattern in next sections, if found in first sections. (checked sections are a requested body, headers, path)
https://github.com/wso2/product-apim/issues/4031
> Fixed Regex Threat Protector performance issue

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandler.java
This PR changes accessibility to obtain BACKEND_REQUEST_END_TIME without enabling analytics. Fixes https://github.com/wso2/product-apim/issues/4188
> Make BACKEND_REQUEST_END_TIME available when analytics is disabled

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/HostObjectUtils.java
….
Fixing Proxy configurations are ignored when calling publisher 'Test' button behind a proxy
> Fix for - Proxy configurations are ignored when calling publisher 'Test' button behind a proxy

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImplTest.java
> This PR provides the fox for https://github.com/wso2/product-apim/issues/4302
> Need to be able to use any claim as the gruopId in multi group application sharing.
> use configuration to read claim attribute.
- Unit tests 
> org.wso2.carbon.apimgt.impl.SAMLGroupIDExtractorImplTest
> fix for https://github.com/wso2/product-apim/issues/4302

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Fixed the issue in APIM 2.6.0 which it doesn't allow to generate a token for the scope without a role. since the access token will be generated with the default scope.
https://github.com/wso2/product-apim/issues/4290
> Fixed the issue in token generation for the scope without role

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/subscription/subscription-list/ajax/subscription-list.jag
This PR fixes the NPE when navigating to api-info page of an api that does not have subscriptions.
Before calling getApplicationKeysForAppId it is checked whether the appId is not null.
> Fix error when loading apis that has not no subscriptions

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
Resolves #5629 
Resources of the apis created in the tenant space are retrieved from the tenant cache instead of the super tenant cache.
In the method **getOpenAPIDefinitionResource** of **APIProviderHostObject.java**, a code block was not properly enclosed in the tenant flow. And this PR fix that.
java version "1.8.0_201"
Ubuntu 18.04 LTS
Chrome Version 72.0.3626.109
> Fix for #5629

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
When adding API through the publisher REST-APIs, tenant admin can set API-provider.
In that process, if the tenant admin set a wrong tenant domain or username without the tenant domain, the API manager could not handle the scenario.
Set API-provider tenant domain validation for adding APIs through publisher REST-API.
* Check the provider-tenant domain and validate it.
* If the tenant domain contains uppercase letters, convert it to lowercase characters.
> Add API-provider tenant domain validation for adding APIs through publisher REST-API

- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/APISynchronizer.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/dto/LabelDTO.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/util/APISynchronizationConstants.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.common/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/common/util/OnPremiseGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/ConfigConstants.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/Configurator.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/dto/MicroGatewayInitializationDTO.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/test/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/ConfiguratorTest.java
This PR consists of the changes related to 'adding labeling feature to WSO2 Cloud Hybrid Gateway'.
(Please refer this mail thread: "Adding Labeling feature to WSO2 Hybrid Gateway" for detailed explanation.)
Followings are the sub tasks implemented:
- Read environment and custom properties configured in on-premise-gateway-properties and send those values (to the Cloud REST API /initialize endpoint) during initialization
- Send label related data during initialization
- Synchronize APIs during server startup for a configured "label". If no label is configured, all the APIs will be synchronized.
- Synchronize APIs periodically. (If a "label" is configured, only the APIs that are published under that label will be synchronized periodically. If not all the APIs will be synchronized)
- Handle …
> Add labeling feature to cloud hybrid gateway

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
This PR contains a fix for the ''Adding microgateway environments to Store console drop-down list''.
As per the current implementation's expectations, after adding a label from Admin portal, those environments (label names) should be listed in the "API Gateways" drop-down list in the Store-API Console. But it's not available in the current product.
Related Git issue is: [carbon apimgt-6083](https://github.com/wso2/carbon-apimgt/issues/6083)
- Ran FindSecurityBugs plugin and verified report? no
[carbon-apimgt/pull/1405](https://github.com/wso2-support/carbon-apimgt/pull/1405)
> Fix for the 'Adding microgateway environments to Store console drop-down list' 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/api-doc/ajax/get.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/api/swagger/template.jag
This PR contains a fix for the ''Adding microgateway environments to Store console drop-down list''.
As per the current implementation's expectations, after adding a label from Admin portal, those environments (label names) should be listed in the "API Gateways" drop-down list in the Store-API Console. But it's not available in the current product when URL is given with spaces. Hence have done the trimming.
Related Git issue is: [carbon apimgt-6083](https://github.com/wso2/carbon-apimgt/issues/6083)
- Ran FindSecurityBugs plugin and verified report? no …
> Fix for the 'Adding microgateway environments to Store console'

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
> This will enable the valid token cache and invalid token cache to get initialized independently from each other.
> Fix invalid token cache initialization issue

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/SynapsePropertiesHandler.java
Fix issue [#3773](https://github.com/wso2/product-apim/issues/3773)
Fix handling POST request without Content-Type for Token API to support backward compatibility
> Fix handling POST request without Content-Type for Token API

- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml
Maven site tries to generate unwanted reports since the correct configuration to skip these reports are not provided.
Fixes wso2/product-apim#4555
> Fix rest api doc generation

- pom.xml
This version bumping is to ensure that apim distribution will not end up with redundant jsonpath jars.
> update analytics-commons version

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/webapp/META-INF/webapp-classloading.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/webapp/META-INF/webapp-classloading.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/webapp/META-INF/webapp-classloading.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/webapp/META-INF/webapp-classloading.xml
This PR is to remove packaging duplicate libraries in war files and enabling them to use jars from lib/runtimes/cxf3 directory.
This also fixes classpath issues.
> Removing redundant libraries from war libs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/SwaggerYamlApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
Supports below to retrieve the swagger definition of a publisher API v1 in yaml format. 
`GET https://localhost:9443/api/am/publisher/v1/swagger.yaml`
> Adding /swagger.yaml resource for publisher api v1

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/SwaggerYamlApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
Supports below to retrieve the swagger definition of a store API v1 in yaml format.
GET https://localhost:9443/api/am/store/v1.0/swagger.yaml
> Adding /swagger.yaml resource for store api v1

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/TokenMergeInterceptor.java
- Implementing Token merge interceptor in which two parts of the divided token coming in the header and in cookie, will be merged and sent as a single token as the "Authorization" token.
> Adding Token Merge Interceptor

- pom.xml
updated jaggery from 0.12.8 to 0. 12.9
fixes wso2/product-apim#4578
> update jaggery version

- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/test/resources/carbon-home/repository/conf/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.common/src/test/resources/carbon-home/repository/conf/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.rest.api/src/test/resources/carbon-home/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.tenant.initializer/src/test/resources/carbon-home/repository.conf/api-manager.xml
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.usage.publisher/src/test/resources/carbon-home/amConfig.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/amConfig.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/resources/amConfig.xml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/life-cycles/template.jag
- fixes wso2/product-apim#4429 
(for non-oauth APIs there will be no **subscription** tier. The existing logic was disabling the LC publish button based on tier availability. This fix does that check only for oauth APIs.)
- Changes default key validation client to WSClient from Thrift (separate PR will be sent to remove thrift dependencies and configs related to this)
> Fixes product-apim#4429

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/introspect.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/token_callback.jag
#6237 
#6236 
Add refresh token grant to DCR and creating a userinfo call to get token user info.
- Enable the creation of refresh token.
- Get the token user info from the userinfo endpoint.
- Add scopes to the request.
> Add refresh token grant to DCR and creating a userinfo call to get token user info.

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
provide the implementation for DELETE api in Publisher REST API.
With this REST api we have introduced a new scope apim:api_delete so that the access token has to be taken with this scope.
Sample request:'
curl -k -H "Authorization: Bearer 6b1fd4d0-eb22-31b4-a804-25a74de296fd" -H "Content-Type: application/json" -X DELETE  https://localhost:9443/api/am/publisher/v1.0/apis/e08b8f07-9c42-4541-9079-230ab1e7860e
> implementation for DELETE /apis REST API

- features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/basic.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/introspect.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/token_callback.jag
product-apim - https://github.com/wso2/product-apim/issues/4662
Implementing authorization_code grant login backend services for store
- Create config.jag to retrieve configs and to perform DCR call.
- Create token_callback.jag to handle the redirect code grant response and to generate a token.
- Create introspect.jag to retrieve scope and user details from the token.
- Create basic.jag to implement basic authentication.
- Adding the necessary URL mapping to jaggery.conf
- Adding services/* package as a resource to store-new app in pom.xml.
User should be able to login to the store.
> Implementing authorization_code grant login backend services for store

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
This PR adds following improvements to api product feature.
* When validating subscriptions, in case two product subscriptions are there for the same consumer key, log a warning and consider the first subscription in result list.
* Update product resources when updating api product.
* Delete product scope and its mappings when deleting a product.
> Allow resource modifications while updating api product

- components/apimgt/org.wso2.carbon.apimgt.keymgt.client/src/main/java/org/wso2/carbon/apimgt/keymgt/client/SubscriberKeyMgtClient.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt.client/src/main/java/org/wso2/carbon/apimgt/keymgt/client/internal/APIMKeyMgtClientComponent.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt.client/src/main/java/org/wso2/carbon/apimgt/keymgt/client/internal/ServiceReferenceHolder.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml
Without this fix, subscriber service calls were intermittently diverting to the synapse layer.
> Set axis2 context to subscriberservice stub

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIGatewayAdminClient.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
Due to two versions of jax-rs apis being bundled into the distribution, issues occur in integration tests. This PR fixes it.
> Remove redundant library from war files

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionFromOpenAPISpec.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/APIDefinitionUsingOASParser.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIOperationsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
1. Add APIs without operations will add an API with a default set of operations /* for GET, PUT, DELETE, POST, PATCH
2. Add APIs with operations will add the API with those operations and a generated minimal swagger definition.
sample `operations` field:
```
"operations":    [
{
"uritemplate": "/order/{orderId}",
"httpVerb": "GET",
"id": "",
"scopes": [],
"authType": "Any",
"throttlingPolicy": "Unlimited"
},
{
"uritemplate": "/order/{orderId}",
"httpVerb": "DELETE",
"id": "",
"scopes": [],
"authType": "Any",
"throttlingPolicy": "Unlimited"
},
{
"uritemplate": "/order/{orderId}",
"httpVerb": "PUT",
"id": "",
"scopes": [],
"authType": "Any",
"throttlingPolicy": "Unlimited"
},
{
"uritemplate": "/menu",
"httpVerb": "GET",
"id": "",
"scopes": [],
"authType": "Any",
"throttlingPolicy": …
```
>  Supporting operations for Publisher REST API /apis

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/AuthenticationContext.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/APIThrottleConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/throttling/publisher/DataProcessAndPublishingAgent.java
This PR adds support for product subscription tiers. 
* During api request authhentication the request is identified as api/product. New productName and productProvider fields are introduced to authentication context to pass along product related details to throttle handler.
* subscriptionLevelThrottleKey key for an api subscription is combination of {applicationId}:{apiContext}:{apiVersion}
* subscriptionLevelThrottleKey key for an api subscription is combination of {applicationId}:{productName}:{productProvider}
> Add Support for Product Subscription Tiers

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/App.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/AuthManager.js
product-apim: https://github.com/wso2/product-apim/issues/4706
- Need to validate user scopes while authenticating users to access resources in publisher.
- Check for "apim:api_view" scope when logging in the user.
First, check for user to exist in local storage, if the user is present check the user for scopes. If the user doesn't exist in the local storage, then get the user from access token by introspection.Then check for the valid scopes.
Users should be validated for relevant scopes before accessing resources.
> Enable scope validation to publisher

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/LifeCycle/Policies.jsx
Product-apim: https://github.com/wso2/product-apim/issues/4709
Resolving policy tiers not getting listed on the drop down issue
Need to display policy tiers when creating a new REST API in publisher.
Changing the incorrect array name reference in the policies array.
Users need to be able to view all the policies when creating a REST API in publisher.
> Resolving policy tiers not getting listed on the drop down issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
- pom.xml
CXF3 runtime has the same version of jackson dependencies. Therefore no need for bundling jackson libs in war files anymore.
> Remove jackson libs from war files

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Errors/ScopeNotFound.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Errors/index.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/AuthManager.js
Product-apim: https://github.com/wso2/product-apim/issues/4710
Need to validate user scopes while authenticating users to access resources in publisher.
- Check for "apim:subscribe" scope when logging in the user.
- Display an error message when directed to an unauthorized resource.
First, check for user to exist in local storage, if the user is present check the user for scopes. If the user doesn't exist in the local storage, then get the user from access token by introspection.Then check for the valid scopes.
Then, the user with valid scopes can access relevant resources. Users can be logged in with default scopes(Anonymous user) but will be restricted access to protected resources.
- Users should be validated for relevant scopes before accessing resources.
- Users should be given an …
> Enable scope validation to store login

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/token_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/login/token_callback.jag
Product-apim: https://github.com/wso2/product-apim/issues/4756
- Need to add expiry time taken from token response, when setting the cookies.
- Remove unnecessary log.info() methods
Cookies should be expired according to the given specific expiry time.
> Adding token expiry time to the cookies

- .travis.yml
Change Travis configs to prevent exceeding execution time cap in Travis free tier.
Note that, I have skip running the test, for the time being, to complete the build within the 50 minutes limit. Until we figure out a way to run the build with tests within 50 min limit.
- Travis default JDK is: `Leiningen 2.9.1 on Java 11.0.2 OpenJDK 64-Bit Server VM`
- Had to change the JDK version. (Since JDK 8 is EOL they don't [use it by default](https://docs.travis-ci.com/user/languages/java/))
With this, we could at least make sure that, Changes will not break the build. Otherwise, there is no use of Travis at all. We just ignore its build failures and merge the PRs?
WDYT?
> Fix Travis configs 

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/token_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/logout/logout.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/avatar/Avatar.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Login/SelectLogin.jsx
Product-apim: https://github.com/wso2/product-apim/issues/4799 
Users should be able to logged out of the application. 
User session in the browser should be destroyed.
User session in the IDP server should be destroyed.
User should be redirected to login page once logged out.
POST request to the oidc/logout endpoint will destory the IDP user logged in session. In this request id_token and redirection url will be provided. This id_token is generated when the user access token request to the /token endpoint happens and will be stored in the session. Once this POST request successfully completed, it will be redirected to provided auth/callback endpoint ,and in here, the user browser cookies will be removed and user will be redirected to the login page.
User should be able to successfully …
> OIDC logout for publisher

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/list.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/subscription/module.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-view/block.jag
The number of scopes can be shown in the drop-down list of APIM Store is limited to 10.if we have more scopes than 10, then scopes which exceed 10 are disappeared from the drop-down list.
refer: https://github.com/wso2/product-apim/issues/4723
Extract all the scopes of subscribed application from the DB
Introduced new method to extract only all the scopes related to an application from the DB level.
> Fix the issue of not showing all the scopes in Store UI 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/subscription/subscription-list/ajax/subscription-list.jag
This PR fixes the issue [1] where Jaggery API [2] does not work when application group sharing is enabled.
[1] wso2/product-apim#4754
[2] https://docs.wso2.com/display/AM260/Store+APIs#StoreAPIs-ListSubscriptionsbyApplication
> Fix getSubscriptionByApplication when group sharing is enabled

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-remove/ajax/application-remove.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/blocks/application/application-update/ajax/application-update.jag
This PR will fix the issue of https://github.com/wso2/product-apim/issues/4614
* The 'CompareCaseInsensitively' parameter in the <APIM_HOME>/repository/conf/api-manager.xml is evaluated in the 'APIConsumerImpl.java'.
* So there is no need of this validation.
* Application updating issue will fix by removing the extra form-data.
> Fix for 'Usernames are sometimes case sensitive but other times the aren't'

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Wizard.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.jsx
When subscribing to API from a new app using the wizard, provide an option to navigate to the API console page once token is generated.
>  Navigate to API console after token generation from Wizard

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ThrottlingPoliciesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApisApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
Add a publisher REST API to retrieve subscription policies of an API. This PR also contains minot refactoring to the same REST API of store
Related PRs : https://github.com/wso2/carbon-apimgt/pull/6378, https://github.com/wso2/carbon-apimgt/pull/6398
> Add publisher REST API to retrieve subscription policy of API

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/service/APILocalEntryAdmin.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/LocalEntryClient.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/LocalEntryAdminClient.java
- pom.xml
- service-stubs/apimgt/org.wso2.carbon.apimgt.localentry.stub/src/main/resources/APILocalEntryAdmin.wsdl
> Adding swagger as a local entry to the API Gateway based on the tenant domain.
Related to [https://github.com/wso2/carbon-apimgt/pull/6128](https://github.com/wso2/carbon-apimgt/pull/6128)
> Fix swagger local entry implemenation to support multi-tenant scenario

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ThrottlingApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/policy/global-policy-edit.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/global/edit/template.jag
Fix HILTONDEV-188
This PR introduces the following changes.
- Remove Key Template exists check from add policy method in Impl layer, instead check if the policy is available.
- Remove Key Template exists check from update policy method in Impl layer. Add the UI restriction for editing policy name.
- Remove Key Template exist check from Add Global Policy REST API
> Fix for Custom policies are not allowed to edit -HILTONDEV-188

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/configs/config.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/configs/config.jag
Authorize endpoint url is composed from the host and the port retrieved from the carbon.xml
>  Fix authorize endpoint url

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ThrottlingApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/policy/global-policy-edit.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/global/edit/template.jag
This PR introduces the following changes.
- Remove Key Template exists check from add policy method in Impl layer, instead check if the policy is available.
- Remove Key Template exists check from update policy method in Impl layer. Add the UI restriction for editing policy name.
- Remove Key Template exist check from Add Global Policy REST API
> Fix for Custom policies are not allowed to edit

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/PatchedSwaggerUIReact.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/webpack.config.js
Hopefully, if https://github.com/swagger-api/swagger-ui/pull/5386 get merged or could find a workaround. We can remove the `PatchedSwaggerUIReact.jsx` file and use the `swagger-ui-react` library directly.
Related issues: 
https://github.com/wso2/product-apim/issues/4958
> Remove redundant authorization button

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/Publisher.jsx
temporarily remove AppErrorBoundary until creating styleless error boundary
> Refactor Publisher.jsx

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/JsonSchemaValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/XMLSchemaValidator.java
When a user tries to invoke GET requests, He/She is getting an error message that says the resource method is not compatible with the validator. But It confuses the user and also it should be handled internally without prompting an error.
> fix issue in schema validator

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
"x-roles" property added for each API resource is unwanted since each resource contains the scope bound (with the property "x-scopes") and scope-role mapping is available in "x-wso2-security" property.
> Remove x-roles property in resources of swagger

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/.eslintrc.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/Tests/Utils/MockAPIModel.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/ApiCreate.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/avatar/Avatar.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/navbar/GlobalNavBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/AppErrorBoundary.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/InlineMessage.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/InteractiveButton.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/LeftMenuItem.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/Message.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/VerticalDivider.jsx
In this PR:
- Fixed the `eslint-plugin-react` version to `v7.13.0`
- Because in [v7.14.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.14.0) they have fixed the nested props validation issue https://github.com/yannickcr/eslint-plugin-react/issues/296. Since we haven't added the validations for nested props objects i:e `classes, theme, api` etc. We could update this plugin to the later version until we add the validation to the code or disabling the eslint validation for `react/prop-types`
- Change the import path for '@stoplight/prism-http/**dist**/mocker/generator/JSONSchema'
> Fixing regression issues caused by version bumps

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java
The issue -[1], _threat_fault.xml file is not getting copied into tenant space is fixed in #5854. But, this file is not getting added into the already created tenant space. This PR contains changes to check whether the file exists in tenant space and add if it is not there during tenant loading.
[1] https://github.com/wso2/product-apim/issues/3927
> Add threatFault.xml to existing tenant space

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/.npmrc
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/constants.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/login/introspect.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/site/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/Tests/README.md
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/Publisher.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/Details.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/NewOverview/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Resources/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Logout.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/RedirectToLogin.jsx
In this PR:
- Remove the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` env variable from `.npmrc` and added it to pom file as mojo plugin configuration. This env variable will be set when building the project.
- TODO: Since we have moved the integration tests to `product-apim` repo https://github.com/wso2/product-apim/pull/5175, We no longer need the puppeteer dependency in SPA apps. We check the usages and remove the dependency safely. 
- Replace hardcoded management hostname and port in introspect.jag which had caused login issues
- Move the application context into `defaultTheme.js` and make the app context configurable.
- Add new `RedirectToLogin` component and util method to handle login redirects.
> Improvements  to Publisher app 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/babel.config.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/AppsAndKeys/Tokens.jsx
Uses https://github.com/akameco/extract-react-intl-messages for autogenerating ids for i18n supported messages. 
- Use `npm run i18n' for regenerating ids.
- npm production build automatically regenerate all ids.
> Adding react-intl-auto for autogenerating i18n ids for Store app

- .travis.yml
Changed the `.travis.yml` as suggested in [here](https://travis-ci.community/t/java-maven-build-completes-successfully-but-m2-local-repository-is-not-getting-cached/4380/3). And now the [caching](https://travis-ci.org/wso2/carbon-apimgt/caches) is back 🙏 😃  . Hopefully, this will reduce the build execution time.
> Update .travis.yml to get the caching work 

- .travis.yml
In this PR
- Improve the build time
- Without tests ![image](https://user-images.githubusercontent.com/3313885/61938980-e9e8da80-afaf-11e9-99d3-9f2ec3494ea0.png)
- With tests ![image](https://user-images.githubusercontent.com/3313885/61941238-b3618e80-afb4-11e9-8924-eb157923caea.png)
- Log file size with tests is `1846448`Bytes ~ 1.76 MB . We need to make sure it doesn’t exceed 4MB [limit](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded)
- Skip the prebuild in Travis for java projects as mentioned in [here](https://docs.travis-ci.com/user/languages/java/#projects-using-maven)
- Remove skipping tests
> Update .travis.yml to improve the build time

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/events/APIMOAuthEventInterceptor.java
product-apim: https://github.com/wso2/product-apim/issues/5247
Using null check instead of isEmpty() method in revoked token properties.
> Null check fix for revoked token notifier properties

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
This PR adds a new method retrieveAllScopes() to URITemplate model. The method name is added as "retrieveAllScopes" instead of "getAllScopes", because when latter is used, API key validation fails while getting URI templates, as the URI template response will contain an empty element "allScopes". Hence to avoid the error, and to return the scope list array using the new method only when needed, we should use a methodname which does not contain "get" prefix.
> Add newmethod retrieveAllScopes() to URITemplate model to support multiple RESTAPI Scopes in Swagger 

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/README.md
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/README.md
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/PostAuthenticationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/SubscriberRegistrationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/BasicAuthInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/BasicAuthenticationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/OAuthAuthenticationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/XACMLAuthenticationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
This PR adds support for basic auth in Publisher/Store v1.0 REST APIs. Along with basic authentication, the BasicAuthInterceptor will do role validation as well. The role validation will be done against the RESTAPIScopes read from tenant-conf.json or REST_API_SCOPE_CACHE. 
With this new improvement, the users can either use OAuth2 or Basic authentication for Store/Publisher v1 REST APIs. The old REST APIs (v0.14) will continue to work with OAuth2 only by default.
> Support Basic Auth for Publisher Store v1 REST APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.admin.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.dcr.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
- features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml
This PR removes the org.wso2.carbon.apimgt.rest.api.util jar from each web-app's lib directory and adds the same jar into <APIM-HOME>/lib/runtimes/cxf3/ directory, so that it will be picked in the runtime.
> Remove rest.api.util jar from web-apps lib directory

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/pages/error-pages/401.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/pages/error-pages/403.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/pages/error-pages/404.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/pages/error-pages/500.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/pages/error-pages/error-page.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/error-pages/401.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/error-pages/403.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/error-pages/404.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/error-pages/500.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/pages/error-pages/error-page.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/error-pages/401.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/error-pages/403.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/error-pages/404.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/error-pages/500.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/pages/error-pages/error-page.html
HTML does not specify charset in the error pages in publisher, store and admin.
> Adding missing HTML boilerplate tags to error pages

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
This PR contains the REST API update property. 
This will comply with the JSON schema validation enable switch in API details configure page.
> fixes for enableSchemaValidation REST API property

- components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportException.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/CertificateDetail.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ExportFormat.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/lifecycle/LifeCycle.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/lifecycle/LifeCycleTransition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/CommonUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ExportApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ExportApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ImportApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ImportApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ExportApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ImportApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/admin-api.json
This PR adds API import-export functionality to Admin REST API. The same logic which was previously there in product-apim/modules/api-import-export is moved to carbon.apimgt.rest.api.admin and carbon.apimgt.impl modules. In addition, the following changes are applied on top of that.
1. Remove "'PUT /{apiId}" resource to update API. Add the same support to "POST /import/api" with optional query parameter "overwrite".
2. Fixed the issue of throwing an error when updating the thumbnail (calling update API with the state "CREATED").
3. Instead of searchAPI to find duplicate API name/context when importing new API, use isAPIAvailable() and isApiNameWithDifferentCaseExist() provider methods.
4. Fixed the issue of throwing gateway deploy error while importing a Published API or updating API …
> Add API import-export REST API and implementation

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
-The issue had occurred when adding i18n support for LifeCycleUpdate.jsx
-Fixes https://github.com/wso2/product-apim/issues/5313
> Fixing i18n issue in LifeCycle status changing message

- components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/SessionDataPublisherImpl.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/internal/APIKeyMgtServiceComponent.java
- pom.xml
product-apim: https://github.com/wso2/product-apim/issues/5120
- We have implemented a custom listener extending AbstractAuthenticationDataPublisher and overriding the publishSessionTermination() to invoke the token revocation when OIDC logout happens.
- Here, all the tokens for that particular user for all sessions will be revoked. Therefore, this will revoke any tokens from other active concurrent sessions for that particular user for relevant applications(admin_store,admin_publisher).
- Although, we are retrieving all the user authorized applications, we are revoking token related to 'admin_store' and 'admin_publisher' applications.
- This will not revoke any tokens related to user created applications.
> Revoke access tokens when user logging out using OIDC logout

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.old.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/Steps/DefaultAPIForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.old.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/Steps/components/DropZoneLocal.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/Steps/components/SelectPolicies.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/headersearch/SearchUtils.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIValidation.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/Wsdl.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/webpack.config.js
In this PR:
- Implement the SOAP to REST API creation wizard
- Add [hapijs/joi](https://github.com/hapijs/joi) for data validation as discussed in `dev@wso2.org:APIM React UI input validation`
- Update [`react-dropzone`](https://github.com/wso2/carbon-apimgt/pull/6872/files#diff-6c484a9723a4898e52fa13ae9a2b8ce7R51) library
- TODO: Need to fix regression issues of this upgrade
- Fix build issue https://github.com/wso2/product-apim/issues/5361
- Fix eslint issues which were shadowed by the above build issue
- Add joi [input validation](https://github.com/wso2/carbon-apimgt/pull/6872/files#diff-2663d0eea59f3a17a62ba034e5f5d72aR1) regex 
- Add new [data file](https://github.com/wso2/carbon-apimgt/pull/6872/files#diff-6d8822c9335410120e4f805becd85676R1) to validate & import WSDL definitions
> Implement SOAP to REST API creation

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
Fixes the below issue
ERROR in ./source/src/app/components/Apis/Details/index.jsx
Module not found: Error: Can't resolve 'lodash.isEmpty' in '/home/jenkins/workspace/platform-builds/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details'
@ ./source/src/app/components/Apis/Details/index.jsx 59:0-37 401:18-25
@ ./source/src/app/components/Apis/Apis.jsx
@ ./source/src/app/ProtectedApp.jsx
@ ./source/src/Publisher.jsx
@ ./source/index.jsx
> Fix build failure due to loadash import

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
This PR handles rejected subscriptions if it exists while adding subscriptions when creating a new version of an API.
> Handle reject subscription if it exists

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/logout/logout_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/Publisher.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Logout.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/jaggery.conf
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/services/logout/logout_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Logout.jsx
product-apim: https://github.com/wso2/product-apim/issues/5422
After user get's logged out from IDP session(where access tokens also get's revoked) and then in the logout callback jag cookies get's cleaned up and then user will be now redirected to /logout endpoint in react app where the user details in the local storage also gets removed.
> Adding feature to remove stored user details in localstorage when logging out

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
OAuth token authentication needs to be independent of the defined Key-Manager. It can be extensible when using 3rd party KM and if the same implementation is used in Store/Publisher UI related tasks it can break the flow because the requests are going to the 3rd party KM instead of using ours.
Directly accessing getTokenMetaData() method by creating an AMDefaultKeyManagerImpl class object instead of accessing the method through key-manager instance.
> Invoking identity OAuth2TokenValidationServices directly instead of using KeyManager instance

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.jsx
Change Create an API using WSDL UI so that File Input type is dependent on the Implementation type.
> Fix Create an API using WSDL UI

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
Issue:
/api/am/publisher/v1.0/apis/{apiId}/documents/{docId} and /api/am/store/v1.0/apis/{apiId}/documents/{docId} throws NPE with 500 status code if an invalid docId is provided
Fix:
404 not found error is provided as a fix 
Closes https://github.com/wso2/product-apim/issues/1643
> Fix get document request with invalid id issue

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SearchApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/TagsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ThrottlingPoliciesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/site/public/css/main.css
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/App.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/AppRouts.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/CustomRouter/BrowserRouter.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/TenantListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Apis.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Credentials/Wizard/Wizard.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/ApiTableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/CommonListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/CustomRouter/BrowserRouter.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/Header/GlobalNavbar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Base/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/LandingPage/ApisWithTag.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Shared/withSettingsContext.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/APIClient.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/data/Tenants.js
Following PR will add the tenant listing UI  and handle loading of data based on tenant for API Store. 
The Store REST API (v1) will now return the error code of **901300** if we have added a invalid tenant domain to x-wso2-tenant header.
To handle the routing of the tenant listing we will be adding an interceptor for the react router. This would require us to extend the currently react router implementation and its history implementation to plugin our custom interceptor [1].
I have added a basic UI to display the tenants, the UI/UX will be needed to be improved. I have created an issue to track this [2] 
[1] - https://github.com/dushansilva/carbon-apimgt/blob/8c139b28baef0543fc6b6bebf19a860c67f77e33/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/s …
> Tenant listing for API Store

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
This PR displays subscription availability box only when tenants are available. If tenants are not available the subscription availability box will not be displayed.
> Display subscription availability box only when tenants are there

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
SDK generation fails due to missing following JSON element in the swagger definition
`security:`
`  - default: []`
This was added to both swagger 2 and openapi3 definition.
Affected version: 3.0.0 M35
> Fix SDK generation issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/AdvertiseInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- docs/apidocs/store/v1/index.html
- docs/apidocs/store/v1/models/API.html
- docs/apidocs/store/v1/models/APIInfo.html
- docs/apidocs/store/v1/models/AdvertiseInfo.html
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/ExternalStores/ExternalStores.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/api.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Applications/Details/Subscriptions.jsx
This PR adds Publisher UI for publishing APIs for external stores. The capability of publishing to external stores is given only for  API is "PUBLISHED" state. 
This PR updates the Store UI for displaying advertised APIs (published as external store APIs).  Only API Documents and API resource views are available for the advertised APIs.
> Add Publisher Store UI for publishing APIs for external stores

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/GraphQLSchemaDefinition.java
To Graphql APIs to support Basic Authentication and JWT, as scope related details, it is needed to be added throttling per operation and auth scheme per operation to local entry, since the swagger definition has not been stored such details.
> Adding Throttling and auth scheme to local entry for graphql APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fix for https://github.com/wso2/product-apim/issues/5608
The issue was happening due to default authorization header is not set. It was set as null if this field is not passed when creating the API. 
As the fix Set it to a default value if this is empty.
> Fix for store console API invocation issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Environments/Environments.jsx
Displaying multiple access urls for microgateway labels separated by commas
> Displaying multiple access urls separated by commas

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/APIThrottleConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
Add Retry-After header support for the throttled-out response. Retry-After is sent as http-date 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After#Syntax
Sample response 
< HTTP/1.1 429 
< activityid: 3f2af26c-d752-4022-91d8-d646a636ebd8
< Access-Control-Expose-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction
< Retry-After: Wed, 18 Sep 2019 05:34:00 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET
< Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction
< accept: application/json
< Content-Type: application/json; charset=UTF-8
< Date: Wed, 18 Sep 2019 05:33:23 GMT
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact …
> Add Retry-After header support for throttled-out response

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
same security definition is added multiple times. this fix prevents it
> Fix adding multiple security element issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Endpoints/Prototype/GenericResource.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/ExternalStores/ExternalStores.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/MediationPolicies/FaultFlow.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/MediationPolicies/InFlow.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/MediationPolicies/OutFlow.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/MediationPolicies/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Monetization/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Properties/Properties.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/index.jsx
Restrict publisher UI elements for users with creator permissions and publisher permissions accordingly. [1]
[1] https://github.com/wso2/carbon-apimgt/wiki/Permission-validation-on-the-Publisher-UI-elemets-for-API-update
> Add Permission validation on the Publisher UI

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberServiceTest.java
Fix following intermittent unit test failure,
APIKeyMgtSubscriberServiceTest.createOAuthApplicationByApplicationInfo:95 » NoClassDefFound
APIKeyMgtSubscriberServiceTest.testDeleteOAuthApplication:371 » NoClassDefFound
> Fix intermittent test case failure

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Environments/Environments.jsx
This PR includes UI improvements to the display info box when no microgateway labels are available.
> UI improvements for display box when no labels are available

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
title and version is missing in the swagger definition when API is created using a wsdl. 
Fixes https://github.com/wso2/product-apim/issues/5693
> Fix missing title and version in swagger definition

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
This PR contains changes to fix the issue reported in https://github.com/wso2/product-apim/issues/5577. As per current implementation, wildcard character - *, is not allowed to have within Access-Control-Allow-Origin.
> Add fix for wso2/product-apim#5577

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
Subscription via API Credentials page was broken due to below error.
[2019-09-27 16:22:20,981] ERROR - GlobalThrowableMapper One or more request body parameters contain disallowed values.
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 1, column: 123] (through reference chain: org.wso2.carbon.apimgt.rest.api.store.v1.dto.SubscriptionDTO["throttlingPolicy"])
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.9.9.3.jar:2.9.9.2]
at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343) …
> fix error in subscription via API Credentials page

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Tags.jsx
Resolves https://github.com/wso2/product-apim/issues/6040
Restricted the maximum characters allowed to 30 as in [1]
[1] https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-old/site/themes/wso2/templates/item-design/js/api-design.js#L1484
> Fix for product-apim#6040

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
This PR includes the step for API creation in the Overview page.
> Overview steps UI

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
This PR fixes the white space issue in the URL when redirected to dev portal in the overview component.
> Fixing white space issue when redirected to dev portal

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Endpoints.jsx
Fix https://github.com/wso2/product-apim/issues/6203 - Endpoint Security is displayed blank in API overview page
> Overview endpoint security

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx
Fixes [wso2/product-apim#5719](https://github.com/wso2/product-apim/issues/5719)
> Fix for add and clear button in resources page is too close

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/SelectEndpoint.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
1. https://github.com/wso2/product-apim/issues/6115
2. https://github.com/wso2/product-apim/issues/6144
3. If no endpoints are provided for the API and a user tried to add a certificate there was an error.
Issue [3] was fixed by providing an error helper text with the required action. If no endpoints are selected/available Save button will be disabled.
> Fixing certificate issues

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Operations.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Resources.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Operations/Operation.jsx
Fixes: 
When the API contains many resources/operations, they have been displayed in a scrollable div and once click the Show More button, it will be redirected to the corresponding resource/operation pages.
For Graphqls
1. https://github.com/wso2/product-apim/issues/6030
For Rest APIs
2. https://github.com/wso2/product-apim/issues/5903
Fix the issue in Graphql Import
> Fixing issue in Overview page and import schema

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js
This PR fixes the issue https://github.com/wso2/product-apim/issues/5848. After this change, "/t" or "/t/" cannot be used in the context
> Fix the issue in validating API context

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
With this fix, the resource level throttling will work in Basic Authentication and JWT Authentication flow. Additional conditional group validation is to be completed.
> Set default condition group to verbInfoDTO in JWT and Basic Auth flow

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/ThrottlePolicyTemplateBuilder.java
Fix evaluated conditions not added properly when the policy is added based on ip range in advance throttling policies.
> Fix adding evaluated conditions for Advance throttling policies.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js
Fixes https://github.com/wso2/product-apim/issues/5541 (1 and 2)
1. The error message should be more user-friendly (without a regex preferably)
2. "value" should be fixed
> Add modified (simplified) error messages for api create form.

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/OpenAPIUtils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidatorTestCase.java
- This will enable the scope and role validation in the JWT and Basic Auth flow
This will fix https://github.com/wso2/product-apim/issues/6224
- Allow retrieval of URITemplates from swagger in the local entry in OAuth2 flow
> Update retrieval of URITemplates, scopes and roles from swagger in the local entry

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionAvailability.jsx
This PR adds a circular progress when saving subscription availability.
> Adding circular progress when saving subscription availability

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/OverviewDocuments.jsx
There is an issue in displaying documents in overview page (total number of comments are used - [1]). This PR fixes it.
[1] https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx#L523
> Fix issue in listing docs in overview page

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/template.jag
This PR allows avoiding abnormal behaviors in Publisher when micro-gateway label is attached.
https://github.com/wso2/product-apim/issues/6063
https://github.com/wso2/product-apim/issues/6064
Avoid case insensitive label name  when adding:(related-https://github.com/wso2/product-apim/issues/6111 )
> Fix for adding case sensitive Micro-gateway label and disable editing the label name 

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionAvailability.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
This PR has the following changes,
- Fixes issue https://github.com/wso2/product-apim/issues/6424
- Remove extra space when selecting specific tenants
- Remove subscription availability label
> Add headings to Subscription elements

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
Fix https://github.com/wso2/product-apim/issues/6143
In APIM 3.0, we store cert alias with the full endpoint URL in the endpoint-conf where we previously used the hostname extracted from the URL.
> Fix certificate export issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js
- This PR improves the regex of API name and context.
- This PR will get rid of the space error displayed when nothing is entered to the text box.
> Improve regex of API name and context

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
Fixes one issue stated in [wso2/product-apim#6454](https://github.com/wso2/product-apim/issues/6454)
> Fix simple typo in Create Credentials component

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/filter/URLMappingFilter.java
Fix: https://github.com/wso2/product-apim/issues/6480
Add the facility to override store webapp's static files ( css, images, fonts etc.. ).
Add following property to jaggery.conf to enable it.
"filters":[
{
"name":"URLMappingFilter",
"class":"org.wso2.carbon.apimgt.impl.filter.URLMappingFilter"
}
]
"filterMappings":[
{
"name":"URLMappingFilter",
"url":"/site/public/*"
}
]
> Add url mapping filter

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
1. Fix https://github.com/wso2/product-apim/issues/6438 - change the "Back to APIs" to "Back to Products" for product list.
Now -
2. Improve convert to json/yaml in definition page.
Now -
Before -
> UI improvements

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/APIMJWTGenerator.java
This change affects only the access token. The backend JWT will not be affected.
> Remove padding in JWT token to comply with the standard

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/override/Readme.txt
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
Add README file to store webapp static file override.
> Add readme file and fix UI issue

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/BotDetectionMediator.java
This fixes an error thrown when the _OpenService synapse file for bot detection is modified and deployed after startup(hot deployed).
> Fix bot detection cache initialization.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/StartupServiceComponent.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/listeners/ServerStartupListener.java
This PR adds a server startup listener to copy identity jsp extension files in <API-M_HOME>/repository/resources/extensions folder if any, into authenticationendpoint and accountrecoveryendpoint webapps extensions folder.
Fixes https://github.com/wso2/product-apim/issues/6468
> Add functionality to copy identity extension pages on server startup

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
- We are currently depending on throttle web app and throttle configs for revoked JWT token retrieval. 
- The publisher profile is removing this webapp with its profile optimizer and disabling blocking conditions config. 
- In order to stop the web service call in this profile, we are going to depend on blocking conditions config.
> Fix jwt token retrieval issues in publisher profile

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json
This PR adds scope related to the Internal/analytics role which is going to be used in the analytics-apim distribution.
> Add scope related to Internal/analytics role

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/PublisherAlertConfigurator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/StoreAlertConfigurator.java
In the current implementation, the alert subscriptions are stored in db even if the sp configuration failed. This PR fixes this issue.
> Fix alert subscription persistance issue.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/avatar/Avatar.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/settings/SettingsButton.jsx
This PR fixes the following
- Capitalization issue in Settings button
- Made logged in user and settings button bold
.
> Fix capitalization issue in Settings button

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Delete.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Edit.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Listing.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/TextEditor.jsx
Fixes https://github.com/wso2/product-apim/issues/5824
This adds the api docs edit/delete permission to the publisher users too. (it was set to allow for only creator users before this). Change the permission conditions in the UI too accordingly.
> Fix api documentation update/create permssion issues

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx
This PR adds spacing after the icons in devportal.
> Add spacing after the icon

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtRemoteUserStoreMgtService.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/resources/META-INF/services.xml
- service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/pom.xml
- service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/src/main/resources/APIKeyMgtRemoteUserStoreMgtService.wsdl
Current implementation is using authAdminService to authenticate a user. This does not work when the user doesn't have login permission.
This PR introduces a new APIMKeyMgt service for authentication and role retrieval. The service needs to be authenticated with super admin credential. However, the operations can be called for any tenant user.
> Fixing basic authentication for APIs

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticatorTest.java
Cross tenant domain requests shouldn't be allowed for basic auth.
> Fix cross domain requests in basic auth

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/alert/AlertTypesPublisher.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/alert/AlertTypesPublisher1Test.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/AlertMgtConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/PublisherAlertConfigurator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/StoreAlertConfigurator.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-old/modules/configure-alert/alerts.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-old/modules/configure-alert/alerts.jag
Rename alert configuration siddhi apps, in order to fix error which occurs when configuring alerts from store/publisher without enabling alerts in analytics server
Related PR: https://github.com/wso2/analytics-apim/pull/704
> Rename alert configuration siddhi apps

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/threatprotection/analyzer/XMLAnalyzer.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/threatprotection/utils/ThreatProtectorConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
When error count is more than one, it gives a common error message in below.
<am:fault xmlns:am="http://wso2.org/apimanager">
<am:code>400</am:code>
<am:message>Bad Request</am:message>
<am:description> # 2 errors in the request </am:description>
</am:fault>
Now it gives specific error messages.
Sample error message:
<am:fault xmlns:am="http://wso2.org/apimanager">
<am:code>400</am:code>
<am:message>Bad Request</am:message>
<am:description>**Schema validation failed in the Request :#/photoUrls: expected type: JSONArray, found: String, #/tags: expected type: JSONArray, found: JSONObject** </am:description>
</am:fault>
> improves error messages in response validator

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Sdk.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/CommonListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx
1- Making the overview info collapsable panel expanded by default.
Following are requirement for cloud users expecting via the theme.
2 - Added the ability to hide the sections of the api details page from theme except the overview page.
3 - Added the ability to add a banner to the devportal via the theme ( image/text )
4 - Added the ability to show hide the ratings via theme.
5 - The correct thumbnail is not coming when we go to the details of an api fixed.
6 - Added the ability to allow a given set of sdks to be displayed in the SDKs section
6 - Added id's to the UI components to make it possible to style via the main.css file ( just in case for edge cases. )
> Making the overview infor collapsabe panel expanded by default

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/OverviewDocuments.jsx
Fix issue in redirection in following section of overview page:
Currently it redirects to '/docs' endpoint, hence it renders page not found:
> Fix issue in redirection to document listing page

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/CommonListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx
Rotate the tagCloud text 180 and fixed some theme parameters missing in the application page.
Note that the following screens are snapshots from the test theming attempt. NOT THE ONE IN THE DEFAULT PACK.
> Fixing tag cloud link text rotation and adding missing style classes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
In windows file.seperator is "\\" .
But when we construct registry paths we need to use the seperator '/'
> fix registry path issue in windows prod-apim#6754

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SettingsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
- docs/apidocs/store/v1/models/APIInfo.html
- docs/apidocs/store/v1/models/Settings.html
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiThumb.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/CommonListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/ApiKey.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Validation.jsx
product-apim: https://github.com/wso2/product-apim/issues/6760
product-apim: https://github.com/wso2/product-apim/issues/6699
- Changing the APIInfo REST API to send "monetizationLabel" which can be "FREE", "PAID" ,"FREEMIUM" and the logic to check which label for the API.
- Changing the settings rest api to get the monetization enabled value from tenant.conf.
- Retrieving the settings response using settings context in store and passing the enableMonetization attribute to API Context.
- Checking if the monetization enabled and adding the label to the API Image Card.
- Adding number validation for API Key timeout field using joi validation library. Now the generate button is active only when numbers are provided and error msg is displayed as helper text.
APIM 3.0.1 UI REST WUM
> adding monetization lables to API image

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
This fixes the grammar mistake "Gateway is not existed for the current API Provider" in APIProviderImpl as "Gateway does not exist for the current API Provider"
> Correcting the Grammer Mistake

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
This provides the capability to import and export client certificates added for mutual ssl enabled APIs.
These certificates are saved in a file in client_certificates.yaml under Meta-information section of the Zip file
See the below structure of the exported zip file
.
└── PizzaShackAPI-1.0.0
├── Docs
│   ├── FileContents
│   │   └── PizzaShackAPIDoc.pdf
│   └── docs.yaml
├── Image
│   └── icon.jpeg
└── Meta-information
├── api.yaml
├── client_certificates.yaml
└── swagger.yaml
Following is the sample content of the client_certificates.yaml file.
-
alias: cert1
certificate: LS0tLS1CRUdJ.,.....
tierName: Gold
apiIdentifier:
providerName: admin
apiName: PizzaShackAPI
version: 1.0.0
-
alias: cert2
certificate: LS0tLS1CRUdJ.......
tierName: Silver
apiIdentifier:
providerName: admin
apiName: …
> Add mTLS client certificate import/export capability to tool

- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/APISynchronizer.java
- components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/util/APISynchronizationConstants.java
If a sequence contains empty namespace as xmlns="", when deploying that sequence in the  on premise gateway in cloud  it undeclares the empty namespace. This caused to not to work payload factory mediators properly when deploying in the onpremise gateway.
This fix will fix the aforementioned issue.
> Fix empty namespace undeclaration issue when deploying sequence in on premise gateway(cloud)

- components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSTaskManager.java
product-apim : wso2/product-apim#6816
changing the getConnectedTaskCount() method to a synchronized block and adding null check for connection url.
> resolving intermittent re-connecting issue

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
Fixes https://github.com/wso2/product-apim/issues/6728
We will not show requirements for next transitions in published state.
> Fixing issue #6728

- components/apimgt/org.wso2.carbon.apimgt.keymgt/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/ResourceConstants.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/ExtendedJWTBearerGrantHandler.java
- pom.xml
product-apim: wso2/product-apim#6765
- Extend the JWTBearerGrantHandler class and override the validateScope() method to retrieve roles and setting it to UserAttributes in the OAuthTokenReqMessageContext.
- Change the RoleBasedScopesIssuer to retrieve those roles from the Token request Message Context and setting it to user roles if the grant type is JWT bearer grant type.
> Adding role based scope validation feature for JWT Bearer Grant

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
Fix https://github.com/wso2/product-apim/issues/6878
This fix will only fix the issue for OpenAPI 3.0. 
For OpenAPI 2, we would need to find a way to customize the hosts in the swagger UI, because of OpenAPI2 only supports one host.
> Fix Swagger UI to show corresponding hostname for transport schemes

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/DocThumb.jsx
When we click on a document that is in the search results listing, the user is being redirected to an incorrect URL.
This PR fixes that issue.
> Fix document link in search result listing

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java
- pom.xml
This PR removes unused imports and sync the carbon.identity-oauth2-grant-jwt.version with that in product apim.
> Sync JWT grant version with product-apim

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
Fix https://github.com/wso2/product-apim/issues/7068
This PR  prevents API getting created with a duplicate scope by validating the scope existence prior to API creation.
> Fix https://github.com/wso2/product-apim/issues/7068

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fixing wso2/product-apim#7106
If publisher access control is set to restrict to roles and store visibility to visible to my domain, store visibility is set only for the restricted roles of the publisher. With this PR, even though publisher access is restricted, store visibility to visible to my domain will set null as the role in registry.
> Fix publisher restriction overriding visible to my domain accessibility

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json
This PR contains the following changes:
In 2.0.0, admin role is not added as a role for apim:subscribe scope, if any user migrates from 2.0.0 to 3.0.0, admin of migrated tenant will not be able to login to dev portal due to forbidden error.
In order to fix this issue, this PR contains changes to add admin role to apim:subscribe scope on the fly. Once, this role is added, there will be a meta entry added to tenant-conf.json as in the format given below, in order to make sure that it is not getting overwritten again.
"Meta": {
"Migration": {
"3.0.0": true
}
}
Related git issue - wso2/product-apim#7188
> Update tenant-conf migration to handle missing roles to handle migration

- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
The test initialization code uses new Date().toString(). Parsing this string with a SimpleDateFormat instance that is initialized with a non US locale does not work.
This change stabilizes the test results for people who run their laptop in another default language than us englisch. It makes the `man clean install` result more reliable.
> Update APIUtilTest.java to make it work anywhere on earth

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/AbstractWSDLProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11ProcessorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL20ProcessorImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDLProcessor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPOperationBindingUtils.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/wsdl/SOAPOperationBindingTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.jsx
Currently, only creating a SOAP to REST API by WSDL URL is supported. 
This PR adds support to import a WSDL file or zip and create a SOAP to REST API.
Fixes: https://github.com/wso2/product-apim/issues/7182
> Support WSDL file/archive upload in SOAP2REST

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPToRESTConstants.java
This PR fixes wso2/product-apim#6973. Currently, elementFormDefault attribute is not considered when adding namespace prefix for complex types. This PR adds it. When generating swagger definition from the provided wsdl, an attribute named as **x-namespace-qualified** is added to complex type definitions in swagger and it is used to check whether the namespace prefix needs to be added or not.
> Add elementFormDefault support to SOAP to REST APIs

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SequenceUtils.java
Fixes wso2/product-apim#7297. There is an issue in sequence generation when complex type definition refers another complex type definition in nested manner. In this case, Swagger generation is successful, but the generated sequence is not complete.
> Fix issue when iteratively referring complex types definitions

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPToRESTConstants.java
1. Fixes https://github.com/wso2/product-apim/issues/7132. Porting the fix done to 2.2.0
2. Fixes wso2/product-apim#7145. When there is no namespace set, payload mediator adds it's default namespace (http://ws.apache.org/ns/synapse) to request. It is fixed by adding an empty namespace as xmlns="" mentioned in [1].
[1] https://docs.wso2.com/display/EI650/PayloadFactory+Mediator#PayloadFactoryMediator-Example4:Suppressingthenamespace
> [3.1.0] SOAP to REST fixes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
Add mutual SSL to the API definition.
Renamed the x-wso2-api-security to x-wso2-application-security.
Fix https://github.com/wso2/product-apim/issues/7388
Related to https://github.com/wso2/product-apim/issues/7205
e.g.
x-wso2-transports: 
http: true
https: false
mutualssl: "mandatory"
x-wso2-application-security: 
security-types: 
- "oauth2"
- "api_key"
optional: false
> Add mutual SSL to the API definition.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/impl/RegistrationServiceImpl.java
product-apim: https://github.com/wso2/product-apim/issues/6735
Adding SP property to disable logout consent page when creating the SP using DCR request by default. Users can re-enable by editing the SP App from carbon console if needed.
> Disabling logout consent page

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtResponseHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/DataPublisherUtil.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeFaultPublisherDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeRequestResponseStreamPublisherDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/FaultPublisherDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/RequestResponseStreamDTO.java
- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/ThrottlePublisherDTO.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
- Support custom analytics data publishing
Custom attributes can include the analytics event by adding a request/response mediation sequence. Custom attributes can be introduced in request and response path. so it support include request/response related information such as headers and query params.
The sample mediation sequence is as follows. 
* request path
```
<?xml version="1.0" encoding="UTF-8"?><sequence xmlns="http://ws.apache.org/ns/synapse" name="request">
<propertyGroup description="A group of properties to include in the greeting.">
<property name="apim.analytics.request.properties" scope="default" type="STRING" value="name,age"/>
<property name="name" scope="default" type="STRING" expression="$trp:name" />
<property name="age" expression="$url:age" scope="default" …
```
> Support custom analytics data publishing

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Add config to consider jwt token as an opaque token. This will pass the jwt token to the keymanager interface to validate instead of validating it from the gateway. 
To enable this add following. (default behavior is to validate the jwt token from the gateway. )
```
[apim.oauth_config]
set_jwt_as_opaque_token = true
```
> Add config to consider jwt token as an opaque token

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx
POST /applications/{applicationId}/generate-keys has a **additionalProperties** element in the body and this is not mapped in the dev portal.
> Add missing property for key-gen api

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
Fix https://github.com/wso2/product-apim/issues/7468
Add following extension to the oas definition
```
x-wso2-response-cache: 
enabled: true
cacheTimeoutInSeconds: 300
```
> Add response cache extension

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
**Fix https://github.com/wso2/product-apim/issues/7210**
The validation was recently modified with https://github.com/wso2/carbon-apimgt/pull/7904/files to fix issue https://github.com/wso2/product-apim/issues/6859. But because of that modification, https://github.com/wso2/product-apim/issues/7210 has occurred. 
It makes sense to remove from the validation and default value assignment for apiLevelPolicy from REST API Level, as this scenario is handled in the DAO layer when adding URL Templates https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java#L6185.
So when an API is created using POST /apis, if the apiLevelPolicy is given, the resource level policies will be neglected. If the …
> Remove the default assignment of APILevel policy from REST API Layer | Fix error when exporting API without endpoints

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/CommonListing.jsx
Fixes https://github.com/wso2/product-apim/issues/7483
> Fix issue with expanded category left pane overlapping api listing content

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/SystemApplicationDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/SessionDataPublisherImpl.java
Fixes https://github.com/wso2/product-apim/issues/7410
Getting the system apps from the database against the tenant and check against the apps authorized for the logout initiated user and revoke all the access token related to those apps.
> Removing the hardcoded system apps names in the logout handler and retrieve from system apps db table

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
Fix for the issue reported in 
https://github.com/wso2/product-apim/issues/6926
as follows
> Adding per api subscription count to overview page

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Endpoints.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Endpoints.jsx
Remove production and sandbox endpoints in Overview and Run-time Configurations  if API is prototyped.
Fixes https://github.com/wso2/product-apim/issues/6906
> Remove production and sandbox endpoints in Overview and Run-time Configurations UI if API is prototyped.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx
Added an info message which appears when disabling HTTPS with mutual SSL enabled. 
Fixes wso2/product-apim#7398
> Mandated HTTPS transport if mutual SSL is in use.

- components/apimgt/org.wso2.carbon.apimgt.hostobjects/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObject.java
- pom.xml
This PR,
Fixes a classDefNotFound error for commons-io FilenameUtils while uploading tenant theme.
Whitelists .ico extension as we are supporting favicon uploads with tenant login themes feature.
> Fix issues in tenant theme upload

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/ScopesIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/AbstractScopesIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIManagerOAuthCallbackHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/util/APIManagerOAuthCallbackHandlerTestCase.java
As of now, we only validate scopes in the grant handler when issuing tokens, we do not perform scope validation in the authcallback during /authorize flow. This PR fixes https://github.com/wso2/product-apim/issues/7331
> Fix scope validation during Implicit grant flow 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/LeftMenuItem.jsx
Fixed Issue
https://github.com/wso2/product-apim/issues/7535
[UX] [Devportal] When clicking an API shows the overview page but "try-it" menu is selected
> Fixing issue [UX] [Devportal] When clicking an API shows the overview page but "try-it" menu is selected

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/ScopesIssuer.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/ScopesIssuerTest.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/util/APIManagerOAuthCallbackHandlerTestCase.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
The PR will provide the capability to extend the scope issuer in the product through a config. In order to extend the scope issuer,  the following config should be given in deployment.toml
[apim.oauth_config]
scope_issuer="<fully qualified class name of the extension>"
> Adding the capability to extend the scope issuer

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java
Currently the Authenticator data structure is private. Making this protected allows users to register a customized authenticator.
We have attempted to provide thsi flexibility by making the initializeAuthenticators() method protected, but we do not get a real
benifit from this if the Authenticator data structure remains private.
> Enable Authenticator access when extending handler

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
This PR fixes issue https://github.com/wso2/analytics-apim/issues/997. From APIM side, the event published when a web socket api was consumed, did not included the api context. Instead a dash character(-) was sent. So when siddhi aggregations are happening like in [here](https://github.com/wso2/analytics-apim/blob/v3.1.0-beta/features/org.wso2.analytics.apim.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi#L63) aggregations used the api context and since all the web sockets have the api context as "-" analytics shown in the dashboards were incorrect(Even the values stored in the aggregation tables were incorrect due to this).  
With this PR, api context is included in the published event from APIM side.
> Include context in the event for a web socket API

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/idp.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/introspect.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/login_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/logout/logout.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/logout/logout_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/la/log-analyzer-proxy.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/idp.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/introspect.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout_callback.jag
Jaggery Log object have been created without using the default constructor which leads to log messages not been printed
at jaggery level. This fix rectifies that issue.
> Fix invalid jaggery log object construction

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
The following format[1] of x-wso2-transport extension was later changed to [2] to support mutual ssl. But after this change, format [1] gives parsing issues.
```
[1]x-wso2-transports:
- "http"
- "https"
[2]x-wso2-transports:
http: true
https: true
mutualssl: "mandatory"
```
This causes backword compatibility issues. Hence the extension was changed to below
```
x-wso2-transports:
- "http"
- "https"
x-wso2-mutual-ssl: "mandatory"
```
Fixing https://github.com/wso2/product-microgateway/issues/1083
Related to https://github.com/wso2/carbon-apimgt/pull/8153
> Add x-wso2-mutual-ssl extension and change transport extension

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/CORSConfiguration.jsx
Fixes https://github.com/wso2/product-apim/issues/7600
**Need to add in the doc that user needs to enable CORS in order to user apikey in the try-out console.**
> Fixes issue apikey not working in try-out console

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
App security extension should be given in the resource level. Otherwise, the default oauth2 scheme defined at each resource level will override application securities.
> Add app-security extension at resource level

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/avatar/Avatar.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/avatar/AvatarMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/rightTopMenu/RightTopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/rightTopMenu/RightTopMenuLinks.jsx
Added extension points to the top right-hand side menu. This is to let the cloud developers override the menu without maintaining our code at there side.
> Adding extension points to header menu

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/CheckboxLabels.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
In publisher portal, user can publish a created API which doesn't have any application layer security and only having mutual SSL as security scheme. 
Fixes https://github.com/wso2/product-apim/issues/7522
> Enable publishing capability when mutual SSL is selected as the only security scheme

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
Fixes https://github.com/wso2/product-apim/issues/6530.
If an API doesn't have older versions, the lifecycle checklist item: "Deprecate old versions after publishing the API" should not be listed.
> Modify lifecycle checklist generation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
Description:  Remove all MGW supported extensions from APIM When a micro gateway compatible swagger file with vendor extensions is imported.
Fix: https://github.com/wso2/product-apim/issues/5162
> Fixing Vendor Extensions visible issue in swagger editor

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx
This fix is fixing the issue in a more general way. 
Checked the following cases.
Add 120 apis.
Navigate to a page > 2 when the number of rows per page is 10.
Now change the number of rows per page to 100.
The page number drops to 0.
Add 120 apis.
Navigate to a page > 1
Now delete all the APIs leaving only leaving one API using Rest API. Or deploy another instance where it has only one API.
The page number drops to 0 and local storage is cleared.
> Fixing pagination issue in publisher

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
Description:
If the API is moving across the environments, it has no idea whether this is a new API or API that created from an existing version. In the next environment, it might not have the same applications and etc. Therefore, subscriptions shouldn't be migrated to next environments.
> Fixing subscriptions are auto assigning issue to new versions

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/caching/CacheProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/handlers/TenantConfigMediaTypeHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/recommendationmgt/RecommenderDetailsExtractor.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Changed the recommendations cache and tenant config cache get methods. Previously, APIUtil.getCache(cacheManagerName,  cacheName, modifiedExp,accessExp) was used to get cache and this might give errors in expiry times. 
Changed the two configs to standard approach with two different methods to create and get the cache in CacheProvider.
> Changed recommendations and Tenant config Cache

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleConditionEvaluator.java
Fix https://github.com/wso2/product-apim/issues/7737 applies for both JWTClaims and QueryParam Throttling. 
For example, a JWTClaim thorttling execution plan will look like this
`...SELECT messageID, (apiTenant == 'abc.com' and resourceTier == 'JWTClaom' AND (regex:find('1.0',cast(map:get(propertiesMap,'http://wso2.org/claims/version'),'string')))) AS isEligible, str:concat(resourceKey,'_condition_232') AS throttleKey, ...` 
Note the **regex:find**
The problem is that in GW, we do a match for the entire string instead of finding for any substring.
> Fix regex pattern find issue for sub string values in JWTClaims and QueryParam Conditional Throttling

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ExportApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/ExportApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ExportApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/ExportApiUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/resources/admin-api.json
During the API export process, the API Provider is a mandatory value. But when having more API providers, it is hard to define the correct API provider for each export request. 
Resolves issue https://github.com/wso2/product-apim-tooling/issues/173
This fix makes API Provider optional by considering the logged-in user's tenant domain and checking it with the API provider's tenant.
- Get currently logged in user name. 
- Get currently logged in user’s tenant domain (API requester domain).
- If the command was executed without the provider name (since it was made optional), get the API provider name using the API name, version which matches with the API requester domain. If such API provider was not found, display an error message.
- If the command was executed with the provider name, steps …
> Make API provider name optional when exporting an API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantOracle.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantPostgreSQL.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsDB2.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsH2MySQL.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/mappings/ApplicationMappingUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/205
- Perform the changes to list applications in an environment without specifying the owner or by specifying the owner
- Change the database queries to retrieve APPLICATION_STATUS as well.
If the owner is not specified based on the tenant ID all the application for that particular tenant was retrieved using getApplicationsByTenantIdWithPagination. The database queries associated with this function were changed since earlier it does not retrieve "APPLICATION_STATUS".
Assume there is an environment named "test".
- When someone has invoked the below command to list applications for an environment **without specifying the owner**, it should list all the applications belongs to the tenant (which the currently logged in user belongs) …
> Modifying listing all the applications for a tenant

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/216
- If an API is exported with a UI thumbnail icon (which is not an image but in .json format), include it in the exported archive.
- If an API is imported with a UI thumbnail icon (which is not an image but in .json format) included in an archive or directory, import it successfully. (Need to work when updating an API as well)
- When exporting an API, earlier if the thumbnail is in .json format it was skipped. But now if the thumbnail is in .json format the particular file will be exported in the archive as a .json file.
- When importing an API, earlier if the thumbnail is in .json format it was skipped. But now if the thumbnail is in .json format the particular file will be imported and will be stored in the registry as a …
> Importing/exporting API thumbnail icon from UI

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
Change the exception handling when importing/exporting API thumbnail icon from UI. 
Fixes: https://github.com/wso2/product-apim-tooling/issues/216
- Change the generic exception to specific ones.
- Justify the need more using comments
- String mimeType = URLConnection.guessContentTypeFromName(fileName) decides the mimetype for image extensions such as .jpg, .jpeg, .png, .gif, .bmp. But if the file type is .json URLConnection returns null. 
- So, used JsonParser which will identify whether it is a valid .json file or not.
- If it is not an image or not a JSON file then the exception should be handled without breaking the flow. (In here the thumbnail will not get imported, but the API will get successfully imported without the thumbnail) 
- https://github.com/wso2/carbon-apimgt/pull/8384
- …
> Modify exceptions when importing/exporting API thumbnail icon from UI

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
This PR includes the following changes:
- GEN.TEST KEY was changed to GET TEST KEY
- Both newly generated tokens for Api Key and Oauth are now persisted.
- Pre Selected Gateway environment displayed.
> Improvements to TryOut console

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/idp.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/utils.js
Fixes: https://github.com/wso2/product-apim/issues/7809
When custom URL is enabled, direct the user to the authentication endpoint containing the custom URL.
If customURL is enabled, assign customURL value to serverURL.
JDK 1.8.0_241
Ubuntu 18.04.4 LTS
> Directing custom URL enabled tenant to appropriate authentication endpoint

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/DefaultClaimsRetriever.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/AbstractAPIManagerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/token/DefaultClaimsRetrieverTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/SubscriptionsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/SubscriptionsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ClaimDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SubscriberInfoDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SubscriptionsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/ApplicationMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/SubscriptionMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- docs/apidocs/publisher/v1/index.html
- docs/apidocs/publisher/v1/models/Claim.html
- docs/apidocs/publisher/v1/models/SubscriberInfo.html
- docs/apidocs/publisher/v1/operations/Subscriber.html
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
This PR adds new Publisher REST API to retrieve subscriber-info. REST API path is : `/subscriptions/{subscription-id}/subscriber-info`
Request format:
`curl -X GET "https://localhost:9443/api/am/publisher/v1/subscriptions/{subscriptionId}/subscriber-info" -H  "Authorization: Bearer xxxxxxx"`
Sample request:
`curl -X GET "https://localhost:9443/api/am/publisher/v1/subscriptions/04b306b6-49da-49fc-88ae-feb6dc87150b/subscriber-info" -H  "Authorization: Bearer 33f03b51-6f97-3076-9eb0-0045b04e1706" `
Sample response:
```
{
"name": "user1@test.com",
"claims": [
{
"name": "First Name",
"value": "user1",
"URI": "http://wso2.org/claims/givenname"
},
{
"name": "Last Name",
"value": "user1",
"URI": "http://wso2.org/claims/lastname"
},
{
"name": "Email",
"value": "user1@wso2.com",
"URI": …
```
> Add REST API to retrieve subscriber-info

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/SearchResultMappingUtil.java
Fixes: https://github.com/wso2/product-apim/issues/7959
Retrieving provider name correctly with @ symbol instead of -AT- in Publisher REST API Unified Search.
In [carbon-apimgt/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/SearchResultMappingUtil.java](url) file, when setting the provider name replaced the -AT- with @ using the function **replaceEmailDomainBack(**).
- When a user retrieves details on APIs or API Products using the REST API [here](https://apim.docs.wso2.com/en/next/develop/product-apis/publisher-v1/#/Unified%20Search), the API provider name will be retrieved correctly with @ sign, if it contains an @ sign actually.
- When a user searches for API or API Product details by logging into …
> Retrieving provider name correctly with @ symbol in Publisher REST API Unified Search

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/doc/model/APIResource.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/277
When updating an API using **_apictl import-api_** with **--update** flag, enforce a condition to check whether any resources that have been used by any API Product has been removed from the swagger definition of the corresponding API.
1. Moved the function named **getRemovedProductResources** (which was in [carbon-apimgt/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java](url)) to impl level (APIProviderImpl.java). 
2. Wrote a new function named **getResourcesToBeRemovedFromAPIProducts** in APIProviderImpl.java to use that moved function.
3. That function was used to check whether any of the resources should be removed from the …
> Checking removed resources that have already been used in API Products when updating an API

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductSearchResultDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/SearchResultMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- docs/apidocs/publisher/v1/models/APIProductSearchResult.html
Currently, the status and the version of an API Product cannot be retrieved. It will be fixed here.
Provide the functionality to retrieve API Product version and the status through Publisher REST API as support for API Products listing in API Controller.
- Set the status of an API Product in SearchResultMappingUtil.java 
- Defined the API Product version in publisher-api.yaml
- Set the version of an API Product in SearchResultMappingUtil.java  
- When a user is using the Publisher REST API (or API Controller) to list API Product details, the version and the status can be retrieved through the REST call.
https://github.com/wso2/product-apim-tooling/pull/287
- Ubuntu 18.04.4 LTS
> Adding the functionality to retrieve API Product status and the version

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
According to [this](https://apim.docs.wso2.com/en/latest/learn/design-api/api-versioning/deprecate-the-old-version/#publish-the-new-version-and-deprecate-old-versions) documentation, only when older versions are available, `Requires re-subscription when publishing API` lifecycle checklist should be displayed.
Currently, when generating the lifecycle checklist, only `Depreciate older versions` item is filtered.
This PR will also filter by the `Requires re-subscription when publishing API` checklist item when generating checklist items.
Fixes: https://github.com/wso2/product-apim/issues/6530
> Require re-subscription lifecycle checklist item displaying

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx
Fixes: https://github.com/wso2/product-apim/issues/7898
* When an application is deleted from a page, if there are applications in the next page, one of those applications will move in to the current page. This is done by fetching relevant applications again when an application is deleted. This will also update the application count when an application is deleted. (Fix for Issue 1 and Issue 2)
* When only one application is present in the last page and that application is deleted, the page number is decreased by 1 to move to the previous page. But if only one application is present (which would be in the first page), then the page will show that no applications are present. (Fix for Issue 3)
* A static variable is introduced to handle the pagination enabling behavior. (Fix for Issue 4)
* …
> Fix devportal application page issues

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
Get API Details using REST API returned null values for business information and the lifecycle state is displayed as "Created". 
(Backported fix from https://github.com/wso2-support/carbon-apimgt/pull/1883)
Fix https://github.com/wso2/product-apim/issues/7596
> Bug-Fix:Get API details using REST API call returned null values

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Providing Flexibility to specify any scope scheme apart from "default" scheme when importing an OpenAPI definition through API publisher or through API Controller and assign those scopes into resources correctly.
Currently, the API publisher does not support multiple OAuth2 scope schemes and support only 'default' scope schemes. But when a customer brings their own API definition as a swagger file there can be OAuth2 scope schemes that are not written in the 'default' scope scheme. In that case, currently, those scopes do not get exposed or used in API publisher to generate tokens or perform any other operations. Since Microgateway supports these types of different OAuth2 scope schemes the APIM product should provide support for this particular scenario. 
Fixes …
> Flexibility to specify any scope scheme apart from "default" scheme when importing an OpenAPI definition

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
When access token for websocket request is provided in query param this parameter was going to backend without being removed.
> Remove token query param from websocket uri

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/BasicAuthenticationInterceptor.java
Fixes: wso2/product-apim#8074
Having object type scope list causes issues later in other places. Scope list in OAuth flow is an string array and that type is expected when scope property is used later in the code.
> Convert scope list to string array

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/311
When there is an overwrite to be done, the imported API Identifier should be assigned by the value of the target API Identifier.
- Wrote setId() function in the API.java file.
- Retrieved the API Identifier of the target API, if exists, and assigned it as the API Identifier of the imported API.
- User stories related to https://github.com/wso2/product-apim-tooling/issues/311 will be covered.
https://github.com/wso2/product-apim-tooling/pull/312
- Ubuntu 18.04.4 LTS
> Assigning the API Identifier of the imported API with the targeted API Identifier when updating

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/TestSchemaValidator.java
- pom.xml
Replace Jackson with GSON without changing the logic of SchemaValidator.
https://github.com/wso2-support/wso2-synapse/pull/787: Set GsonJsonProvider as the default config for Jayway JsonPath when init the server.
fix wso2/product-apim#7949
fix https://github.com/wso2/product-apim/issues/8056
> Fix schema validation when property "json-eval($.)" is used

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/SettingsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
Add analyticsEnabled property to admin v1 settings API to determine whether analytics is enabled or not.
Invoking settings API would provide the following repsonse.
Fixes: https://github.com/wso2/product-apim/issues/8116
> Add analyticsEnabled property to admin v1 settings API

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketHandlerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
With the following PR,
- Throttle events would be published to the analytics.
- Bug Fix: Closed WebSocket frame will not increase the throttle counter. As well as it will not be published to the analytics under API Usage.
- Request events will be published to the analytics for both inbound and outbound frames (for the connection between client and the gateway)
public issue: wso2/product-apim#7879
> Publish analytics events for throttling scenario

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/rxts/api.rxt
When creating API from Registry Entry (Import from definition file or from definition URL) and revert the new field added to API RXT file. 
When creating API from Endpoint Registry Entry, endpointConfig should be specified as mentioned below:
```
"endpointConfig": {
"endpoint_type": "Registry",
"endpoint_id": "{registry-name}:{entry-name}:{entry-version}"
}
```
> Publisher API implementation changes to create API from Registry Entry

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
fix wso2/product-apim#8094
Front port: https://github.com/wso2-support/carbon-apimgt/pull/2069
- Correct gateway environment not found exception in store REST API
- Handle invalid state of API's gateway environment
- Handle server error in dev-portal UI
- Select a valid gateway environment when creating an API from OpenAPI, GraphQL and Sample
- GET | {{storeHost}}/api/am/store/v1/apis/{{api-id}}/swagger?environmentName=staging
```json
{
"code": 404,
"message": "Not Found",
"description": "Gateway environment 'staging' not found",
"error": []
}
```
- GET | {{storeHost}}/api/am/store/v1/apis/{{api-id}}/swagger
```log
200 OK
```
- GET | {{storeHost}}/api/am/store/v1/apis/{{api-id}}/swagger?environmentName=dev
```log
200 OK
```
> [Front Port] Fix UI tryout issue when gateway environment name is renamed

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/GraphQLQueryDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/SubscriptionThrottlePolicyDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
This PR will add the following two optional fields to the SubscriptionThrottlePolicyDTO to support GraphQL Query Analysis.
1. graphQLMaxComplexity
2. graphQLMaxDepth
> Modify SubscriptionThrottlePolicyDTO to support GraphQL Query Analysis

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/fr.json
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Base/RouteMenuMapping.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Application/AddEdit.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Custom/AddEdit.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Custom/List.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Custom/index.jsx
This PR includes the following changes
- Moving Blacklist policies to a new page
- Put the "The following sample siddhi query ..." text into an infobox
- Add key template helper text
- Validate Key Templates from UI
**Define policy:**
**Edit policy:**
> Moving Blacklist policies to a new page

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SettingsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SettingsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/ScopeSettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/SettingsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
Fix https://github.com/wso2/product-apim/issues/7975 (https://github.com/wso2/product-apim/issues/7954)
Scenario: When transferring ownership of an application to a user, that user should hold the role Internal/subscriber
There are two required parameters used to validate the existence of scope.
- username(query)
- scope(path)
The scope will be returned if the user has the particular scope else empty list will be returned.
And 404 will be thrown if the user name or scope name does not exist.
Sample cURL request and response:
Request: curl -k -X GET "https://localhost:9443/api/am/admin/v1/settings/scopes/apim:subscribe?username=john" -H "accept: application/json" -H "Authorization: Bearer e2fd27f7-cdf4-36ae-9b32-db4a47dcb14a"
Response: {"name":"apim:subscribe"}
Request: curl -k -X GET …
> Added REST API to validate a given user has a particular scope.

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/services/login/idp.jag
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/data/AuthManager.js
With availability of the settings API for admin portal, the scopes are now retrieved from the settings API.
> Note: `isNotAdminPortal()` is removed due to 0 usages.
> [Admin Portal Revamp]Get scopes from settings API

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/APICategories/ListApiCategories.jsx
Fix API Category listing to be compatible with REST API v1.
Now the `Number of APIs` is displayed
> [Admin Portal Revamp] Fix API Categories Listing

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/BotDetection/DetectedBotData/ListDetectedBotData.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/BotDetection/EmailConfig/ListEmails.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/data/api.js
- Use App context to retrieve `isAnalyticsEnabled` variable.
- Remove duplicate api method.
> [Admin Portal Revamp]Use App context in bot data detection feature

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/endpoint/registry/impl/EndpointRegistryImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/EndpointRegistryImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/main/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/impl/RegistriesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/main/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/util/EndpointRegistryMappingUtils.java
- Refractor **RegistriesApiServiceImpl** class
- Introduced private methods to check the existence of Registry/Entry
- Moved endpoint definition retrieving and validation to a new method
- Fix service-catalog/entry **displayName** update issue
- With new implementation, if a user does not send displayName in the payload(during an update resource call), the current displayName will not be updated
> Fix service-catalog/entry displayName update issue and Refractor RegistriesApiServiceImpl

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
Add apim:bot_data scope and associated role to tenant-conf.json
```
{
"Name": "apim:bot_data", 
"Roles": "admin"
}
```
Added the above mentioned scope to role mapping to the following files.
1. components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
2. components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
> Add apim:bot_data scope to tenant-conf.json

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/SettingsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/SettingsMappingUtil.java
The admin Settings REST API is a white-listed API which means that an access token is not required to invoke the API. Hence anonymous users also can invoke the admin settings API. This PR restricts the settings API to return only the scopes when an anonymous user invokes the API.
> Restrict admin settings API content for anonymous user

- components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSMessageListener.java
Fixes https://github.com/wso2/product-apim/issues/8012
Adds a patterns to detect the API Product throttle keys which takes the formats `<product-name>/1.0.0/<resource>:<method>` and `<product-name>:1.0.0`
> Adding API Product throttle key detection

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/conf/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/TopMenu.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/CommonListing.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/defaultTheme.js
Adding support to disable one of the Grid or List view from the API Listing pages.
Old config will work as expected
```
custom: {
defaultApiView: 'grid',
}
```
The following will disable the grid view and set the list view. And it will hide the toggle buttons.
```
custom: {
defaultApiView: ['list'],
}
```
Setting the following will be the same as the old-style config.
```
custom: {
defaultApiView: ['list','grid'],
}
```
For both publisher and devportal the same config will work.
> Adding support to disable one of the Grid or List view

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/CustomRuleDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ThrottlingApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/RestApiAdminUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
This PR contains functionality which validates the following when creating Custom Policies.
1. siddhiQuery field is required
2. siddhiQuery field cannot be blank
3. keyTemplate field is required
4. keyTemplate field cannot be blank
5. policyName field cannot be blank
Fixes: https://github.com/wso2/product-apim/issues/8198
> Fix issues related to custom policy creation

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
When importing an OAS definition using publisher portal or apictl, product throws a null pointer exception when the given OAS definition doesn't contain any scopes.
```
2020-06-16 11:51:10,835] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
at org.wso2.carbon.apimgt.impl.definitions.OAS3Parser.injectOtherScopesToDefaultScheme_aroundBody88(OAS3Parser.java:1399) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
at org.wso2.carbon.apimgt.impl.definitions.OAS3Parser.injectOtherScopesToDefaultScheme(OAS3Parser.java:1345) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
```
This occurs due to lack of check conditions to check whether _Components_ and _securityDefinitions_ are null or not in the …
> Fix for #8760

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/ApplicationImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java
Fixes https://github.com/wso2/product-apim/issues/7840
When there are APIs with similar names in the requested tenant domain, the wildcard search query,
```name=*apiName*&version=*apiVersion*``` will return all matching APIs in the search result leading to issues. But in fact we need only the exact match for the name and version. Hence removing the wildcard from the search query.
> Fixing Application import issue when there are APIs with similar names

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
The issue is related to read JWT Config -> ConvertClaimsToConsumerDialect.
This was read using the first property. Hence this should be read as JWTConfiguration.ConvertClaimsToConsumerDialect.
But it was there without the "."(dot) separation. This PR fixes that issue.
> Fixing JWTConfig read issue.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Fix wso2/product-apim/issues/8210
Created an API product via "POST /api/am/publisher/v1/api-products" by providing sample tags in the payload.
"tags": [ "product", "test" ]
The response contains the tags that we give in the payload, and it is visible in dev portal.
> Added tags to API artifact in registry.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Operations/Operations.jsx
This PR is fixing the random sorting with the GQL operations list when an operation is performed on one of the rows making the location of the row changed.
The fix is at the UI side but the Rest API side also has to be fixed.
https://github.com/wso2/product-apim/issues/8478
> GQL Operation sorting fixed from the UI side

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/APICategories/AddEditAPICategory.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/AdminPages/Addons/InputListBase.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/BotDetection/EmailConfig/AddEmail.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/MicrogatewayLabels/AddEditMGLabel.jsx
On the Admin Portal, when a Add popup is displayed, errors will be shown on mandatory fields (Field is empty).
**Expected behavior:** Validation should start after the user has started entering values.
This PR fixes the mentioned behavior.
> [UI] Admin portal Initial validation error fix

- pom.xml
Downgrade Swagger codegen version to fix Travis CI, because it is unable to
download the latest codegen plugin version.
> Downgrade Swagger codegen version

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/throttling/publisher/DataProcessAndPublishingAgent.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/publisher/DataProcessAndPublishingAgentTest.java
Fix the issue related to X-Forwarded-For header containing a IP address with a port value.
> Remove port value from IP address in X-Forwarded-For header

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
The store password change enabled configuration is added to the store settings api.
When password change is disabled.
```
{"grantTypes":[],"scopes":
["apim:api_key","apim:app_import_export","apim:app_manage","apim:store_settings","apim:sub_alert_manage",
"apim:sub_manage","apim:subscribe","openid"],"applicationSharingEnabled":false,"mapExistingAuthApps":false,
"apiGatewayEndpoint":null,"monetizationEnabled":false,"recommendationEnabled":false,"IsUnlimitedTierPaid":false,
"identityProvider":{"external":false},"IsAnonymousModeEnabled":true,"IsPasswordChangeEnabled":false}
```
> Add passwordChangeEnabled resource to store settings API

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/ChangePassword/ChangePassword.jsx
With this PR the following user password policies are validated on the UI.
- The `PasswordJavaRegEx` cofigured in the UserStoreManager
- The regex configured in deployment.toml file under `passwordPolicy.properties.pattern`
- Min and Max password legths defined under `passwordPolicy.properties.'min.length'` and `passwordPolicy.properties.'max.length'` in deployment.toml file.
> Note: When the password policy is overridden by the management console per tenant, those policies will also be followed.
When the password doesn't match with the provided password regex
> Devportal Password change - validation on UI

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ImportApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
Providing a detailed error message when a user imports an API using apictl with a corrupted swagger or OpenApi Definition.
Currently, When importing an API with invalid swagger definition, Tool returns a 500 internal server error message instead of providing correct error information to the developer.
This PR will solve that issue and provide a 400 Bad Request error as it supposed to and message will say that something is wrong with the metadata of importing Project.
> Fixes https://github.com/wso2/product-apim-tooling/issues/396
Current output when a wrong swagger is provided.
```
API ID: 0974174c-372a-4ac0-8049-e68793a3692b
Error importing API.
Status: 500 
Response: {"code":500,"message":"Internal server error","description":"Error while importing API","moreInfo":"","error":[]}
apictl: …
```
> Handling error messages when corrupted swagger is provided with APICTL [Fix for https://github.com/wso2/product-apim-tooling/issues/396]

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/GatewayArtifactSynchronizerProperties.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- Resolves https://github.com/wso2/product-apim/issues/8611
- Related to https://github.com/wso2/product-apim/issues/8246
- Adding a config of `gateway_startup`
- By default gateway Startup will be in a Synchronous manner. Here the server will wait until all the APIs been deployed. If there is any failure in the deployment, it will again be triggered for **n** times where **n** is the maximum retry count. If the APIs are not deployed even in **n** retries then the server will start with un deployed API artifacts.
- If the user wants to switch the startup mode to an Asynchronous mode then he needs to specify it in the configs as `gateway_startup= "async"`. Here the server will be up, independent of the deployment of synapse artifacts in gateway.
> Provide the ability to configure gateway startup

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/AdminPages/Dashboard/RateLimitingCard.jsx
Some rate limiting links on the dashboard card was missing links. This PR adds them.
> Fix Admin Portal dashboard rate limiting card links

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SystemScopesApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SystemScopesApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/RoleAliasDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/RoleAliasListDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/SystemScopesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/SystemScopesMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
This PR contains GET and PUT operations for role-alias mapping. The original role can be mapped with a different name when customizing. 
GET :
Request : curl  -k -X GET 'https://localhost:9443/api/am/admin/v1/system-scopes/role-aliases' -H "Authorization: Bearer eb435e9d-f067-38b3-901a-c1104ca0095d" 
Response : `{
"count": 2,
"list": [
{
"role": "Internal/subscriber",
"aliases": [
"testing,test"
]
},
{
"role": "Internal/creator",
"aliases": [
"alias"
]
}
]
}`
PUT :
Request  : curl -k -X PUT 'https://localhost:9443/api/am/admin/v1/system-scopes/role-aliases' -H 'Authorization: Bearer 2992c6bc-08e7-3051-ace9-be2ce3111392'  -H 'Content-Type: application/json' 
-d  '{"count":1,"list":[{ "role":"Internal/subscriber","aliases":"testing,test"}, {"role": "Internal/creator","aliases": "alias"}]}' …
> Admin REST API]- Role-Alias mapping 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/KeyManagerClientException.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/ClientInfo.java
This PR will point the DCR and user-info  endpoints to "keymanager-operations" Rest API
> Changing dcr and user-info endpoints to keymanager-operations rest API

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/AppConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewCurl.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
Key manager config read the additionalProperties attribute to populate the token/revoke endpoints.
Key manager config ex.
```java
{
"id": "a5bc256f-c893-4d4f-9a1c-18420c496377",
"name": "Default",
"type": "default",
"displayName": null,
"description": "This is Key Manager",
"enabled": true,
"availableGrantTypes": [
"refresh_token",
"urn:ietf:params:oauth:grant-type:saml2-bearer",
"password",
"client_credentials",
"iwa:ntlm",
"urn:ietf:params:oauth:grant-type:device_code",
"authorization_code",
"urn:ietf:params:oauth:grant-type:jwt-bearer"
],
"tokenEndpoint": "https://localhost:9443/oauth2/token",
"revokeEndpoint": "https://localhost:9443/oauth2/revoke",
"userInfoEndpoint": null,
"enableTokenGeneration": true,
"enableTokenEncryption": false,
"enableTokenHashing": false, …
```
> Reading urls from additionalProperties

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
After exporting an API using the APICTL, when we reimport the API to APIM and edit it in publisher the store will display the context by appending the version twice. This PR will solve this issue.
Fixes https://github.com/wso2/product-apim-tooling/issues/404
Removing process of extracting up x-wso2-basepath extension from a swagger or open API definition and set that value as the context of API when importing an API through the API Controller tool. 
Importing an API using the API Controller tool.
OS - Ubuntu 20.04 LTS
Java - JDK 1.8_252
APIM - 3.2.0
GO - 1.14
APICTL- 3.2.0 Beta
> Avoid appending the version twice to the context when updating an exported-imported API using APICTL (Fix for product-apim-tooling/issues/404) 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
Fixes: https://github.com/wso2/product-apim/issues/8683
Eliminate the error message which was shown in the resources list when an API product was created using multiple APIs' resources, containing OpenAPI response schemas.
Check whether the requestBody, schema, parameter, response and header is not null before adding to components.
https://github.com/wso2-support/carbon-apimgt/pull/2191
> Eliminating the error when displaying the resources of API Products

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ImportApiServiceImpl.java
When importing an application using APICTL, if the user import an existing application again without --update flag, it gives as Internal Server Error with 500 status code instead of Resource already exists Error with 409 status code. This PR will solve this issue and provide a 409 status error code as it supposed to do initially.
Fixes https://github.com/wso2/product-apim-tooling/issues/409
1. Currently, when a user tries to import an existing application without --update flag, the output will be shown as follows.
`./apictl import-app -f /home/chamindu/.wso2apictl/exported/apps/dev/admin_default-apictl-app -e dev `
```
Error importing Application.
Status: 500 
Response: {"code":500,"message":"Internal server error","description":"Error while importing …
```
> Provide 409 status code instead of 500 when application is already exists in devportal.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/listeners/ServerStartupListener.java
This PR fixes https://github.com/wso2/product-apim/issues/8730
With this fix, all the custom assets like logos, etc should be added to 
```<APIM_HOME>/repository/resources/extensions/customAssets``` folder for login customization steps in document [1].
[1] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher/#customizing-different-sections-of-identity-server-related-jsp-pages
> Fix copying custom assets for login customization

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/pages/index.jag
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/DevPortal.jsx
Redirection to a given URL is not supposed to work when custom URLs enabled and the following config is set.
```java
publicTenantStore: {
active: false,
redirectToIfInactive: 'https://wso2.com/api-management/cloud/',
},
```
> Fixing customURL tenant domain coming as null issue

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/ApplicationImportExportManager.java
When importing An Application using API Controller it gives an error when that importing application has an active subscription with an API Product. This PR will solve this issue and remove the above mentioned blocker
Fixes https://github.com/wso2/product-apim-tooling/issues/418
When search query executed on REST API, it will return a map of objects which are equal to the given search query. But the latest new feature support of API products from APICTL tool this map will return both API and API Product objects. Currently this import application method only assert the subscriptions of API objects only.
So this PR will provide the ability to detect the type of the returning object (API or APIProduct) and assert that object. Then necessary steps will be executed the import Application based …
> Fix for https://github.com/wso2/product-apim-tooling/issues/418

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
Change scope scheme mapping in OAS2Parser and OAS3Parser after migration changes
> Change scope scheme mapping in swagger parsers after migration changes

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/WorkflowProperties.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Related to https://github.com/wso2/product-apim/issues/8541
By setting following to false, you could stop listing pending tasks in the admin portal. Default behavior is true
[apim.workflow]
list_pending_tasks = false
> Add config to disable workflow listing

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
With this change, if one wants to specify some additional scope that are needed to skip validating while scope validation below config should be added in deployment.toml
[apim.oauth_config]
allowed_scopes = ["^device_.*", "some_random_scope"]
> change whitelisted term to allowed

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
Admin app key manager config is missing the connector config for initial loading.
> Fixing connector configuration missing for initial editing

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
Fixing issue
https://github.com/wso2/product-apim/issues/8917
New API resources cannot be added when unassigned local scopes are defined for the API
> Fixing https://github.com/wso2/product-apim/issues/8917

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/437
Add missing properties related to operational level attributes.
- Used the function **generateAPIDefinition** to generate API definition using the given API's URI templates and the swagger while also adding missing properties related to operational level attributes.
- The attributes such as **x-auth-type**, **x-throttling-tier** and **security: - default: []** will be added where necessary.
- The attributes such as **x-scopes-bindings** will be modified as required.
- When a user imports an API using the Dev First Approach, the operational level attributes such as security, rate-limiting policies and operation scopes for resources will be visible/enabled in the Publisher Portal.
> Adding the missing attributes (operational level) when importing an API using the API Controller

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ImportExternalApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Fixing
Application Prod,Sandbox key view generate page break after enabling key provisioning
https://github.com/wso2/product-apim/issues/8952
and
Developer Portal Try out page Get Test Key not working for GraphQL
https://github.com/wso2/product-apim/issues/8954
> Fixing devportal issues

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/InMemoryAPIDeployer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/GatewayArtifactsMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
Previously undeploy method did not work as the API was in the published state and the undeploy method is querying the database based for artifacts in remove state. This returned an empty DTO. With this fix, even though the artifact is in publish state, we will use the same DTO to undeploy the API. DTO already contained information to undeploy the APIs.
Fixes:https://github.com/wso2/product-apim/issues/9026
> Fixed the undeploy resource in Gateway Rest API

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
When a key manager is disabled and we are trying to generate Access Tokens from it, the UI doesn't produce a proper error message.
This PR produces an error Alert stating that Key Manager is not enabled.
Fixes: https://github.com/wso2/product-apim/issues/8930
> Produce Alerts when trying to generate key from a disabled key manager

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
fix https://github.com/wso2/product-apim/issues/9132
- Limit local scope names to 60 in Publisher Portal
> Limit local scope names in Publisher Portal

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/refresh/refresh.jag
Fixes: https://github.com/wso2/product-apim/issues/9150
```
var tenantDomain;
if (appUtils.isPerTenantServiceProviderEnabled()) {
tenantDomain = appUtils.getTenantDomain();
}
```
The above code block which initializes the tenantDomain doesn't get executed when isPerTenantServiceProviderEnabled is false (default). Hence tenantDomain remains uninitialized which cases the issue in token refreshing.
> Fix token refresh issue in publisher

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/si.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
This PR fixes the issue https://github.com/wso2/product-apim/issues/9103 only in the UI level by adding a UI validation to restrict the document name length to 60characters.
> Fix "Too long names for API Documentation is not validated in the UI" issue

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
This PR updates the WWW-Authenticate header to `Bearer` as specified in https://tools.ietf.org/html/rfc6750#section-3.
The response header would look as follows.
`"WWW-Authenticate: Bearer realm="WSO2 API Manager", error="invalid_token", error_description="The access token expired"`
Fixes - https://github.com/wso2/product-apim/issues/9110
> Changing WWW-Authenticate header to Bearer

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fixes: https://github.com/wso2/product-apim/issues/9152
When updating the scope-role mapping in the tenant-conf, merging should be done instead of overriding.
- Wrote a new function **mergeTenantConfScopes** which takes the existing scope-role mappings and the new scope-role mappings and merge those two.
- Modified the prettifying tenant-conf code in the functions **updateTenantConfOfRoleScopeMapping** and **updateTenantConfRoleAliasMapping**.
When you update/save the roles and permissions from the Admin portal the scopes related to APIM Analytics will be not be removed from the tenant_conf.json as mentioned in https://github.com/wso2/product-apim/issues/9152.
> Merging the scope-role mappings when updating the role permissions (from Admin portal)

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/Create/CreateScope.jsx
This is a similar fix as https://github.com/wso2/carbon-apimgt/pull/9218 for global scpoes names.
UI validation shows in the UI as follows
fixes wso2/product-apim#9132
> Limit global scope names in Publisher Portal

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
When importing OpenAPI definitions via API controller or via publisher portal, those definitions have resource level throttling defined inside them. Currently, this throttling level extension is supported only with _**x-throttling-tier**_ when defining resource level throttling. But there is a use case from the micro gateway which defines these throttling tiers with _**x-wso2-throttling-tier**_ in resource level. This PR will provide that support
Fixes https://github.com/wso2/product-apim/issues/8974
Fixes https://github.com/wso2/product-apim/issues/8975
In OASParsers of APIM, there are methods to preprocess swagger definitions before actually processing and creating API objects. On that level, the OAS parsers can map x-wso2-throttling-tier extension values into x-throttling-tier in OAS …
> Map and inject Mgw throttling Extensions To Default extensions when importing an API definition

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
x-wso2-application-security is not supported when defined in API definition when creating an API with existing API definition.
This application security values should be applied under the runtime configurations in API. 
When the Following extension is defined in the API definition this should reflect it's changed configs in publisher UI which is not supported currently.
```
x-wso2-application-security: 
security-types: 
- "api_key"
optional: false
```
This PR will support this task.
Improve the extension support which is used by the micro gateway.
Fixes https://github.com/wso2/product-apim/issues/9133
and https://github.com/wso2/product-apim-tooling/issues/469
In OASParsers of APIM, there are methods to preprocess swagger definitions before actually processing and creating API objects. On …
> [Improvement] Add support for "x-wso2-application-security" mgw extension in API level

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
When importing OpenAPI definitions via API controller or via publisher portal, those definitions have resource level security defined inside them. Currently, this security extension is supported only with _**x-auth-type**_ when defining resource level security. But there is a extension  in the micro gateway which can uses to disable any type of security for any resource in API definition. That is the  **`x-wso2-disable-security`** extension. This extension can be provided in API level to disable security for all resources and define in resource level to disable security for single resource. This PR will provide that support for both cases.
Improve the extension support which are used by micro gateway.
In OASParsers of APIM, there are methods to preprocess swagger definitions before …
> [Improvement] Add support for "x-wso2-disable-security" mgw extension in API level 

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
PUBLISHED -> CREATED transition is a valid API Lifecycle transition which is normally done by "Demote to Created" lifecycle action.
By editing the api.yaml of an exported API, we should be able to to that transition and this PR will provide that ability by fixing the issues that occurred previously when importing an API using API controller.
```
availableTiers:
- name: Unlimited
status: CREATED
visibility: public
transports: http,https
```
Fixes https://github.com/wso2/product-apim-tooling/issues/478
and https://github.com/wso2/product-apim-tooling/issues/460 for Master branch
Import API via API Controller.
Import API via Publisher Portal
No doc changes required.
Ubuntu 20.04 LTS
Java JDK 1.8_241
APIM 3.2.0
APICTL 3.2.0
> [Master]Ability to Change LC state from  PUBLISHED -> CREATED by updating api.yaml 

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
This fix will set the key gen request to have the default value of a multiple value additional property not as a string but an empty array.
> Fixing error when multiple value additional properties send without selecting any value.

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidatorTest.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/jwt/SignedJWTInfo.java
With this fix, the tokens will be checked against the token in parseJWTToken cache and retrieval of JWTValidation info will only happen for signature verified tokens
> Fix JWT cache issue

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/AdminPages/Dashboard/APICategoriesCard.jsx
Fixes: wso2/product-apim#9157
Overflowing text will be clipped and partially displayed since this is a dashboard card.
> Fix API Categories Dashboard card 

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/ServerStartupListener.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottlingHandlerWrapper.java
Fixes: https://github.com/wso2/product-apim/issues/9226
Providing an alternative fix for https://github.com/wso2/product-apim/issues/8144
Frontporting the below PRs.
- https://github.com/wso2-support/carbon-apimgt/pull/2373
- https://github.com/wso2-support/carbon-apimgt/pull/2417
- https://github.com/wso2-support/carbon-apimgt/pull/2373
- https://github.com/wso2-support/carbon-apimgt/pull/2417
- https://github.com/wso2-support/carbon-analytics-common/pull/209
> Initializing throttle publisher via ServerStartupObserver

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SubscriptionDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
When enabled subscription update workflow and subscription update is in pending state, when viewing publisher subscriptions throws missing enum error.
> Fixing enum missing issue for subscription in publisher rest API

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
Fix for https://github.com/wso2/product-apim/issues/9336
As the fix, disabled the import button when the URL is empty and enable it when this field is filled
without url
with url
> Fix for product-apim/issues/9336

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Create.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx
Fixed an issue where the OPTIONS tooltip would not display
Also fixed an issue where the Cancel button would not show up in Documentation.
Related to these issues:
https://github.com/wso2/product-apim/issues/9325
https://github.com/wso2/product-apim/issues/9327
> Fixed Issues with Missing UI Elements

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/EditableRow.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
fix https://github.com/wso2/product-apim/issues/9165
- Validate space for API custom property name
- Overflow of table content
- Validate for long API custom property
> Validate for long API custom property and validate spaces and overflow of table content

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
Previously JWT expiry time was set to the token cache expiry time. During the cache cleanup task window( usually 30seconds), even though the JWT is expired still the previous expired token was returned. To avoid that, added a buffer of one minute.
fixing wso2/product-apim#9380
> Added a buffer to JWT expiry time of Backend JWT

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
- This fixes wso2/product-apim#9349
- This PR will include adding the API name and end user name to message context when using JWT token
> Set username to message context when using JWT token

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIAndAPIProductCommonUtil.java
This fix is the master branch fix for issue: wso2/product-apim-tooling#513.
> Fix export Api creates multiple InlineContents/FileContents folders

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java
- This fixes wso2/product-apim#8079
- This PR resolves the JSON schema validation errors when integer value is provided in quotes for a string field and when there is an array with one element.
> Fixing JSON schema validation errors

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/521
Adding login permission to the Internal/devops role.
Added login permission when creating the Internal/devops role.
- A user with the Internal/devops role can login using "apictl login".
https://github.com/wso2-support/carbon-apimgt/pull/2589
> Adding login permission to the Internal/devops role

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIAndAPIProductCommonUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIProductExportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIProductImportUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ImportApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/ApplicationImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/329
Eliminate the inconsistencies when adding throttling policies when importing an API/API Product/Application. 
The changes have been done related to the three (3) main throttling policies. 
1. **Advanced Throttling Policies**
1. Modifications related to **API/Product Level Throttling Policies**
- When we try to import an API/API Product with an Advanced Throttling Policy that has been assigned to the  API/API Product, which is not currently available in the API Manager, an error was displayed earlier. But with this PR, now you will receive an error and the import will be failed.
2. Modifications related to **Resource Level Throttling Policies**
- No changes needed to be done.
2. **Application-level Throttling Tiers/Policies**
- …
> Fixing inconsistencies when importing/exporting APIs/API Products/Applications with Throttling Policies using the API Controller

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/SynapsePropertiesHandler.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Front Porting https://github.com/wso2-support/carbon-apimgt/pull/2274
- A new configurations has been introduced for IS-KM Reverse Proxy which is disabled by default. To enable the support, the following should be added to the /repository/conf/deployment.toml
**[apim.auth_manager]**
**iskm_reverseproxy_enabled = true**
- When this configurations is enabled, the code will check whether the API context is "/authorize", "/commonauth" or "/oidc" while status code is 302 and if so, modify the location header value by replacing the Key Manager host with the Gateway host.
- This modification is done only if the location header contains "/authenticationendpoint", "/oauth2/authorize", "/commonauth", "/logincontext"or "/oidc".
- IS Related PRs
- …
> Add ISKM Reverse Proxy Support

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/8528
Handle throwing a null pointer exception and internal server error (500) as response when the publisher rest api is invoked without 'additionalProperties'(/api/am/publisher/v1/apis/import-openapi).
Added validation part to the begining of importOpenAPIDefinition() to check whether the additionalProperties is null.
> Fix the error when importing an Open API Definition without additionalProperties

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- Add missing allowed REST API resources to the AllowedURI list.
- Fixes: https://github.com/wso2/product-apim/issues/8549
- Provide ability to invoke REST API resources which do not require scopes to be invoked without providing a token.
- There were several REST API resources with no scopes attached to its resource definition (OAuth2Security: [ ]), but were missing in the AllowedURIs list defined in the api-manager.xml.j2 file. Those missing resources were added to the AllowedURIs list to provide the ability for those resources to be invoked without providing a token.
> Add Missing Allowed REST API Resources to the AllowedURIs List

- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/DefaultKeyValidationHandler.java
Fixes: https://github.com/wso2/product-apim/issues/9386
To solve the failure of scope validation when invoking default version of an API using Oauth as token type with no version in the uri.
Defined new variable inside the DefaultKeyValidationHandler.java to store pure api version since default api versions are prefixed with `_default_` and it causes to fail the api search using `getApiByContextAndVersion()`.
> Fix scope validation issue when invoking default API with Oauth token

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
Fixes: https://github.com/wso2/product-apim/issues/9275
Prevent API creation when the API version contains ':' character.
Add ':' character to the illegal characters list
JDK 1.8.0_241
Ubuntu 20.04.1 LTS
> Add ':' character to the illegal characters list

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java
This pr is for restricting an APIKey protected API when refere header is not provided while App is protected by permittedrefere.
> fix for https://github.com/wso2/product-apim/issues/9581

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/site/public/conf/defaultTheme.js
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/ProtectedApp.jsx
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/Navigator.jsx
Fixed by taking the override styles out of the jsx files and in to the defaultTheme.js.
Now users can user theme.overrides object to override material UI component styles.
Example to override the left menu background colors. The following config is there in the newly updated defaultTheme.js. The backgroundColor can be changed accordingly to update the background colors of the left drawer.
```
MuiDrawer: {
paper: {
backgroundColor: '#18202c',
},
},
MuiListItem: {
root: {
'&.itemCategory': {
backgroundColor: '#232f3e',
boxShadow: '0 -1px 0 #404854 inset',
paddingTop: 8,
paddingBottom: 8,
},
},
},
},
```
> Fixing for https://github.com/wso2/product-apim/issues/9573

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes the issue mentioned in https://github.com/wso2/product-apim-tooling/issues/330#issuecomment-737692783
Export multiple custom mediation policies attached to an API and import those when importing that particular API.
- Previously only one mediation policy per direction (in/out/fault) was exported. But with this improvement, all the attached mediations to a particular API will be exported for all the directions.
```
PizzaShackAPI-1.0.0
├── api.yaml
├── Definitions
│   └── swagger.yaml
└── Sequences
├── fault-sequence
│   └── Custom
│       └── sequence1.xml
├── in-sequence
│   └── Custom
│       ├── sequence1.xml
│       └── sequence2.xml
└── out-sequence
└── disable_chunking.xml
```
As shown in the above example, you can see that there are multiple **in-sequences** inside the …
> Support to export/import multiple custom mediation policies attached to an API through APICTL

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/generator/AbstractAPIMgtGatewayJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/token/TokenGenTest.java
JTI standard claim was missing in JWT token. Hence it is added.
Fixing https://github.com/wso2/product-apim/issues/9501
> Adding JTI claim for JWT.

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
- The fixes wso2/product-apim#9463
- Fixing throwing a null pointer error when the gateway type is set to production or sandbox and when trying to access the applications on devportal.
> Fixing null pointer error when using gateway type as production or sandbox

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/CommonUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- The proposal is to be able to maintain deployment-specific resources external to the API project in its folder structure so that it can be maintained in its deployment repo. So the same API Project can be paired with different deployment data by the deployment job in a CI/CD pipeline.
- This is more of a best practice guideline that we are providing for separately maintain project data and deployment data so that it can be leveraged by apictl to deploy to across multiple environments effectively.
Fixes https://github.com/wso2/product-apim-tooling/issues/545
The resource artefact to be passed with publisher/v1/api/import REST API calls a single zip artefact. Therefore the folder structure based on the use case that user is referring should be identified and the packaging of the …
> Support new directory structure when bundling Deployment directory when importing APIs [APIM]

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/ImportExportAPIServiceImpl.java
Preserving endpoint credentials when exporting an API using the APICTL.
Preserve the endpoint credentials when exporting an API, so that when importing it would be easy.
Manipulate the preserveCredentials variable introduced in [1]
- When someone is downloading the API from the Publisher UI, the endpoint credentials will not be preserved.
- When someone is exporting the API from APICTL, the endpoint credentials will be preserved.
- https://github.com/wso2/carbon-apimgt/pull/9458
- https://github.com/wso2/carbon-apimgt/pull/9406
[1] https://github.com/wso2/carbon-apimgt/pull/9458
> Preserving endpoint credentials when exporting an API via APICTL

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/TransportHeaderHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/TransportHeaderUtil.java
This PR adds **TransportHeaderHandler** to the gateway component.
**TransportHeaderHandler** is a global synapse handler which can be used to filter out the request and response headers in WSO2 API Manager.
The following configurations will be added to <APIM_HOME>/repository/conf/synapse-handlers.xml file to enable the handler when invoking an API.
```
<handler name = "TransportHeaderHandler" class="org.wso2.carbon.apimgt.gateway.handlers.common.TransportHeaderHandler">
<parameter name="removeRequestHeaders" value="true"/>
<parameter name="preserveRequestHeaders" value=""/>
<parameter name="excludeRequestHeaders" value=""/>
<parameter name="excludeResponseHeaders" value=""/>
</handler>
```
Parameter Name | Description
-- | --
removeRequestHeaders | true or false indicating whether to …
> Add handler to remove transport headers

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/564
Enhance the current capability of defining subscription tiers (of an API) in api.yaml file by providing the capability to override them using api_params.yaml file, if the user wants.
This procedure modified the template of api_params.yaml as shown in the below example. 
- A new field was added as **policies** which is an array that consists of the subscription tier names for an API in an environment.
```
environments:
- name: dev
configs:
endpoints:
production:
url: 'https://dev.wso2.com'
security:
enabled: true
type: basic
username: admin
password: admin
certs:
- hostName: 'https://dev.wso2.com'
alias: Dev
path: dev.crt 
gatewayEnvironments:
- Production and Sandbox
policies:
- Gold
- Silver   
```
- If the policies parameter …
> Support to override subscription policies of an API using the api_params.yaml

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/MicroGateway.jsx
Fixes: https://github.com/wso2/product-apim/issues/9679
Changed schema property name of microgateway labels from **access_urls** to **accessUrls**
> Update accessUrls property name of mgw-label schema

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/CommonUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApplicationsApi.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/ApplicationsApiService.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoListDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIInfoMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/models/ExportedApplication.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/models/ExportedSubscribedAPI.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/utils/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/utils/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
Fixes: https://github.com/wso2/product-apim-tooling/issues/324
Restructure the code segments related to exporting/importing an Application by introducing new schemas via reading required DTOs.
- Created Store REST API resources to export/import an Application The resources are as follows.
1. POST applications/import
2. GET applications/export
- The old implementations of exporting/importing Applications have been modified to read DTOs from the importing files, instead of models.
- Introduced a parameter to define the format as JSON or YAML when exporting an Application.
Below is an example of an exported application with keys and subscriptions, in the new schema format.
```
type: application
version: v4
data:
applicationInfo:
applicationId: 93bf6b68-74dc-4c56-a4e4-66bad2883ea5
name: …
```
> Restructuring functionalities to Export/Import an Application with new schemas with relevant DTOs for APICTL

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/si.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/MarkdownEditor.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx
Provide a markdown editor to add/edit the description in the publisher portal.
Related Issue: https://github.com/wso2/product-apim/issues/9272
1. Removed the Description TextField in the Design Configurations UI page and added a link button to Add/Edit Description.
2. Added functionality to open up a Markdown Editor to add/edit the description when the link button is clicked.
JDK 1.8.0_241
Ubuntu 20.04.1 LTS
> Provide Markdown Editor to Add/Edit Description

- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/RuntimeArtifactsApiServiceImpl.java
Then the apis.zip was downloaded over the https://localhost:9443/internal/data/v1/runtime-artifacts, it gave an error related io.StreamClosed.
While debugging I found out that the fileinputstream is not necessary.
> Fixing runtimeArfifact zip serving issue.

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/MediationPolicies/EditMediationPolicy.jsx
- Fixes: https://github.com/wso2/product-apim/issues/9690
- When NONE mediation policy is selected, an object with **name: "none"** and **type: "none"** is created and set as the active policy. This solves scenarios when switching from Custom or Common mediation policy to NONE mediation policy.
> Handle Error Scenarios when Switching from Custom or Common Mediation Policy to NONE Mediation Policy

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
Fixes: https://github.com/wso2/product-apim/issues/9718
Removing the "Test Console" menu item from the left bar of Publisher portal if the API is in PUBLISHED state
Users are restricted to use the test console when an API is in the PUBLISHED state.
> Restricting API "Test Console" Menu Item when API is in PUBLISHED state

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Overview.jsx
- Remove the Token Type field display from Applications Overview page in the DevPortal
- Fixing of https://github.com/wso2/product-apim/issues/9441 for APIM-4.0.0
- The Applications Overview Page in the DevPortal contains the Token Type field as shown below.
- This PR removes the Token Type field from Applications Overview Page. After removal, the Applications Overview Page looks as shown below.
> Remove Token Type Field from Applications Overview Page

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
Fixes: https://github.com/wso2/product-apim/issues/9706
- The problem arised due to a null value. Its because the updateSubscription method had only considered the APIIdentifier and not the APIProductIdentifier.
- When the resource is an API Product, the SubscribedAPI has an APIIdentifier value of null and has a value to APIProductIdentifier. In the current scenario, the code retrieves the APIIdentifier value of the SubscribedAPI (which is null) and pass it to other methods which eventually causes the error.
- Updated the code to to consider the APIProductIdentifier value, when APIIdentifier value of SubscribedAPI is null. 
> Fix Issue of API Products Subscription Blocking

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/AnalyticsMetricsHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/PublisherUtils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/dto/ResponseEvent.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/APIMgtLatencyStatsHandler.java
- pom.xml
- Adding initial event publisher client for APIM
To engage the analytics handler, add the following code to deployment.toml
```
enabled_global_handlers=["external_call_logger", "open_tracing", "analytics"]
[synapse_handlers.analytics]
name="analytics"
class="org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler"
```
> Adding initial event publisher client for APIM

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ApiCategoriesApiServiceImpl.java
Fix for wso2/product-apim#8951
As the fix, used the same validation done in the UI https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/APICategories/AddEditAPICategory.jsx#L93
> Add validation for category name in REST api v2

- components/apimgt/org.wso2.carbon.apimgt.internal.service/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.gateway.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.throttle.service.interceptors/pom.xml
- pom.xml
There are some identified security vulnerabilities in a recent security scan. One of them is Hibernate Validator Engine dependency. Even though it has been added in pom files, there is no usage of it in our source code. It is successfully building the repo without this dependency and made sure it is not being used.
After removing this it will not detect this kind of security issue in future, by scans.
> Removing unused hibernate-validator dependency

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/APIConfigContext.java
After configuring an API to use only API Key security or Basic Auth security type, when invoking the API using the sandbox API Key, the request is directed to the production endpoint. This PR will solve that issue.
Fixes https://github.com/wso2/product-apim/issues/8483
The velocity template was not checking for `apiKey authenticated` property and `basic_aut authenticated`  property. It only checks `oauth2 authenticated` property when mapping hybrid endpoints. Therefore, the api.xml resources are generated without both endpoint types(SandBox and Production). This fix will check for the missing properties and make the validation and templating will be done after that.
> Hybrid endpoint support when invoking APIs secured with ApiKey only or BasicAuth only

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/webhook/WebhookApiHandler.java
This PR add a handler for webhook apis, which is needed for scope based authorization.
```xml
<handler class="org.wso2.carbon.apimgt.gateway.handlers.streaming.webhook.WebhookApiHandler">
<property name="subscriptionResourcePath" value="/subscription"/>
<property name="topicQueryParamName" value="hub.secret"/>
</handler>
```
Since the actual matching resource path is included in the query param, this handler extracts it from request and set the API_ELECTED_RESOURCE property for the message context. This needs to be added before the APIAuthenticationHandler
Fixes https://github.com/wso2/product-apim/issues/9769
> Add webhook api handler

- components/apimgt/org.wso2.carbon.apimgt.gateway/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketUtil.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketWSClient.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/websocket/WebSocketApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/websocket/WebSocketApiException.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandlerTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketUtilTestCase.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/AbstractKeyValidationHandler.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationService.java
- components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationServiceTest.java
This PR add scope based access control for web socket APIs depending on the introduction of  of resources for web socket APIs https://github.com/wso2/wso2-synapse/pull/1691.
**Handle Scope Based Access Control**
Before the request is authenticated, the matching resource is selected from the request path and passed for authentication.
**Handle Default Versioned API**
For the default version of API, a relevant api is assumed to be present in synapse config with the
name of corresponding api + _d + version of corresponding api
and when it is identified, the corresponding matching api  name is reconstructed and the request is processed in the normal path thereafter.
> Add scope based access control for web socket apis

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/TemplateBuilderUtil.java
Adding the following handlers to the velocity template builder, when API type is WebSub.
- `org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler`
- `org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler`
> [Streaming API] Add CORSHandler & APIAuthenticationHandler in WebSub velocity template builder

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/TemplateBuilderUtil.java
Adding the following handler to the API, for Websub Streaming APIs:
```xml
<handler class="org.wso2.carbon.apimgt.gateway.handlers.streaming.webhook.WebhookApiHandler">
<property name="topicQueryParamName" value="hub.topic" />
<property name="eventReceivingResourcePath" value="/webhooks_events_receiver_resource" />
</handler>
```
> Add WebhookApiHandler to velocity template builder

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/StreamingApiHanlder.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/sse/SseApiHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/streaming/webhook/WebhookApiHandler.java
This sets the http method as subscribe  before the authentication handler and reset it as after it, since this DB entry is added as susbcribe.
> Update http method to subscribe for websub and sse

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java
$subject. This caused the issue of both secured websocket and http inbound to be not present in the tenant when its loaded.
> Fix naming issues with secure web socket inbound in tenant space

- components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/DataPublisherUtil.java
Fixes: https://github.com/wso2/product-apim/issues/9740
Removing the port from the extracted X-Forwarded-For value
> Removing the port from header x_forwarded_for

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
This PR adds `$ref` support for parameters when schema is not present in the API swagger definition during the creation of an API Product.
Fixes https://github.com/wso2/product-apim/issues/9790
> Add ref support for parameters when schema is not present

- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ApplicationSettings/EditApplication.jsx
When changing the ownership of an application using the admin portal UI, 
when the target application owner is a valid `subscriber` and hasn't logged into the devportal at least once,
the REST API responses with `500`. But since this is a special troubleshooting step which is included in the [docs](http://localhost:8000/learn/consume-api/manage-application/advanced-topics/changing-the-owner-of-an-application/) too, we need to display a meaningful Error alert.
> Please note that the separate API call which is used for checking the target owner is a subscriber or not is returning with true even if that user hasn't logged into the devportal at least once. (which is expected behavior IMO). Therefore, the error message update is needed.
This PR updates the error message to `Error while …
> [Admin Portal][UI]Update error message on application ownership change

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/ImportExportAPIServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
Previously when a revision is exported, the working copy's docs and icon was exported as the revision's docs and icon. This made inconsistencies with the exported revision artifacts as the exported artifact might vary with the current working copy. This is has been fixed to export the docs and images from the time revision was created.
> Fixed the working copy docs getting exported in revision error

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
This avoids a NPE which occurrs at `AbstractAPIManagerTestCase`, when checking `api. isAsync()`
> Fix NPE occurring at AbstractAPIManagerTestCase

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Tier.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ThrottlingPolicyDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ThrottlingPolicyMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ThrottlingPolicyDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ThrottlingPolicyMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml
As $subject, this pr will add the following parameters as read-only parameters for the response of  /throttling-policies REST API in publisher and store.
**Publisher**:    quotaPolicyType, rateLimitCount, rateLimitUnit, dataunit
**Store**:    quotaPolicyType, rateLimitCount, rateLimitUnit, timeUnit, dataunit
After adding the above parameters the responses of the store and publisher  /throttling-policies API as follows.
- **Publisher:**
curl:   https://localhost:9443/api/am/publisher/v1/throttling-policies/subscription
- **Store**
curl:   https://localhost:9443/api/am/store/v1/throttling-policies/subscription
https://github.com/wso2/product-apim/issues/9695
> Add addtional throtling tier paramaters to the REST API response in the store and publisher

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLQueryAnalysisHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityConstants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/APIThrottleConstants.java
- Use throttled out error code for "QUERY TOO DEEP" and "QUERY TOO COMPLEX" error codes. 
- Fixed https://github.com/wso2/product-apim/issues/9972
> Use different error codes for graphQL errors

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
When the API Name contains the value of API version current implementation of retrieving api source path fails.
Ex: 
API Name = Test1
API Version = 1
> Fixing getting api source path when creating revisions

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandlerTest.java
When the APIM 3.2.0 is configured with third-party keymanager(Ex: Keycloak) and a deny policy is added to block the API invocation to a particular user, that user is able to invoke the API without having any issue. This is happening because the auth context does not contain the correct form of value as the `authorizedUser`.
Fixes https://github.com/wso2/product-apim/issues/9957
The existing code extracts the **authorizedUser** value from the **authContext** using the `getUSername()` method. But it does not provide the correct form of `<username>@<tenant_domain>` when using a 3rd Party Key manager. The fix will be changed to get the correct form of this **authorizedUser** from the **authContext**.
> authorizedUser = authContext.Username() + "@" + apiTenantDomain;
> Extracting the correct form of username from auth context when using 3rd party KMs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Added the support to overwrite deployment environments specified in the api artifact at import with the api_params.yaml file. 
Also fixed https://github.com/wso2/product-apim-tooling/issues/623
> Add the support to overwrite deployment envs at import with params 

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
When importing the api, deployment environments will be validated with the existing labels and environment names.
Related issue: https://github.com/wso2/product-apim-tooling/issues/601
> Added a validation for the gateway labels

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SettingsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/PreAuthenticationInterceptor.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
Fixes: https://github.com/wso2/product-apim/issues/9722
the REST API restriction when the anonymous mode is disabled for developer portal
- Used **PreAuthenticationInterceptor.java** to do the restriction for REST APIs
- Executed the integration tests and all were passed.
- When the "EnableAnonymous" is "false", a user cannot access the Devportal REST APIs without any credentials.
```
wasura@wasura:~$ curl 'https://localhost:9443/api/am/devportal/v2/apis?limit=10&offset=0' -k 
{"code":401,"message":"","description":"Unauthenticated request","moreInfo":"","error":[]}
```
> Adding the REST API restriction when anonymous mode is disabled for developer portal

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
To solve below issues associated with support tickets.
**For OAS3:**
When importing the API via apictl or publisher the security and securitySchemes have been introduced. The implicit flow is added in this scenario. According to the OAS3 specification, the security or securitySchemes are not mandatory. But if we defined for code or implicit grants then we need to provide authorizationURL as it is a mandatory field.
**For OAS2:**
To solve critical error shows when validating auto updated swagger 2.0 definition after uploading the original definition to APIM-3.X.X.
To prevent from https://github.com/wso2/product-apim/issues/9889 and https://github.com/wso2/product-apim/issues/9912 issues in future
Add mock authorizatoinURL (https://test.com) to the authorizationUrl if it is not present and …
> Add missing mandatory elements to OAS definitions

- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
Add monetization config required to support  data retrieval from Choroe analytics. It includes two new configs to configure the query api endpoint of choro which is used to retreive data and the token required to authenticate to the above endpoint. 
With the intrroduction of this config, it has to be configured as follows in the deployment.toml
[apim.monetization]
analytics_query_api_endpoint= "<query api endpoint of choroe analytics>"
analytics_access_token = "<token retrieved from choreo analytics>"
Fixes https://github.com/wso2-enterprise/choreo-analytics-apim/issues/164
> Add monetization config changes required to support Cloud analytics

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/VHostUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
- fix https://github.com/wso2/product-apim/issues/10151 : Resolve default vhost to null DB value (so users are able to change default vhost eg: first it was "localhost" and now it is changed to "dev.wso2.com")
-  If default vhost is coming from the payload of deploy revision request, set null as the Vhost in `AM_DEPLOYMENT_REVISION_MAPPING`.
- If null is set in `AM_DEPLOYMENT_REVISION_MAPPING` as vhost set default vhost (first) of read-only environment
- Refactor setting endpoint URLs in GET /api of store Rest API
- Set custom URL for tenants
- Set swagger server URLs for vhost
Enforce vhost not null when deploy a revision:
This is for checking default vhost (only in read only environments - to reduce DB lookups also - So there should not be a vhost with dynamic environment in the DB …
> Resolve default vhost to null DB value and Update swagger server URL

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/637
Change the structure of the `deployment_environments.yaml` to be more descriptive and follow the standard of other yaml files found in the project.
Updated the deployment_environment.yaml to be exported in the following format.
```
type: deployment_environments
version: v4.0.0
data:
-
displayOnDevportal: true
deploymentEnvironment: Production and Sandbox
-
displayOnDevportal: true  
deploymentEnvironment: Label1  
-
displayOnDevportal: false  
deploymentEnvironment: Label2 
```
https://github.com/wso2/product-apim-tooling/pull/648
> Modify the structure of deployment_environments.yaml for APICTL tasks

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
This PR fixes an issue where API creation is blocked when the Unlimited throttling tier is disabled.
Fixes https://github.com/wso2/product-apim/issues/9974
> Add support for API creation when Unlimited throttling tier is disabled

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/ImportExportAPIServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/650
Adding the support for API Product params file via APICTL.
- Added the support to override the parameters of **dependentAPIs** of an API Product
- Added the support to override the parameters such as Mutual SSL certificates, subscription policies, deployment environments using the API Product params file.
- Refactored the existing functions used to override API params to enhance the functionality for API Products.
_**Sample params file for an API Product**_
```
environments:
- name: production
configs:
policies:
- Gold
- Silver
deploymentEnvironments:
- displayOnDevportal: true
deploymentEnvironment: Production and Sandbox
mutualSslCerts:
- tierName: Gold
alias: Alice
path: alice.crt
- tierName: Silver
alias: Bob
path: bob.cr …
```
> Add the support for API Products params file via APICTL

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/SynapseArtifactGenerator.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/654
The functionality to import/update an Async API definition should be added for **apictl import api**.
- Validate the Async API definition during import API, before adding the API to the APIM
- Import/update (overwrite) the Async API definition that comes inside the API archive to the APIM
- Provide the support for both YAML and JSON Async API definitions to get read.
> Import Async API definition during the API import via APICTL

- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SubscriptionMappingUtil.java
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/api.jsx
This PR fixes the following issues:
- Subscriptions REST API not returning the pagination in the response
- Only first 25 subscriptions are shown under Subscriptions in an API in Devportal.
Fixes https://github.com/wso2/product-apim/issues/10140
Fixes https://github.com/wso2/product-apim/issues/10127
> Fix pagination issues with Subscriptions in Devportal

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/650
When you provide --params with the deployment directory link when importing an API Product, overriding the certificates of the dependent APIs will get failed due to an issue in the directory path.
Fix the above stated problem
> Fix the issue on certificate overriding for dependent APIs of API Products via params

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
Resource with a trailing slash being treated as a resource without a trailing slash ( /echo/ --> /echo )
This PR fixes that issue.
Public fix for https://github.com/wso2-support/carbon-apimgt/pull/2514
- Remove trailing slash when adding a resource with trailing slash.
- Remove trailing slash in Create API using swagger Definition workflow
- Remove trailing slash in editing swagger from UI
- Remove trailing slash in the REST API operations of,
- Create API
- Update API  
- Update Swagger Definitions
> Fix scope does not work with trailing "/" issue

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
Currently, requestBody definition with the following format is supported when creating an API Product.
```
requestBody:
content:
application/json:
schema:
type: object
required: true
```
If the requestBody definition in the original API takes the following format, an error will be shown when accessing the Resources of the API Product.
```
requestBody:
$ref: '#/components/requestBodies/Order'
components:
requestBodies:
Order:
description: Order object that needs to be added
content:
application/json:
schema:
$ref: '#/components/schemas/Order'
required: true
```
This issue is fixed through this PR.
Fixes https://github.com/wso2/product-apim/issues/10325
Fixes https://github.com/wso2/product-apim/issues/10423
> Add ref support for requestBodies when content is null

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/667
Fixes: https://github.com/wso2/product-apim-tooling/issues/665
Fixes: https://github.com/wso2/product-apim-tooling/issues/668
Fixes the issue when integer values are passed to **endpointConfigs** via the params file and the issue on reflecting HTTP/SOAP endpoints when passed through params.
- Wrote a new function to convert integers in the **endpointConfigs** to strings 
- Corrected the constant used for HTTP/SOAP endpoints via params file
> Convert integers in the endpointConfig to strings and fix reflecting the HTTP/SOAP endpoints when provided through params

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- This PR fixes https://github.com/wso2/product-apim/issues/10283
- Adds the revoked API keys to db.
- This resolves the issue on being able to invoke an API after a server restart with the revoked APIKEY token.
> Fix the issue of being able to invoke API after a server restart with revoked API Key

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/ImportExportConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/utils/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/670
Fixes: https://github.com/wso2/product-apim-tooling/issues/672
Add the directory/archive validation for applications and support endpoint security for production and sandbox separately.
- Validated the application directory/archive and throw exceptions if incorrect.
- Introduced the support to override endpoint security using the params file for Production and Sandbox separately. Below is a sample params file with the changes.
```
environments:
- name: production
configs:
endpoints:
production:
url: 'https://localhost:9443/am/sample/prod/pizzashack/v1/api/'
sandbox:
url: 'https://localhost:9443/am/sample/sand/pizzashack/v1/api/'
security:
production:
enabled: true
type: basic
username: admin
password: admin
sandbox:
enabled: …
```
> Support for endpoint security for production/sandbox separately and validate Application projects

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/Constants.java
- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/SynapseAnalyticsDataProvider.java
Changed the correlation id of analytics to the Id in axis2 context in order to be consistent with APIM.
Fixes https://github.com/wso2/product-apim/issues/10441
> Fix analytics corelation id to be consistent wth APIM

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
Remove on the fly migration of json_fault.xml for 2.0.0 to 2.1.0. This will now be handled by the migration client [1].
Related Issue: wso2/product-apim#10238
[1] https://github.com/wso2-extensions/apim-migration-resources/pull/99
> Remove On the Fly Migration of json_fault.xml for 2.0.0 to 2.1.0

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- $subject
- enforce vHost in Rest API when deploying (not required when un-deploying) an API product revision
- fix https://github.com/wso2/product-apim/issues/10628
> Set vhost when deploy API-Product to dynamic environment in Publisher portal

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/JMSMessageListener.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
- features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventpublishers/blockingEventJMSPublisher.xml
- features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventpublishers/jmsEventPublisher.xml
- features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventpublishers/jmsEventPublisher_1.10.0.xml
- features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventpublishers/keyTemplateEventPublisher.xml
MGW need this to be in json format for processing. Current impl sends the message in 'JMS Content-Type: amqp/map' format which is not parsable easily. This response has to be in a protocol agnostic format. Earlier we have made this change (with #9560) to other event publishers except throttle publishers
> Update throttle event message type to json

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
To solve console ERROR when trying to access tenant devportal with secondary user store user
Fixes: https://github.com/wso2/product-apim/issues/10272
Applied "wso2.anonymous.user" for user name, if the user's tenant domain is not equals to the tenant domain which the request has made .
> Fix console error when login with secondary user store user

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
I ran into an NPE here using generated Scala client code with API Manager 3.2.0 (which I guess runs v6.7.206 of this repo, but this part of the code is the same there and in master).  There's an easy client-side workaround for this of course but since it took me an hour to figure out I thought I'd post what I believe is the proper fix - feel free to do as you wish with it.
> check for null gatewayEnvironments API field

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Constants.js
- When vhost is deleted after a revision is deloyed with that vhsot, use default ports.
- Show display name instead of name of gateway environemnt
fix https://github.com/wso2/product-apim/issues/10710
fix https://github.com/wso2/product-apim/issues/10711 
show Display Name of gw environment
- name: us-region
- displanName: US Region
> Publisher TryOutConsole - Use default ports when vhost is deleted after a deployment and show DisplayName

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ServiceCatalog.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/ServiceCatalogImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ServiceCatalogDAO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/src/main/java/org/wso2/carbon/apimgt/rest/api/service/catalog/impl/ServicesApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/src/main/java/org/wso2/carbon/apimgt/rest/api/service/catalog/utils/ServiceEntryMappingUtil.java
Fixes  https://github.com/wso2/product-apim/issues/10730
With this fix, for the request ```https://127.0.0.1:9443/api/am/service-catalog/v0/services?limit=1```, the response would be:
```
{
"list": [
{
"id": "aac98982-e160-4c0d-af0c-901323ba83d1",
"name": "Car",
"description": "This is a sample server Uber server",
"version": "2.0.0",
"serviceKey": "Car-2.0.0",
"serviceUrl": "http://www.mocky.io/v2/5d01e59f3100005100ab2a62",
...
}
],
"pagination": {
"offset": 0,
"limit": 1,
"total": 4,
"next": "/services?name=&version=&definitionType=&displayName=null&key=&sortBy=name&sortOrder=asc&limit=1&offset=1",
"previous": ""
}
}
```
> Fix pagination issue in services search

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java
Fixes partially:  https://github.com/wso2/product-apim-tooling/issues/675
Fixes the issues of not using the persistence instance when importing thumbnails, documents, WSDL files and SOAP to REST mediations according to [1]. 
- Refactor the code to use persistence instance when adding the thumbnails, documents, WSDL files and SOAP to REST mediations
- Limited exporting WSDL files only for SOAP APIs (not for SOAP to REST)
- Restricted exporting SOAP to REST mediations since those can be derived from the swagger file during the import.
- Fix an issue of not exporting API Product thumbnails.
[1] https://github.com/wso2/product-apim-tooling/issues/675
> Fixing the issues of not using the persistence instance when importing thumbnails, documents, WSDL files and SOAP to REST mediations

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/GatewayUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/TemplateBuilderUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/template/EndpointConfigContext.java
This PR adds support to get AWS Secret Key from secure vault when secure vault is enabled.
Fixes https://github.com/wso2/product-apim/issues/10715
> Add SecureVault support for AWS Lambda credentials

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/utils/RegistryLCManager.java
Fixes the following issues: 
https://github.com/wso2/product-apim/issues/10505
https://github.com/wso2/product-apim/issues/10690
Workflows: https://github.com/RAVEENSR/carbon-apimgt/runs/2269521213
API in Published state(Before):
API in Published state(After):
----------------------------------------------------------------------------------------------------------
API in Prototyped state(Before):
API in Prototyped state(After):
> Stop adding incorrect transitions for Prototyped and Published states

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
Fixes issue https://github.com/wso2/product-apim/issues/10515.
Before: 
After:
Even though in the issue it is stated that we need to remove **Subscription and Key Generation Wizard** option, did not removed it. Instead disabled it. The main reason is we have followed this approach when it comes to:
- Mutual SSL APIs
- APIs with only Basic Authentication
> Disable Subscription and Key Generation Wizard for prototype APIs

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
This PR adds `apim.analytics.backend.start.time` property to AWS Lambda API message context to calculate backend latency when Analytics is enabled.
Fixes https://github.com/wso2/product-apim/issues/10784
> Fix Lambda API invocation failure with Analytics

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Monetization/index.jsx
Improve user experience of monetization UI by disabling the monetization properties to be edited when the checkbox to enable monetization is not checked.
> Improve monetization UX

- components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/utils/BlockConditionDBUtil.java
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/raw.en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/pages/index.jag
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/LoadBalanceConfig.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/LoadbalanceFailoverConfig.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/endpointUtils.js
- This PR 
1. fixes https://github.com/wso2/product-apim/issues/9686
2. fixes https://github.com/wso2/product-apim/issues/9767
3. fixes https://github.com/wso2/product-apim/issues/10196
- This PR ports the following fixes:
1. https://github.com/wso2-support/carbon-apimgt/pull/2755
2. https://github.com/wso2-support/carbon-apimgt/pull/2818
3. https://github.com/wso2-support/carbon-apimgt/pull/3022
- This PR fixes client claim name saved change not reflecting in Admin portal when configuring PingFederate key manager
- This PR fixes IP range Deny policies not working after server restart
- This PR adds the support to enable or disable failover property for load balance endpoints from the Publisher portal
> Fix client claims in Admin portal not changing, IP range deny policy not working and add support to enable failover for loadbalance endpoints

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/GoToTryOut.jsx
Fixes issue https://github.com/wso2/product-apim/issues/10788.
Now when clicking on the try out button, redirects to the Try Out section.
> Fix TRY OUT button for Prototyped APIs

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/AsyncApiConsole/GenericSubscriptionUI.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/AsyncApiConsole/WebhookSubscriptionUI.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Definitions/AsyncApi/AsyncApiDefinitionUI.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Utils.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/defaultTheme.js
- Use the same colors used in API publisher, when rendering topics in the 'Try Out' page of Dev portal [1].
- Avoid rendering the 'servers' portion from the AsyncAPI definition. Fixes: https://github.com/wso2/product-apim/issues/10744
[1]
> [Streaming API] UI fixes in DevPortal

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
Fixes https://github.com/wso2/product-apim/issues/10838.
Before:
After:
> Remove API Audit option for Async APIs

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/APICreateRoutes.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/StreamingAPI/APICreateStreamingAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Landing/Menus/StreamingAPIMenu.jsx
Fixes https://github.com/wso2/product-apim/issues/10759
When the user selects a Streaming API type as shown in [1], the protocol will be automatically selected as shown in [2].
[1]
[2]
> [Streaming API] Select streaming API protocol automatically

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
Fix icon alignment issue Postman Collection and OpenAPI icon in dev portal
> Fix icon alignment issue in DevPortal

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
Fixes: https://github.com/wso2/product-apim/issues/10790
To fix the issue of giving wrong response when invoking REST API generated from Soap back end.
Revert removed exporting of WSDL and SOAP to REST mediations of SOAPTOREST APIs
Actions https://github.com/YasasRangika/carbon-apimgt/actions/runs/732358528
> Fix error response when invoking SOAPTOREST API

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
This PR adds `apim:api_generate_key` for publisher role.
Fixes https://github.com/wso2/product-apim/issues/10854
> Update scopes for Internal/publisher

- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Any type of files can be added as API thumbnails through the REST API. This PR adds a restriction for the type of files which can be added as API thumbnails
Added a check condition to check whether the uploaded thumbnails file extension is in the following list
["jpg", "png", "jpeg", "gif"]
> Add File Restrictions for API Thumbnails

- components/apimgt/org.wso2.carbon.apimgt.rest.api.gateway/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.service.catalog/src/main/webapp/WEB-INF/beans.xml
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
This PR adds the "allowedOrigins" property to the "CrossOriginResourceSharingFilter" of the Product REST APIs. 
This "allowedOrigins" property will be reading values from System parameters. The defined system parameters are as follows.
- For Publisher REST APIs : rest.api.publisher.allowed.origins
- For Store REST APIs : rest.api.store.allowed.origins
- For Gateway REST APIs : rest.api.gateway.allowed.origins
- For Service Catalog REST APIs : rest.api.service.catalog.allowed.origins
Hence, the allowed origins for a particular REST API should be configured as a system parameter as follows.
[system.parameter]
'rest.api.publisher.allowed.origins' = "https://null.jsbin.com"
'rest.api.store.allowed.origins' = "https://null.jsbin.com,https://fiddle.jshell.net"
'rest.api.gateway.allowed.origins' …
> Add CORS allowedOrigins Property to CrossOriginResourceSharingFilter of Product REST APIs

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
As $subject, this will disable the key generation wizard button when a resident key manager or all key manager option is not selected from the publisher for an API.
After disabling it, **Subscription & key Generation Wizard** button will appear as follows
Fixes https://github.com/wso2/product-apim/issues/9031
> Disable key generation wizard button when all or resident key manager option is not selected

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/APICategoryThumb.jsx
This PR,
1. Adds category descriptions to Devportal
2. Set Https by default in the publisher test console
Fixes https://github.com/wso2/product-apim/issues/10450, https://github.com/wso2/product-apim/issues/10510
> Add category descriptions to Devportal

- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/EnvironmentDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
$subject
Fixes https://github.com/wso2/product-apim/issues/10578 
Fixes https://github.com/wso2/product-apim/issues/10573
Workflow : https://github.com/SuKSW/carbon-apimgt/runs/2317817809?check_suite_focus=true
> Update gateway env name validation regex to avoid unicode

- components/apimgt/org.wso2.carbon.apimgt.rest.api.common/src/main/java/org/wso2/carbon/apimgt/rest/api/common/RestApiConstants.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/10275
To restrict API Creators can delete Published or Deprecated APIs
Checked user's role and the status of the API before calling the deleteAPI.
Actions: https://github.com/wso2/carbon-apimgt/actions/runs/735521276
> Fix the issue of API Creators can delete Published APIs

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
This pr improves error handling when protocol is not given in Async API Service Definition. Related issue - https://github.com/wso2/product-apim/issues/10933
Fixes: https://github.com/wso2/product-apim/issues/10970
> Improve error handling when protocol is not given in Async API Service Definition

- components/apimgt/org.wso2.carbon.apimgt.persistence/src/main/java/org/wso2/carbon/apimgt/persistence/RegistryPersistenceImpl.java
Fixes https://github.com/wso2/product-apim/issues/10946
Approach :
* Here I have introduced a new toggle field (within the code, the field does not need to be added to document rxt)
* The issue earlier was because the document indexer did not get invoked because there was no change on the actual document artifact upon a document content update.
* The new toggle field will contain a boolean value which will be inverted each time a new document content update is done, thus a change in underlying document artifact and the document indexer will get triggered.
> Fix issue with doc content indexing

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/ChangePassword/ChangePassword.jsx
As $subject, this will avoid saving when the repeat password is not matched with the new password
Fixes https://github.com/wso2/product-apim/issues/10893
> Disable saving when new password doesn't match with the repeat password

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/raw.en.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
As $subject, this will improve the error message and allow some characters to have in the source file name when uploading source files as API documents. Otherwise, if this has other special characters it throws backend exceptions when uploading the file.
Fixes https://github.com/wso2/product-apim/issues/10841
> Improve error mesage and allow some characters for document source file

- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/StreamingAPI/APICreateStreamingAPI.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js
- Validate WebSocket endpoint URL [1]
- Disable the verify endpoint button for WebSocket Streaming APIs. Fixes https://github.com/wso2/product-apim/issues/10773
[1]
> [Streaming API] Validate WebSocket endpoint URL

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
Fixes: https://github.com/wso2/product-apim/issues/10953
Prevent showing 'Postman Collection' and 'OpenAPI' download options for SOAP APIs in devportal
Checked the type of API before rendering these buttons
> Fix showing download postman collection and OpenAPI for SOAP APIs

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes:  https://github.com/wso2/product-apim-tooling/issues/675
Fixes the issues of not using the persistence instance when importing/exporting sequences.
- Refactor the code to use persistence instance when adding mediation sequences
- Fix exporting SOAP to REST mediations correctly
- Restricted exporting SOAP to REST mediations only for gateway projects not for apictl projects.
- Restrict import API/API Products when specified nonexisting gateway envs and throw an error.
> Fixing the issues of not using the persistence instance when importing/exporting mediations and fix other issues

- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLConsole.jsx
- features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx
Fixes: https://github.com/wso2/product-apim/issues/10976
Remove 'Postman Collection' download option for GraphQL APIs in devportal.
Removed GraphQL schema processing from `GraphQLConsole`.
> Remove download postman collection button for GraphQL APIs

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Environment.java
- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/VHost.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/VHostDTO.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/EnvironmentMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
- features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/asyncapi/Runtime.jsx
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Constants.js
- features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Utils.js
The following properties are added to `deployment.toml`, to configure WebSub event receiver HTTP endpoint and HTTPS endpoint.
```toml
[[apim.gateway.environment]]
######## other properties ########
websub_event_receiver_http_endpoint = "http://localhost:7788"
websub_event_receiver_https_endpoint = "https://localhost:7789"
```
- Load these configurations and show WebSub event receiver endpoint URLs (Fixes https://github.com/wso2/product-apim/issues/10756 , Fixes https://github.com/wso2/product-apim/issues/10754).
- Add Copy to Clipboard button to the above (Fixes https://github.com/wso2/product-apim/issues/10360).
https://github.com/wso2/product-apim/pull/10956
> [Streaming API] Load WebSub event receiver endpoint details from config

- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
Adds scopes related to service-catalog and comments are not added to tenant-conf.json. Fixes https://github.com/wso2/product-apim/issues/11041
> Add new scopes to tenant-conf.json

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIControllerUtil.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/697
Fixing the issue of certificates are not getting imported when both the deployment and source repos have certs
- Deleted the existing certificates meta files before writing the new meta files in **APIControllerUtil.java**
- Ran all the apictl integration tests and got passed.
> Fixing certs import issue when both the deployment and source repos have certs

- .github/workflows/main-forks.yml
Current git actions in forked repos is using 3 runners and taking ~2h 15m.
This increases the runners to 5 results with ~1h 30m build time.
Run: https://github.com/malinthaprasan/carbon-apimgt/actions/runs/764499838
> [git actions] increase runners to 5 in forked builds

- components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- Set missing application owner in basic auth
- Fixed https://github.com/wso2/product-apim/issues/11077
> Set missing application owner in basic auth

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/APIMappingUtil.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/11043
This PR addresses three issues.
- When creating new API version with service which has different version than the existing service's version, API version is appended to the newly created API's context.
- In sub tenant, when creating new version of API from different version of the service, the newly created API's context get appended by tenant-domain each time.
- Create new API is only needed when the new version uses another version of service than the existing API has used. Otherwise it will directly call to `createNewAPIVersion()` method in APIProviderImpl.
- To prevent appending API version to the context in new version of API created from other version of service
- To prevent appending tenant domain each time to the context in …
> Fix context issues when creating new API versions from services

- components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
Fixes: https://github.com/wso2/product-apim/issues/10999
To show scopes in admin portal scope mapping that are available for Service Catalog api.
Added missing `service-catalog-api.yaml` to `fileNameArray`
Actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/766825899
> Fix missing admin portal scope-mapping scopes for Service Catalog

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ExportUtils.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/ImportUtils.java
Fixes: https://github.com/wso2/product-apim-tooling/issues/709
Fixes: https://github.com/wso2/product-apim-tooling/issues/708
- Added an API type check whether it is a SOAPTOREST API before adding SOAPTOREST sequences which will solve https://github.com/wso2/product-apim-tooling/issues/708
- Export the AsyncAPI Definition using the function that we use in the REST API which will solve https://github.com/wso2/product-apim-tooling/issues/709
> Fixes GraphQL import issue and AsyncAPI definition export issue

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/11100
Handle throwing NullPointer Exception when use invalid service version to create new version of API
Added null check to `ServiceEntry` value after searching service from `getServiceByNameAndVersion()`
Actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/771578866
> Handle Exception when creating new version of API from invalid service version

- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
Solve inconsistency in deployment page after the fix: https://github.com/wso2/carbon-apimgt/pull/10452
Fixes: https://github.com/wso2/product-apim/issues/11211
- Added else if check for `query:false` state
- Added else body to return all the revisions when `query: `
Actions: https://github.com/YasasRangika/carbon-apimgt/actions/runs/833773590
> Handling query:empty and query:false situations

- components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractKeyManager.java
- components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/ApplicationImportExportManager.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
- components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/utils/ImportUtils.java
Fixes wso2/product-apim#11125
if oauth app creation is disabled for the KM, we should treat it as an out of band app and use the mapped keys provided with the app.
implementation to avoid interface changes.
new overloaded method for `requestApprovalForApplicationRegistration` was introduced with `isImported` arg to identify if the request is coming from `import-app` API. This is then used to provide error msg when rest API is being used to generate keys for `create oauth apps` disabled KMs.
> Support importing keys for KMs configured with 'no oauth apps'
