wso2/carbon-apimgt

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Configuration/components/MaxBackendTps.jsx

https://github.com/wso2/product-apim/issues/5563

Publisher UI to configure maximum TPS for backends

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx

Fix https://github.com/wso2/product-apim/issues/5688

Fix issue duplicate document name

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Shared/CustomIcon.jsx

Fixes: https://github.com/wso2/product-apim/issues/5546

Fix overview icon issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx

Add error when deleting with active subscription
This warning is added to the detail view page and list view page
Fixes https://github.com/wso2/product-apim/issues/5609

Add error when deleting with active subscription

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/template/SOAPToRESTConfigContext.java

fix for https://github.com/wso2/product-apim/issues/5672

Fix NPE when soapAction is missing issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisher.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/publishers/WSO2APIPublisherTestCase.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ImportApiServiceImpl.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json

Add support for importing and exporting graphql apis.
Handle WSO2APIPublisher to export APIs removing custom sequences and endpoint certificates to publish to external stores.

Add support for importing and exporting graphql apis.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/Delete.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/EditScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Details/Scopes/index.jsx

Fixed scope UI rendering issues

Fixed scope UI rendering issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Base/Header/avatar/Avatar.jsx

Fix for https://github.com/wso2/product-apim/issues/5695

Fix login button click issue

---

components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/test/resources/carbon-home/repository/tenants/1/synapse-configs/default/sequences/jane-AT-gmail.com-AT-org12--YahooWeather_v1.0--In.xml
components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/pom.xml
components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
features/apimgt/org.wso2.carbon.apimgt.feature/pom.xml
pom.xml

Upgrade kernel version and incorporate changes relating to following
https://github.com/wso2/carbon-kernel/pull/2308
https://github.com/wso2/carbon-kernel/pull/2304

Upgrade carbon.kernel to 4.5.1

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/components/Apis/Create/WebSocket/ApiCreateWebSocket.jsx

Fixes part of https://github.com/wso2/product-apim/issues/2879

Fix WebSocket API creation issue in new UI

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/source/src/app/components/Apis/Listing/ApiTableView.jsx

This PR fixes issue https://github.com/wso2/product-apim/issues/5352 and a minor issue with rating in Store api list view.

Fix product-apim issue #5352

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberServiceTest.java

Fixed test case

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/left/template.jag

https://github.com/wso2/product-apim/issues/5358
1. Added view change without Analytics

Bot detection Feature - APIM 3.0.0 - Required Modification

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/GoTo/GoTo.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIProduct.js

In this PR:
- Fix the Resources page update issue for API products

Fix api product rate limiting UI issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Edit.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiTableView.jsx

This PR fixes the following issues in Publisher
1. https://github.com/wso2/product-apim/issues/5814
2. https://github.com/wso2/product-apim/issues/5712

Fix publisher issues

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/Documentation.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/OverviewDocuments.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx

This PR fixes following issues:
1. Fix issue in viewing documentation form left panel
2. Fix issue in redirecting to documentation page from API overview
3. Removes routes related to API Products in Store

Fix issue in viewing API docs in Store

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberServiceTest.java

Ignoring some tests in this Test class as they fail intermittently, causing Travis build unusable.
Issue to track: https://github.com/wso2/carbon-apimgt/issues/7232
Un-ignore these tests once fixed.

Ignoring intermittently failing tests

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json

related to https://github.com/wso2/carbon-apimgt/pull/7233
Fix APIM Store overview UI issue

Restoring material core version in devportal[new]

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json

Fix build failure of npm ci command due to duplicate eslint-config-airbnb config in package.json

fix build failure devportal

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ImageGenerator.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx

Fix https://github.com/wso2/product-apim/issues/5734 - Error in thumbnail upload page
Fix issue in upload image using dropzone.
Fix image preview issue.
Fix https://github.com/wso2/product-apim/issues/5929 - background color select not working properly

Fix Thumbnail view issues

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIProvider.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/API.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifecyclePending.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

This PR will 
Add rest api for life cycle task cleanup.
Add UI to handle life cycle state change and task cleanup

Add life cycle state change workflow 

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/SubscribeToApi.jsx

This PR fixes https://github.com/wso2/product-apim/issues/5878

fix issue in subscription in credentials page

---

features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2

**Issue**:
#5358
**Description**:
Added stream value to api-manager.xml/j2 file

 Add api-manager j2 changes of Bot detection feature- APIM 3.0.0

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx

Resolves https://github.com/wso2/product-apim/issues/5686

Fix for product-apim#5686

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClient.java

fixes https://github.com/wso2/product-apim/issues/5965

Fix inverted advance throttle policy in WSClient mode

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js

Fix for https://github.com/wso2/product-apim/issues/5750

Add validation for apiname, version and context length

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/SubscibeButtonPanel.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/Wizard.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/ApiKey.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx

Following PR fixes https://github.com/wso2/product-apim/issues/6033

improve credentials page namings

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx

Fixed resource path populating issue

Fixed resource path populating issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

Set API's default OAS version to 3
Fixed eslint issue

Set API's default OAS version to 3

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/EndpointsNew/Endpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycle.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Monetization/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx

Fix page title styles across pages and button spaces
Fixes: https://github.com/wso2/product-apim/issues/6093

Fix page title styles across pages

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx

Fixes [wso2/product-apim#5914](https://github.com/wso2/product-apim/issues/5914)

Fix unwanted comma in Overview page in API Security

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx

Fixed operation updated issue

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSTransportHandler.java
components/oidc-authenticator/org.wso2.carbon.apimgt.hostobjects.oidc/src/main/java/org/wso2/carbon/apimgt/hostobjects/oidc/OIDCRelyingPartyObject.java

Add secured algorithm SHA-256 to hash the password to be kept in the cache.
Prevent XXE attacks.
Fix improper resource shutdown or release.

Fix security issues 

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx

Fix for https://github.com/wso2/product-apim/issues/5641

Fix thumbnail image setting issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json

Related to https://github.com/wso2/carbon-apimgt/pull/7277

Fixing typo

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/LandingPage/Contact.jsx

Fixing https://github.com/wso2/product-apim/issues/6137

Correcting spelling mistake in devportal contact us in home page

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Tags.jsx

Resolves https://github.com/wso2/product-apim/issues/6037
When a tag is entered with illegal characters, a validation error message is displayed and the tag is marked in red. And the Save button in the configuration page is disabled until the invalid tag is corrected.

Fix for product-apim#6037

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

Fixed endpoint information to MG

Fixed endpoint information to MG

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/AppRouts.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/index.jsx

This PR fixes https://github.com/wso2/carbon-apimgt/issues/7171

fix application not redirecting to login issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/BusinessInformation/BusinessInformation.jsx

Fixes: https://github.com/wso2/product-apim/issues/6094

Fix business information page layout

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/SelectEndpoint.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx

Fixing https://github.com/wso2/product-apim/issues/6151

Fix for product-apim#6151

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx

This PR will fix https://github.com/wso2/product-apim/issues/5744

check app name exist case insensitivly

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Operations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/ProductResources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/StringFormatter.js

Fixes [wso2/product-apim#6183](https://github.com/wso2/product-apim/issues/6183)

Fix for inconsistent API Overview page and ApiThumb

---

.travis.yml
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/TenantsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/TenantsApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/operations/Tenants.html

Added scope validation

---

.travis.yml
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/TenantsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/TenantsApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/operations/Tenants.html

Reverts wso2/carbon-apimgt#7308

Revert "Added scope validation"

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/RolesApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/operations/Roles.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/Configuration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/MaxBackendTps.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx

Resolves https://github.com/wso2/product-apim/issues/6006

Fix for product-apim#6006

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/AbstractWSDLProcessor.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11ProcessorImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL20ProcessorImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.jsx

Fixes: wso2/product-apim/issues/5677

WSDL creation page improvements

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-old/site/conf/locales/jaggery/locale_default.json

fixes https://github.com/wso2/product-apim/issues/6222

Add missing locale texts 

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/avatar/Avatar.jsx

fix https://github.com/wso2/product-apim/issues/6095

Fix logout button outside click issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/Documentation.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/View.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/OverviewDocuments.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/UseWindowSize.jsx

Fixes for 
https://github.com/wso2/product-apim/issues/5706
https://github.com/wso2/product-apim/issues/5645
https://github.com/wso2/product-apim/issues/5586
https://github.com/wso2/product-apim/issues/5511

document related fixes

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js

Fix for https://github.com/wso2/product-apim/issues/5775

Fix creator edit prototype info issue

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/EnvironmentEndpointsDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/EnvironmentMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/EnvironmentEndpoints.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/MicroGateway.jsx

Fixes https://github.com/wso2/product-apim/issues/2879

Display Websocket endpoints of Environment instead of HTTP

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json

This PR will downgrade the swagger-ui version to 3.22.2 as the try out console does not work with the latest version of swagger-ui for OAS3 request body

fix swagger-ui console issue for request body

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/global/edit/template.jag

Enhance custom key template to support https://github.com/wso2/product-apim/issues/6047

resolves #6047

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionAvailability.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/TenantAutocomplete.jsx

This PR shows the selected values once the save button in clicked in the subscription availability component.

Showing selected values even when reloaded

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java

Fix https://github.com/wso2/product-apim/issues/6216

Listing created scopes sorted by name

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/MenuButton.jsx

Fix for https://github.com/wso2/product-apim/issues/5894

Disable api create button for publisher user

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java

fixes https://github.com/wso2/carbon-apimgt/issues/7288

Fix https://github.com/wso2/carbon-apimgt/issues/7288

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Constants.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Constants.jsx

This PR fixes issue in https://github.com/wso2/product-apim/issues/6207

Fix issue with OPTIONS resources

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx

Fix https://github.com/wso2/product-apim/issues/6233 - Option to sort API Scopes according to Action column
Fix https://github.com/wso2/product-apim/issues/6226 - Error when trying to sort API scopes
Removed the column-wise sort as it is not required/suited.

Fix scope page issue - remove sort column

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java

Resolves https://github.com/wso2/product-apim/issues/6034

Fix for product-apim#6034

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/MenuButton.jsx

Reverts wso2/carbon-apimgt#7361

Revert "Disable api create button for publisher user"

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/MenuButton.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiTableView.jsx

Fixing https://github.com/wso2/product-apim/issues/6237
Also, setting camel case to devportal list view headers

Fix for product-apim#6237

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiTableView.jsx

Fixed https://github.com/wso2/product-apim/issues/6167
Fixed https://github.com/wso2/product-apim/issues/6087
Fixed https://github.com/wso2/product-apim/issues/5932

Fixed bugs

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/LeftMenuItem.jsx

Fixes: https://github.com/wso2/product-apim/issues/6150

Fix sidebar menu items order

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Environments.jsx

Fix: 
https://github.com/wso2/product-apim/issues/5989
https://github.com/wso2/product-apim/issues/5717

Fix UI issues

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/pom.xml
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/pom.xml
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
pom.xml

Add CORS support for store/publisher REST APIs

Add CORS support for store/publisher REST APIs

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx

Fixed https://github.com/wso2/product-apim/issues/6283

Modified API Creation forms

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/policy/apiPolicy.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/policy/module.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/policy/subscription/edit/ajax/subscription-policy-edit.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/edit/js/edit.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/edit/template.jag

 Add role validations for subscription tier add/edit view

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx

Fixed https://github.com/wso2/product-apim/issues/6237

Fixed https://github.com/wso2/product-apim/issues/6237

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx

Fixing issue https://github.com/wso2/product-apim/issues/6056

Fixing issue #6056

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/MicroGateway.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Resource.js

Fixes https://github.com/wso2/product-apim/issues/6031

Fix errors in publishing WebSocket APIs

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx

Fix: https://github.com/wso2/product-apim/issues/5992

Fix https://github.com/wso2/product-apim/issues/5992

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/EditScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx

Fixed https://github.com/wso2/product-apim/issues/5707
Fixed https://github.com/wso2/product-apim/issues/5661

Fixed scope related issues

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/SubscriptionPolicySelect.jsx

fixing https://github.com/wso2/product-apim/issues/6015

Fix for product-apim#6015

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java

Fix WSDL->REST API generation issue

remove ACCESS_EXTERNAL_DTD feature set due to dependency issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx

This PR fixes issue https://github.com/wso2/product-apim/issues/6177

Fixing issue #6177

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fix https://github.com/wso2/product-apim/issues/6318

Fix error while product creation 

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Prototype/InlineEndpoints.jsx

Fix for https://github.com/wso2/product-apim/issues/6187

Fix prototype default payload

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

This PR fixes wso2/product-apim#6017

Fix issue wso2/product-apim#6017

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

Fixed MG related swagger properties refer in https://github.com/wso2/product-apim/issues/6274

Fixed MG related swagger properties

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comments.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/Documentation.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/LeftMenuItem.jsx

Fixed application detail page broken links

Fixing application detail page link problem

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/SettingsDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/SettingsMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/Settings.html
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx

Retrieve devportal URL from api-manager.xml configurations and set to settings API.
Fix store redirect URL links.

[Do not Merge] Add devportal URL to settings API and fix devportal URL link

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comment.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/CommentAdd.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/CommentOptions.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comments.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx

Fixing comments related issues and fixing some style issues.

comment related issues

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/ApplicationTableHead.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx

This PR will fix 
several grammar mistakes and typos.
Broken links to sandbox keys and subscription pages

Ux improvements and fix broken page links

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/CheckboxLabels.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx

Fixed in Lifecycle page as well.
Fixes: https://github.com/wso2/product-apim/issues/5828, https://github.com/wso2/product-apim/issues/1798

Fix business plans name

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APISecurityConstants.java

Fix https://github.com/wso2/product-apim/issues/6112

Fixed graphql specific intermittent issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java

fix for https://github.com/wso2/product-apim/issues/6331

Add missing script import

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx

This PR fixes the following issues,
https://github.com/wso2/product-apim/issues/5846
https://github.com/wso2/product-apim/issues/6197

Fixing issue #6197 and #5846

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java

Fixes the issue https://github.com/wso2/product-apim/issues/6345

Fix issue in publishing APIs in tenant

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/edit/template.jag

fixes https://github.com/wso2/product-apim/issues/6285

Fix https://github.com/wso2/product-apim/issues/6285

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx

Fix the issue of not showing copy icon in consumer secret and consumer key

improve view keys UI

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx

This will improve application listing UI to match styling of publisher

improve app listing ui

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java

fix for https://github.com/wso2/product-apim/issues/6158

Fix wsdl api invocation issue with jwt

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comment.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/CommentAdd.jsx

fixes for:https://github.com/wso2/product-apim/issues/5786

Fix store comment page issues

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java

Below exception can be seen when GET /swagger in Store when no Environments are selected in the API 
```
[2019-10-10 15:43:54,702] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.util.NoSuchElementException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1447) ~[?:1.8.0_211]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_211]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl.apisApiIdSwaggerGet(ApisApiServiceImpl.java:565) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.ApisApi.apisApiIdSwaggerGet(ApisApi.java:223) ~[classes/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessor …
```

Fixing NoSuchElementException during GET /swagger when no Environments in API

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx

This PR will fix broken buttons in credentials page and applications page when no applications exists

fix broken buttons clicks

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx

This PR fixes issue https://github.com/wso2/product-apim/issues/6168
The fix displays an error once an expired certificate is saved.

Fixing issue #6168

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/CORSConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Endpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Flow.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/MaxBackendTps.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/ResponseCaching.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/SchemaValidation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx

Fixes: https://github.com/wso2/product-apim/issues/5682, https://github.com/wso2/product-apim/issues/5481

Move message mediation to runtime configurations

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/AppErrorBoundary.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Adding a width to the api logo for devportal and publisher

Giving a width for the doc

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/GlobalNavbar.jsx

This PR fixes issue https://github.com/wso2/product-apim/issues/6314

Fixing issue #6314

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx

Change color of mandatory star to red
fix alignment issue when application attribute feature is enabled

Application createform minor changes

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/APIClient.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Constants.jsx

Fix login issue when an invalid token is present

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fix https://github.com/wso2/product-apim/issues/6372

Fix error while creating product in tenant

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/Documentation.jsx

Fixes: https://github.com/wso2/product-apim/issues/6389

Fix text orientation

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/manage/template.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/js/edit.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-add/template.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/label/label-list/template.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/app/manage/template.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/global/manage/template.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/resource/policy-list/template.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/policy/subscription/manage/template.jag

Fix below issues:
https://github.com/wso2/product-apim/issues/6106
https://github.com/wso2/product-apim/issues/6110
https://github.com/wso2/product-apim/issues/6125
https://github.com/wso2/product-apim/issues/3605

Fix admin portal UI and validation issues (6106,6110,6125,3605)

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/EditableRow.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx

FIxed https://github.com/wso2/product-apim/issues/6368

Fixed api property validation

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleImage.jsx

Fix for https://github.com/wso2/product-apim/issues/6248

Fix lc image arrow issue for blocked state

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/SubscriptionTableRow.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx

This PR fixes issue https://github.com/wso2/product-apim/issues/5629

Fixing issue #5629

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtilTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/definitions/endpointsData.json

Added security information to swagger

Added security information to swagger

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMgtDBUtil.java

remove -Dsetup on api manager database

remove -Dsetup on api manager database

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

Fixed formatting issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/BusinessInformation/BusinessInformation.jsx

Fixed https://github.com/wso2/product-apim/issues/6367

Fixed https://github.com/wso2/product-apim/issues/6367

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/GenericDisplayDialog.jsx

fixes https://github.com/wso2/product-apim/issues/6413

fix missing create app button

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/Tests/README.md
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/SelectPolicies.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/APICreateMenu.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/MenuButton.jsx

Depends on https://github.com/wso2/product-apim/pull/6426

Add element  ids for integration tests

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java

https://github.com/wso2/product-apim/issues/6376 - Api provider name of product in tenant

Fix producer -AT- in publisher

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java

Original issue can be found here on https://github.com/wso2/product-apim/issues/5988 - Business owner's name is not displayed in devportal.
This PR will fix it for the API products.

Show Business owner for product

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/TemplateUtilContext.java

Fix for https://github.com/wso2/product-apim/issues/5823

Remove whitespace fro url

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Create.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Edit.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/InlineMessage.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comments.jsx

Fixes for issue https://github.com/wso2/product-apim/issues/6385
Note that. Item 2 and 4 is not addressed.

Fixes for Properties page

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/AlertSubscriptionsApiServiceImpl.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/Alerts/Alerts.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/Settings.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/SettingsBase.jsx

Fixes https://github.com/wso2/product-apim/issues/6420
Fixes https://github.com/wso2/product-apim/issues/6409

Fix Alerts UX issues.

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/operations/APIs.html

Set support OAS versions as enum

Set support OAS versions as enum

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/EditScope.jsx

Fixed scope UI consistency issue

Fixed scope UI consistency issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx

This PR removes the super tenant domain when logging in as mentioned in [1] in issue https://github.com/wso2/product-apim/issues/6393
[1] https://github.com/wso2/product-apim/issues/6393#issuecomment-540999903

Remove super tenant domain when logging in

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx

Fix https://github.com/wso2/product-apim/issues/6400

Remove Prototyped APIs from the Subscriptions view of the Applications

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Monetization/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Resources.jsx

Fix overview page scroll issue.
**Previous**
**Change**
Fix endpoint certificate page UI issue.
Fix Monatization UI issue.

Fix UX issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/ResponseCaching.jsx

Fixing wso2/product-apim/issues/6443

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx

This PR fixes https://github.com/wso2/product-apim/issues/6428

fix token generation issue in client_credentials

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx

Fixes https://github.com/wso2/product-apim/issues/6065

Fix issue with onChangeRowsPerPage in publisher

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Prototype/InlineEndpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js

This pr fixes the following issues in the endpoints page.
1. Styling issues in the Endpoints Header.
2. Move the CircularProgress to the end of the save button.
3. Fix issue with removing endpoint security config.
Fixes https://github.com/wso2/product-apim/issues/6440
4. Add validation for endpoint security.
5. Fixes https://github.com/wso2/product-apim/issues/6391
6. Fixes https://github.com/wso2/product-apim/issues/5907
7. Fixes https://github.com/wso2/product-apim/issues/5910

Add Endpoints page fixes.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx

Fixes https://github.com/wso2/product-apim/issues/6433

Fix API display count in Publisher

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java

fixes https://github.com/wso2/product-apim/issues/6401
and also fixes authorization header not returned in api product get

Fix api product context issue and auth header issues

---

features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx

Fixes https://github.com/wso2/product-apim/issues/6427

Fixes alert page navigation issue for Internal/subscriber role.

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/SubscriptionsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/SubscriptionsApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
docs/apidocs/store/v1/operations/Subscriptions.html

Fix: https://github.com/wso2/product-apim/issues/5753
https://github.com/wso2/product-apim/issues/6378

Fix x-tenant subscription issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/EditableRow.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx

Fixes: https://github.com/wso2/product-apim/issues/6385

Fix properties page style and typo

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/refresh/refresh.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout_callback.jag

Fixed the issue in https://github.com/wso2/product-apim/issues/6265

Fixing security protection issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js

This PR fixes the following issues
- Set Maximum length of 30 and 60 characters to API Name and API context respectively.
- https://github.com/wso2/product-apim/issues/5732
- https://github.com/wso2/product-apim/issues/5761

Fixing issues #5761 and #5732

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifecyclePending.jsx

fixes https://github.com/wso2/product-apim/issues/6469

change lifecycle workflow button style

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/SaveOperations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx

Fixes https://github.com/wso2/product-apim/issues/6241

Add option to unset resource scope

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Delete.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Edit.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/TextEditor.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx

Fixed https://github.com/wso2/product-apim/issues/5369
Fixed https://github.com/wso2/product-apim/issues/5836

Fixed UI bugs

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/TenantListing.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiTableView.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Fixes https://github.com/wso2/product-apim/issues/5879

fix tenant scenario routing issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/LastUpdatedTime.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx

Fix https://github.com/wso2/product-apim/issues/5939 - Flicker subscriptions page content in Publisher SPA api details page
https://github.com/wso2/product-apim/issues/6414 - Publisher subscriptions page loading issue
Fix https://github.com/wso2/product-apim/issues/6390 - Move last updated time a bit down

Fix UI issues on publisher - last updated time and subscription page

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ApiEndpointValidationResponseDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/index.html
docs/apidocs/publisher/v1/models/ApiEndpointValidationResponse.html
docs/apidocs/publisher/v1/operations/Validation.html

Fixes https://github.com/wso2/product-apim/issues/6489

Add REST api operation for endpoint url validation

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Related to the wso2/product-apim#6489

Add appropriate error messages for endpoint test

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIInfoDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
docs/apidocs/store/v1/models/API.html
docs/apidocs/store/v1/models/APIInfo.html
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx

This PR fixes the following issues,
- https://github.com/wso2/product-apim/issues/6473
- https://github.com/wso2/product-apim/issues/6474

Fix issues 6473 and 6474

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/DescriptionAndSummary.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx

Fix https://github.com/wso2/product-apim/issues/6444 - Publisher resource page text alignment issue.
Previous - 
After fixing -

UI improvement Fix resource page text alignment issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fixed https://github.com/wso2/product-apim/issues/6166
Fixed https://github.com/wso2/product-apim/issues/6193

fir x for https://github.com/wso2/product-apim/issues/6193

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx

This PR fixes issue https://github.com/wso2/product-apim/issues/5743

Fixing issue #5743

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Message.jsx

This PR adds stacking for multiple messages in Publisher.
Fixes https://github.com/wso2/product-apim/issues/5764

Add stacking for multiple alert messages in Publisher

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/indexing/indexer/DocumentIndexer.java

Fixed https://github.com/wso2/product-apim/issues/6242

Fixed https://github.com/wso2/product-apim/issues/6242

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java

Fixes https://github.com/wso2/product-apim/issues/6482

Fix wso2/product-apim#6482

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx

This Pr fixes https://github.com/wso2/product-apim/issues/6498

Fix wso2/product-apim#6498

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/jaggery.conf
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/conf/site.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/pages/index.html
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/pages/index.jag

https://github.com/wso2/product-apim/issues/6369

remove hard coded context to support reverse proxy

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiTableView.jsx

Fixes https://github.com/wso2/product-apim/issues/5934

Remove sorting for the remaining two columns

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/GoTo/GoTo.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/CreateNewVersionButton.jsx

Removed lastUpdatedTime from top menu
Fixes: https://github.com/wso2/product-apim/issues/6029

Fix menu bar widths

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/MediationPolicies/EditMediationPolicy.jsx

Fixes: https://github.com/wso2/product-apim/issues/6457

Fix custom mediation policy select

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Create.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/MediationPolicies/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Security/AddPolicy.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Security/SecurityOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/LeftMenuItem.jsx

Get left menu transform style from default theme

Fix button style

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java

Fix https://github.com/wso2/product-apim/issues/6432

Fix condition group checking issue at Throttle handler

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/AppsTableContent.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx

Fixes https://github.com/wso2/product-apim/issues/6485
Fixes https://github.com/wso2/product-apim/issues/6180

application listing pagination related fixes

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/JWTAccessTokenIssuerDTO.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/APIMTokenIssuer.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/APIMJWTGenerator.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIMTokenIssuerUtil.java

This PR implements the following.
- Support for implicit grant JWT tokens
- Per service provider token validity period for JWT (honours validity period set via management console for user and app tokens)
- Refactoring code to minimize code duplication

Token Issuer fixes to support implicit grant and validity periods

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx

Fix https://github.com/wso2/product-apim/issues/5039

Fix for https://github.com/wso2/product-apim/issues/5039

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java

fixes https://github.com/wso2/product-apim/issues/6292

Fix https://github.com/wso2/product-apim/issues/6292

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/babel.config.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/introspect.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/refresh/refresh.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/pages/index.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/Tests/README.md
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/Configuration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/AddParameter.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/EditParameter.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/ListParameters.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/Parameters.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/operationUtils.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Download.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/stringFormatter.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js

In this PR:
Fixes: https://github.com/wso2/product-apim/issues/5655
Fixes: https://github.com/wso2/product-apim/issues/5515
Fixes: https://github.com/wso2/product-apim/issues/6228
Fixes: https://github.com/wso2/product-apim/issues/2660
Fixes: https://github.com/wso2/product-apim/issues/2661 (Support Microsoft Edge 20+)
Improvements: 
* Show warning and disable delete when an operation is used in API Product
* Add parameters for operations
* Change warning message

Add resource parameter list, add edit option

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/pages/index.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/blueBird.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/settings.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/App.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/LoginDenied.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Login/RedirectToLogin.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/APIClient.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Utils.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/webpack.config.js

Removing the non theme params from the defaultTheme.js and added the settings.js to keep the other params such as web app context.

Removing the non theme params from the defaultTheme.js

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java

Fix https://github.com/wso2/product-apim/issues/6508

Fix products are not listed in devportal issue

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java

Fix for https://github.com/wso2/product-apim/issues/6513

Fix NPE in subscription list page in publisher

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx

Fixes:https://github.com/wso2/product-apim/issues/6405

Fix api product backend info

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/CheckboxLabels.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx

Fix https://github.com/wso2/product-apim/issues/5596
Fix https://github.com/wso2/product-apim/issues/6501

Hiding credential tab for annoymous user and prototype info for graphql

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APISearchResultDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SearchApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SearchResultMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
docs/apidocs/store/v1/models/APISearchResult.html

Fix https://github.com/wso2/product-apim/issues/6495 -
Fixed -
1. When list by production, business owner and rating are not displayed.
2. Context is shown with and without version.
3. API products are not listed when production is selected.
4. -AT- sign is there when listed by production search
5. API product and API contexts are with and without version.

fix devportal search result api list issues

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIAdmin.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/LabelsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/test/java/org/wso2/carbon/apimgt/rest/api/admin/impl/LabelApiServiceImplTestCase.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/label/label-manage.jag

fixes for:
https://github.com/wso2/product-apim/issues/6069
https://github.com/wso2/product-apim/issues/6060
https://github.com/wso2/product-apim/issues/6057

Handling delete Micro-gateway label when it is attached to an API

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/headersearch/HeaderSearch.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/headersearch/SearchUtils.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/SearchUtils.jsx

Fixes https://github.com/wso2/product-apim/issues/6509

Fix header search box loading indicator

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/bot-detected-data/alert-list.jag

This is a fix to align with the name and field changes in analytics siddhi app.

Fix bot detection dashboard.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointListing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/LoadbalanceFailoverConfig.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Prototype/PrototypeEndpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

This PR includes the UI for endpoint testing for the create form and endpoint page.
This PR addresses https://github.com/wso2/product-apim/issues/6490

Testing endpoint UI

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx

This PR includes improvements for the Test Endpoint UI.

Improvements for Test Endpoint UI

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx

Fixes: https://github.com/wso2/product-apim/issues/6504
Related: https://github.com/wso2/product-apim/issues/6454

Fix duplicate add new buttons

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/lifecycles/APILifeCycle.xml

Fixes [wso2/product-apim#6442](https://github.com/wso2/product-apim/issues/6442)

Fix for incorrect grammar in API Lifecycle Page

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx

Fixes [wso2/product-apim#6459](https://github.com/wso2/product-apim/issues/6459)

Fixing Overlapping buttons in Developer Portal

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/StarRatingBar.jsx

Fix https://github.com/wso2/product-apim/issues/6463

Fix apithumb average rating stars

---

features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2

Map apim-handler-pingai configs from deployment.toml to api-manager.xml

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/GoTo/RouteMappings.jsx

Adding missing route mappings for the GoTo feature, specifically for GraphQL APIs.

Adding missing route mappings for GoTo Feature

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProduct.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/APIConfigContext.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/APIProduct.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/APIProduct/APIProductCreateWrapper.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx

This PR will, 
1. Fix the issues related to runtime configuration in APIProduct ( Security, Response Caching, schema validation)
2. Fix the typo issue in API Product create
3. Hide the sample api product deployment
4. Fix the issue in validation
Related issue : https://github.com/wso2/product-apim/issues/6510

Fixing issues related api Product

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes issue wso2/product-apim/issues/6255

Fixing store visibility issue with tenants

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json

Fixes https://github.com/wso2/product-apim/issues/6535

Fix incorrect config in tenant-conf.json

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/Wizard.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/ApplicationFormHandler.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx

Fix for 
https://github.com/wso2/product-apim/issues/6517
https://github.com/wso2/product-apim/issues/6519

Add workflow pending messages

---

features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ProvideOAuthKeys.jsx

Change enable parameter to enable_key_provisioning
Fix inconsistant UI style

minor changes to key provisioning feature

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/StarRatingBar.jsx

Fix for issues
https://github.com/wso2/product-apim/issues/6307
https://github.com/wso2/product-apim/issues/6544
https://github.com/wso2/product-apim/issues/6464

Store Fixes

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/SelectPolicies.jsx

Fixes https://github.com/wso2/product-apim/issues/6542

Fix API product and api create form issues.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiTableView.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/Alert.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/Message.jsx

Fixing https://github.com/wso2/product-apim/issues/6169 and styling store alert messages to look the same as publisher and nice.

Fixing issue https://github.com/wso2/product-apim/issues/6169

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java

fix for https://github.com/wso2/product-apim/issues/6518

Fix invoke api using blocked subscription jwt

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEditWorkspace.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Environments.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx

Fixing issues 
https://github.com/wso2/product-apim/issues/6113
https://github.com/wso2/product-apim/issues/6407

Fixing 6113 and 6407

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/SwaggerYamlApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/SwaggerYamlApi.java

Fixes: https://github.com/wso2/product-apim/issues/6553

Fixes 404 errors when loading the swagger from UIs

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx

* Set proper endpoint type for SOAP and SOAPTOREST api types.
* Fix SOAP api create flow wizard step rendering issue.
* Fix endpoints page to show the required configuration for api types.
Fixes https://github.com/wso2/product-apim/issues/5864

Add api publisher fixes.

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java

Fixing issue https://github.com/wso2/product-apim/issues/6573

Fixing -AT- issue in provider name for cross subscription

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fix for https://github.com/wso2/product-apim/issues/6554

Fix product unsubscribe issue

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fix for scope adding in tenant mode

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json

This PR replaces old scopes with new scopes related to the apim-analytics distribution

Replace old scopes with new scopes related to apim-analytics distribution

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java
components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/GraphQLSchemaDefinition.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Operations/Operations.jsx

This PR will support for Graphql invocation with nested level operations to do throttling, authorization, authentication
Related issues : 
https://github.com/wso2/product-apim/issues/6525
https://github.com/wso2/product-apim/issues/6560

Refactor the codebase to support nested level query operations

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SettingsApiServiceImpl.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx

Fixes https://github.com/wso2/product-apim/issues/6570

Fix application attributes not working for tenant issue

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
docs/apidocs/store/v1/models/Settings.html
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/App.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewCurl.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx

Following PR will add default gateway endpoint details to settings api, This will be used in constructing the curl in applications page in devportal
Fix issue of not getting settings of logged in user in api context

add gateway endpoint details to settings api

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Settings/Alerts/AlertConfiguration.jsx

Fixes https://github.com/wso2/product-apim/issues/6588

Enable alert subscription for API Products.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx

Fixes https://github.com/wso2/product-apim/issues/6567

Set redirect to runtime configurations page when selecting dynamic endpoints.

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Operations/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx

This Pr will fix the issue in scope drop drown of operation page,  file uploading, Style issue in the thumb box

Fixing issues in edge cases of graphql

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIProductDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/store/v1/operations/SDKs.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/ScopeValidation.jsx

1. Fix Publisher APIProduct delete button not rendering 
2. Fix unable to unsubscribe from APIProduct

API Product related fixes

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java

Fixes https://github.com/wso2/product-apim/issues/6568

Fix https://github.com/wso2/product-apim/issues/6568

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes https://github.com/wso2/product-apim/issues/6547

Fix Mutual SSL certificate upload issue for API Products.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/TenantAutocomplete.jsx

This PR changes the placeholder message of Subscription availability component.
It also displays upto 15 suggested tenants.

Change placeholder message

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx

Fix issue of publish button being disabled for admin in the overview stepper.

Publish button is disabled for admin

---

docs/apidocs/store/v1/operations/SDKs.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx

Fixes https://github.com/wso2/product-apim/issues/6600
Fixes https://github.com/wso2/product-apim/issues/6601

Fix API Publisher issues.

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/SubscriptionTableRow.jsx

Improve UI color

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/ProductResources/APIProductOperations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Resource.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

Allow re-deploy when current state is Published 

---

features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json

Fixes related to https://github.com/wso2/product-apim/issues/6591

change ntlm default configs

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java

Fix the Schema validation issue in swagger version 2

fixes #6602

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/TenantListing.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx

Order tenant list to alphabetical order
Fixes: https://github.com/wso2/product-apim/issues/5766
Fixes: https://github.com/wso2/product-apim/issues/6598

Fix tenant list oder and application name display length

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx

Remove * from the curl of the swagger ui for default resources (/*)

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/ExpiredJWTCleaner.java

implementing double check synchronization

Improve locking mechanism for JWT revoked token cleaner

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes https://github.com/wso2/product-apim/issues/6565 .With this fix, mediation sequence will be added to the registry only if it is valid.

Fix issue wso2/product-apim#6565

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/SubscriberRegistrationInterceptor.java

This fixes the issue https://github.com/wso2/product-apim/issues/6621

Fix wso2/product-apim#6621

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes https://github.com/wso2/product-apim/issues/6456

Fix store visibility role validation

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java

Fix for https://github.com/wso2/product-apim/issues/6617 is partially available already. This PR adds an improvement.

Fix https://github.com/wso2/product-apim/issues/6617

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java

Fix https://github.com/wso2/product-apim/issues/6620 - When tenant updates an API resource, they are not visible to others

Fix product-apim/issues/6620

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/NewEndpointCreate.jsx

Fixes https://github.com/wso2/product-apim/issues/6626
Fixes https://github.com/wso2/product-apim/issues/6627

Fix Publisher issues.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js

Fixes https://github.com/wso2/product-apim/issues/6624

Fixing issue when local storage timeout

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

This PR handles processing API swagger files with reference objects when generating the API Product swagger

Fix handling ref objects in APIProduct swagger

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Utils.jsx

Fixes https://github.com/wso2/product-apim/issues/6632

fix local storage & login user mismatch issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Scopes/Scopes.jsx

Fix page wrapper and create scope secondary button style
Fixes: https://github.com/wso2/product-apim/issues/6599#event-2735816593

Fix page wrapper

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/Background.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/Background.jsx

Fixes https://github.com/wso2/product-apim/issues/6587

Fix thumbnails not showing in edge

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIProvider.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fix https://github.com/wso2/product-apim/issues/6628

Fixing store visibility issue in API product

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes https://github.com/wso2/product-apim/issues/6630

Get URI Templates from the swagger when publishing api

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fix https://github.com/wso2/product-apim/issues/6658

Fixing operation listing issue in Graphql

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fixes https://github.com/wso2/product-apim/issues/6643

Fix API Product visibility issue in dev portal and publisher

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Reverts wso2/carbon-apimgt#7769

Revert "Fix store visibility role validation"

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx

Fixing https://github.com/wso2/product-apim/issues/6656

Fixing publisher access control edit failure

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/NewEndpointCreate.jsx

Modify mocked and prototype endpoint headings.

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/SearchUtils.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Fixes https://github.com/wso2/product-apim/issues/6661

Temporary fix to API Store Search bar alignment breaks in low resolution

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java

Fix https://github.com/wso2/product-apim/issues/6682 - Devportal pagination issues
**Description**
Product artifacts were not properly deleted when deleting a product. This caused pagination issues in devportal and product listing in publisher. This PR will fix it.

Fix product not deleted properly.

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java

Fix for https://github.com/wso2/product-apim/issues/6456

Add role validation for store visibility

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Add the suggested changes in the PR https://github.com/wso2/carbon-apimgt/pull/5904

Add the suggested changes in old PRs

---

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIStoreHostObject.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-old/site/themes/wso2/templates/overview/template.jag

Contains changes for comments in the following PR's 
- https://github.com/wso2/carbon-apimgt/pull/5770

Add suggested changes mentioned in PR comments 

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/UserAwareAPIConsumer.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fix for https://github.com/wso2/product-apim/issues/6708

Fix store visibility issue based on publisher role

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java

Fixes scope listing UI issue in Devportal and scope retrieval issue in scope issuer.
Fixes https://github.com/wso2/product-apim/issues/6649

Fix scope listing and invocation issue for products

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx

Fix: 
https://github.com/wso2/product-apim/issues/6684

Fixing issue in context validation for tenant user

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java

Fix https://github.com/wso2/product-apim/issues/6710

Fix display multiple versions not working in devportal issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java

Fixes https://github.com/wso2/product-apim/issues/6780

Adding null check for the extensions in OAS2 &OAS3 parsers.

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/tenant/tenant-conf.json

fix https://github.com/wso2/product-apim/issues/6702

Add Internal/analytics role to have apim:api_view scope

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fix for https://github.com/wso2/product-apim/issues/6770

Add descriptive error message for update apis in rest api publisher

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Settings/Alerts/Alerts.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/Alerts/Alerts.jsx

Fixes https://github.com/wso2/product-apim/issues/6768

Fix issue UI inconsistency issue in manage alerts

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx

fix minor ux issues

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx

Fixes issue 3 in https://github.com/wso2/product-apim/issues/6683
Fix ESlint issues in InfoBar.jsx file
Short App names
Long App names

Fix issue 3 in #6683

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/AddParameter.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/Parameters.jsx

Fixes https://github.com/wso2/product-apim/issues/6772
Fixes https://github.com/wso2/product-apim/issues/6737
Fixes https://github.com/wso2/product-apim/issues/6783

Fixing issues with resource parameters

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2

fixes https://github.com/wso2/product-apim/issues/6743
Add the following config to deployment.toml to enable the fix.
[apim.skip_roles_by_regex]
regex = "Application/.*"

Fix github 6743

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Progress.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/__snapshots__/Progress.test.jsx.snap

In this PR:
- Fixes https://github.com/wso2/product-apim/issues/6809
- Fixes https://github.com/wso2/product-apim/issues/6815

Fix default operation security value, error saving api design config and minor improvements 

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/SearchUtils.jsx

Fixes https://github.com/wso2/product-apim/issues/6698

Fix header search bar overlap issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/executors/APIExecutor.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/APIMJWTGenerator.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx

Reverts wso2/carbon-apimgt#7752
'
'Need to handle data migration cases
because there can be existing data with username without tenant domain and this fix add the username to the db with the tenantdomain in the case of carbon.super

Revert "Emailuser"

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SelectAppPanel.jsx

fixes https://github.com/wso2/product-apim/issues/6652

Fix https://github.com/wso2/product-apim/issues/6652

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx

Fixes https://github.com/wso2/product-apim/issues/5708

Fix issue #5708

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java

Fixes https://github.com/wso2/product-apim/issues/6439

Fix https://github.com/wso2/product-apim/issues/6439 

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/ApiContext.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/avatar/Avatar.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js

Fixes https://github.com/wso2/product-apim/issues/6695

Fix issue #6695

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/CertificateManagerImpl.java

Fix for: https://github.com/wso2/product-apim/issues/6834

Fix product-apim/issues/6834

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/PublisherAlertConfigurator.java

Fix https://github.com/wso2/product-apim/issues/6771

Fix alert configuration issue for same API in multi tenant environment

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Footer/Footer.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Footer/__snapshots__/Footer.test.jsx.snap
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Footer/Footer.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Fixes https://github.com/wso2/product-apim/issues/6666
Fixes https://github.com/wso2/product-apim/issues/6681
Change footer API-M version to v3.1.0

Fix issues #6666 and #6681

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java

This PR fixes the issue where scope retrieval fails for mysql.

Fix issue with scope retrieval in mysql

---

pom.xml

Reverts wso2/carbon-apimgt#7880

Revert "Version bump"

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/menu/left/template.jag

Fixes https://github.com/wso2/product-apim/issues/6678

Fix product-apim issue #6678

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/EditContent.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/GoToEdit.jsx

Fixes the following issues,
- Issue 1 in https://github.com/wso2/product-apim/issues/6561
- <FormattedMessage> not imported issue

Fixing issue 1 in issue #6561

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java

Fixes https://github.com/wso2/product-apim/issues/6562

Fix issue #6562

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Set throttling level when creating an API.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/APICreateMenu.jsx

Fixes https://github.com/wso2/product-apim/issues/6892
Fixes https://github.com/wso2/product-apim/issues/6890

Fixes issues #6890 and #6892

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/ApiKey.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ApiKeyManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewToken.jsx

Fixes https://github.com/wso2/product-apim/issues/6700
Fix ES lint issues as well

Fix issue #6700

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SubscriptionMappingUtil.java

Fixes product-apim/issues/6911

Fixing product-apim/issues/6911

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/Download.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/NewEndpointCreate.jsx

Fixes https://github.com/wso2/product-apim/issues/6846
Fixes https://github.com/wso2/product-apim/issues/6776

Fix issues #6846 and #6776

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx

Fixes https://github.com/wso2/product-apim/issues/6814

Fixing issue #6814

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/GoToEdit.jsx

Fixes https://github.com/wso2/product-apim/issues/6910

Fixing issue #6910

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtUsageHandler.java

Fix to support graphQL analytics

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/APICreateMenu.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/ApplicationFormHandler.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/SettingsBase.jsx

Fixes https://github.com/wso2/product-apim/issues/6907
Fixes https://github.com/wso2/product-apim/issues/6908
Fixes https://github.com/wso2/product-apim/issues/6923

Fixes  issues #6907, #6908 and #6923

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/babel.config.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/babel.config.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/customPolyfill.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/index.jsx

Fixes https://github.com/wso2/product-apim/issues/6940

add polyfill to enable TextEncoder for ms edge

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Settings/Alerts/AlertConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Settings/Alerts/Alerts.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/Alerts/AlertConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Settings/Alerts/Alerts.jsx

Fixes https://github.com/wso2/product-apim/issues/6680
Fixes https://github.com/wso2/product-apim/issues/6685
In both Publisher and Dev Portal

Fixes issues #6680 and #6685

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Invoice.jsx

Fixes https://github.com/wso2/product-apim/issues/6673
Fix ES lint issues

Fixing issue #6673

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/APISecurity.jsx

Fixes https://github.com/wso2/product-apim/issues/6888

Fixing issue #6888

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/ResourceConstants.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java

Changing the variable name and value.

Changing the varibale name and value in skipping role scope validation during JWT bearer grant

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes https://github.com/wso2/product-apim/issues/6851

Add mediation policy using inline content.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/EditableRow.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js

Fixes https://github.com/wso2/product-apim/issues/6527

Fixing issue #6527

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/components/DeleteApiButton.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx

Fixes https://github.com/wso2/product-apim/issues/6975

Fixing issue #6975

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/APISecurity.jsx

Fixing API Product issue in Runtime Configurations.

Fixing API Product issue

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java

Fixes https://github.com/wso2/product-apim/issues/6813

Add missing default parameters to the soap api definition.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx

Add UI support for advanced endpoint configurations in dynamic endpoints.

Fix https://github.com/wso2/product-apim/issues/6839

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/Wizard.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/ApiKey.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Validation.jsx

Fixes https://github.com/wso2/product-apim/issues/6748
Eslint fixes

add validity period button for first time keygen

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/View.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx

Fixes https://github.com/wso2/product-apim/issues/7035
Fixes https://github.com/wso2/product-apim/issues/7022

Fixing issues #7035 and #7022

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/SubscriptionTableRow.jsx

Fixes https://github.com/wso2/product-apim/issues/7023

Fixing issue #7023

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Labels.jsx

Fixes https://github.com/wso2/product-apim/issues/7060
Fixes ES Lint issues.

Fixing issue #7060

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java

Fix issue in exporting and importing SOAP to REST converted API

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx

Fixes https://github.com/wso2/product-apim/issues/6742

add apikey to api tryout console

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SwaggerData.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/AWSLambdaSettings.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/AmznResourceName.jsx

[AWS Lambda] Adding timeout for each resource

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointListing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GenericEndpointAdd.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/LoadbalanceFailoverConfig.jsx

Fixes https://github.com/wso2/product-apim/issues/6727

Fixing issue #6727

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SwaggerData.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/AmznResourceName.jsx

Reverts wso2/carbon-apimgt#7997

Revert "[AWS Lambda] Adding timeout for each resource"

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/avatar/Avatar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Fixes https://github.com/wso2/product-apim/issues/6677
Change avatar icon in devportal

Fixing issue #6677

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/GoTo/RouteMappings.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx

Fixes https://github.com/wso2/product-apim/issues/6642
Fixes https://github.com/wso2/product-apim/issues/6841

Fixes issues #6642 and #6841

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx

fixes https://github.com/wso2/product-apim/issues/7098

add space for curl bearer

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

1. Fixes https://github.com/wso2/product-apim/issues/7094
2. Adds more debug logs to the on the fly scope migration flow of tenant-conf.json

Fixing wso2/product-apim#7094 and adding more debug logs

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/API.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx

Fixes https://github.com/wso2/product-apim/issues/6979

Persist the wsdlUrl when updating API

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsH2MySQL.java

Applications were not sorted when the arrow is clicked for H2 database. It has been resolved.
Fix wso2/product-apim/issues/7034

Sort applications when arrow is clicked.

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/listeners/KeyManagerUserOperationListener.java

Fixes product-apim/issues/7138

Fixing product-apim/issues/7138

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/listeners/KeyManagerUserOperationListenerTestCase.java

Fixes product-apim/issues/7138

Fixing unit test failures

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java

Fixes https://github.com/wso2/product-apim/issues/7158

Fixing APIs in publisher dissappears for email user

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/SAMLGroupIDExtractorImpl.java

This PR will fix the issue https://github.com/wso2/product-apim/issues/7165

Fixing the multi-attribute claim value retrieval issue

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyDataStore.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/APIKeyValidatorClient.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/keys/WSAPIKeyDataStore.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidatorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/AbstractKeyValidationHandler.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/KeyValidationHandler.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationService.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/src/main/resources/APIKeyValidationService.wsdl

Add subscription Validation with key manager

Add subscription validation with Key Manager in the jwt authentication

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APISecurityAudit.jsx

Fixes [wso2/product-apim#7140](https://github.com/wso2/product-apim/issues/7140)

Fix for UI issue in API Security Audit Feature

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx

Fixes https://github.com/wso2/product-apim/issues/7151

Fixing issue #7151

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json

Fixing [carbon-apimgt#8048](https://github.com/wso2/carbon-apimgt/issues/8048)

Downgraded the swagger-ui version

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag

Fix resource parameter cannot be deleted issue if resource path contained a dot

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SwaggerData.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/URITemplate.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIOperationsDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/APIOperations.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/AWSLambdaSettings.jsx
service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/src/main/resources/APIKeyValidationService.wsdl

[AWS Lambda] Adding timeout for each resource 

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/DevPortal.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/api.jsx

In this PR:
- Fix Dev portal sample CURL not reflecting gateway endpoint URL issue
- Rename component name to `DevPortal`

Fixing https://github.com/wso2/product-apim/issues/7197

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/refresh/refresh.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/APIClient.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx

Address https://github.com/wso2/product-apim/issues/7203 issue

Fix auto token refresh issue in devportal

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comment.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comments.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/Documents.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Sdk.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Overview.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ApiKeyManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/InlineMessage.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/LeftMenuItem.jsx

Subscription listing page reorganized.

Fixing Application detail page menu issues

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

fixes wso2/product-apim#7211
adding a check for already existing caches and if the cache is already existing returning the existing cache.

Fix caches already existing when initializing issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/endpointUtils.js

Fix https://github.com/wso2/product-apim/issues/6909

Fix issue in endpoint page of migrated APIs

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

Fixes https://github.com/wso2/product-apim/issues/6919.

Fix issue in creating API Products from migrated APIs

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/IDPConfiguration.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/APIStateChangeSimpleWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationCreationSimpleWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationDeletionSimpleWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationRegistrationSimpleWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/ApplicationRegistrationWSWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionCreationSimpleWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/SubscriptionDeletionSimpleWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/UserSignUpSimpleWorkflowExecutorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/workflow/UserSignUpWSWorkflowExecutorTest.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/constants.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/logout/logout.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/constants.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/logout/logout.jag

Fixes : https://github.com/wso2/product-apim/issues/6758

Support externalizing authorize/logout endpoints to a different WSO2 IDP

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java

Fixed https://github.com/wso2/product-apim/issues/7233

Fixed https://github.com/wso2/product-apim/issues/7233

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java

Fix wso2/product-apim/issues/7186

Fix exception during setup of grant types of application.

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java

Refactor the code.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/loader.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/override/src/Readme.txt
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/conf/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/loader.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/CopyAccessTokenStep.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/CreateAppStep.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/GenerateAccessTokenStep.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/GenerateKeysStep.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/SubscribeToAppStep.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Wizard/Wizard.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/DocList.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/ViewToken.jsx

Fixing issue 
https://github.com/wso2/product-apim/issues/7135
and
Adding jsx overriding ability to the publisher.

UI fixes for devportal

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java

Fix for https://github.com/wso2/product-apim/issues/7152

Fix for #7152

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIConsumer.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/utils/ApplicationImportExportManager.java

This PR will fix the issue when importing applications
Fix: https://github.com/wso2/carbon-apimgt/issues/8051

Fixing the importing application issue

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SubscriptionDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
docs/apidocs/store/v1/models/Subscription.html

This PR is a front ported fix for https://github.com/wso2/product-apim/issues/7204

Add support for http workflow response in rest api

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/impl/WebAppAuthenticatorImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/URLValidationInterceptor.java

Fix 
https://github.com/wso2/product-apim/issues/6537
https://github.com/wso2/product-apim/issues/6912

Fix for #6912 & #6537

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/ImportDefinition.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/AppErrorBoundary.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Loading/Loading.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx

In this PR:
- Fixes https://github.com/wso2/product-apim/issues/6827

 Fix import API definition issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/ApisApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/WSDLInfoDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/docs/examples/apis/wsdl/apiId_wsdl_info_get.yaml
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/index.html
docs/apidocs/publisher/v1/models/API.html
docs/apidocs/publisher/v1/models/WSDLInfo.html
docs/apidocs/publisher/v1/operations/APIs.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/WSDL/Steps/ProvideWSDL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/ImportDefinition.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/WSDL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/Resource.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

- Viewing the WSDL of SOAP APIs
- Downloading WSDL or WSDL ZIP archive
- Import and update the WSDL (by URL, File or ZIP)
Fixes: https://github.com/wso2/product-apim/issues/7332

Publisher - WSDL View/Update UI

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/ApiKeyGenerator.java

Fix: https://github.com/wso2/product-apim/issues/7295

Add issuer claim to API Key

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/webapp/WEB-INF/beans.xml
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml

fix for https://github.com/wso2/product-apim/issues/7317

Add Content-Disposition header in exposeHeaders

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fixes: https://github.com/wso2/product-apim/issues/7345

Fixing API update issue with SOAP APIs

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/jagg/jaggery_acs.jag

Fixes second issue stated in https://github.com/wso2/product-apim/issues/7315

Fix issue in admin portal sso logout

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11ProcessorImpl.java

This PR fixes wso2/product-apim#7291 and https://github.com/wso2/product-apim/issues/6415.

Fix issue when complex types parameters have same name and wsdl has xsd imports

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
docs/apidocs/publisher/v1/operations/APIs.html

add configuration to disable Default Application creation from tenant-wise

resolves #https://github.com/wso2/product-apim/issues/7333

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPOperationBindingUtils.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPToRESTConstants.java

This PR fixes https://github.com/wso2/product-apim/issues/6732 and fixes https://github.com/wso2/product-apim/issues/5897

Fix issues wso2/product-apim/#6732 and wso2/product-apim#5897

---

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/TenantManagerHostObject.java

NOTE
---------
Do not merge this PR until the per tenant SPs for APIM apps is done.
--------------------------------------------------------------------------------------------------------
This PR adds support for loginTheme.json file inside tenant_themes folder
related product-apim PR : https://github.com/wso2/product-apim/pull/7303

Add support for loginTheme.json file inside tenant_themes folder

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/conf/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/index.jsx

Fixes: https://github.com/wso2/product-apim/issues/6707
Made the stepper background colors themeable via default theme

Improve overview stepper UX

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java

This PR fixes https://github.com/wso2/product-apim/issues/7178

Fix issue with importing APIs using apictl when Secure Endpoint is enabled

---

pom.xml

This PR upgrades the Identity Server component dependencies.

Upgrade IS dependencies

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java

Fixed https://github.com/wso2/product-apim/issues/7343

Fixed https://github.com/wso2/product-apim/issues/7343

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Fixes https://github.com/wso2/product-apim/issues/7285
Fixes https://github.com/wso2/product-apim/issues/7267

Fixing issue #7267 and #7285

---

pom.xml

Reverts wso2/carbon-apimgt#8142

Revert "Downgrade identity saml2 version"

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

Fix https://github.com/wso2/product-apim/issues/7205
Description:
This PR will introduce an x-wso2-api-security extension to present the application level security types allowed for the API.

Add x-wso2-api-security extension

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes: https://github.com/wso2/product-apim/issues/7093
Fixes: https://github.com/wso2/product-apim/issues/4998

Fixing swagger update issue and appOwner update autocommit issue

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx

Fixes https://github.com/wso2/product-apim/issues/7338

Fixing issue #7338

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/BasicAuthenticationInterceptor.java

Fixes https://github.com/wso2/product-apim/issues/7391

Validate scopes in REST APIs when invoked using basic auth 

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Login/RedirectToLogin.jsx

Addressed review comments in https://github.com/wso2/carbon-apimgt/pull/7031, https://github.com/wso2/carbon-apimgt/pull/8039

Addressed review comments

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/TenantInfoApiServiceImpl.java

This PR encodes username for the tenant-info api.

Support encoded username for the tenant-info api

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java

Set base path extension

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java

Fixes https://github.com/wso2/product-apim/issues/7408

Fix incomplete swagger generation when SOAP message has many parts

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/Utils.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/MutualSSLCertificateHandler.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/authenticator/MutualSSLAuthenticator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/reloader/CertificateReLoader.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/certificatemgt/reloader/CertificateReLoaderUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.unit-resolve.json
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml

add functionality to validate Mutual SSL certificate as a Header

add functionality to validate Mutual SSL certificate as a Header

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/utils/APIUtilTest.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/AbstractScopesIssuer.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopeIssuerTestCase.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/PermissionBasedScopesIssuerWrapper.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerTestCase.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuerWrapper.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/scope-mapping/scope-mapping.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/blocks/settings/scope-mapping/ajax/scope-mapping.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/settings/scope-mapping/js/scope-mapping.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/settings/scope-mapping/template.jag

Fixes https://github.com/wso2/product-apim/issues/6605
UI changes done in Admin portal webapp :

Add support for role mapping in tenant-conf.json 

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/wsdl/WSDLSOAPOperationExtractorImplTestCase.java

This PR fixes wso2/product-apim#7108. Ports the fix added to 2.6.0

Fix the issue in generating swagger when WSDL has inline nested complex types definitions 

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

fix for  wso2/product-apim#7003

fix for registry resource is added as the mediation seuence file name

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx

Fixes: https://github.com/wso2/product-apim/issues/7386

Fix security tooltip text

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIMWSDLReader.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/SequenceGenerator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SOAPToRESTConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/wsdl/WSDLSOAPOperationExtractorImplTestCase.java

Fixes https://github.com/wso2/carbon-apimgt/issues/7969. Ports the fix added in 2.6.0

Fixes  https://github.com/wso2/carbon-apimgt/issues/7969

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/AuditReportDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/AuditReport.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APISecurityAudit.jsx

Fixing [wso2/product-apim#7424](https://github.com/wso2/product-apim/issues/7424)

Adding link to report in 42Crunch Platform

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx

Fixing issue cannot switch between API and Operation level

Fixing issue cannot switch between API and Operation level

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx

Fixes: https://github.com/wso2/product-apim/issues/6969

Add none option to operation scope select

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx

Reloading the portals continuously issue

disbaling SLO feature

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java
features/apimgt/org.wso2.carbon.apimgt.gateway.feature/pom.xml
features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml

Added swagger-inflector jar to store/gw profile

Added swagger-inflector jar to store/gw profile

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx

product-apim: https://github.com/wso2/product-apim/issues/7410
Adding redirect to login with prompt=none when session changes.

Resolve Single Logout loop issue

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/DevPortal.jsx

Along with [1] we are changing the directory structire for tenant theming as below. This PR adds the changes required for APIM devportal theming.
[1]. https://github.com/wso2/product-apim/pull/7454

Change tenant theme directory structure

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx

Fixes [https://github.com/wso2/product-apim/issues/7465](https://github.com/wso2/product-apim/issues/7465)
Created a style class 'paper' and added the padding styles to fix the [3.1.0][UX] Resource Page Styling issue.

Added padding to fix publisher resource page styling issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/SwaggerEditorDrawer.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/swaggerUI/PatchedSwaggerUIReact.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/swaggerUI/SwaggerUI.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx

This PR fixes the issue related to cursor shifting in the swagger editor.
Fixes wso2/product-apim#7446
The commit (https://github.com/wso2/carbon-apimgt/pull/8203/commits/e1c3ebe9334030c397e144b8c016b3ae3e178ac4)  Fixes https://github.com/wso2/product-apim/issues/7482
Along with that, this PR updates the spotlight/prism-http version.

 Revamp Swagger Editor

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/RestApiPublisherUtils.java

This PR fixes https://github.com/wso2/product-apim/issues/7489

Fix issue in SOAP API generation

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APICategories.jsx

fixes https://github.com/wso2/product-apim/issues/7491

Add notification text to category drop down when there are no api categories defined.

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/OpenAPIUtils.java

This PR fixes issue https://github.com/wso2/product-apim/issues/7470.

Fix issue in basic auth scope validation

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIKey.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/ApplicationKeyDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/ApplicationKeyMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
docs/apidocs/store/v1/models/ApplicationKey.html
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx

Add additionalProperties parameter to pass additional information to the keymanager interface for update oauth application. This would be useful when plugin an external keymanager and needs to pass custom attributes

Improvements to key-gen apis

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/Operation.jsx

Fixes [https://github.com/wso2/product-apim/issues/7477](https://github.com/wso2/product-apim/issues/7477)
Added scope to the resources publisher UI to the operations list expansion panel summary and did few adjustments in styles.

added scopes to resources publisher UI

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiThumb.jsx

Fixes https://github.com/wso2/product-apim/issues/7476

Added chip to display API state in devportal

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/InfoBar.jsx

Fixes https://github.com/wso2/product-apim/issues/7515

Fixed deletion alert issue and intl ids

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx

Fixes: https://github.com/wso2/product-apim/issues/6719
Fixes: https://github.com/wso2/product-apim/issues/7525

Fix typography

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/DocumentSearchResultDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/Flow.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/SaveOperations.jsx

Fixes https://github.com/wso2/product-apim/issues/7508 and fixes https://github.com/wso2/product-apim/issues/7519

Fixes wso2/product-apim#7508 and wso2/product-apim#7519

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtSubscriberService.java

Fix https://github.com/wso2/product-apim/issues/5962

Fix token gen after application name update issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx

Fixes https://github.com/wso2/product-apim/issues/7463 in product-apim

Enable Create button without waiting for any event in UI

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java

Fixes https://github.com/wso2/product-apim/issues/7021

Fix issue in importing APIs with docs

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2

Fixes https://github.com/wso2/product-apim/issues/7319
Fixes https://github.com/wso2/product-apim/issues/7244

Fixing issues #7319 and #7244

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comment.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/Comments.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx

Fixing issue https://github.com/wso2/product-apim/issues/7020
Comments show no comments for a brief moment when navigating from another tab.
Fixing issue https://github.com/wso2/product-apim/issues/7018
When navigating from another tab to Subscription tab loading text appears

Fixing Devportal issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx

Ref: https://github.com/wso2/product-apim/issues/7386

Add localizations

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fixes [wso2/product-apim#7543](https://github.com/wso2/product-apim/issues/7543)

Fix for improve error handling in API Security Audit feature

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApiProductsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes https://github.com/wso2/product-apim/issues/7486 related to API update when mutual SSL is enabled

Fix issue in API update when mutual SSL is enabled

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/APIMgtGatewayConstants.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/dto/JWTInfoDto.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/dto/JWTTokenPayloadInfo.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/generator/APIMgtGatewayJWTGeneratorImpl.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/generator/APIMgtGatewayUrlSafeJWTGeneratorImpl.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/transformer/DefaultJWTTransformer.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/transformer/JWTTransformer.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/ServiceReferenceHolder.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/TenantServiceCreator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidatorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/caching/CacheProvider.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/JWKSConfigurationDTO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/JWTConfigurationDto.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/TokenIssuerDto.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2

Fix https://github.com/wso2/product-apim/issues/7467

Improvement to support multiple token issuers with Claim Mappings

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx

Fixes: https://github.com/wso2/product-apim/issues/6860

Make Lifecycle buttons primary

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIProviderImplTest.java

Fix wso2/product-apim/issues/7448

Adding visibility of docs when API is made public from the restricted by roles

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/utils/mappings/APIMappingUtil.java

This PR fixes the issue product-apim-tooling/issues/165 in the Publisher REST API 0.15

fix for https://github.com/wso2/product-apim-tooling/issues/165

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/recommendationmgt/AccessTokenGenerator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/recommendationmgt/RecommendationEnvironment.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/recommendationmgt/RecommenderDetailsExtractor.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/recommendationmgt/RecommenderEventPublisher.java
components/apimgt/org.wso2.carbon.apimgt.output.adapter.http/src/main/java/org/wso2/carbon/apimgt/output/adapter/http/ExtendedHTTPEventAdapter.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/RecommendationsApiServiceImpl.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2

With this PR following changes are done to the recommendations feature.
1. Improve Application details extraction
2. Send resource description and summery with events
3. Make getRecommendation request nonblocking using a caching mechanism
4. Updated the default maxRecommendations to 6
5. Added the support to skip OAuth URL for output adapter if publishing URL is from the same server.

Recommendation feature changes

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/pom.xml
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/Readme.txt
features/apimgt/org.wso2.carbon.apimgt.store.feature/pom.xml
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/Readme.txt

Fixes https://github.com/wso2/product-apim/issues/7541

Add source code to APIM pack

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/APIDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml

Fix https://github.com/wso2/product-apim/issues/7520

Fix https://github.com/wso2/product-apim/issues/7520

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleHistory.jsx

Fixes https://github.com/wso2/product-apim/issues/6529

Change Lifecycle history order

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/GraphQL/Steps/ProvideGraphQL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx

Fixes https://github.com/wso2/product-apim/issues/6018

Added effect hook for graphql file validation

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Overview.jsx

Fixes #https://github.com/wso2/product-apim/issues/7574

Fixing issue #7574

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java

Fixes https://github.com/wso2/product-apim/issues/7571.

Fix issue in invoking GraphQL APIs using API key

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx

Fixes https://github.com/wso2/product-apim/issues/7569

Fixing api not updating after swagger definition is updated

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/.eslintignore
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx

Fixes #https://github.com/wso2/product-apim/issues/7580
This PR only adds Basic Auth to the Try Out tab

Add Basic Auth to Try Out Tab in DevPortal

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/ImportDefinition.jsx

fixing https://github.com/wso2/product-apim/issues/7502
Fixing import execution going in a wrong path.

Fix graphQL import schema issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/APITemplateBuilderImpl.java

Fixes: https://github.com/wso2/product-apim/issues/7599

Fix for generating soap2rest synapse sequences in wsdl file/zip upload

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/ExtendedJWTBearerGrantHandler.java

fixes https://github.com/wso2/product-apim/issues/7514
checking the IDP returned and returning relevant error messages.

Fix null pointer exception issue in JWT grant

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/manage/js/manage.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/manage/template.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/Alert.jsx

Formating JSON in Blacklisted Items page

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/events/TokenRevocationNotifierImpl.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/events/TokenRevocationNotifierImplTest.java

This PR fixes testDeleteAuthorizedAppById test failure in IS KM.

Fix testDeleteAuthorizedAppById failure in iskm

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.dcr/src/main/java/org/wso2/carbon/apimgt/rest/api/dcr/web/impl/RegistrationServiceImpl.java

fixing https://github.com/wso2/product-apim/issues/7624
remove the username prepend logic.

Remove admin username prepend from SP applications

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/XACMLAuthenticationInterceptor.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx

Fixes: https://github.com/wso2/product-apim/issues/7613
Fixes: https://github.com/wso2/product-apim/issues/7623

Fix issues

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProductResource.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/EndpointSecurity.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/APITemplateBuilderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/EndpointSecurityModel.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/SecurityConfigContext.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/SecurityConfigContextTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/template/SecurityConfigContextWrapper.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.tracing/pom.xml

Resolves #https://github.com/wso2/product-apim/issues/1547

add production and sandbox security

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/apikey/ApiKeyAuthenticator.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/CORSConfiguration.jsx

Fixes issue apikey not working
Remove adding CORS from UI

Fixes issue apikey not working

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx

Change label Referenced(Oauth) to Oauth in devPortal

Change label Referenced(Oauth) to Oauth

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/AbstractApplicationRegistrationWorkflowExecutor.java

Fix for https://github.com/wso2/product-apim/issues/7640

Set Application attributes to the oAuthAppRequest object

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml

Fixes: https://github.com/wso2/product-apim/issues/7641

Replace spaces in name/version when importing APIs

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx

Fixes https://github.com/wso2/product-apim/issues/7422

Adding conditional alerts and i18n

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/SubscribeToApi.jsx

The PR fixes the issue raised in [https://github.com/wso2/product-apim/issues/7615](https://github.com/wso2/product-apim/issues/7615)

Fixes https://github.com/wso2/product-apim/issues/7615

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/graphQL/GraphQLAPIHandler.java

Fix: https://github.com/wso2/product-apim/issues/7645

Supporting nested level mutation in Graphql

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/ApiKeyGenerator.java

Fixes https://github.com/wso2/product-apim/issues/7638

Fix issue #7638

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLAuthentication.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx

graphql tryout console

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLAuthentication.jsx

modify graphql tryout console

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

This PR adds a check to verify existence of workflow configurations file to avoid errors on IS KM startup.

Check existence of workflow configurations file

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/ImportApiServiceImpl.java

Fix  https://github.com/wso2/product-apim/issues/7576

Set tokenType to DEFAULT when importing application tokenType is null

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java

Fix https://github.com/wso2/product-apim/issues/7665

Fix pagination issues in REST API

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/DevPortal.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ImageGenerator.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/Header/LanuageSelector.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Utils.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/defaultTheme.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/webpack.config.js

1 - Devportal local change and applying language files to each browser local was not behaving as expected. This PR is fixing that.
2 - After merging the graphql try it tool, there is load of warnings printed on the npm build mode. This PR is fixing that as well.

Fixing language issues and removing multiple warnings in the dev mode

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx

Fixing the publisher UI test failure

Fixing test failure

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/ExtendedJWTBearerGrantHandler.java

Null check for Role Claim

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/ExtendedJWTBearerGrantHandler.java

Fix issues when role claim is null

Fix issues when role claim is null

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java

Setting empty array for userRole

Setting empty array for userRole 

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java

Fixes https://github.com/wso2/product-apim/issues/7708.

Add support to dateTime type in SOAP to REST feature

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fix wso2/product-apim/issues/7719

Modified doc visibility for all doc types.

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/utils.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/pages/index.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/CustomRouter/BrowserRouter.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Fixes the cloud custom URL issue by adding the tenant domain coming from the header to the Settings global javascript object and reading it from the client-side and doing the needed changes to the single-page app.

Fixing custom-url issue

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java

Fixes https://github.com/wso2/product-apim/issues/7784

Fix issue in attaching api categories in tenant domain

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx

Fixes: https://github.com/wso2/product-apim/issues/7789

Fix scope detach issue from resource in publisher

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java

fixes https://github.com/wso2/product-apim/issues/7791

fix monetization properties replaced during api republish

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/ApiTagThumb.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/TagCloudListingTags.jsx

Minor issues in TagWise mode and Tag cloud

Fixing issue https://github.com/wso2/product-apim/issues/7785

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx

Fixes: https://github.com/wso2/product-apim/issues/7758

Add technical owner details

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/.eslintignore
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SelectAppPanel.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx

Fixes https://github.com/wso2/product-apim/issues/7581

Re-arranging Try-out console and adding generate token

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/rxts/api.rxt

Add type field to api rxt

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/dto/JWTInfoDto.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/generator/APIMgtGatewayJWTGeneratorImpl.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java

Fixes https://github.com/wso2/product-apim/issues/7886

Add API Name into JWT

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java

failed to validate roles in the "Internal" domain when using basic auth.

Fixing role validation failure in "Internal" domain

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx

Fixes https://github.com/wso2/product-apim/issues/1547

Add UI for production and sandbox endpoint security

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/GatewayUtils.java

Fixes https://github.com/wso2/carbon-apimgt/issues/8411

Message Fix Fix Mediation Policies (xml_validator) failing with Global Mediation Extensions with FULL log

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx

pass field name to validateandUpdateSecurity method

pass field name to validateandUpdateSecurity

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/template/SecurityConfigContext.java

Fixes https://github.com/wso2/product-apim/issues/7924

Fixing issue #7924

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/.eslintignore
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/jaggery.conf
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/Admin.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/Base/Header/navbar/LeftMenu.jsx

Fix routing issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/package.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/package.json

Fix: https://github.com/wso2/product-apim/issues/7905

Add i18 run to prod build

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/AdminOperations/APICategories/APICategories.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/AdminOperations/APICategories/CreateAPICategory.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/AdminOperations/APICategories/EditAPICategory.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/AdminOperations/APICategories/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/AdminOperations/CreateBanner.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/data/api.js

Please find the implementation for the  API Category: Edit functionality.
> Note: Previously added code snippets for development purposes have been cleaned.

Admin portal revamp - API Category Edit functionality

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/LifeCycle/CheckboxLabels.jsx

Fixes https://github.com/wso2/product-apim/issues/7871
**Note: Please review do not merge until 3.1.0 is released**

Show a warning if gateway environment not selected

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java

This PR update the spike arrest subscription policy at the throttle handler if the max request count or the spike arrest unit time of the subscription policy is changed by:
- Changing the subscription tier
- Updating the policy at the admin console (if gateway cache is enabled, this change will take effect only 
after the cache period expires)
Fixes wso2/product-apim#7507
**Note: Please review do not merge until 3.1.0 is released**

Fix updating burst control throttle policy

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantOracle.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantPostgreSQL.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsDB2.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsH2MySQL.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java

This fixes [https://github.com/wso2/product-apim/issues/5073](https://github.com/wso2/product-apim/issues/5073)

Fixing issue in case sensitivity of username while searching for applications in api store

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java

Fix duplicate entry error for key 'APP_NAME_TENANT' when two APIM servers are started in parallel

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx

Fix token generated from application not working in tryout console

Fix token generated from application not working in tryout console

---

.gitignore
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/SubscriptionsApiServiceImpl.java

Fixes wso2/product-apim#7965
Tier was not properly set on the correct object during adding multiple subscriptions.

Fix mutiple subscriptions post operation

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

This PR adds UI to show the subscriber claims as shown in the screenshot below:
This needs to be merged after merging - https://github.com/wso2/carbon-apimgt/pull/8405

Add UI to show subscriber claims

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/util/BlockingConditionRetrieverTest.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/throttling/util/KeyTemplateRetrieverTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml

Fix tests related to https://github.com/wso2/carbon-apimgt/pull/8457
wso2/product-apim#7983

fix tests related to throttle data service

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinitionValidationResponse.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx

fixes https://github.com/wso2/product-apim/issues/7397

Modified response of OAS/Swagger validation in API creation

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jaggery.conf
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jest.config.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/settings/settings.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/utils.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/pages/index.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/Tests/Utils/settings.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/utils.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx

Fixed wso2/product-apim/issues/7850
Depends on : wso2/product-apim/pull/7951

Fixed external idp iframe issue.

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/index.jsx

fixes https://github.com/wso2/product-apim/issues/7666

Handled unauthorized requests(403) in dev portal

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx

Fixes [wso2/product-apim#7805](https://github.com/wso2/product-apim/issues/7805)

Disable API Security Audit for GraphQL APIs

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/events/TokenRevocationNotifierImplTest.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/webapp/WEB-INF/beans.xml
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/TokenMergeInterceptor.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/modules/policy/global-policy-edit.jag
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_default.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/conf/locales/jaggery/locale_en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx

resolves requested changes in 
https://github.com/wso2/carbon-apimgt/pull/6467
https://github.com/wso2/carbon-apimgt/pull/6197
https://github.com/wso2/carbon-apimgt/pull/6177
https://github.com/wso2/carbon-apimgt/pull/6270
https://github.com/wso2/carbon-apimgt/pull/8069
https://github.com/wso2/carbon-apimgt/pull/7973

Resolve localization and requested issues

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/edit/template.jag

Fixes https://github.com/wso2/product-apim/issues/7908
Fixes https://github.com/wso2/product-apim/issues/7432

Support '-' in application name in blocking conditions.

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin/site/themes/wso2/templates/conditions/edit/template.jag

public fix for https://github.com/wso2/product-apim/issues/7970

Allow adding an user name with hyphens for blacklisting

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/site/public/images/logo.svg
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/AdminPages/Addons/ContentBase.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/Base/Header/Avatar.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/Base/Header/index.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/Base/Navigator.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/Base/NavigatorChildren.jsx

Aligning the admin theme with the provided design

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/OpenAPIDefinitionValidationResponseInfoDTO.java
docs/apidocs/publisher/v1/models/OpenAPIDefinitionValidationResponse_info.html

generated files were missed in the PR #8300. This PR is to add that file.

Adding generated files that missed in the PR #8300

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/AppsTableContent.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/GenericDisplayDialog.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/InlineMessage.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx

Fixing issue https://github.com/wso2/product-apim/issues/8032

Adding missing application search functionality

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/EndpointRegistryImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/main/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/impl/RegistriesApiServiceImpl.java

Also fixes converting to correct DTO in update registry operation.

Add audit logs for endpoint registry rest api operations

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json

Fixes https://github.com/wso2/analytics-apim/issues/1127

Redefine apim analytics scopes

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/pom.xml
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/main/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/impl/RegistriesApiServiceImpl.java

- Validate the reachability of the definition URL
- Validate the content of the definition file

Add endpoint registry - definition validation 

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java

Fixed https://github.com/wso2/product-apim/issues/8073

Fixed https://github.com/wso2/product-apim/issues/8073

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/conf/settings.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/theme/settings.js
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/ProtectedApp.jsx

Fixed https://github.com/wso2/product-apim/issues/8080

Fixed https://github.com/wso2/product-apim/issues/8080

---

components/apimgt/org.wso2.carbon.apimgt.api/pom.xml
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/OpenAPIDefinitionValidationResponseInfoDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
docs/apidocs/publisher/v1/models/OpenAPIDefinitionValidationResponse_info.html

WSO2 Micro gateway currently supports processing several x-wso2 vendor extensions defined at swagger level which contain all the information required to create APIs. Processing these needs to be supported at APIM level in order to allow the same swagger definition to be used to create a complete API on APIM as well as importing a complete API definition as a swagger. This fix will provide support for the mentioned issue.
Extension | API level | Resource Level
-- | -- | --
x-wso2-basePath | Fixed |  
x-wso2-production-endpoints | Supported Already | No support from APIM yet
x-wso2-sandbox-endpoints | Supported Already | No support from APIM yet
x-wso2-endpoints | Supported Already | No support from APIM yet
x-wso2-throttling-tier | Fixed | Fixed
x-wso2-cors | Fixed |   …

 Support x-wso2 Swagger extensions that are already supported by Micro Gateway when importing OAS definitions.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js

[UI][Publisher]Fix issue when typing OpenAPI URL when creating an API

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/admin_new/source/src/app/components/Base/Header/Breadcrumbs.jsx

Breadcrumbs component is now implemented to work with the RouteMenuMapping and behave dynamically with page navigation.

[Admin Portal Revamp] Breadcrumbs implementation

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApplicationsApiServiceImpl.java

Fix SQLServer SQL_Latin1_General_CP1_CS_AS colation incompatibility as described
in https://github.com/wso2/product-apim/issues/8098

Fix SQL_Latin1_General_CP1_CS_AS incompatibility

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/dao/test/APIMgtDAOTest.java

Fixes https://github.com/wso2/product-apim/issues/7933

Adding subscriber name to CREATED_BY column value of AM_SUBSCRIPTION table

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/AdminPages/Addons/ListBase.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Application/AddEdit.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Blacklist/AddEdit.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Blacklist/List.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Custom/AddEdit.jsx

- Fix BlackList column render issue 
- Remove autofocus from unnecessary fields

Fix BlackList column render issue and remove autofocus

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/APIConsumerImplTest.java

resolve InvalidUseOfMatchers

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java

Fix database connection leak when importing APIs

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Application/AddEdit.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Blacklist/AddEdit.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Custom/AddEdit.jsx

Fix API calls of Application, Blacklist and Custom throttling policies.

Fix Policies API calls

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/EndpointRegistryImplTest.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/test/java/org.wso2.carbon.apimgt.rest.api.endpoint.registry/impl/RegistriesApiServiceImplTest.java

Update test cases for https://github.com/wso2/carbon-apimgt/pull/8542

Fix test failures in get endpoint registry entries

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

UTF8 characters are not correctly stored into WSO2 APIM

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/APIImportExportManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/CommonUtil.java

Fixes https://github.com/wso2/product-apim/issues/7980

Add a meaningful name to Downloaded API .zip file .

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/ThrottlingApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/ThrottlingApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/APICategoryDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/BlockingConditionStatusDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ThrottlingApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml

Fix https://github.com/wso2/product-apim/issues/8033 related to https://github.com/wso2/product-apim/issues/7954

[Admin REST API] - API to update block condition status

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Scope.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/AlertSubscriptionsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/AlertTypesApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/AlertsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ScopeDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/SharedScopeMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/Scope.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jaggery.conf
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Operations/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Base/Header/navbar/GlobalNavLinks.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/Create/CreateScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/Delete/Delete.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/EditScope.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/Listing/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/Scopes.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

Screenshots for the shared scope management UI.
**Add Scope**
**Edit Scope**
**Listing Scopes**

Adding Shared Scope Management UI

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/services/constants.jag
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/data/APIClient.js
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/data/Utils.js

Switch to Admin REST API V1

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Application/AddEdit.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Application/List.jsx

Fix Application Policies to suit REST API payload changes

Fix Application Policies to suit REST API payload changes

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/ServiceReferenceHolder.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ApisNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ApplicationNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ApplicationRegistrationNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/Notifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/PolicyNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/SubscriptionsNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/APIEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/APIPolicyEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/ApplicationEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/ApplicationPolicyEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/ApplicationRegistrationEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/Event.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/SubscriptionEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/SubscriptionPolicyEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/ThrottlePolicyEvent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/exceptions/NotifierException.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/APIStateWorkflowDTO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/WorkflowUtils.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/WorkflowsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/WorkflowsApiServiceImpl.java

Adding event notifier interfaces which can be used to send various events data such as creation,updation,deletion of Subscriptions, Applications, APIs, Policies, Keys to Pilot node.

Adding Event Notifier base component

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/EndpointRegistryImplTest.java

Related to this change https://github.com/wso2/carbon-apimgt/pull/8577

Fix EndpointRegistryImpl test failures

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Application/List.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Custom/List.jsx

Remove unnecessary new Promise

Remove unnecessary new Promise

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx

Revert adding FormattedMessage with Typography in devportal UI
fix https://github.com/wso2/carbon-apimgt/pull/8569/files#diff-f3866f16ab71cdc24cd16a8036008babR316-R327

Revert adding FormattedMessage with Typography in devportal UI

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/data/api.js

Add settings API to context

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIDefinition.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS2Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

Fixing DOC Comments related to https://github.com/wso2/carbon-apimgt/pull/8485 and https://github.com/wso2/carbon-apimgt/pull/8461 PRs.
Provide alternations to reduce the line of codes related to above PRs.

Fixing doc comments and reducing code length

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIClientGenerationManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/java/org/wso2/carbon/apimgt/rest/api/store/impl/ApisApiServiceImpl.java

This PR contains fixes for the issue (https://github.com/wso2/product-apim/issues/8127) and issue "Can't view application after deleting the application tier"(https://github.com/wso2/product-apim/issues/8037).
Adding fixes for public branch

Public branch fixes for issues

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java

Fixes https://github.com/wso2/product-apim/issues/8038

Fix for product-apim#8038

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/ExtendedJWTBearerGrantHandler.java

Fix for https://github.com/wso2/product-apim/issues/8044

Fix JWT bearer grant role extraction issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ApisNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ApplicationNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/ApplicationRegistrationNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/PolicyNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/SubscriptionsNotifier.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notifier/events/Event.java
components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSConstants.java
components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSMessageListener.java
components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSTransportHandler.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/jndi.properties.j2
features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventpublishers/notificationEventJMSPublisher.xml
features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventreceivers/notificationsWSO2EventReceiver.xml
features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventstreams/org.wso2.apimgt.notification.stream_1.0.0.json

Adding JMS publisher and Listener implementation for event notification feature.

Adding implementation for event notification JMS publisher and listener

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx

PRs resolved:
https://github.com/wso2/carbon-apimgt/pull/8569
wso2/product-apim#8094
front port: https://github.com/wso2-support/carbon-apimgt/pull/2082

Fix additional properties in publisher UI and restore sample API

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/AdminPages/Addons/ListBase.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Advanced/AddEdit.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Advanced/HelpLinks.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Advanced/List.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/Throttling/Advanced/index.jsx

Now we can push additional action buttons in the Action column.
You need to define your component in the listing component and pass It to the ListBase as follows.
const addedActions = [
(props) => {
const { rowData, updateList } = props;
const updateSomething = () => {
alert(`Do something with ${JSON.stringify(rowData)}`);
updateList();
};
return (
<Button variant='contained' size='small' onClick={updateSomething}>
<FormattedMessage
id='Throttling.Advanced.List.custom.action'
defaultMessage='Some Action'
/>
</Button>
);
},
];
Pass it as follows.
<ListBase
...
...
addedActions={addedActions}
...
/>

Providing the ability to push additional action buttons

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Operations/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Operations/Operations.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/Delete/Delete.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Scopes/Listing/Listing.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/api.js

UI Screenshots
GraphQL Operations

Adding multiple scopes UI support

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/gen/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/RegistriesApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/gen/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/RegistriesApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/gen/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/SettingsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/gen/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/SettingsApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/main/resources/endpoint-registry-api.yaml
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/swagger.json

Scopes
> service_catalog:view
> service_catalog:write
> service_catalog:entry_view
> service_catalog:entry_write
Roles
> Internal/service_catalog_admin
> Internal/service_catalog_user
> Internal/service_catalog_viewer

Refractor service catalog scope names and role names

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/data/AuthManager.js

add admin_settings scope

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/AdminAlertConfigurator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/AlertMgtConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/AlertSubscriptionsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/AlertSubscriptionsApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/AlertTypesApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/AlertTypesApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/AlertTypeDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/AlertTypesListDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/AlertsInfoDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/AlertsSubscriptionDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/AlertSubscriptionsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/AlertTypesApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/AlertsMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/webapp/WEB-INF/beans.xml

The REST APIs required for admin alert management https://github.com/wso2/product-apim/issues/8108

Admin Alert management APIs

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/AdminPages/Addons/InputListBase.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/components/MicrogatewayLabels/AddEditMGLabel.jsx

On Edit window of a micro-gateway label with a 2 or more hosts, Clicking `Remove` on one host results in removing all hosts.
This PR fixes it.

[Admin Portal Revamp] Fix Micro-gateway Label Edit

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin_new/source/src/app/ProtectedApp.jsx

Change landing page to application throttling

Change landing page to application throttling

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/alertmgt/AdminAlertConfigurator.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/AlertSubscriptionsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/AlertSubscriptionsApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/GraphQLQueryDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/SubscriptionThrottlePolicyDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/AlertSubscriptionsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/AlertsMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml

The DELETE /alert-subscription resource implementation requested in https://github.com/wso2/product-apim/issues/8108

Adding alert unsubscribe API

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/endpoint/registry/api/DefinitionValidationException.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/endpoint/registry/constants/EndpointRegistryConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/endpoint/registry/util/DefinitionValidator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/endpoint/registry/util/EndpointRegistryUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/endpoint/registry/util/GraphQLDefinitionValidator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/endpoint/registry/util/OASDefinitionValidator.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/endpoint/registry/util/WSDLDefinitionValidator.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/pom.xml
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/main/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/impl/RegistriesApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.endpoint.registry/src/test/java/org/wso2/carbon/apimgt/rest/api/endpoint/registry/impl/RegistriesApiServiceImplTest.java

- Added a new interface **DefinitionValidator**
- Implemented parsing logic for different definition types implementing the DefinitionValidator

Improve definition validation in endpoint registry

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SettingsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SettingsApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/ScopeDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/ScopeListDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/SettingsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/utils/mappings/SettingsMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml

Reverts wso2/carbon-apimgt#8648

Revert "Revert "[Admin-REST API] API to get role-scope mapping.""

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtFaultHandler.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/analytics/APIMgtThrottleUsageHandler.java
components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeFaultPublisherDTO.java
components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java
components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/FaultPublisherDTO.java
components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/ThrottlePublisherDTO.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml

Fixed https://github.com/wso2/product-apim/issues/8232

Fixed https://github.com/wso2/product-apim/issues/8232

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/Header/index.jsx

Remove bell notifications icon from top bar

Remove bell notifications icon from top bar

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml

Introducing the following root scope for all admin REST APIs
"Name": "apim:admin",
"Roles": "admin"

Introducing the apim:admin root scope for admin REST APIs

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/subscription/URLMapping.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/SubscriptionValidationDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SubscriptionValidationSQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApiPoliciesApi.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApisApi.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApplicationKeyMappingsApi.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApplicationPoliciesApi.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/ApplicationsApi.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/SubscriptionPoliciesApi.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/SubscriptionsApi.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/dto/ApiPolicyDTO.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/gen/java/org/wso2/carbon/apimgt/internal/service/dto/URLMappingDTO.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/resources/api.yaml
components/apimgt/org.wso2.carbon.apimgt.internal.service/swagger.json
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/API.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/APIPolicyList.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/ApiPolicy.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/Policy.java

fix for https://github.com/wso2/product-apim/issues/8269

add scopes to API resouces 

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/subscription/APIPolicy.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/subscription/APIPolicyConditionGroup.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/SubscriptionValidationDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SubscriptionValidationSQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/webapp/WEB-INF/beans.xml
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/SubscriptionDataLoader.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/SubscriptionDataStore.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataLoaderImpl.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataStoreImpl.java

Fix for https://github.com/wso2/product-apim/issues/8293

add REST API support forAPIPolicies

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx

This PR will fix the issue in https://github.com/wso2/product-apim/issues/8157

Fixing loading issue in Try Out Console when user is not logged in

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.gateway.v1/pom.xml
features/apimgt/org.wso2.carbon.apimgt.rest.api.gateway.feature/pom.xml
pom.xml

Bumped the versions of synapse, carbon-mediation, gateway rest api and gateway rest api feature

Bumped the versions

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/css/main.css
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/pages/index.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/Publisher.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/ProtectedApp.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ApiThumb.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/BaseThumbnail.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/DocThumb.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Progress.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIClient.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIProduct.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/webWorkers/swagger.worker.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/webWorkers/swaggerWorkerInit.js
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js

Publisher UI performance Optimization
Fixes issue https://github.com/wso2/product-apim/issues/8100

Publisher UI performance Optimization

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/AdminPages/Dashboard/RateLimitingCard.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/AdminPages/Dashboard/TasksWorkflowCard.jsx

[Admin Portal UI] Fix dashboard icons to match Leftmenu

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Prototype/InlineEndpoints.jsx

Fixes https://github.com/wso2/product-apim/issues/7921

Fix issue #7921

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/APIAdmin.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/ExceptionCodes.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIAdminImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/resources/tenant-conf.json
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SettingsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SystemScopesApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/SystemScopesApiService.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/SettingsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/SystemScopesApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/webapp/WEB-INF/beans.xml

Already existing API has been modified with different resource path.

Added REST API to validate the scope.

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/impl/TenantInfoApiServiceImpl.java

This PR fixes issues reported after the PR analysis of the following PRs:
https://github.com/wso2/carbon-apimgt/pull/8155

Fix PR review comments

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx

Fixes https://github.com/wso2/product-apim/issues/8346

Fix issue #8346

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SubscriptionValidationSQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/AbstractKeyValidationHandler.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/SubscriptionDataLoader.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataLoaderImpl.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyValidationService.java

- Fix subscription policy loading by name
- fix subscription policy per tenant
- add policy check for situation where policy is not in the map (due to tenant loading)

Fix subscription loading by policy name rest api

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Apis.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Prototype/GenericResource.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Endpoints/Prototype/InlineEndpoints.jsx

Fixes https://github.com/wso2/product-apim/issues/7904
- Added new progress bar to details component

Fix issue #7904

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/handlers/AbstractKeyValidationHandler.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataLoaderImpl.java

- Add logic to load subscription related info if does not have the info
- fix NPE

Refactor subscription validation logic

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java

Fixes [wso2/product-apim#8401](https://github.com/wso2/product-apim/issues/8401)

Fix for Inline Prototype Implementation not working

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Throttling/Application/AddEdit.jsx

Fix Application Policy UI after new REST changes

Fix Application Policy UI after new REST changes

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIIdentifier.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/APIProductIdentifier.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Identifier.java
components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/SubscribedAPI.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/WorkflowUtils.java

Fix
- Subscription update event (add updated policy)
- Subscription deletion event
- Event sent after subscription creation workflow approval

Fix subscription related events

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java

Fixes https://github.com/wso2/product-apim/issues/7823

Honour isDefaultVersion config value in api.yaml when importing an API

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/EditParameter.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/webpack.config.js

In this PR:
- fixes https://github.com/wso2/product-apim/issues/8423

Resource param fix

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/internal/APIHandlerServiceComponent.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/listeners/GatewayStartupListener.java

Related issue: wso2/product-apim#8246

Adding Listener component for loading synapse artifacts in server startup

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx

Fix Runtime Configurations page

Fix Runtime Configurations page

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/APIDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
docs/apidocs/store/v1/models/API.html
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/InfoBar.jsx

fixes https://github.com/wso2/product-apim/issues/8426
fixes https://github.com/wso2/product-apim/issues/8431

Adding keyManagers to API overview in Devportal

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/ImportDefinition.jsx

Fixing https://github.com/wso2/product-apim/issues/7320

Adding Operation configs when importing modified SDL with old operations

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIExportUtil.java

This PR adds the front ported fix for https://github.com/wso2/product-apim/issues/7930

Improve swagger definition for apictl export

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthCredentialValidator.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/test/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticatorTest.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/BasicAuthValidationInfoDTO.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/APIKeyMgtRemoteUserStoreMgtService.java
service-stubs/apimgt/org.wso2.carbon.apimgt.keymgt.stub/src/main/resources/APIKeyMgtRemoteUserStoreMgtService.wsdl

This PR front ports the fix for https://github.com/wso2/product-apim/issues/7953

Fix secondary userstore domain appending to username with API Basic Auth

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx

Fix GET TEST KEY for API Key
Fixes Issue 2 of https://github.com/wso2/product-apim/issues/8443

Fix GET TEST KEY for API Key

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx

Adding loading animation when the page is changing.

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/Listing.test.jsx

fix test failure from https://github.com/wso2/carbon-apimgt/pull/8776

fix test failure from https://github.com/wso2/carbon-apimgt/pull/8776

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx

Fix https://github.com/wso2/product-apim/issues/8446

Fix devportal app key related issues

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/AdminPages/Dashboard/RateLimitingCard.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/RouteMenuMapping.jsx

Change LeftBar menu icons

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/AccessControl.jsx

This PR fixes the following issues:
1. Ability to configure CORS header "Access-Control-Expose-Headers" in WSO2 API Manager(https://github.com/wso2/product-apim/issues/4461)
2. Issue regarding Access Control Visibility in APIM(https://github.com/wso2/product-apim/issues/8267)
3. Additional properties missing when creating new API version issue

Bug fixes and improvements

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jaggery.conf
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/RedirectToLogin.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/errorPages/ErrorList.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/errorPages/ErrorPage.jsx

Fixes https://github.com/wso2/product-apim/issues/7498 for Publisher

Fix issue #7498

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/jaggery.conf
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/RedirectToLogin.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/errorPages/ErrorList.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/errorPages/ErrorPage.jsx

Reverts wso2/carbon-apimgt#8859

Revert "Revert "Fix issue #7498""

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/errorPages/ErrorPage.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/errorPages/ErrorPage.jsx

Fix build failure

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx

Fix cannot see GET TEST KEY issue

Fix cannot see GET TEST KEY issue

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/services/login/login_callback.jag

Fix single logout issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/listeners/ServerStartupListener.java

This PR fixes the names of the files that would be copied during Login page customization.

Fix login customization file names

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APICategories.jsx

This PR fixes https://github.com/wso2/product-apim/issues/7837

Disable API Category selection drop down baesd on user permissions

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/TableView/TableView.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Listing/CommonListing.jsx

1. Fixes https://github.com/wso2/product-apim/issues/8095
2. Fixes https://github.com/wso2/product-apim/issues/8096

Fix UI issues related to API Listing and API Categories

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java

This PR fixes the issue https://github.com/wso2/product-apim/issues/7964

Fix Backend JWT generation in product-apim issue #7964

---

components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/ApiPoliciesApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/ApplicationKeyMappingsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/ApplicationPoliciesApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/ApplicationsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/SubscriptionPoliciesApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/impl/SubscriptionsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/utils/SubscriptionValidationDataUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/auth/BasicAuthenticationInterceptor.java

add tenant validation to avoid requesting different tenants data

add tenant validation to avoid requesting different tenants data

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fixes https://github.com/wso2/product-apim/issues/8289

Add kid claim to JWT

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstantsMSSQL.java

This PR fix the issue of the limit parameter when invoking GET API api/am/store/v1/applications

Fix the limit parameter issue in the devportal API v1

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Throttling/Subscription/AddEdit.jsx

Change order of GraphQL fields in Subscription Policy UI

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java

Related issue: wso2/product-apim#8246

Adding Artifact synchroniser feature for websocket API

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OASParserUtil.java

Fixes https://github.com/wso2/product-apim/issues/8227

Fix $ref not being honoured properly when used in parameters in API Products

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package-lock.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/APIDefinition/APISecurityAudit.jsx

Removing react-visibility-sensor and adding method comments for API Security Audit implementation
Fixes [wso2/product-apim#8393](https://github.com/wso2/product-apim/issues/8393)

Removing react-visibility-sensor

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPIProduct.jsx

Fix for https://github.com/wso2/product-apim/issues/8509

Fix #8509 - publisher user cant create APIProduct

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/BotDetection/DetectedBotData/ListDetectedBotData.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/api.js

Bot data listing UI is now made compatible with the newly provided API resource.

Update Bot detected data listing

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ApplicationSettings/EditApplication.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/api.js

When changing the owner of an application using Admin Portal, the new owner should be validated whether a holder of `apim:subscribe` scope. This PR implements the mentioned validation.

Admin Portal -  Update Application owner change validation

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/recommendationmgt/RecommenderDetailsExtractor.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/RecommendationsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java

This PR fixes the incorrect string comparisons.

Fix incorrect string comparison methods

---

components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/java/org/wso2/carbon/apimgt/internal/service/utils/SubscriptionValidationDataUtil.java

Fixes https://github.com/wso2/product-apim/issues/8511

Fix wso2/product-apim#8511 - Resolve correct tenant domain for data retrieval services

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/index.jsx

Fixes: https://github.com/wso2/product-apim/issues/8407

Fix Admin Portal Footer alignment

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPIProduct.jsx

Fix for https://github.com/wso2/product-apim/issues/8509 to handle both admin and publisher users

Fix for #8509

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/util/SequenceUtils.java

fixing https://github.com/wso2/product-apim/issues/8525

Fix issue of updating inflow sequences in SOAP to REST APIs.

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Base/index.jsx

Change Alert Configure to Configure Alerts

Change Alert Configure to Configure Alerts

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/recommendationmgt/RecommenderDetailsExtractor.java

Fixed an issue in the API details publishing to recommendation flow.
Added a few logs for better visibility.

Fixed recommendations feature issues in 3.2.0

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/workflow/TenantWorkflowConfigHolder.java

Fixes https://github.com/wso2/product-apim/issues/8540

Fix migration issue for subscription update feature

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/Subscription.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataLoaderImpl.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataStoreImpl.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/KeyManagerDataServiceImpl.java

Reverts wso2/carbon-apimgt#8904

Revert "fix interminet subscription inactive issue"

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/services/constants.jag
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/services/login/idp.jag
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/services/login/login_callback.jag
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/services/refresh/refresh.jag

Fix https://github.com/wso2/product-apim/issues/8552

Remove old app check

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Throttling/Subscription/AddEdit.jsx

Fixes https://github.com/wso2/product-apim/issues/8537

Fix issue #8537

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/services/login/login_callback.jag

Fixes https://github.com/wso2/product-apim/issues/8563

Fixing devportal SSO session logout issue

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/entity/Subscription.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataLoaderImpl.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/model/impl/SubscriptionDataStoreImpl.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/service/KeyManagerDataServiceImpl.java

Reverts wso2/carbon-apimgt#8909

"fix interminet subscription inactive issue""

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx

fixes https://github.com/wso2/product-apim/issues/8535

fix out of band provisioning UI issue

---

components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/DataPublisherUtil.java
components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeFaultPublisherDTO.java
components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeRequestResponseStreamPublisherDTO.java
components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeThrottlePublisherDTO.java

Fixed https://github.com/wso2/product-apim/issues/8571

fixed https://github.com/wso2/product-apim/issues/8571

---

components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/KeyManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/UserInfoDTO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/Claim.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/ClaimsList.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/kmclient/model/UserClient.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/DefaultClaimsRetriever.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/token/ExtendedDefaultClaimsRetriever.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/test/java/org/wso2/carbon/apimgt/impl/token/DefaultClaimsRetrieverTestCase.java
components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/JWTGenerator.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json

This PR is to get user claims from external service and generated the backend JWT token using that

Generate backend jwt using claims from external rest api

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/admin/v1/impl/ImportApiServiceImpl.java

Fixes: https://github.com/wso2/product-apim/issues/8572

Fixing NPE when importing application with keys

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Throttling/Blacklist/Delete.jsx

This PR renames the deny policy delete dialog title.

Rename deny policy delete dialog title

---

components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/token/TokenGenTest.java

Will be fixed in https://github.com/wso2/carbon-apimgt/issues/8932

temporarily disable

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/resources/tenant/tenant-conf.json

changed analytics related scopes as follows 
manager_dashboard --> business_analytics
publisher_dashboard --> api_analytics
subscriber_dashboard --> application_analytics

Update analytics related scopes

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/v1/dto/SettingsDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SettingsApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/SettingsMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/store-api.yaml
docs/apidocs/store/v1/models/Settings.html

Fixes part-2 of the issue https://github.com/wso2/product-apim/issues/8500

Add properties to return password policy/pattern regex in settings api

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java

Fixes https://github.com/wso2/product-apim/issues/8620
sample response :
TID: [-1234] [2020-07-08 17:14:48,217]  INFO {AUDIT_LOG} - {"performedBy":"admin","action":"updated","typ":"Subscription","info":"{\"application_name\":\"NewApp\",\"tier\":\"Gold\",\"provider\":\"admin\",\"api_name\":\"PizzaShackAPI\",\"requested_tier\":\"Silver\",\"application_id\":2}"}

Fix subscription update audit log issue

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java

Fixes https://github.com/wso2/product-apim/issues/8630

Fix already existing tier update request update issue

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/en.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/locales/fr.json
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/APISecurity.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/AuthorizationHeader.jsx

Disable application level security if all resources are unsecured.

Disable application level security if all resources are unsecured 

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java

Fixes https://github.com/wso2/product-apim/issues/8633

Fix lifecycle update issue in migrated APIM 3.2.0

---

components/apimgt/org.wso2.carbon.apimgt.impl/pom.xml
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/containermgt/K8sManager.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/containermgt/k8scrd/APICustomResourceDefinitionSpec.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/containermgt/k8scrd/Status.java
pom.xml

This PR will provide the fixes for following issues. 
Fixing [#8543](https://github.com/wso2/product-apim/issues/8543)
Fixing [#8542](https://github.com/wso2/product-apim/issues/8542)

Handing deployment of an API in privateJet mode when the APIM running in the same kubernetes cluster & fixing bugs in API re-publish path

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/BotDetectionDataApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/LabelsApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/PoliciesApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/ThrottlingApi.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/admin/v1/dto/BotDetectionDataDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml

- Modify the scope descriptions of admin REST API
- Enclose bot detection data schema examples in quotes
Closes: https://github.com/wso2/product-apim/issues/8146

Modify the scope descriptions of admin REST API

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/RouteMenuMapping.jsx

This PR fixes: https://github.com/wso2/product-apim/issues/8647

Update Bot-Detection Data Icon

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/BotDetection/EmailConfig/ListEmails.jsx
features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/data/api.js

On the admin portal, the bot detection email alert subscribing UI is updated to comply with the rest api changes.

Fix Email subscription rest api calls

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SubscriptionsApiServiceImpl.java

Fixes: https://github.com/wso2/product-apim/issues/5159

Add workflow status check when subscribing

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ManageAlerts/ManageAlerts.jsx

This PR Fixes: https://github.com/wso2/product-apim/issues/8409

Fix Manage Alerts loading flicker

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/SelectAppPanel.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx

Fixed issues 1 to 3 https://github.com/wso2/product-apim/issues/8379

Fix Tryout page accessibility issues

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java

Fixes https://github.com/wso2/product-apim/issues/8637

Fix invalid JWT token error response code issue

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/CommentAdd.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Comments/CommentOptions.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/DocList.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/Documents/View.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/ConfirmDialog.jsx
features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Shared/CustomIcon.jsx

Fixes: https://github.com/wso2/product-apim/issues/8380, https://github.com/wso2/product-apim/issues/8383

Fix comments and docs pages accessibility issues

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIValidation.js

Fixes https://github.com/wso2/product-apim/issues/8641

Fixes #8641

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/dto/ProductAPIDTO.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml
docs/apidocs/publisher/v1/models/ProductAPI.html
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/NewOverview/ProductResources.jsx

This PR fixes https://github.com/wso2/product-apim/issues/8631

Add API version to Product Overview

---

components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml

Fix https://github.com/wso2/product-apim/issues/8597

Corrected typo error.

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/wsdl/WSDL11SOAPOperationExtractor.java

fix https://github.com/wso2/product-apim/issues/8280

fix https://github.com/wso2/product-apim/issues/8280

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/ManageAlerts/ManageAlerts.jsx

Fixes https://github.com/wso2/product-apim/issues/8605

Fixes #8605

---

features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Applications/Listing/Listing.jsx

Fixing issue https://github.com/wso2/product-apim/issues/8656
Updated the empty app page to align with the no search results page.

Fixing Application search inconsistent behavior

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Configuration/components/KeyManager.jsx
features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx

Fixes https://github.com/wso2/product-apim/issues/8670

Fixes #8670

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/APIManagerComponent.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/internal/ServiceReferenceHolder.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.notification/src/main/java/org/wso2/carbon/apimgt/notification/TokenRevocationNotifierImpl.java
components/apimgt/org.wso2.carbon.apimgt.notification/src/main/java/org/wso2/carbon/apimgt/notification/internal/ApimgtNotificationServiceComponent.java
components/apimgt/org.wso2.carbon.apimgt.notification/src/main/java/org/wso2/carbon/apimgt/notification/internal/ServiceReferenceHolder.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/org.wso2.carbon.apimgt.core.default.json

https://github.com/wso2/product-apim/issues/8710

resolves #https://github.com/wso2/product-apim/issues/8710

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/constants/SQLConstants.java

Setting API type in AM_API table in AM DB
Run unit testing and integration testing.

Setting API type in AM DB

---

features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Documents/MarkdownEditor.jsx

Fixes https://github.com/wso2/product-apim/issues/8385

Fixes #8385

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dto/EventHubConfigurationDto.java

This PR removes unused hardcoded password and username fields from EventHubConfigurationDto.java class.

Remove unused hardcoded password and username fields

---

components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java
components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java

Fixes https://github.com/wso2/product-apim/issues/8718

Fix throttling issue in websocket APIs when using JWT tokens

---

components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/gatewayartifactsynchronizer/DBRetriever.java

Resolves https://github.com/wso2/product-apim/issues/8717
Related to wso2/product-apim#8246

Update service URL for DBRetriever HTTP calls

---

components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java
components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/test/resources/carbon-home/repository/conf/api-manager.xml
components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.common/src/test/resources/carbon-home/repository/conf/api-manager.xml
components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/test/resources/carbon-home/repository/conf/api-manager.xml
components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.rest.api/src/test/resources/carbon-home/api-manager.xml
components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.tenant.initializer/src/test/resources/carbon-home/repository.conf/api-manager.xml
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/importexport/utils/APIImportUtil.java
components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ScopesApiServiceImpl.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/interceptors/PreAuthenticationInterceptor.java
components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/utils/RestApiUtil.java
components/apimgt/org.wso2.carbon.apimgt.tokenmgt/src/main/java/org/wso2/carbon/apimgt/tokenmgt/internal/APITokenMgtServiceComponent.java
components/apimgt/org.wso2.carbon.apimgt.tokenmgt/src/main/java/org/wso2/carbon/apimgt/tokenmgt/issuers/AbstractScopesIssuer.java
components/apimgt/org.wso2.carbon.apimgt.tokenmgt/src/main/java/org/wso2/carbon/apimgt/tokenmgt/issuers/PermissionBasedScopeIssuer.java
components/apimgt/org.wso2.carbon.apimgt.tokenmgt/src/main/java/org/wso2/carbon/apimgt/tokenmgt/issuers/RoleBasedScopesIssuer.java
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/conf_templates/templates/repository/conf/api-manager.xml.j2
features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml

Fix for https://github.com/wso2/product-apim/issues/8713

change whitlisted term to 'allowed'

---

features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Throttling/Advanced/AddEdit.jsx

Fix https://github.com/wso2/product-apim/issues/8603

Fix bandwidth policy creation issue

---

features/apimgt/org.wso2.carbon.apimgt.rest.api.gateway.feature/src/main/resources/p2.inf

Related to https://github.com/wso2/product-apim/issues/8246

Adding p2 advice file for gatewayRESTAPI
